Repository knative/serving, pull requests merged in 2018-11, with the labels that each got.

#2375 Drop the vestigial tracker from labeler.
  pkg/reconciler/v1alpha1/labeler/labeler.go
  pkg/reconciler/v1alpha1/labeler/labeler_test.go
Labels: approved, lgtm, size/S

#2376 Update controllers to reconcile on child resource deletion
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/service/service.go
Labels: approved, lgtm, size/M

#2340 Fix gofmt, ineffassign, and misspell errors
  pkg/activator/dedupe_test.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/filtering_handler.go
  pkg/apis/networking/register.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/multiscaler_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  test/conformance/route_test.go
Labels: approved, lgtm, size/M

#2373 Don't rely on TypeMeta to be properly populated.
  Gopkg.lock
  pkg/reconciler/helper.go
  pkg/reconciler/helper_test.go
  pkg/reconciler/v1alpha1/route/route.go
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/pkg/testing/doc.go
  vendor/github.com/knative/pkg/testing/register.go
  vendor/github.com/knative/pkg/testing/resource.go
  vendor/github.com/knative/pkg/testing/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#2333 Return error on lastPinned update failures
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
Labels: approved, lgtm, size/S

#2235 Add configurationGeneration label to revisions #2222
  docs/spec/normative_examples.md
  docs/spec/spec.md
  pkg/apis/serving/register.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  test/states.go
Labels: approved, lgtm, size/M

#2378 apply bound for all scale
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
Labels: approved, lgtm, size/S

#2383 [RELEASE 0.2] Pull in proposed cherry-picks
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/helper.go
  pkg/reconciler/helper_test.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/websocket/connection.go
  third_party/VENDOR-LICENSE
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/knative/pkg/apis/duck/patch.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/testing/doc.go
  vendor/github.com/knative/pkg/testing/register.go
  vendor/github.com/knative/pkg/testing/resource.go
  vendor/github.com/knative/pkg/testing/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#2395 Have Activator key off of Active not Ready.
  pkg/activator/revision.go
  pkg/activator/revision_test.go
Labels: approved, lgtm, size/S

#2392 Retire "Targetable" duck type from Route & Service in favor of "Addressable" with the same meaning.
  Gopkg.lock
  Gopkg.toml
  docs/spec/spec.md
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/route_types_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
  test/e2e/service_to_service_test.go
  test/states.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/duck/verify.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/controller/helper.go
  vendor/github.com/knative/pkg/kmeta/accessor.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
  vendor/github.com/knative/pkg/tracker/enqueue.go
  vendor/go.opencensus.io/plugin/ochttp/client.go
  vendor/go.opencensus.io/plugin/ochttp/client_stats.go
  vendor/go.opencensus.io/plugin/ochttp/doc.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/b3/b3.go
  vendor/go.opencensus.io/plugin/ochttp/server.go
  vendor/go.opencensus.io/plugin/ochttp/stats.go
  vendor/go.opencensus.io/plugin/ochttp/trace.go
  vendor/go.opencensus.io/trace/propagation/propagation.go
Labels: approved, lgtm, size/XXL

#2385 Update productivity-approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2363 Fix log extraction after tests.
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#2400 Start to refactor the way builds are created.
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
Labels: approved, lgtm, size/L

#2403 Remove the base route name from hosts in virtualservice
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
Labels: approved, lgtm, size/S

#2241 Refer to knative/docs cluster setup instead of duplicating
  DEVELOPMENT.md
  docs/creating-a-kubernetes-cluster.md
Labels: approved, lgtm, size/L

#2401 Start to label builds with a hash of the spec from which they were created.
  pkg/apis/serving/register.go
  pkg/reconciler/v1alpha1/configuration/resources/build.go
  pkg/reconciler/v1alpha1/configuration/resources/build_test.go
Labels: approved, lgtm, size/S

#2386 Disable scale-to-zero during activation (#2155)
  pkg/apis/autoscaling/v1alpha1/kpa_types.go
  pkg/apis/autoscaling/v1alpha1/kpa_types_test.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
Labels: approved, lgtm, size/L

#2412 Remove unused account `autoscaler`
  config/200-serviceaccount.yaml
  config/201-clusterrolebinding.yaml
Labels: approved, kind/cleanup, lgtm, size/S

#2408 chg: doc: added info on using docker hub.
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#2382 Use a single approach for building Serving for test and release
  Gopkg.lock
  hack/README.md
  hack/generate-yamls.sh
  hack/release.sh
  test/cluster.sh
  test/e2e-tests.sh
  test/performance-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#2244 Emit metrics about the scaled entity from the autoscaler.
  pkg/autoscaler/autoscaler.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
Labels: approved, lgtm, size/S

#2402 Don't create builds unless the BuildSpec changes.
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  test/conformance/route_test.go
  test/e2e/build_test.go
Labels: approved, lgtm, size/L

#2415 Exclude the `test` dir from coverage
  .gitattributes
Labels: approved, lgtm, size/XS

#2416 [RELEASE 0.2] Cherry pick #2392
  Gopkg.lock
  Gopkg.toml
  docs/spec/spec.md
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/route_types_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
  test/e2e/service_to_service_test.go
  test/states.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/duck/verify.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/controller/helper.go
  vendor/github.com/knative/pkg/kmeta/accessor.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
  vendor/github.com/knative/pkg/tracker/enqueue.go
  vendor/github.com/knative/pkg/webhook/certs.go
  vendor/go.opencensus.io/plugin/ochttp/client.go
  vendor/go.opencensus.io/plugin/ochttp/client_stats.go
  vendor/go.opencensus.io/plugin/ochttp/doc.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/b3/b3.go
  vendor/go.opencensus.io/plugin/ochttp/server.go
  vendor/go.opencensus.io/plugin/ochttp/stats.go
  vendor/go.opencensus.io/plugin/ochttp/trace.go
  vendor/go.opencensus.io/trace/propagation/propagation.go
Labels: approved, lgtm, size/XXL

#2418 Update the vendored test-infra dir
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#2419 [RELEASE 0.2] Cherry pick #2382
  Gopkg.lock
  hack/README.md
  hack/generate-yamls.sh
  hack/release.sh
  test/cluster.sh
  test/e2e-tests.sh
  test/performance-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#2420 Add the missing vendored test-infra/tools/dep-collector
  Gopkg.lock
  Gopkg.toml
  hack/update-deps.sh
  vendor/github.com/knative/test-infra/LICENSE
  vendor/github.com/knative/test-infra/scripts/dummy.go
  vendor/github.com/knative/test-infra/tools/dep-collector/README.md
  vendor/github.com/knative/test-infra/tools/dep-collector/imports.go
  vendor/github.com/knative/test-infra/tools/dep-collector/licenses.go
  vendor/github.com/knative/test-infra/tools/dep-collector/main.go
Labels: approved, lgtm, size/XL

#2429 Fix release script
  hack/release.sh
Labels: approved, lgtm, size/S

#2426 ContainerConcurrency as environment variable.
  cmd/queue/main.go
  cmd/util/env.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/queue_test.go
Labels: approved, area/autoscale, lgtm, size/L

#2423 Clean up duplicate logLevelKey and component field
  cmd/activator/main.go
  cmd/autoscaler/main.go
  cmd/controller/main.go
  cmd/webhook/main.go
  test/controller/main.go
Labels: approved, lgtm, size/S

#2433 remove useless name funcs in route controller
  pkg/reconciler/v1alpha1/route/resources/names/names.go
  pkg/reconciler/v1alpha1/route/table_test.go
Labels: approved, lgtm, size/S

#2424 Wait until no connections are active before shutting down istio-proxy.
  third_party/istio-1.0.2/istio.yaml
  third_party/istio-1.0.2/prestop-sleep.yaml.patch
Labels: approved, lgtm, size/S

#2396 Don't special-case the Build condition.
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, lgtm, size/L

#2410 Gracefully shutdown all test applications.
  test/performance/observed-concurrency/observed_concurrency.go
  test/test_images/autoscale/autoscale.go
  test/test_images/envvars/envvars.go
  test/test_images/helloworld/helloworld.go
  test/test_images/httpproxy/httpproxy.go
  test/test_images/pizzaplanetv1/main.go
  test/test_images/pizzaplanetv2/main.go
  test/test_images/singlethreaded/main.go
  test/util.go
Labels: approved, lgtm, size/M

#2387 Add upgrade test
  test/cluster.sh
  test/presubmit-tests.sh
  test/upgrade-tests.sh
  test/upgrade/README.md
  test/upgrade/service_postdowngrade_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/service_preupgrade_test.go
  test/upgrade/upgrade.go
Labels: approved, lgtm, size/L

#2320 Get the latency numbers for observed-concurrency app
  Gopkg.lock
  test/cluster.sh
  test/e2e-tests.sh
  test/performance-tests.sh
  test/performance/observed-concurrency/README.md
  test/performance/observed-concurrency/reporter.lua
  test/performance/observed-concurrency/run.sh
  test/performance/observed_concurency_test.go
  test/performance/performance.go
  test/prometheus/prometheus.go
  test/test_images/observed-concurrency/README.md
  test/test_images/observed-concurrency/app.yaml
  test/test_images/observed-concurrency/observed_concurrency.go
  vendor/github.com/knative/test-infra/tools/testgrid/testgrid.go
  vendor/github.com/prometheus/client_golang/AUTHORS.md
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/fnv.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/github.com/prometheus/client_golang/prometheus/untyped.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/istio.io/fortio/LICENSE
  vendor/istio.io/fortio/fhttp/http_client.go
  vendor/istio.io/fortio/fhttp/http_server.go
  vendor/istio.io/fortio/fhttp/http_utils.go
  vendor/istio.io/fortio/fhttp/httprunner.go
  vendor/istio.io/fortio/fnet/network.go
  vendor/istio.io/fortio/log/logger.go
  vendor/istio.io/fortio/periodic/periodic.go
  vendor/istio.io/fortio/stats/stats.go
  vendor/istio.io/fortio/version/version.go
Labels: approved, lgtm, size/XXL

#2435 Clearly log when setup fails during E2E tests
  test/cluster.sh
  test/e2e-tests.sh
  test/performance-tests.sh
Labels: approved, lgtm, size/M

#2425 Add markusthoemmes as autoscaling-approver
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2406 Refactor shutdown logic in queue-proxy.
  cmd/queue/main.go
Labels: approved, lgtm, size/M

#2299 Scale to 0 solely based on metrics.
  config/config-autoscaler.yaml
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
  pkg/autoscaler/dynamic_config_test.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/L

#2444 Update tracker to handle deletion events
  pkg/reconciler/helper.go
  pkg/reconciler/helper_test.go
  pkg/reconciler/v1alpha1/route/route.go
Labels: approved, lgtm, size/L

#2432 Dump logs for all pods of the applications.
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#2451 Document lifecycle handlers on user-container.
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
Labels: approved, lgtm, size/S

#2436 Pull in support for non-terminal conditions
  Gopkg.lock
  Gopkg.toml
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/errors_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
Labels: approved, lgtm, size/XXL

#2438 More events!
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/service/resources/route.go
  pkg/reconciler/v1alpha1/service/service.go
Labels: approved, lgtm, size/L

#2446 Simplify some of the object construction in Revision controller.
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, lgtm, size/L

#2399 Reduce the scale-to-zero knobs to 30s/60s.
  config/config-autoscaler.yaml
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
Labels: approved, lgtm, size/S

#2456 Add missing apply to kubectl when creating prometheus
  test/cluster.sh
Labels: approved, lgtm, size/XS

#2455 update-deps.sh in clean branch
  Gopkg.lock
  vendor/github.com/knative/pkg/testing/doc.go
  vendor/github.com/knative/pkg/testing/register.go
  vendor/github.com/knative/pkg/testing/resource.go
  vendor/github.com/knative/pkg/testing/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#2469 Cleanup test-images' yaml files.
  test/e2e/helloworld_shell_test.go
  test/test_images/envvars/envvars.yaml
  test/test_images/helloworld/helloworld.yaml
  test/test_images/observed-concurrency/app.yaml
Labels: approved, lgtm, size/M

#2471 Fix typo in serving's CONTRIBUTIONS.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#2422 Add signal handling to the runtime contract.
  docs/runtime-contract.md
Labels: approved, lgtm, size/XS

#2474 Remove unused cluster role
  config/200-clusterrole.yaml
Labels: approved, kind/cleanup, lgtm, size/M

#2473 Update runtime-contract.md
  docs/runtime-contract.md
Labels: approved, lgtm, size/XS

#2468 Bring up monitoring for perf tests
  test/cluster.sh
  test/performance-tests.sh
Labels: approved, lgtm, size/S

#2405 Rename Activator to KBuffer
  cmd/kbuffer/OWNERS
  cmd/kbuffer/kodata/HEAD
  cmd/kbuffer/kodata/LICENSE
  cmd/kbuffer/kodata/VENDOR-LICENSE
  cmd/kbuffer/main.go
  cmd/queue/main.go
  config/400-activator-service.yaml
  config/config-logging.yaml
  config/kbuffer.yaml
  config/monitoring/logging/elasticsearch/100-fluentd-configmap.yaml
  config/monitoring/logging/stackdriver/100-fluentd-configmap.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  config/monitoring/metrics/prometheus/100-prometheus-scrape-config.yaml
  docs/scaling/DEVELOPMENT.md
  pkg/apis/autoscaling/v1alpha1/kpa_types_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/kbuffer/OWNERS
  pkg/kbuffer/README.md
  pkg/kbuffer/activator.go
  pkg/kbuffer/dedupe.go
  pkg/kbuffer/dedupe_test.go
  pkg/kbuffer/handler/concurrency_reporter.go
  pkg/kbuffer/handler/concurrency_reporter_test.go
  pkg/kbuffer/handler/enforce_length_handler.go
  pkg/kbuffer/handler/enforce_length_handler_test.go
  pkg/kbuffer/handler/filtering_handler.go
  pkg/kbuffer/handler/filtering_handler_test.go
  pkg/kbuffer/handler/handler.go
  pkg/kbuffer/handler/handler_test.go
  pkg/kbuffer/handler/requestevent_handler.go
  pkg/kbuffer/handler/requestevent_handler_test.go
  pkg/kbuffer/images/kbuffer_activeRevision.png
  pkg/kbuffer/images/kbuffer_reserveRevision.png
  pkg/kbuffer/images/routeTraffic.png
  pkg/kbuffer/revision.go
  pkg/kbuffer/revision_test.go
  pkg/kbuffer/stats_reporter.go
  pkg/kbuffer/stats_reporter_test.go
  pkg/kbuffer/util/header.go
  pkg/kbuffer/util/header_test.go
  pkg/kbuffer/util/io_test.go
  pkg/kbuffer/util/rewinder.go
  pkg/kbuffer/util/rewinder_test.go
  pkg/kbuffer/util/transports.go
  pkg/kbuffer/util/transports_test.go
  pkg/logging/config.go
  pkg/reconciler/v1alpha1/route/README.md
  pkg/reconciler/v1alpha1/route/doc/images/active_revisions.svg
  pkg/reconciler/v1alpha1/route/doc/images/inactive_revision.svg
  pkg/reconciler/v1alpha1/route/doc/images/inactive_revisions.svg
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  test/conformance/blue_green_test.go
Labels: approved, lgtm, size/XL

#2490 Tweak the logic in the helper used to access the last time changed.
  pkg/reconciler/v1alpha1/revision/helpers.go
Labels: approved, lgtm, size/XS

#2492 Update issue-template.md with a proposal kind
  .github/issue-template.md
Labels: approved, lgtm, size/XS

#2494 Make it easier to install different Knative versions in E2E tests
  Gopkg.lock
  test/cluster.sh
  test/e2e-tests.sh
  test/performance-tests.sh
  test/presubmit-tests.sh
  test/upgrade-tests.sh
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/testgrid/testgrid.go
Labels: approved, lgtm, size/L

#2437 Add timeoutSeconds to RevisionSpec
  Gopkg.lock
  Gopkg.toml
  pkg/apis/networking/v1alpha1/clusteringress_validation_test.go
  pkg/apis/serving/v1alpha1/configuration_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/service_defaults_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/field_error.go
Labels: approved, lgtm, size/L

#2501 Add coverage for MarkRevisionCreationFailed
  pkg/apis/serving/v1alpha1/configuration_types_test.go
Labels: approved, lgtm, size/S

#2502 Rename upgrade-tests.sh to e2e-upgrade-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, lgtm, size/XS

#2493 Refactor the Configuration following #2447
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/XL

#2477 Filter ClusterIngress by controller class
  pkg/reconciler/filter.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
Labels: approved, lgtm, size/M

#2487 Remove arbitrary 20 second sleep in queue-proxy.
  cmd/queue/main.go
Labels: approved, lgtm, size/M

#2506 Fix downgrade test name
  test/upgrade/service_postdowngrade_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/service_preupgrade_test.go
Labels: approved, lgtm, size/XS

#2447 Convert the Revision controller to use functional options to reduce boilerplate.
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/XXL

#2450 Implement E2E test that kills pods under an in-flight request.
  test/e2e/destroypod_test.go
  test/test_images/timeout/README.md
  test/test_images/timeout/timeout.go
Labels: approved, lgtm, size/L

#2503 Rename kbuffer revision_response_count to revision_request_count
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  pkg/kbuffer/handler/handler.go
  pkg/kbuffer/handler/handler_test.go
  pkg/kbuffer/revision.go
  pkg/kbuffer/revision_test.go
  pkg/kbuffer/stats_reporter.go
  pkg/kbuffer/stats_reporter_test.go
  pkg/metrics/config.go
Labels: approved, lgtm, size/L

#2491 Update spec.md with additional Service examples
  docs/spec/spec.md
Labels: approved, lgtm

#2508 Drop useless constant parameter.
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, lgtm, size/L

#2512 Don't use go_test_e2e() with performance tests
  test/performance-tests.sh
Labels: approved, lgtm, size/XS

#2516 Fix virtualservice event
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
Labels: approved, lgtm, size/XS

#2486 Add configmap for clusteringress
  config/config-istio.yaml
  hack/update-codegen.sh
  pkg/reconciler/v1alpha1/clusteringress/config/doc.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio_test.go
  pkg/reconciler/v1alpha1/clusteringress/config/store.go
  pkg/reconciler/v1alpha1/clusteringress/config/store_test.go
  pkg/reconciler/v1alpha1/clusteringress/config/testdata/config-istio.yaml
  pkg/reconciler/v1alpha1/clusteringress/config/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#2476 Pass annotations from route to clusteringress
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
Labels: approved, lgtm, size/S

#2519 Remove the e2e when running go test.
  test/performance-tests.sh
Labels: approved, lgtm, size/XS

#2518 Revert "Rename Activator to KBuffer (#2405)"
  cmd/activator/OWNERS
  cmd/activator/kodata/HEAD
  cmd/activator/kodata/LICENSE
  cmd/activator/kodata/VENDOR-LICENSE
  cmd/activator/main.go
  cmd/queue/main.go
  config/400-activator-service.yaml
  config/activator.yaml
  config/config-logging.yaml
  config/monitoring/logging/elasticsearch/100-fluentd-configmap.yaml
  config/monitoring/logging/stackdriver/100-fluentd-configmap.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  config/monitoring/metrics/prometheus/100-prometheus-scrape-config.yaml
  docs/scaling/DEVELOPMENT.md
  pkg/activator/OWNERS
  pkg/activator/README.md
  pkg/activator/activator.go
  pkg/activator/dedupe.go
  pkg/activator/dedupe_test.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/enforce_length_handler.go
  pkg/activator/handler/enforce_length_handler_test.go
  pkg/activator/handler/filtering_handler.go
  pkg/activator/handler/filtering_handler_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/requestevent_handler.go
  pkg/activator/handler/requestevent_handler_test.go
  pkg/activator/images/activator_activeRevision.png
  pkg/activator/images/activator_reserveRevision.png
  pkg/activator/images/routeTraffic.png
  pkg/activator/revision.go
  pkg/activator/revision_test.go
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
  pkg/activator/util/header.go
  pkg/activator/util/header_test.go
  pkg/activator/util/io_test.go
  pkg/activator/util/rewinder.go
  pkg/activator/util/rewinder_test.go
  pkg/activator/util/transports.go
  pkg/activator/util/transports_test.go
  pkg/apis/autoscaling/v1alpha1/kpa_types_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/logging/config.go
  pkg/reconciler/v1alpha1/route/README.md
  pkg/reconciler/v1alpha1/route/doc/images/active_revisions.svg
  pkg/reconciler/v1alpha1/route/doc/images/inactive_revision.svg
  pkg/reconciler/v1alpha1/route/doc/images/inactive_revisions.svg
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  test/conformance/blue_green_test.go
Labels: approved, lgtm, size/XL

#2525 Update EnqueueLabelOf usage
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/route.go
  vendor/github.com/knative/pkg/controller/controller.go
Labels: approved, lgtm, size/M

#2431 Re-enable Route prober in the tests
  test/conformance/route_test.go
  test/conformance/service_test.go
Labels: approved, lgtm, size/XS

#2504 [RELEASE 0.2] Cherry pick #2429
  hack/release.sh
Labels: approved, lgtm, size/S

#2409 Prevent replacing "default" other than in namespace
  test/e2e/helloworld_shell_test.go
Labels: approved, lgtm, size/XS

#2527 Networking to own queue and activator
  cmd/queue/OWNERS
  pkg/activator/OWNERS
  pkg/http/h2c/OWNERS
  pkg/queue/OWNERS
Labels: approved, lgtm, size/XS

#2522 Have queue-proxy enforce revisiontimeout
  cmd/queue/main.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/queue_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/util.go
Labels: approved, lgtm, size/L

#2530 Only use more than one activator in testing.
  config/activator.yaml
  test/cluster.sh
Labels: approved, lgtm, size/XS

#2535 Use WaitForEndpointState instead of ProbeDomain
  test/conformance/blue_green_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/single_threaded_test.go
  test/route.go
Labels: approved, lgtm, size/M

#2542 Run gofmt
  pkg/reconciler/v1alpha1/revision/table_test.go
  test/performance/observed_concurency_test.go
  test/prometheus/prometheus.go
  test/service.go
  vendor/github.com/prometheus/procfs/fixtures/26231/exe
Labels: approved, lgtm, size/S

#2472 Simplify instructions so less linking is required
  DEVELOPMENT.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#2545 Use the metrics constants in autoscaler and activator stats reporter
  Gopkg.lock
  Gopkg.toml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
  pkg/autoscaler/stats_reporter.go
  pkg/autoscaler/stats_reporter_test.go
  vendor/github.com/knative/pkg/metrics/doc.go
  vendor/github.com/knative/pkg/metrics/metricskey/constants.go
Labels: approved, lgtm, size/L

#2520 Document additional env vars in runtime contract
  docs/runtime-contract.md
Labels: approved, lgtm, size/XS

#2550 Fix concurrencyModel in api example
  docs/spec/normative_examples.md
Labels: approved, kind/doc, lgtm, size/XS

#2548 add response code class for activator metrics
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
Labels: approved, lgtm, size/M

#2551 Readd a 20 second sleep before shutting down a user-level container.
  cmd/queue/main.go
  third_party/istio-1.0.2/istio.yaml
  third_party/istio-1.0.2/prestop-sleep.yaml.patch
Labels: approved, lgtm, size/S

#2345 Provide an e2e test that asserts autoscaler stability
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/M

#2556 Add Dan to the list of folks getting assigned reviews.
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2563 Docs for Active not being a terminal condition for Revisions
  docs/spec/errors.md
Labels: approved, lgtm, size/S

#2559 Publish nightly knative/serving releases to knative-nightly
  Gopkg.lock
  hack/release.md
  hack/release.sh
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/imports.go
  vendor/github.com/knative/test-infra/tools/testgrid/testgrid.go
Labels: approved, lgtm, size/M

#2567 Set terminationGrace of a pod according to the timeout of the revision.
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  test/configuration.go
  test/crd.go
  test/e2e/destroypod_test.go
Labels: approved, lgtm, size/M

#2358 Queue Prometheous Exporter
  cmd/queue/main.go
  pkg/queue/stats_reporter.go
  pkg/queue/stats_reporter_test.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#2558 Update activator metrics name per review
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
Labels: approved, lgtm, size/S

#2561 Make verify-codegen.sh also check /vendor
  DEVELOPMENT.md
  hack/verify-codegen.sh
Labels: approved, lgtm, size/XS

#2560 Remove the use system-node-critical priority class
  config/monitoring/logging/elasticsearch/200-fluentd.yaml
  config/monitoring/logging/stackdriver/200-fluentd.yaml
Labels: approved, lgtm, size/XS

#2574 Fix issues in ManagedConnection
  pkg/websocket/connection.go
  pkg/websocket/connection_test.go
Labels: approved, lgtm, size/M

#2510 Applying functional options to the Route controller.
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/XXL

#2584 Clean up Gateway for upgrade test.
  test/cluster.sh
Labels: approved, lgtm, size/XS

#2585 Relax the pod count range in TestAutoscaleUpCountPods.
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XS

#2434 Allow config ingress gateway
  Gopkg.lock
  Gopkg.toml
  config/202-gateway.yaml
  docs/setting-up-custom-ingress-gateway.md
  docs/setting-up-ingress-static-ip.md
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/names/names.go
  pkg/reconciler/v1alpha1/route/resources/service_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  test/README.md
  test/cluster.sh
  test/e2e/helloworld_shell_test.go
  test/performance/performance.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/github.com/knative/pkg/apis/istio/authentication/v1alpha1/policy_types.go
  vendor/github.com/knative/pkg/apis/istio/common/v1alpha1/string.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/destinationrule_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/metrics/metricskey/constants.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
Labels: approved, area/networking, kind/feature, lgtm, size/XL

#2552 Guard RequestedPodCount metric against negative values.
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
Labels: approved, lgtm, size/XS

#2586 Try to fixup #2117
  docs/spec/spec.md
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  test/configuration.go
  test/crd.go
  test/e2e/resources_test.go
  test/test_images/bloatingcow/README.md
  test/test_images/bloatingcow/bloatingcow.go
Labels: approved, lgtm, size/L

#2457 Reconcile HPA class PodAutoscalers #2
  cmd/autoscaler/main.go
  config/200-clusterrole.yaml
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  pkg/apis/autoscaling/v1alpha1/pa_defaults_test.go
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/autoscaling/v1alpha1/pa_types_test.go
  pkg/apis/autoscaling/v1alpha1/pa_validation.go
  pkg/apis/autoscaling/v1alpha1/pa_validation_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa_test.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/doc.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_test.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
  pkg/reconciler/v1alpha1/testing/listers.go
Labels: approved, area/autoscale, lgtm, size/XL

#2538 Try to reduce flakes due to Istio control plane overload
  test/cluster.sh
  third_party/istio-1.0.2/download-istio.sh
  third_party/istio-1.0.2/istio-lean.yaml
  third_party/istio-1.0.2/istio.yaml
Labels: approved, lgtm, size/S

#2591 Run goimports
  pkg/apis/serving/v1alpha1/metadata_validation_test.go
  pkg/apis/serving/v1alpha1/service_validation.go
  test/conformance/configuration_test.go
  test/conformance/util.go
  test/service.go
Labels: approved, lgtm, size/S

#2597 Make e2e tests wait for knative-ingressgateway if exists.
  test/cluster.sh
Labels: approved, lgtm, size/XS

#2546 Move to Istio 1.0.4
  DEVELOPMENT.md
  hack/generate-yamls.sh
  third_party/istio-1.0.4/README.md
  third_party/istio-1.0.4/download-istio.sh
  third_party/istio-1.0.4/istio-crds.yaml
  third_party/istio-1.0.4/istio-lean.yaml
  third_party/istio-1.0.4/istio.yaml
  third_party/istio-1.0.4/namespace.yaml.patch
  third_party/istio-1.0.4/prestop-sleep.yaml.patch
Labels: approved, lgtm, size/XL
