Repository knative/serving, pull requests merged in 2018-08, with the labels that each got.

#1770 Invert the relationship between controller.Base and derivatives.
  cmd/controller/main.go
  cmd/multitenant-autoscaler/main.go
  pkg/controller/autoscaling/autoscaling.go
  pkg/controller/autoscaling/autoscaling_test.go
  pkg/controller/configuration/configuration.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/queueing_test.go
  pkg/controller/controller.go
  pkg/controller/keep.go
  pkg/controller/revision/queueing_test.go
  pkg/controller/revision/revision.go
  pkg/controller/revision/revision_test.go
  pkg/controller/revision/table_test.go
  pkg/controller/route/cruds.go
  pkg/controller/route/cruds_test.go
  pkg/controller/route/labels.go
  pkg/controller/route/queueing_test.go
  pkg/controller/route/route.go
  pkg/controller/route/route_test.go
  pkg/controller/route/table_test.go
  pkg/controller/service/service.go
  pkg/controller/service/service_test.go
  pkg/controller/testing/table.go
Labels: approved, lgtm, size/XL

#1671 Refactor revision.go: move the reconciling logic from revision.go to cruds.go
  pkg/controller/revision/cruds.go
  pkg/controller/revision/reconcile_resources.go
  pkg/controller/revision/revision.go
  pkg/controller/route/reconcile_resources.go
  pkg/controller/route/reconcile_resources_test.go
Labels: approved, lgtm, size/XXL

#1777 Move to use the controller.Impl from knative/pkg
  Gopkg.lock
  cmd/controller/main.go
  cmd/multitenant-autoscaler/main.go
  pkg/controller/autoscaling/autoscaling.go
  pkg/controller/autoscaling/autoscaling_test.go
  pkg/controller/configuration/configuration.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/queueing_test.go
  pkg/controller/reconciler.go
  pkg/controller/revision/queueing_test.go
  pkg/controller/revision/revision.go
  pkg/controller/revision/revision_test.go
  pkg/controller/revision/table_test.go
  pkg/controller/route/queueing_test.go
  pkg/controller/route/route.go
  pkg/controller/route/route_test.go
  pkg/controller/route/table_test.go
  pkg/controller/service/service.go
  pkg/controller/service/service_test.go
  pkg/controller/testing/table.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/logging/config.go
Labels: approved, lgtm, size/L

#1775 Add documentation about Route's Istio child objects.
  pkg/controller/route/README.md
  pkg/controller/route/doc/images/active_revisions.svg
  pkg/controller/route/doc/images/inactive_revision.svg
  pkg/controller/route/doc/images/inactive_revisions.svg
Labels: approved, lgtm, size/M

#1726 Add activator metrics and dashboard
  cmd/activator/main.go
  config/activator.yaml
  config/monitoring/150-elasticsearch/100-scaling-configmap.yaml
  config/monitoring/200-common/300-prometheus/100-scrape-config.yaml
  pkg/activator/activator.go
  pkg/activator/dedupe.go
  pkg/activator/dedupe_test.go
  pkg/activator/revision.go
  pkg/activator/revision_test.go
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
  pkg/controller/names.go
  pkg/controller/route/resources/virtual_service.go
  pkg/controller/route/resources/virtual_service_test.go
  pkg/controller/route/route_test.go
Labels: approved, lgtm, size/XXL

#1785 Disable the service-to-service test.
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/L

#1782 Move docs missed due to merge conflict.
  pkg/reconciler/v1alpha1/route/README.md
  pkg/reconciler/v1alpha1/route/doc/images/active_revisions.svg
  pkg/reconciler/v1alpha1/route/doc/images/inactive_revision.svg
  pkg/reconciler/v1alpha1/route/doc/images/inactive_revisions.svg
Labels: approved, lgtm, size/XS

#1781 Use pks/apis oneof error methods.
  Gopkg.lock
  Gopkg.toml
  pkg/apis/serving/v1alpha1/route_validation.go
  pkg/apis/serving/v1alpha1/route_validation_test.go
  pkg/apis/serving/v1alpha1/service_validation.go
  pkg/apis/serving/v1alpha1/service_validation_test.go
  vendor/github.com/knative/pkg/apis/field_error.go
Labels: approved, lgtm, size/L

#1786 Accept goroutines less than original as success.
  pkg/autoscaler/statserver/server_test.go
Labels: approved, lgtm, size/XS

#1771 Use Istio 1.0.0.
  DEVELOPMENT.md
  docs/creating-a-kubernetes-cluster.md
  hack/release.sh
  test/e2e-tests.sh
  third_party/istio-1.0-prerelease/README.md
  third_party/istio-1.0.0/README.md
  third_party/istio-1.0.0/download-istio.sh
  third_party/istio-1.0.0/istio.yaml
  third_party/istio-1.0.0/namespace.yaml.patch
Labels: approved, lgtm, size/XXL

#1788 Route.Reconcile() to return no error in case of missing target.
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
Labels: approved, lgtm, size/S

#1789 Make `cluster.local` domain works without sidecar.
  pkg/reconciler/v1alpha1/route/resources/names/names.go
  pkg/reconciler/v1alpha1/route/resources/service.go
  pkg/reconciler/v1alpha1/route/resources/service_test.go
Labels: approved, lgtm, size/S

#1725 [RELEASE 0.1] Change our configurations to work with Istio 1.0 validation.
  config/202-gateway.yaml
  pkg/controller/names.go
  pkg/controller/route/resources/virtual_service_test.go
Labels: approved, lgtm, size/S

#1790 Deflake E2E test: ServiceToServiceTest
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/XS

#1678 Dynamic logging reconfiguration for multitenant autoscaler
  cmd/multitenant-autoscaler/main.go
Labels: approved, lgtm, size/S

#1793 No need to pass a build name around when reconciling a configuration
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
Labels: approved, lgtm, size/M

#1798 Add status propagation tests for Service
  pkg/reconciler/v1alpha1/service/service_test.go
Labels: approved, lgtm, size/L

#1809 Dynamic reconfiguration of multitenant autoscaler
  cmd/autoscaler/main.go
  cmd/multitenant-autoscaler/main.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/config.go
  pkg/autoscaler/dynamic_config.go
  pkg/autoscaler/dynamic_config_test.go
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
  pkg/autoscaler/revision_scaler_test.go
Labels: approved, area/autoscale, lgtm, size/L

#1693 Use table tests for revision scaler (#1677)
  pkg/autoscaler/revision_scaler_test.go
Labels: approved, lgtm, size/L

#1819 Use real listers to simplify table testing
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/table.go
Labels: approved, lgtm, size/XL

#1821 Split e2e test flags into common and serving
  test/adding_tests.md
  test/conformance/blue_green_test.go
  test/e2e/service_to_service_test.go
  test/e2e_flags.go
  test/request.go
Labels: approved, lgtm, size/M

#1823 Update build vendor to HEAD and third-party release.yaml to latest
  Gopkg.lock
  Gopkg.toml
  third_party/config/build/release.yaml
  vendor/github.com/knative/build/AUTHORS
  vendor/github.com/knative/build/cmd/controller/kodata/LICENSE
  vendor/github.com/knative/build/cmd/controller/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/cmd/creds-init/kodata/LICENSE
  vendor/github.com/knative/build/cmd/creds-init/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/cmd/git-init/kodata/LICENSE
  vendor/github.com/knative/build/cmd/git-init/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/cmd/webhook/kodata/LICENSE
  vendor/github.com/knative/build/cmd/webhook/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/pkg/apis/build/register.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/build_template_types.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/build_types.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/register.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/build/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/knative/build/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/knative/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_build.go
  vendor/github.com/knative/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_buildtemplate.go
  vendor/github.com/knative/build/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/code-generator/Godeps/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
Labels: approved, lgtm, size/L

#1723 Introduce short names for Knative resources
  config/300-configuration.yaml
  config/300-revision.yaml
  config/300-route.yaml
  config/300-service.yaml
Labels: approved, lgtm, size/S

#1820 Remove double teardown banner
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1817 Use sort.Slice instead of sort.Sort
  Gopkg.lock
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/code-generator/Godeps/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
Labels: approved, size/L

#1792 Drop Dockerfile in test images
  test/README.md
  test/conformance/test_images/pizzaplanetv1/Dockerfile
  test/conformance/test_images/pizzaplanetv2/Dockerfile
  test/e2e-tests.sh
  test/e2e/helloworld_shell_test.go
  test/e2e/test_images/README.md
  test/e2e/test_images/autoscale/Dockerfile
  test/e2e/test_images/helloworld/Dockerfile
  test/e2e/test_images/httpproxy/Dockerfile
  test/e2e_flags.go
  test/test_images/README.md
  test/test_images/autoscale/README.md
  test/test_images/autoscale/autoscale.go
  test/test_images/helloworld/README.md
  test/test_images/helloworld/helloworld.go
  test/test_images/helloworld/helloworld.yaml
  test/test_images/httpproxy/README.md
  test/test_images/httpproxy/httpproxy.go
  test/test_images/pizzaplanetv1/README.md
  test/test_images/pizzaplanetv1/main.go
  test/test_images/pizzaplanetv2/README.md
  test/test_images/pizzaplanetv2/main.go
  test/upload-test-images.sh
Labels: approved, lgtm, size/L

#1835 Update to the latest and greatest knative/pkg
  Gopkg.lock
  Gopkg.toml
  cmd/webhook/main.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/volatile_time_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/revision/helpers_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  vendor/github.com/knative/pkg/apis/doc.go
  vendor/github.com/knative/pkg/apis/volatile_time.go
  vendor/github.com/knative/pkg/apis/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#1808 Implement "observed concurrency" performance test.
  test/README.md
  test/performance/README.md
  test/performance/observed-concurrency/README.md
  test/performance/observed-concurrency/observed_concurrency.go
  test/performance/observed-concurrency/reporter.lua
  test/performance/observed-concurrency/run.sh
Labels: approved, lgtm, size/L

#1780 Update copyright to 'Knative Authors'
  test/configuration.go
  test/logging.go
  test/route.go
  test/service.go
Labels: approved, area/test-and-release, kind/cleanup, lgtm, size/S

#1758 Fix flakiness in the autoscaler stat server tests
  pkg/autoscaler/statserver/server.go
  pkg/autoscaler/statserver/server_test.go
  pkg/autoscaler/statserver/server_testing_test.go
Labels: approved, lgtm, size/M

#1689 Activator unit tests
  cmd/activator/main.go
  cmd/queue/main.go
  pkg/activator/activator.go
  pkg/activator/handler/coverage.out
  pkg/activator/handler/enforce_length_handler.go
  pkg/activator/handler/enforce_length_handler_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/reporting_handler.go
  pkg/activator/handler/reporting_handler_test.go
  pkg/activator/util/coverage.out
  pkg/activator/util/io_test.go
  pkg/activator/util/retryer.go
  pkg/activator/util/retryer_test.go
  pkg/activator/util/rewinder.go
  pkg/activator/util/rewinder_test.go
  pkg/activator/util/transports.go
  pkg/activator/util/transports_test.go
  pkg/h2c/transport.go
Labels: approved, lgtm, size/XXL

#1825 Define the KPA resource.
  config/300-kpa.yaml
  hack/update-codegen.sh
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/doc.go
  pkg/apis/autoscaling/v1alpha1/kpa_defaults.go
  pkg/apis/autoscaling/v1alpha1/kpa_defaults_test.go
  pkg/apis/autoscaling/v1alpha1/kpa_types.go
  pkg/apis/autoscaling/v1alpha1/kpa_types_test.go
  pkg/apis/autoscaling/v1alpha1/kpa_validation.go
  pkg/apis/autoscaling/v1alpha1/kpa_validation_test.go
  pkg/apis/autoscaling/v1alpha1/register.go
  pkg/apis/autoscaling/v1alpha1/register_test.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_autoscaling_client.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_podautoscaler.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/podautoscaler.go
  pkg/client/informers/externalversions/autoscaling/interface.go
  pkg/client/informers/externalversions/autoscaling/v1alpha1/interface.go
  pkg/client/informers/externalversions/autoscaling/v1alpha1/podautoscaler.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/autoscaling/v1alpha1/expansion_generated.go
  pkg/client/listers/autoscaling/v1alpha1/podautoscaler.go
Labels: approved, lgtm, size/XXL

#1836 This adds the KPA to our webhook validation and defaulting.
  cmd/webhook/main.go
Labels: approved, lgtm, size/XS

#1814 Backoff retries in the activator.
  cmd/activator/main.go
  pkg/activator/util/retryer.go
  pkg/activator/util/retryer_test.go
Labels: approved, lgtm, size/L

#1822 [RELEASE 0.1] Update build release.yaml to build 0.1.1
  third_party/config/build/release.yaml
Labels: approved, lgtm, size/XS

#1826 Create the method for synthesizing KPA from Revision.
  pkg/reconciler/v1alpha1/revision/resources/kpa.go
  pkg/reconciler/v1alpha1/revision/resources/kpa_test.go
  pkg/reconciler/v1alpha1/revision/resources/names/names.go
  pkg/reconciler/v1alpha1/revision/resources/names/names_test.go
Labels: approved, lgtm, size/L

#1841 Have the Revision controller start producing KPAs.
  cmd/controller/main.go
  config/200-clusterrole.yaml
  pkg/logging/logkey/constants.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, lgtm, size/L

#1811 Switch to default namespace when deploying Knative Serving
  hack/deploy.sh
Labels: approved, lgtm, size/XS

#1854 Adding serving specific name validation to serving.
  Gopkg.lock
  Gopkg.toml
  pkg/apis/serving/v1alpha1/configuration_validation.go
  pkg/apis/serving/v1alpha1/configuration_validation_test.go
  pkg/apis/serving/v1alpha1/metadata_validation.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/route_validation.go
  pkg/apis/serving/v1alpha1/route_validation_test.go
  pkg/apis/serving/v1alpha1/service_validation.go
  pkg/apis/serving/v1alpha1/service_validation_test.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#1852 Create a new DynamicConfig constructor that takes a map.
  cmd/autoscaler/main.go
  cmd/multitenant-autoscaler/main.go
  pkg/autoscaler/dynamic_config.go
  pkg/autoscaler/dynamic_config_test.go
  pkg/autoscaler/multiscaler_test.go
Labels: approved, lgtm, size/M

#1853 Rename key to drop revision prior to switch.
  cmd/multitenant-autoscaler/main.go
  cmd/queue/main.go
  pkg/autoscaler/autoscaler.go
Labels: approved, lgtm, size/S

#1850 Use `false` instead of `exit 1` for failing build
  test/e2e/build_test.go
Labels: approved, lgtm, size/XS

#1842 Vendor the test-infra scripts
  Gopkg.toml
  hack/deploy.sh
  hack/release.sh
  hack/update-deps.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#1862 update filter when using EnqueueControllerOf in route controller
  pkg/reconciler/v1alpha1/route/route.go
Labels: approved, lgtm, size/S

#1864 Turn on the multi-tenant autoscaler.
  config/config-controller.yaml
Labels: approved, lgtm, size/XS

#1830 Rework pkg/autoscaler in terms of KPA.
  cmd/multitenant-autoscaler/main.go
  cmd/queue/main.go
  pkg/apis/autoscaling/register.go
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
  pkg/autoscaler/revision_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/resources/service.go
  pkg/reconciler/v1alpha1/revision/resources/service_test.go
Labels: approved, lgtm, size/XXL

#1861 Cleanup checked in temporary files.
  .gitignore
  pkg/activator/handler/coverage.out
  pkg/activator/util/coverage.out
Labels: approved, lgtm, size/M

#1867 Remove single tenant autoscaler
  cmd/autoscaler/main.go
  cmd/multitenant-autoscaler/OWNERS
  cmd/multitenant-autoscaler/kodata/LICENSE
  cmd/multitenant-autoscaler/kodata/VENDOR-LICENSE
  cmd/multitenant-autoscaler/main.go
  config/autoscaler.yaml
  config/config-controller.yaml
  docs/scaling/DEVELOPMENT.md
  pkg/reconciler/v1alpha1/revision/config/controller.go
  pkg/reconciler/v1alpha1/revision/config/controller_test.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/resources/autoscaler.go
  pkg/reconciler/v1alpha1/revision/resources/autoscaler_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/names/names.go
  pkg/reconciler/v1alpha1/revision/resources/names/names_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/queue_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, lgtm, size/XXL

#1873 Add logic to ignore negative scales.
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
Labels: approved, lgtm, size/S

#1866 Export observed metrics from multi-tenant autoscaler
  cmd/autoscaler/main.go
  config/monitoring/150-elasticsearch/100-scaling-configmap.yaml
  config/monitoring/200-common/300-prometheus/100-scrape-config.yaml
Labels: approved, lgtm, size/S

#1871 Make the conditions better reflect the sequence diagram.
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
Labels: approved, lgtm, size/S

#1875 Log stats received at debug
  pkg/autoscaler/statserver/server.go
Labels: approved, lgtm, size/XS

#1880 Do not read and wrap a nil request body
  pkg/activator/util/rewinder.go
  pkg/activator/util/transports.go
Labels: approved, lgtm, size/S

#1860 Break test clients into different clients so that we can move common parts
  test/adding_tests.md
  test/clients.go
  test/configuration.go
  test/conformance/blue_green_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/crd_checks.go
  test/e2e/autoscale_test.go
  test/e2e/build_test.go
  test/e2e/e2e.go
  test/e2e/errorcondition_test.go
  test/e2e/helloworld_test.go
  test/e2e/service_to_service_test.go
  test/kube_checks.go
  test/request.go
  test/route.go
  test/service.go
Labels: approved, lgtm, size/L

#1884 Re-vendor test-infra to get the latest changes
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#1885 Unit test for nil body in Activator.
  pkg/activator/util/transports_test.go
Labels: approved, lgtm, size/S

#1886 Verify requests succeed while testing autoscaling.
  pkg/activator/util/retryer.go
  pkg/activator/util/retryer_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/e2e/autoscale_test.go
  test/e2e/build_test.go
  test/e2e/helloworld_test.go
  test/e2e/service_to_service_test.go
  test/request.go
Labels: approved, lgtm, size/M

#1887 Remove no longer needed workaround.
  pkg/activator/handler/handler.go
Labels: approved, lgtm, size/XS

#1888 Add a prober in e2e tests route_test and service_test to make sure Route is always healthy during update
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/route.go
Labels: approved, lgtm, size/M

#1897 Create a common test logging library
  test/adding_tests.md
  test/cleanup.go
  test/configuration.go
  test/conformance/blue_green_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/crd.go
  test/e2e/autoscale_test.go
  test/e2e/build_test.go
  test/e2e/e2e.go
  test/e2e/errorcondition_test.go
  test/e2e/helloworld_shell_test.go
  test/e2e/helloworld_test.go
  test/e2e/service_to_service_test.go
  test/e2e_flags.go
  test/logging/logging.go
  test/request.go
  test/route.go
  test/service.go
  test/spoof/spoof.go
  test/util.go
Labels: approved, lgtm, size/L

#1894 Fix TestRouteCreation flakiness
  test/conformance/route_test.go
Labels: approved, lgtm, size/S

#1882 Move all of the logic that changes the deployment scale to KPA scaler.
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, lgtm, size/L

#1901 Refactor the condition logic.
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
Labels: approved, lgtm, size/L

#1904 Log the error of route prober instead of failing the test since the prober is flaky
  test/conformance/route_test.go
  test/conformance/service_test.go
Labels: approved, lgtm, size/XS

#1912 Adopt OWNERS_ALIASES
  OWNERS_ALIASES
  cmd/controller/OWNERS
  pkg/reconciler/OWNERS
Labels: approved, lgtm, size/S

#1900 Change per-Revision Service to the default type ClusterIP.
  pkg/reconciler/v1alpha1/revision/resources/service.go
  pkg/reconciler/v1alpha1/revision/resources/service_test.go
Labels: approved, lgtm, size/XS

#1908 Filter requests sent by the activator itself.
  cmd/activator/main.go
  pkg/activator/handler/filtering_handler.go
  pkg/activator/handler/filtering_handler_test.go
  pkg/activator/util/transports.go
  pkg/activator/util/transports_test.go
Labels: approved, lgtm, size/L

#1893 Update Knative Authors copyright to the year 2018
  cmd/webhook/main.go
  pkg/apis/autoscaling/v1alpha1/kpa_defaults.go
  pkg/apis/autoscaling/v1alpha1/kpa_defaults_test.go
  pkg/apis/autoscaling/v1alpha1/kpa_validation.go
  pkg/apis/autoscaling/v1alpha1/kpa_validation_test.go
  pkg/apis/serving/v1alpha1/configuration_defaults.go
  pkg/apis/serving/v1alpha1/configuration_defaults_test.go
  pkg/apis/serving/v1alpha1/configuration_validation.go
  pkg/apis/serving/v1alpha1/configuration_validation_test.go
  pkg/apis/serving/v1alpha1/metadata_validation.go
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/route_defaults.go
  pkg/apis/serving/v1alpha1/route_defaults_test.go
  pkg/apis/serving/v1alpha1/route_validation.go
  pkg/apis/serving/v1alpha1/route_validation_test.go
  pkg/apis/serving/v1alpha1/service_defaults.go
  pkg/apis/serving/v1alpha1/service_defaults_test.go
  pkg/apis/serving/v1alpha1/service_validation.go
  pkg/apis/serving/v1alpha1/service_validation_test.go
  test/test_images/autoscale/autoscale.go
Labels: approved, lgtm, size/M

#1906 Add a delay following inactivity before scaling to zero.
  cmd/autoscaler/main.go
  config/config-autoscaler.yaml
  pkg/apis/autoscaling/v1alpha1/kpa_types.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
  pkg/autoscaler/dynamic_config_test.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/L

#1902 Use the common logging package form knative/pkg
  Gopkg.lock
  Gopkg.toml
  test/cleanup.go
  test/configuration.go
  test/conformance/blue_green_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/crd.go
  test/e2e/autoscale_test.go
  test/e2e/build_test.go
  test/e2e/e2e.go
  test/e2e/errorcondition_test.go
  test/e2e/helloworld_shell_test.go
  test/e2e/helloworld_test.go
  test/e2e/service_to_service_test.go
  test/e2e_flags.go
  test/request.go
  test/route.go
  test/service.go
  test/spoof/spoof.go
  test/util.go
  vendor/github.com/knative/pkg/test/logging/logging.go
Labels: approved, lgtm, size/M

#1889 Add a lighter istio.yaml, just enough to run Knative serving.
  hack/release.sh
  test/e2e-tests.sh
  third_party/istio-1.0.0/download-istio.sh
  third_party/istio-1.0.0/istio-lean.yaml
Labels: approved, lgtm, size/XXL

#1919 Fix several minor problems with the e2e tests.
  test/e2e-tests.sh
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XS

#1899 Make Revision controller insensitive to ServingState.
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, lgtm, size/XL

#1807 Deflake breaker tests
  pkg/queue/breaker.go
  pkg/queue/breaker_test.go
Labels: approved, lgtm, size/L

#1905 Propagate Active status to Revision.
  docs/spec/errors.md
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, lgtm, size/XL

#1929 Remove the system.Namespace dependency.
  pkg/reconciler/testing/table.go
Labels: approved, lgtm, size/S

#1930 Refactor the reconciler table test logic so that the core is separable into knative/pkg.
  pkg/reconciler/testing/keep.go
  pkg/reconciler/testing/table.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
Labels: approved, lgtm, size/L

#1868 Only reconcile knative service spec we set
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/resources/service.go
Labels: approved, lgtm, size/S

#1938 More logging in e2e tests
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1916 Update the vendored test-infra scripts to the latest version
  Gopkg.lock
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, size/L

#1943 Fix my username in OWNERS_ALIASES.
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1940 Add retries to VirtualService Spec
  pkg/reconciler/v1alpha1/route/resources/virtual_service.go
  pkg/reconciler/v1alpha1/route/resources/virtual_service_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
Labels: approved, lgtm, size/M

#1939 Move to a nightly Istio 1.0.1 release for better installation.
  DEVELOPMENT.md
  docs/creating-a-kubernetes-cluster.md
  hack/release.sh
  test/e2e-tests.sh
  third_party/istio-1.0.1/README.md
  third_party/istio-1.0.1/download-istio.sh
  third_party/istio-1.0.1/istio-lean.yaml
  third_party/istio-1.0.1/istio.yaml
  third_party/istio-1.0.1/namespace.yaml.patch
Labels: approved, lgtm, size/L

#1840 Fix e2e/conformance tests on minikube
  docs/creating-a-kubernetes-cluster.md
  test/README.md
  test/conformance/blue_green_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/e2e/autoscale_test.go
  test/e2e/build_test.go
  test/e2e/e2e.go
  test/e2e/errorcondition_test.go
  test/e2e/helloworld_shell_test.go
  test/e2e/helloworld_test.go
  test/e2e/service_to_service_test.go
  test/e2e_flags.go
  test/upload-test-images.sh
  test/util.go
Labels: approved, lgtm, size/L

#1935 Eliminate loggerWith... functions.
  Gopkg.lock
  Gopkg.toml
  cmd/queue/main.go
  pkg/activator/revision.go
  pkg/autoscaler/multiscaler.go
  pkg/logging/logkey/constants.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/resources/virtual_service.go
  pkg/reconciler/v1alpha1/route/resources/virtual_service_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/service/service.go
  vendor/github.com/knative/pkg/apis/istio/authentication/register.go
  vendor/github.com/knative/pkg/apis/istio/authentication/v1alpha1/doc.go
  vendor/github.com/knative/pkg/apis/istio/authentication/v1alpha1/policy_types.go
  vendor/github.com/knative/pkg/apis/istio/authentication/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/istio/authentication/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/istio/common/v1alpha1/string.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/destinationrule_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/register.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/knative/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/knative/pkg/client/clientset/versioned/fake/register.go
  vendor/github.com/knative/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/authentication/v1alpha1/authentication_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/authentication/v1alpha1/doc.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/authentication/v1alpha1/fake/doc.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/authentication/v1alpha1/fake/fake_authentication_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/authentication/v1alpha1/fake/fake_policy.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/authentication/v1alpha1/generated_expansion.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/authentication/v1alpha1/policy.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/istio/v1alpha3/destinationrule.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/istio/v1alpha3/fake/fake_destinationrule.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/istio/v1alpha3/fake/fake_istio_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/istio/v1alpha3/generated_expansion.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/istio/v1alpha3/istio_client.go
  vendor/github.com/knative/pkg/client/informers/externalversions/authentication/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/authentication/v1alpha1/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/authentication/v1alpha1/policy.go
  vendor/github.com/knative/pkg/client/informers/externalversions/factory.go
  vendor/github.com/knative/pkg/client/informers/externalversions/generic.go
  vendor/github.com/knative/pkg/client/informers/externalversions/istio/v1alpha3/destinationrule.go
  vendor/github.com/knative/pkg/client/informers/externalversions/istio/v1alpha3/interface.go
  vendor/github.com/knative/pkg/client/listers/authentication/v1alpha1/expansion_generated.go
  vendor/github.com/knative/pkg/client/listers/authentication/v1alpha1/policy.go
  vendor/github.com/knative/pkg/client/listers/istio/v1alpha3/destinationrule.go
  vendor/github.com/knative/pkg/client/listers/istio/v1alpha3/expansion_generated.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/logging/logkey/constants.go
Labels: approved, lgtm, size/XXL

#1946 Break revisionActivator.ActiveEndpoint() into smaller chunks.
  Gopkg.lock
  pkg/activator/revision.go
  third_party/VENDOR-LICENSE
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, lgtm, size/XL

#1950 Fix small typo pin spec.md
  docs/spec/spec.md
Labels: approved, lgtm, size/XS

#1949 Set PORT environment var
  pkg/reconciler/v1alpha1/revision/resources/constants.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#1945 Move to Istio 1.0.1 official release.
  third_party/istio-1.0.1/download-istio.sh
  third_party/istio-1.0.1/istio-lean.yaml
  third_party/istio-1.0.1/istio.yaml
Labels: approved, lgtm, size/L

#1917 Add Revision ContainerConcurrency
  cmd/autoscaler/main.go
  cmd/queue/main.go
  config/config-autoscaler.yaml
  docs/spec/spec.md
  pkg/apis/autoscaling/v1alpha1/kpa_defaults.go
  pkg/apis/autoscaling/v1alpha1/kpa_defaults_test.go
  pkg/apis/autoscaling/v1alpha1/kpa_types.go
  pkg/apis/autoscaling/v1alpha1/kpa_validation.go
  pkg/apis/autoscaling/v1alpha1/kpa_validation_test.go
  pkg/apis/serving/v1alpha1/configuration_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/service_defaults_test.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
  pkg/autoscaler/dynamic_config.go
  pkg/autoscaler/dynamic_config_test.go
  pkg/queue/breaker.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling_test.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/kpa.go
  pkg/reconciler/v1alpha1/revision/resources/kpa_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/queue_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XXL

#1968 TestAutoscaleUpDownUp to ignore Evicted pod in when done.
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/S

#1959 Add missing app.yaml and fix minor issue in script.
  test/performance/observed-concurrency/app.yaml
  test/performance/observed-concurrency/run.sh
Labels: approved, lgtm, size/M

#1970 Update knative-ingressgateway to match Istio 1.0.1
  config/202-gateway.yaml
Labels: approved, lgtm, size/M
