Repository knative/serving, pull requests merged in 2018-09, with the labels that each got.

#1947 Assorted fixes in //hack
  hack/deploy.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
Labels: approved, lgtm, size/M

#1975 Update test-infra dependency
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#1974 Remove trampoline methods WithLogging and FromContext
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/multiscaler.go
  pkg/logging/logger.go
  pkg/reconciler/v1alpha1/autoscaling/autoscaling.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/labels.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/service/service.go
Labels: approved, lgtm, size/L

#1896 Fix test resources not being cleaned up
  test/clients.go
Labels: approved, lgtm, size/M

#1978 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#1982 log when probing starts in blue/green conformance tests
  test/conformance/blue_green_test.go
Labels: approved, lgtm, size/XS

#1948 More output for Blue/Green test when Revision fails to come up.
  test/conformance/blue_green_test.go
  test/crd_checks.go
Labels: approved, lgtm, size/M

#1994 Minor nits in e2e tests
  test/e2e-tests.sh
  test/e2e/helloworld_shell_test.go
Labels: approved, lgtm, size/S

#1977 Clean up some of the reconcilation testing infrastructure
  pkg/reconciler/testing/actions.go
  pkg/reconciler/testing/actions_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/sorter.go
  pkg/reconciler/testing/sorter_test.go
  pkg/reconciler/testing/table.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/queueing_test.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/queueing_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/aliases.go
  pkg/reconciler/v1alpha1/testing/factory.go
  pkg/reconciler/v1alpha1/testing/listers.go
Labels: approved, lgtm, size/XL

#1989 Limit burst to 20 requests to reduce e2e flakiness.
  test/crd.go
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XS

#1953 Added constants for serving headers
  pkg/activator/activator.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/reporting_handler.go
  pkg/activator/handler/reporting_handler_test.go
  pkg/reconciler/names.go
  pkg/reconciler/v1alpha1/route/resources/virtual_service.go
  pkg/reconciler/v1alpha1/route/route_test.go
Labels: approved, lgtm, size/M

#1983 bump knative/pkg to 0122abd98318e
  Gopkg.lock
  Gopkg.toml
  test/e2e_flags.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/test/cleanup.go
  vendor/github.com/knative/pkg/test/clients.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/logging/logging.go
Labels: approved, lgtm, size/M

#1891 Use golang.org/x/net/http2/h2c instead of our copy
  Gopkg.lock
  cmd/activator/main.go
  cmd/queue/main.go
  pkg/h2c/h2c.go
  pkg/h2c/transport.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/configure_transport.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/go111.go
  vendor/golang.org/x/net/http2/go17.go
  vendor/golang.org/x/net/http2/h2c/h2c.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/not_go111.go
  vendor/golang.org/x/net/http2/not_go17.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
Labels: approved, lgtm, size/XL

#2001 Add Options structure for test parameters.
  test/configuration.go
  test/conformance/blue_green_test.go
  test/conformance/route_test.go
  test/crd.go
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
  test/e2e/errorcondition_test.go
  test/e2e/helloworld_test.go
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/M

#2007 Add tcnghia to third_party/OWNERS.
  third_party/OWNERS
Labels: approved, lgtm, size/XS

#1985 fix a typo in the scale doc
  docs/scaling/DEVELOPMENT.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1847 Remove retryer and replace with wait package.
  cmd/activator/main.go
  pkg/activator/util/retryer.go
  pkg/activator/util/retryer_test.go
  pkg/activator/util/transports.go
  pkg/activator/util/transports_test.go
Labels: approved, lgtm, size/L

#2003 Have the Revision controller start instantiating Image cache resources.
  cmd/controller/main.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/imagecache.go
  pkg/reconciler/v1alpha1/revision/resources/imagecache_test.go
  pkg/reconciler/v1alpha1/revision/resources/names/names.go
  pkg/reconciler/v1alpha1/revision/resources/names/names_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/testing/factory.go
  pkg/reconciler/v1alpha1/testing/listers.go
Labels: approved, lgtm, size/L

#1915 Allow the activator to deal with multiple service ports.
  pkg/activator/revision.go
  pkg/activator/revision_test.go
  pkg/reconciler/v1alpha1/revision/resources/constants.go
  pkg/reconciler/v1alpha1/revision/resources/service.go
Labels: approved, lgtm, size/M

#1925 Factor out websocket connection primitives.
  cmd/queue/main.go
  pkg/websocket/connection.go
  pkg/websocket/connection_test.go
Labels: approved, lgtm, size/L

#2017 Fix TODO link
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1966 Set Knative application environment variable
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/env_var.go
  test/e2e/envvars_test.go
  test/e2e/helloworld_test.go
  test/test_images/envvars/README.md
  test/test_images/envvars/envvars.go
  test/test_images/envvars/envvars.yaml
Labels: approved, lgtm, size/L

#2014 Add GetGroupVersionKind to our CRD objects
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/configuration_types_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/route_types_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/reconciler/owner_references.go
Labels: approved, lgtm, size/M

#2020 Update Gopkg.lock & VENDOR-LICENSE
  Gopkg.lock
  third_party/VENDOR-LICENSE
Labels: approved, lgtm, size/L

#2023 Report clear error on missing configuration in observed-concurrency test.
  test/performance/observed-concurrency/reporter.lua
Labels: approved, lgtm, size/S

#2004 Include metadata.resourceVersion when applying a PATCH to a CRD
  pkg/reconciler/v1alpha1/route/labels.go
  pkg/reconciler/v1alpha1/route/table_test.go
Labels: approved, lgtm, size/M

#2027 ran codegen.
  vendor/github.com/knative/caching/OWNERS
  vendor/github.com/knative/caching/hack/OWNERS
  vendor/github.com/knative/test-infra/CONTRIBUTING.md
  vendor/github.com/knative/test-infra/LICENSE
  vendor/github.com/knative/test-infra/OWNERS
  vendor/github.com/knative/test-infra/README.md
  vendor/github.com/knative/test-infra/WORKSPACE
  vendor/github.com/knative/test-infra/ci/README.md
  vendor/github.com/knative/test-infra/ci/gubernator/README.md
  vendor/github.com/knative/test-infra/ci/gubernator/config.yaml
  vendor/github.com/knative/test-infra/ci/prow/Makefile
  vendor/github.com/knative/test-infra/ci/prow/README.md
  vendor/github.com/knative/test-infra/ci/prow/boskos/README.md
  vendor/github.com/knative/test-infra/ci/prow/boskos/config.yaml
  vendor/github.com/knative/test-infra/ci/prow/boskos/config_start.yaml
  vendor/github.com/knative/test-infra/ci/prow/boskos/resources.yaml
  vendor/github.com/knative/test-infra/ci/prow/cluster.yaml
  vendor/github.com/knative/test-infra/ci/prow/config.yaml
  vendor/github.com/knative/test-infra/ci/prow/config_start.yaml
  vendor/github.com/knative/test-infra/ci/prow/plugins.yaml
  vendor/github.com/knative/test-infra/ci/prow/prow_setup.md
  vendor/github.com/knative/test-infra/ci/testgrid/Makefile
  vendor/github.com/knative/test-infra/ci/testgrid/README.md
  vendor/github.com/knative/test-infra/ci/testgrid/config.yaml
  vendor/github.com/knative/test-infra/dummy.go
  vendor/github.com/knative/test-infra/images/README.md
  vendor/github.com/knative/test-infra/images/apicoverage/Dockerfile
  vendor/github.com/knative/test-infra/images/apicoverage/Makefile
  vendor/github.com/knative/test-infra/images/apicoverage/README.md
  vendor/github.com/knative/test-infra/images/prow-tests/Dockerfile
  vendor/github.com/knative/test-infra/images/prow-tests/Makefile
  vendor/github.com/knative/test-infra/images/prow-tests/README.md
  vendor/github.com/knative/test-infra/test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/tools/README.md
  vendor/github.com/knative/test-infra/tools/apicoverage/README.md
  vendor/github.com/knative/test-infra/tools/apicoverage/apicoverage.go
  vendor/github.com/knative/test-infra/tools/apicoverage/gcs.go
  vendor/github.com/knative/test-infra/tools/apicoverage/testgrid.go
  vendor/github.com/knative/test-infra/tools/githubhelper/Makefile
  vendor/github.com/knative/test-infra/tools/githubhelper/README.md
  vendor/github.com/knative/test-infra/tools/githubhelper/githubhelper.go
  vendor/k8s.io/code-generator/Godeps/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
Labels: approved, lgtm, size/XXL

#2015 Adding Common Conditionals
  config/config-autoscaler.yaml
  hack/update-codegen.sh
  pkg/activator/revision_test.go
  pkg/apis/autoscaling/v1alpha1/kpa_types.go
  pkg/apis/autoscaling/v1alpha1/kpa_types_test.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/condition_set.go
  pkg/apis/condition_status_type.go
  pkg/apis/doc.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/configuration_types_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/route_types_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/helpers_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/errors_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
Labels: approved, lgtm, size/XXL

#2032 Use compact array syntax.
  pkg/activator/revision_test.go
Labels: approved, lgtm, size/S

#2013 Remove a vestigial test.
  pkg/reconciler/v1alpha1/revision/revision_test.go
Labels: approved, lgtm, size/M

#2034 Use OWNERS_ALIASES for basically all OWNERS files
  OWNERS_ALIASES
  cmd/activator/OWNERS
  cmd/autoscaler/OWNERS
  cmd/queue/OWNERS
  config/monitoring/OWNERS
  docs/debugging/OWNERS
  docs/scaling/OWNERS
  hack/OWNERS
  pkg/activator/OWNERS
  pkg/autoscaler/OWNERS
  pkg/h2c/OWNERS
  pkg/logging/OWNERS
  pkg/queue/OWNERS
  pkg/reconciler/v1alpha1/autoscaling/OWNERS
  test/OWNERS
  third_party/OWNERS
  third_party/config/monitoring/OWNERS
Labels: approved, lgtm, size/L

#2038 Include Active as one of our core Revision conditions.
  pkg/activator/revision_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
Labels: approved, lgtm, size/XS

#2036 Set container-concurrency-target to 1.0 to stabilize autoscaling.
  config/config-autoscaler.yaml
Labels: approved, lgtm, size/XS

#2002 Upgrade to Istio 1.0.2 official release
  DEVELOPMENT.md
  hack/release.sh
  test/e2e-tests.sh
  third_party/istio-1.0.2/README.md
  third_party/istio-1.0.2/download-istio.sh
  third_party/istio-1.0.2/istio-lean.yaml
  third_party/istio-1.0.2/istio.yaml
  third_party/istio-1.0.2/namespace.yaml.patch
Labels: approved, lgtm, size/M

#2053 Disable autoscaling e2e test until flakiness is sorted out.
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XS

#2035 Add Jon and Dave as Serving reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2049 Remove unneeded tests and duck -> duckv1alpha1
  pkg/activator/revision_test.go
  pkg/apis/autoscaling/v1alpha1/kpa_types.go
  pkg/apis/autoscaling/v1alpha1/kpa_types_test.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/configuration_types_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/route_types_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/helpers_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/errors_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
Labels: approved, lgtm, size/XL

#2047 Activator Header Fixes
  cmd/queue/main.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/reporting_handler.go
  pkg/activator/util/header.go
  pkg/activator/util/header_test.go
  pkg/http/header.go
  pkg/http/header_test.go
Labels: approved, lgtm, size/L

#2031 Add a comment clarifying what one of our Route table tests is testing.
  pkg/reconciler/v1alpha1/route/table_test.go
Labels: approved, lgtm, size/XS

#2009 Reconciler configs are snapshotted at the start of each reconciliation
  hack/update-codegen.sh
  pkg/reconciler/config/store.go
  pkg/reconciler/config/store_test.go
  pkg/reconciler/v1alpha1/revision/config/store.go
  pkg/reconciler/v1alpha1/revision/config/store_test.go
  pkg/reconciler/v1alpha1/revision/config/testdata/config-autoscaler.yaml
  pkg/reconciler/v1alpha1/revision/config/testdata/config-logging.yaml
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/resolve.go
  pkg/reconciler/v1alpha1/revision/resolve_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/config/doc.go
  pkg/reconciler/v1alpha1/route/config/store.go
  pkg/reconciler/v1alpha1/route/config/store_test.go
  pkg/reconciler/v1alpha1/route/config/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/testing/aliases.go
Labels: approved, lgtm, size/XXL

#2057 Add coverage of KPA's CanScaleToZero.
  pkg/apis/autoscaling/v1alpha1/kpa_types_test.go
Labels: approved, lgtm, size/M

#2054 Leverage Generation Duck typing for the webhook.
  Gopkg.lock
  Gopkg.toml
  cmd/webhook/main.go
  pkg/apis/autoscaling/v1alpha1/kpa_types.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targettable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/duck_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/fake/fake_duck_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/fake/fake_generational.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/generated_expansion.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/generational.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/generational.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/generic.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/expansion_generated.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/generational.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL

#2059 Add oidc plugin in E2E tests
  Gopkg.lock
  test/clients.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
Labels: approved, lgtm, size/L

#2066 cleanup: remove unused servingSystemInformerFactory
  cmd/controller/main.go
Labels: approved, lgtm, size/XS

#2069 gofmt
  pkg/activator/dedupe_test.go
  pkg/activator/handler/filtering_handler_test.go
  pkg/activator/handler/reporting_handler_test.go
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
  pkg/reconciler/names.go
  pkg/reconciler/v1alpha1/revision/config/observability.go
  pkg/reconciler/v1alpha1/revision/resources/constants.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  test/cleanup.go
  test/conformance/route_test.go
  test/crd.go
  test/test_images/httpproxy/httpproxy.go
Labels: approved, lgtm, size/L

#2067 Update serving to use new FieldError.Also
  Gopkg.lock
  Gopkg.toml
  pkg/apis/autoscaling/v1alpha1/kpa_validation.go
  pkg/apis/autoscaling/v1alpha1/kpa_validation_test.go
  pkg/apis/serving/v1alpha1/configuration_validation.go
  pkg/apis/serving/v1alpha1/configuration_validation_test.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/route_validation.go
  pkg/apis/serving/v1alpha1/route_validation_test.go
  pkg/apis/serving/v1alpha1/service_validation.go
  pkg/apis/serving/v1alpha1/service_validation_test.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/knative/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/knative/pkg/client/clientset/versioned/fake/register.go
  vendor/github.com/knative/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/doc.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/duck_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/fake/doc.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/fake/fake_duck_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/fake/fake_generational.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/fake/fake_kresource.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/fake/fake_target.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/fake/fake_topic.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/generated_expansion.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/generational.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/topic.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/generational.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/topic.go
  vendor/github.com/knative/pkg/client/informers/externalversions/factory.go
  vendor/github.com/knative/pkg/client/informers/externalversions/generic.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/expansion_generated.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/generational.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/topic.go
Labels: approved, lgtm, size/XXL

#2039 add conformance test for labels
  docs/spec/spec.md
  test/conformance/labels_test.go
Labels: approved, lgtm, size/L

#2072 Remove unrelated comment
  pkg/reconciler/v1alpha1/route/table_test.go
Labels: approved, lgtm, size/XS

#2068 Implement Targetable.
  Gopkg.lock
  Gopkg.toml
  docs/spec/spec.md
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/table_test.go
  test/e2e/service_to_service_test.go
  test/states.go
  vendor/github.com/knative/pkg/apis/duck/unstructured.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#2075 Pick up the KindToResource helper.
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targetable_types.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/apis/kind2resource.go
Labels: approved, lgtm, size/L

#2077 Update build vendor to pick up nop-image
  Gopkg.lock
  Gopkg.toml
  third_party/config/build/release.yaml
Labels: approved, lgtm, size/S

#2065 Decouple from build: swap out build client: creating build
  Gopkg.lock
  cmd/controller/main.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/testing/table.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/queueing_test.go
  pkg/reconciler/v1alpha1/configuration/resources/build.go
  pkg/reconciler/v1alpha1/configuration/resources/build_test.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  pkg/reconciler/v1alpha1/testing/factory.go
  test/crd.go
  test/e2e/build_test.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
Labels: approved, lgtm, size/XL

#2042 Add performance tests script to run oberserved concurrency test
  Gopkg.lock
  test/cluster.sh
  test/e2e-tests.sh
  test/performance-tests.sh
  test/performance/observed-concurrency/reporter.lua
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#1851 Rename the monitoring namespace to knative-monitoring (#1774)
  config/config-observability.yaml
  config/monitoring/100-common/100-namespace.yaml
  config/monitoring/150-elasticsearch/100-fluentd-configmap.yaml
  config/monitoring/150-elasticsearch/100-scaling-configmap.yaml
  config/monitoring/150-stackdriver/fluentd-configmap.yaml
  config/monitoring/200-common/100-fluentd.yaml
  config/monitoring/200-common/100-grafana-dash-knative-efficiency.yaml
  config/monitoring/200-common/100-grafana-dash-knative.yaml
  config/monitoring/200-common/100-grafana.yaml
  config/monitoring/200-common/100-istio.yaml
  config/monitoring/200-common/100-zipkin.yaml
  config/monitoring/200-common/200-prometheus-exporter/kube-controller-metrics.yaml
  config/monitoring/200-common/200-prometheus-exporter/prometheus.yaml
  config/monitoring/200-common/300-prometheus/100-scrape-config.yaml
  config/monitoring/200-common/300-prometheus/200-prometheus.yaml
  docs/debugging/application-debugging-guide.md
  docs/telemetry.md
  third_party/config/monitoring/common/istio/istio-dashboard.json
  third_party/config/monitoring/common/istio/mixer-dashboard.json
  third_party/config/monitoring/common/istio/pilot-dashboard.json
  third_party/config/monitoring/common/kubernetes/fluentd/fluentd-ds.yaml
  third_party/config/monitoring/common/kubernetes/kube-state-metrics/100-kube-state-metrics-service-account.yaml
  third_party/config/monitoring/common/kubernetes/kube-state-metrics/200-kube-state-metrics-role.yaml
  third_party/config/monitoring/common/kubernetes/kube-state-metrics/201-kube-state-metrics-role-binding.yaml
  third_party/config/monitoring/common/kubernetes/kube-state-metrics/202-kube-state-metrics-cluster-role.yaml
  third_party/config/monitoring/common/kubernetes/kube-state-metrics/203-kube-state-metrics-cluster-role-binding.yaml
  third_party/config/monitoring/common/kubernetes/kube-state-metrics/300-kube-state-metrics-deployment.yaml
  third_party/config/monitoring/common/kubernetes/kube-state-metrics/300-kube-state-metrics-service.yaml
  third_party/config/monitoring/common/prometheus-operator/dashboards/deployment-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/dashboards/kubernetes-capacity-planning-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/dashboards/kubernetes-cluster-health-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/dashboards/kubernetes-cluster-status-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/dashboards/kubernetes-control-plane-status-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/dashboards/kubernetes-resource-requests-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/dashboards/nodes-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/dashboards/pods-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/dashboards/statefulset-dashboard.json
  third_party/config/monitoring/common/prometheus-operator/node-exporter/100-node-exporter-service-account.yaml
  third_party/config/monitoring/common/prometheus-operator/node-exporter/200-node-exporter-cluster-role.yaml
  third_party/config/monitoring/common/prometheus-operator/node-exporter/201-node-exporter-cluster-role-binding.yaml
  third_party/config/monitoring/common/prometheus-operator/node-exporter/300-node-exporter-daemonset.yaml
  third_party/config/monitoring/common/prometheus-operator/node-exporter/301-node-exporter-service.yaml
  third_party/config/monitoring/elasticsearch/es-service.yaml
  third_party/config/monitoring/elasticsearch/es-statefulset.yaml
  third_party/config/monitoring/elasticsearch/kibana-deployment.yaml
  third_party/config/monitoring/elasticsearch/kibana-service.yaml
Labels: approved, lgtm, size/L

#2085 Override no metrics with ServingState Active
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go
  pkg/reconciler/v1alpha1/autoscaling/kpa_scaler_test.go
Labels: approved, lgtm, size/M

#2024 Removed hardcoded cluster domain form queue-proxy
  cmd/queue/main.go
Labels: approved, lgtm, size/XS

#2083 fix log format in activator
  cmd/activator/main.go
Labels: approved, lgtm, size/XS

#2098 Give autoscaling OWNERS of pkg/apis/autoscaling.
  pkg/apis/autoscaling/OWNERS
Labels: approved, lgtm, size/XS

#2089 Use trackers from knative/pkg.
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/testing/tracker.go
  pkg/reconciler/v1alpha1/revision/buildtracker.go
  pkg/reconciler/v1alpha1/revision/buildtracker_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  vendor/github.com/knative/pkg/tracker/doc.go
  vendor/github.com/knative/pkg/tracker/enqueue.go
  vendor/github.com/knative/pkg/tracker/interface.go
Labels: approved, lgtm, size/XL

#2095 move go init func to the top of the code
  cmd/autoscaler/main.go
  cmd/controller/main.go
Labels: approved, lgtm, size/S

#2063 Re-enable the autoscale UpDownUp e2e test.
  test/e2e/autoscale_test.go
  test/e2e/diagnose.go
  test/test_images/autoscale/autoscale.go
Labels: approved, lgtm, size/L

#2106 Removed ConfigurationName from Route.Status.TrafficTarget
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, lgtm, size/S

#2104 Revert the API portions of #2065.
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/resources/build.go
  pkg/reconciler/v1alpha1/configuration/resources/build_test.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  test/crd.go
  test/e2e/build_test.go
Labels: approved, lgtm, size/L

#2108 Update knative/test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, size/M
