Repository knative/serving, pull requests merged in 2019-02, with the labels that each got.

#2887 Rename TestPerformanceLatency to TestTimeToServeLatency
  test/performance/latency_test.go
Labels: approved, lgtm, size/S

#3060 Increase the timeout for e2e test.
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#3054 move pkg to head:
  Gopkg.lock
  Gopkg.toml
  pkg/logging/config_test.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/logging/config.go
Labels: approved, lgtm, size/M

#3047 Hollow out our ConfigMaps.
  config/999-cache.yaml
  config/config-autoscaler.yaml
  config/config-controller.yaml
  config/config-domain.yaml
  config/config-gc.yaml
  config/config-istio.yaml
  config/config-logging.yaml
  config/config-network.yaml
  config/config-observability.yaml
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
  pkg/gc/config_test.go
  pkg/gc/testdata/config-fail-duration.yaml
  pkg/gc/testdata/config-fail-minimum-generations.yaml
  pkg/gc/testdata/config-gc-defaults.yaml
  pkg/logging/config_test.go
  pkg/reconciler/testing/configmap.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio_test.go
  pkg/reconciler/v1alpha1/revision/config/controller.go
  pkg/reconciler/v1alpha1/revision/config/controller_test.go
  pkg/reconciler/v1alpha1/revision/config/network.go
  pkg/reconciler/v1alpha1/revision/config/network_test.go
  pkg/reconciler/v1alpha1/revision/config/observability.go
  pkg/reconciler/v1alpha1/revision/config/observability_test.go
  pkg/reconciler/v1alpha1/revision/config/store_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/config/domain.go
  pkg/reconciler/v1alpha1/route/config/domain_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  test/e2e/autoscale_test.go
  test/e2e/testdata/config-autoscaler.yaml
Labels: approved, lgtm, size/XL

#3068 An attempt to fix some panics in the tests.
  pkg/pool/pool.go
  pkg/pool/pool_test.go
Labels: approved, lgtm, size/M

#3072 Replace map[string]bool to k8s.Sets.
  pkg/activator/util/transports.go
  pkg/activator/util/transports_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
Labels: approved, lgtm, size/M

#3083 Add missing Lock, formatting, documentation, additional tests.
  pkg/queue/breaker.go
  pkg/queue/breaker_test.go
Labels: approved, lgtm, size/M

#3081 Revert "Update Istio to 1.0.5."
  DEVELOPMENT.md
  hack/generate-yamls.sh
  third_party/istio-1.0.2/README.md
  third_party/istio-1.0.2/conn-timeout.yaml.patch
  third_party/istio-1.0.2/download-istio.sh
  third_party/istio-1.0.2/istio-crds.yaml
  third_party/istio-1.0.2/istio-lean.yaml
  third_party/istio-1.0.2/istio-pilot-hpa.yaml
  third_party/istio-1.0.2/istio.yaml
  third_party/istio-1.0.2/namespace.yaml.patch
  third_party/istio-1.0.2/prestop-sleep.yaml.patch
Labels: approved, lgtm, size/XL

#2873 Update Config Metadata Test for existing Labels and Annotations
  test/conformance/configuration_test.go
Labels: approved, lgtm, size/M

#3073 Make our ConfigMaps significantly more self-documenting.
  config/config-autoscaler.yaml
  config/config-controller.yaml
  config/config-domain.yaml
  config/config-gc.yaml
  config/config-istio.yaml
  config/config-logging.yaml
  config/config-network.yaml
  config/config-observability.yaml
  pkg/autoscaler/config_test.go
  pkg/gc/config_test.go
  pkg/logging/config_test.go
  pkg/reconciler/testing/configmap.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio_test.go
  pkg/reconciler/v1alpha1/revision/config/controller_test.go
  pkg/reconciler/v1alpha1/revision/config/network_test.go
  pkg/reconciler/v1alpha1/revision/config/observability_test.go
  pkg/reconciler/v1alpha1/route/config/domain.go
  pkg/reconciler/v1alpha1/route/config/domain_test.go
Labels: approved, lgtm, size/XL

#3095 Fixing autoscaler url
  cmd/activator/main.go
Labels: approved, lgtm, size/XS

#3093 replace map[string]bool with k8s set.
  pkg/apis/serving/v1alpha1/revision_validation.go
Labels: approved, lgtm, size/S

#3082 Introduce throttler in the activator (do not use it yet)
  pkg/activator/testing/utils.go
  pkg/activator/throttler.go
  pkg/activator/throttler_test.go
  pkg/reconciler/names.go
Labels: approved, lgtm, size/L

#3098 removing hard coded cluster.local references
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio.go
  pkg/reconciler/v1alpha1/route/README.md
Labels: approved, lgtm, size/S

#3061 Allow VolumeMounts to be specified in Container.
  docs/runtime-contract.md
  docs/spec/spec.md
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  test/conformance/volumes_test.go
  test/service.go
  test/test_images/hellovolume/hellovolume.go
  test/test_images/hellovolume/service.yaml
  test/util.go
Labels: approved, lgtm, size/XL

#3091 Use ko's --tags option to publish tags.
  test/upload-test-images.sh
Labels: approved, lgtm, size/S

#3065 Add conformance test for cgroup configuration
  test/conformance/cgroup_test.go
  test/conformance/conformancetest_helper.go
  test/conformance/runtime_contract_types.go
  test/conformance/util.go
  test/test_images/runtime/handlers/handler.go
  test/test_images/runtime/handlers/runtime.go
  test/test_images/runtime/main.go
  test/test_images/runtime/service.yaml
  test/types/runtime.go
Labels: approved, lgtm, size/XL

#3099 Some readability nits, I didn't get a chance to comment
  pkg/activator/throttler.go
  pkg/activator/throttler_test.go
  pkg/queue/breaker.go
Labels: approved, lgtm, size/L

#3102 Default to using 1 pod for istio-ingressgateway.
  third_party/istio-1.0.2/download-istio.sh
  third_party/istio-1.0.2/istio-lean.yaml
  third_party/istio-1.0.2/istio.yaml
Labels: approved, lgtm, size/S

#3092 Clean up deploy_test [2/2]
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
Labels: approved, lgtm, size/XL

#3105 Use t.Name() in place of constants across our e2e testing.
  test/conformance/blue_green_test.go
  test/conformance/configuration_test.go
  test/conformance/envpropagation_test.go
  test/conformance/envvars_test.go
  test/conformance/errorcondition_test.go
  test/conformance/filesystem_perm_test.go
  test/conformance/resources_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/single_threaded_test.go
  test/e2e/build_test.go
  test/e2e/destroypod_test.go
  test/e2e/helloworld_shell_test.go
  test/e2e/helloworld_test.go
  test/e2e/service_to_service_test.go
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/scale_from_zero_test.go
  test/upgrade/service_postdowngrade_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/service_preupgrade_test.go
Labels: approved, lgtm, size/M

#3115 Update google/go-containerregistry
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/doc.go
  vendor/github.com/google/go-containerregistry/pkg/name/registry.go
  vendor/github.com/google/go-containerregistry/pkg/v1/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/hash.go
  vendor/github.com/google/go-containerregistry/pkg/v1/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/with.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/ping.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/transport.go
  vendor/github.com/google/go-containerregistry/pkg/v1/stream/layer.go
Labels: approved, lgtm, size/L

#3121 golang format tools
  pkg/activator/testing/utils.go
  pkg/reconciler/names.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio.go
  pkg/reconciler/v1alpha1/revision/config/controller.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  test/crd.go
  test/crd_checks.go
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/scale_from_zero_test.go
  test/performance/scale_test.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#3046 Fix scale-from-zero perf test units
  test/performance/scale_from_zero_test.go
Labels: approved, lgtm, size/XS

#3124 merge latest test-infra, ignores broken lint links
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/shared/prow/prow.go
Labels: approved, lgtm, size/M

#3117 Fix some stuff around the tests
  test/conformance/service_test.go
  test/conformance/util.go
  test/util.go
Labels: approved, lgtm, size/M

#3135 Use fancier issue templates like knative/docs.
  .github/ISSUE_TEMPLATE/ask-question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: approved, lgtm, size/L

#3118 This modifies the service-to-service test to test cluster-local services.
  test/configuration.go
  test/crd.go
  test/e2e/service_to_service_test.go
  test/route.go
Labels: approved, lgtm, size/M

#3133 move head of the knative/pkg for logging improvements
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/metrics/exporter.go
  vendor/github.com/knative/pkg/metrics/metricskey/constants.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/M

#3136 This is failing knative/serving due to preexisting dead links.
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#3120 Refactor the pool to resolve race condition.
  pkg/pool/pool.go
Labels: approved, lgtm, size/M

#3111 Change the breaker's way of updating capacity.
  pkg/activator/throttler.go
  pkg/queue/breaker.go
  pkg/queue/breaker_test.go
Labels: approved, lgtm, size/L

#3106 Default to using 1 pod for cluster-local-gateway.
  test/e2e-common.sh
  third_party/istio-1.0.2/download-istio.sh
  third_party/istio-1.0.2/istio-lean.yaml
  third_party/istio-1.0.2/istio.yaml
Labels: approved, lgtm, size/S

#3140 Test suite improvements for environments with limited resources
  test/README.md
  test/crd.go
  test/e2e/scale_test.go
Labels: approved, lgtm, size/M

#3084 Make body parsing more robust, report failed requests.
  test/performance/observed_concurency_test.go
Labels: approved, lgtm, size/S

#3104 Add one more case to cover @latest as part of the traffic split.
  test/conformance/service_test.go
  test/crd_checks.go
  test/service.go
Labels: approved, lgtm, size/L

#3041 Tighten up the pod check for autoscale_test.
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/S

#3055 Use actual pods from K8S Informer for scaling rate
  .gitattributes
  cmd/autoscaler/main.go
  cmd/autoscaler/main_test.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/stats_scraper_test.go
Labels: approved, lgtm, size/L

#3143 Semaphore is the internal implementation detail of the breaker.
  pkg/queue/breaker.go
  pkg/queue/breaker_test.go
Labels: approved, lgtm, size/S

#3146 No more dead links in serving md files
  Gopkg.lock
  docs/roadmap/scaling-2018.md
  docs/scaling/DEVELOPMENT.md
  docs/spec/normative_examples.md
  pkg/apis/roadmap-2018.md
  test/presubmit-tests.sh
  test/test_images/environment/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#3144 this is the last change to convert to sets, hopefully
  pkg/autoscaler/autoscaler.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/labeler/labeler.go
  pkg/reconciler/v1alpha1/labeler/labels.go
  pkg/reconciler/v1alpha1/revision/config/controller.go
  pkg/reconciler/v1alpha1/revision/config/controller_test.go
  pkg/reconciler/v1alpha1/revision/config/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/resolve.go
  pkg/reconciler/v1alpha1/revision/resolve_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
Labels: approved, lgtm, size/L

#3156 Drop replicas from the activator.
  config/activator.yaml
Labels: approved, lgtm, size/XS

#3142 Bump timeout of 'TestGlobalResyncOnConfigMapUpdate' to 3 seconds.
  pkg/reconciler/v1alpha1/revision/revision_test.go
Labels: approved, lgtm, size/XS

#2701 Test not scaling to zero with low traffic
  pkg/autoscaler/autoscaler_test.go
Labels: approved, lgtm, size/M

#3113 Increase unit test coverage of hpa controller and pa_types.
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/autoscaling/v1alpha1/pa_types_test.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa_test.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/resources/metric.go
Labels: approved, lgtm, size/L

#3161 Fix spelling errors
  pkg/autoscaler/autoscaler_test.go
  test/conformance/service_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3145 Permit global resync rests to run with count > 1
  Gopkg.lock
  Gopkg.toml
  cmd/activator/main.go
  cmd/queue/main.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/testing/aliases.go
  vendor/github.com/knative/pkg/logging/testing/util.go
  vendor/github.com/knative/pkg/test/clients.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/websocket/connection.go
Labels: approved, lgtm, size/L

#3159 Fix issues pointed out by 'go vet'.
  pkg/autoscaler/statserver/server_test.go
  pkg/reconciler/v1alpha1/revision/helpers_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
  test/conformance/runtime_contract_types.go
Labels: approved, lgtm, size/S

#3158 Fix t.Error/t.Fatal calls in goroutines throughout our tests.
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_test.go
  test/e2e/scale.go
Labels: approved, lgtm, size/L

#3114 Fix network config patching
  hack/dev-patch-config-gke.sh
Labels: approved, lgtm, size/S

#3163 Disable markdown linting in presubmits.
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#3160 golang format tools
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/resolve.go
  pkg/reconciler/v1alpha1/revision/revision.go
  test/conformance/service_test.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#3168 Fix the deploy script
  hack/deploy.sh
Labels: approved, lgtm, size/XS

#3076 Consistently use ObservedGeneration across our types and controllers.
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/networking/v1alpha1/clusteringress_types.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/route.go
  test/states.go
Labels: approved, lgtm, size/S

#3129 Add conformance tests for lifecycle hooks
  test/conformance/container_test.go
Labels: approved, lgtm, size/M

#3162 Format markdown
  docs/resources-overview.md
  docs/roadmap/scaling-2018.md
  docs/spec/normative_examples.md
  docs/spec/spec.md
  pkg/reconciler/v1alpha1/route/README.md
  test/README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#3178 golang format tools
  pkg/reconciler/v1alpha1/revision/revision_test.go
Labels: approved, lgtm, size/XS

#3170 Allow setting the default ClusterIngress class.
  config/config-network.yaml
  hack/update-codegen.sh
  pkg/network/OWNERS
  pkg/network/doc.go
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/network/testdata/config-network.yaml
  pkg/network/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/revision/config/store.go
  pkg/reconciler/v1alpha1/revision/config/store_test.go
  pkg/reconciler/v1alpha1/revision/config/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/config/store.go
  pkg/reconciler/v1alpha1/route/config/store_test.go
  pkg/reconciler/v1alpha1/route/config/testdata/config-network.yaml
  pkg/reconciler/v1alpha1/route/queueing_test.go
  pkg/reconciler/v1alpha1/route/reconcile_resources_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/L

#3173 Replace LimitReadCloser with http.MaxBytesReader.
  pkg/activator/handler/enforce_length_handler.go
  pkg/activator/handler/enforce_length_handler_test.go
  pkg/activator/util/io.go
  pkg/activator/util/io_test.go
  pkg/activator/util/transports_test.go
Labels: approved, lgtm, size/L

#3175 Cleanup some of the breaker/semaphore code.
  cmd/queue/main.go
  pkg/queue/breaker.go
  pkg/queue/breaker_test.go
Labels: approved, lgtm, size/L

#3177 Hoist RevisionReady event to only fire when we're really ready.
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, lgtm, size/M

#3139 Enable throttler in activator
  cmd/activator/main.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/throttler.go
  pkg/activator/throttler_test.go
  pkg/reconciler/filter.go
  pkg/reconciler/filter_test.go
Labels: approved, lgtm, size/XL

#3172 Another attempt at stabilizing global resync tests.
  pkg/reconciler/v1alpha1/revision/revision_test.go
Labels: approved, lgtm, size/M

#3181 Fix validation so users can use generateName
  pkg/apis/serving/v1alpha1/metadata_validation.go
  pkg/apis/serving/v1alpha1/metadata_validation_test.go
Labels: approved, lgtm, size/M

#2990 Move docs and update references
  DEVELOPMENT.md
  docs/debugging/OWNERS
  docs/debugging/application-debugging-guide.md
  docs/debugging/images/autoscaler_dash1.png
  docs/debugging/images/cpu_dash1.png
  docs/debugging/images/request_dash1.png
  docs/debugging/images/zipkin1.png
  docs/debugging/images/zipkin2.png
  docs/debugging/performance-investigation-guide.md
  docs/setting-up-custom-ingress-gateway.md
  docs/setting-up-ingress-static-ip.md
  docs/telemetry.md
Labels: approved, lgtm, size/XL

#3184 Update test-infra to latest
  Gopkg.lock
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/scale_from_zero_test.go
  test/performance/scale_test.go
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/shared/loadgenerator/loadgenerator.go
  vendor/github.com/knative/test-infra/shared/testgrid/testgrid.go
Labels: approved, lgtm, size/M

#3185 Speed up TestAutoscaleUpDownUp
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XS

#3148 Fix TestGlobalResyncOnConfigMapUpdate flakiness
  pkg/reconciler/v1alpha1/revision/revision_test.go
Labels: approved, lgtm, size/L

#3187 Use knative/pkg instead of knative/serving/pkg
  Gopkg.lock
  Gopkg.toml
  cmd/activator/main.go
  cmd/autoscaler/main.go
  cmd/controller/main.go
  cmd/webhook/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/logging/config_test.go
  pkg/network/network_test.go
  pkg/reconciler/testing/table.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_test.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
  pkg/reconciler/v1alpha1/configuration/queueing_test.go
  pkg/reconciler/v1alpha1/revision/config/controller_test.go
  pkg/reconciler/v1alpha1/revision/config/observability_test.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/queue_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/config/domain_test.go
  pkg/reconciler/v1alpha1/route/queueing_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  test/conformance/blue_green_test.go
  test/conformance/single_threaded_test.go
  test/e2e/autoscale_test.go
  test/e2e/build_test.go
  test/upgrade/service_postdowngrade_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/service_preupgrade_test.go
  test/upgrade/upgrade.go
  vendor/github.com/knative/pkg/system/clock.go
  vendor/github.com/knative/pkg/system/names.go
  vendor/github.com/knative/pkg/system/testing/names.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/webhook/webhook.go
  vendor/github.com/knative/pkg/websocket/connection.go
Labels: approved, lgtm, size/L

#3179 Change the naming strategy of revisions and builds
  config/300-revision.yaml
  pkg/reconciler/testing/generate_name_reactor.go
  pkg/reconciler/testing/generate_name_reactor_test.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/resources/build.go
  pkg/reconciler/v1alpha1/configuration/resources/build_test.go
  pkg/reconciler/v1alpha1/configuration/resources/names/doc.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/aliases.go
  pkg/reconciler/v1alpha1/testing/factory.go
  pkg/reconciler/v1alpha1/testing/functional.go
  test/e2e/build_pipeline_test.go
Labels: approved, lgtm, size/XL

#3192 Add a guard to the throttler against exceeding MaxConcurrency.
  pkg/activator/throttler.go
  pkg/activator/throttler_test.go
Labels: approved, lgtm, size/L

#3195 Take sleep out of activator tests.
  pkg/activator/handler/handler_test.go
Labels: approved, lgtm, size/L

#3198 Fix spelling errors
  pkg/reconciler/filter_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3197 golang format tools
  cmd/activator/main.go
  cmd/autoscaler/main.go
  cmd/controller/main.go
  cmd/webhook/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/handler.go
  pkg/reconciler/filter_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_test.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
  pkg/reconciler/v1alpha1/configuration/queueing_test.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/queue_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/queueing_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  test/conformance/blue_green_test.go
  test/conformance/single_threaded_test.go
  test/e2e/autoscale_test.go
  test/e2e/build_test.go
  test/upgrade/service_postdowngrade_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/service_preupgrade_test.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#3196 Format markdown
  DEVELOPMENT.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#3193 Revert setting a timeout in the autoscale test.
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XS

#3147 Conformance Tests for Protocols
  test/conformance/protocol_test.go
  test/conformance/util.go
  test/crd.go
  test/test_images/protocols/README.md
  test/test_images/protocols/protocols.go
  test/util.go
Labels: approved, lgtm, size/L

#3207 Update deps:test-infra - skip presubmit test for documentation only PR
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#3191 Lower SLO for TestScaleToN.
  test/e2e/scale.go
Labels: approved, lgtm, size/S

#3203 FF head for new interface
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/M

#3213 Update Runtime Contract to clarify base HTTP/1.1 Headers
  docs/runtime-contract.md
Labels: approved, lgtm, size/XS

#3029 Add service.yaml files for test images
  test/test_images/autoscale/README.md
  test/test_images/autoscale/service.yaml
  test/test_images/bloatingcow/README.md
  test/test_images/bloatingcow/service.yaml
  test/test_images/environment/README.md
  test/test_images/environment/service.yaml
  test/test_images/failing/README.md
  test/test_images/failing/service.yaml
  test/test_images/helloworld/README.md
  test/test_images/helloworld/service.yaml
  test/test_images/httpproxy/README.md
  test/test_images/httpproxy/service.yaml
  test/test_images/observed-concurrency/README.md
  test/test_images/observed-concurrency/service.yaml
  test/test_images/pizzaplanetv1/README.md
  test/test_images/pizzaplanetv1/service.yaml
  test/test_images/pizzaplanetv2/README.md
  test/test_images/pizzaplanetv2/service.yaml
  test/test_images/printport/README.md
  test/test_images/printport/service.yaml
  test/test_images/singlethreaded/README.md
  test/test_images/singlethreaded/service.yaml
  test/test_images/timeout/README.md
  test/test_images/timeout/service.yaml
Labels: approved, lgtm, size/L

#3204 Reclaim the use of the revision label `configurationGeneration`
  pkg/apis/serving/register.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/resources/build_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  test/states.go
Labels: approved, lgtm, size/L

#3100 Test "/etc/resolv.conf" in filesystem conformance.
  test/conformance/filesystem_perm_test.go
  test/conformance/runtime_contract_types.go
Labels: approved, lgtm, size/M

#2963 Immediately scale up autoscaler for cold-start
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
Labels: approved, lgtm, size/M

#3216 Format markdown
  docs/runtime-contract.md
  test/test_images/failing/README.md
  test/test_images/protocols/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#3206 Fix activator test flakes (again).
  pkg/activator/handler/handler_test.go
Labels: approved, lgtm, size/M

#3219 Bump knative/pkg - we drop webhook logic that increments spec.generation
  Gopkg.lock
  Gopkg.toml
  pkg/apis/autoscaling/v1alpha1/pa_types_test.go
  pkg/apis/networking/v1alpha1/clusteringress_types_test.go
  pkg/apis/serving/v1alpha1/build_compat_test.go
  pkg/apis/serving/v1alpha1/configuration_types_test.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/apis/serving/v1alpha1/route_types_test.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#3116 Add conformance test for request headers
  test/conformance/header_test.go
  test/test_images/runtime/handlers/request.go
  test/types/runtime.go
Labels: approved, lgtm, size/L

#3225 Switch "latest", "candidate", and "current" to be named constants.
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/reconciler/v1alpha1/service/resources/route.go
  pkg/reconciler/v1alpha1/service/resources/route_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
  test/conformance/service_test.go
Labels: approved, lgtm, size/L

#3212 Creator/updator annotations.
  Gopkg.lock
  docs/spec/spec.md
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  test/conformance/service_test.go
Labels: approved, lgtm, size/L

#3220 Validate generateName
  Gopkg.lock
  pkg/apis/serving/v1alpha1/metadata_validation.go
  pkg/apis/serving/v1alpha1/metadata_validation_test.go
  vendor/k8s.io/apimachinery/pkg/api/validation/doc.go
  vendor/k8s.io/apimachinery/pkg/api/validation/generic.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
Labels: approved, lgtm, size/XL

#3228 Add dgerd to list of serving-api-approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3226 Fixes #3201. Improves the speed of ./test/upload-test-images.sh
  test/upload-test-images.sh
Labels: approved, lgtm, size/S

#3199 Remove 'knative.dev/type' from the specification.
  docs/spec/spec.md
  test/test_images/helloworld/helloworld.yaml
Labels: approved, lgtm, size/XS

#3235 golang format tools
  pkg/apis/serving/v1alpha1/service_types.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3214 Revert defaulting of local-gateway settings.
  config/config-istio.yaml
  pkg/reconciler/v1alpha1/clusteringress/config/istio.go
  pkg/reconciler/v1alpha1/clusteringress/config/istio_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
Labels: approved, lgtm, size/L

#3176 Document how to use --ingressendpoint.
  test/README.md
Labels: approved, lgtm, size/S

#3238 Split our cluster role using aggregated cluster roles.
  config/200-clusterrole.yaml
  test/e2e-common.sh
  third_party/config/build/clusterrole.yaml
  third_party/config/pipeline/clusterrole.yaml
Labels: approved, lgtm, size/M

#3234 Cleanup multiscaler test.
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
Labels: approved, lgtm, size/L

#3211 Use test.CreateRunLatestServiceReady in TestProtocols conformance test
  test/conformance/protocol_test.go
Labels: approved, lgtm, size/M

#3227 Fix the test that had a potential deadlock and other beautifications.
  test/performance/observed_concurency_test.go
Labels: approved, lgtm, size/L

#3130 autoscale_test: Make the pod check exit as soon as the desired condition is met.
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/M

#3243 Use latest knative/pkg to pickup websocket/hijack.go.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/test/request.go
  vendor/github.com/knative/pkg/websocket/hijack.go
Labels: approved, lgtm, size/M

#2962 Docs cleanup
  DEVELOPMENT.md
  README.md
  docs/creating-a-kubernetes-cluster.md
  docs/setting-up-a-docker-registry.md
  test/README.md
Labels: approved, lgtm, size/L

#3245 Change our test build to use the aggregated clusterrole.
  test/config/200-clusterrole.yaml
  test/config/201-clusterrolebinding.yaml
Labels: approved, lgtm, size/S

#3240 Add WebSocket support and e2e test to verify.
  pkg/activator/handler/handler.go
  pkg/queue/timeout.go
  test/e2e/websocket_test.go
  test/service.go
  test/test_images/wsserver/README.md
  test/test_images/wsserver/echo.go
  test/test_images/wsserver/service.yaml
Labels: approved, area/networking, lgtm, size/L

#3205 gRPC e2e tests
  test/e2e/grpc_test.go
  test/test_images/grpc-ping/main.go
  test/test_images/grpc-ping/proto/ping.pb.go
  test/test_images/grpc-ping/proto/ping.proto
  test/test_images/grpc-ping/service.yaml
Labels: approved, lgtm, size/XL

#3246 Add missing service.yaml
  test/test_images/protocols/service.yaml
Labels: approved, lgtm, size/S

#3253 Make our ReverseProxies unbuffered and flushable.
  cmd/queue/main.go
  pkg/activator/handler/handler.go
  pkg/queue/timeout.go
  test/e2e/grpc_test.go
Labels: approved, lgtm, size/S

#3171 Run both conformance tests and e2e tests in one command.
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#3263 Document our dependency on 1.12rc1
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#3261 Make all 'CallSyncHandler' tests work the same.
  pkg/reconciler/v1alpha1/configuration/queueing_test.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
Labels: approved, lgtm, size/M

#3260 Remove the need for a doneCh in Multiscaler tests.
  pkg/autoscaler/multiscaler_test.go
Labels: approved, lgtm, size/M

#3244 Flyby changes/improvements to readability.
  pkg/queue/breaker.go
  pkg/queue/stats_reporter.go
  pkg/queue/timeout.go
Labels: approved, lgtm, size/M

#3264 Eliminate global test variables.
  Gopkg.lock
  pkg/autoscaler/config.go
  test/crd.go
  test/e2e/autoscale_test.go
  test/e2e/service_to_service_test.go
  test/e2e/testdata/config-autoscaler.yaml
  test/e2e/websocket_test.go
  vendor/github.com/knative/pkg/test/helpers/data.go
Labels: approved, lgtm, size/L

#3265 Remove logger param from AppendRandomString
  test/conformance/blue_green_test.go
  test/conformance/configuration_test.go
  test/conformance/conformancetest_helper.go
  test/conformance/container_test.go
  test/conformance/errorcondition_test.go
  test/conformance/protocol_test.go
  test/conformance/resources_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/single_threaded_test.go
  test/conformance/volumes_test.go
  test/crd.go
  test/e2e/build_pipeline_test.go
  test/e2e/build_test.go
  test/e2e/e2e.go
  test/e2e/scale.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/scale_from_zero_test.go
Labels: approved, lgtm, size/L

#3266 Share TearDown methods across e2e/conformance
  test/cleanup.go
  test/configuration.go
  test/conformance/blue_green_test.go
  test/conformance/configuration_test.go
  test/conformance/conformancetest_helper.go
  test/conformance/errorcondition_test.go
  test/conformance/protocol_test.go
  test/conformance/resources_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/single_threaded_test.go
  test/conformance/util.go
  test/conformance/volumes_test.go
  test/e2e/autoscale_test.go
  test/e2e/build_pipeline_test.go
  test/e2e/build_test.go
  test/e2e/destroypod_test.go
  test/e2e/e2e.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_shell_test.go
  test/e2e/helloworld_test.go
  test/e2e/scale.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/performance.go
  test/performance/scale_from_zero_test.go
Labels: approved, lgtm, size/L

#3267 Stop using BaseLogger
  Gopkg.lock
  Gopkg.toml
  test/configuration.go
  test/conformance/blue_green_test.go
  test/conformance/cgroup_test.go
  test/conformance/configuration_test.go
  test/conformance/conformancetest_helper.go
  test/conformance/container_test.go
  test/conformance/envpropagation_test.go
  test/conformance/envvars_test.go
  test/conformance/errorcondition_test.go
  test/conformance/filesystem_perm_test.go
  test/conformance/header_test.go
  test/conformance/protocol_test.go
  test/conformance/resources_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/single_threaded_test.go
  test/conformance/sysctl_test.go
  test/conformance/util.go
  test/conformance/volumes_test.go
  test/e2e/autoscale_test.go
  test/e2e/build_pipeline_test.go
  test/e2e/build_test.go
  test/e2e/destroypod_test.go
  test/e2e/diagnose.go
  test/e2e/e2e.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/scale.go
  test/e2e/scale_test.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/performance.go
  test/performance/scale_from_zero_test.go
  test/performance/scale_test.go
  test/prober.go
  test/route.go
  test/service.go
  test/upgrade/service_postdowngrade_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/service_preupgrade_test.go
  test/upgrade/upgrade.go
  test/util.go
  vendor/github.com/knative/pkg/test/clients.go
  vendor/github.com/knative/pkg/test/helpers/data.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/test/request.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
Labels: approved, lgtm, size/XXL

#3269 Use a fake recorder in the SyncHandler tests
  pkg/reconciler/v1alpha1/configuration/queueing_test.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/queueing_test.go
Labels: approved, lgtm, size/S

#3268 Use test name in e2e test resources, so we can tell which resources belong to which test.
  test/adding_tests.md
  test/conformance/blue_green_test.go
  test/conformance/configuration_test.go
  test/conformance/conformancetest_helper.go
  test/conformance/container_test.go
  test/conformance/errorcondition_test.go
  test/conformance/protocol_test.go
  test/conformance/resources_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/single_threaded_test.go
  test/conformance/volumes_test.go
  test/crd.go
  test/e2e/build_pipeline_test.go
  test/e2e/build_test.go
  test/e2e/e2e.go
  test/e2e/scale.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
Labels: approved, lgtm, size/L

#3248 Run e2e tests in parallel
  test/conformance/blue_green_test.go
  test/conformance/cgroup_test.go
  test/conformance/configuration_test.go
  test/conformance/container_test.go
  test/conformance/envpropagation_test.go
  test/conformance/envvars_test.go
  test/conformance/errorcondition_test.go
  test/conformance/filesystem_perm_test.go
  test/conformance/header_test.go
  test/conformance/protocol_test.go
  test/conformance/resources_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/single_threaded_test.go
  test/conformance/sysctl_test.go
  test/conformance/volumes_test.go
  test/e2e-tests.sh
  test/e2e/autoscale_test.go
  test/e2e/build_pipeline_test.go
  test/e2e/build_test.go
  test/e2e/destroypod_test.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_shell_test.go
  test/e2e/helloworld_test.go
  test/e2e/service_to_service_test.go
  test/scale/scale_test.go
Labels: approved, lgtm, size/M

#3271 Improve readability and debuggability of the scale to test
  test/performance/scale_from_zero_test.go
Labels: approved, lgtm, size/M

#3221 Tighten 'MatchesBody' and 'EventuallyMatchesBody' to not mask 503s.
  test/conformance/resources_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/util.go
  test/e2e/autoscale_test.go
  test/e2e/build_pipeline_test.go
  test/e2e/build_test.go
  test/e2e/destroypod_test.go
  test/e2e/helloworld_test.go
  test/e2e/scale.go
  test/performance/scale_from_zero_test.go
  test/upgrade/upgrade.go
Labels: approved, lgtm, size/S

#3277 Remove unnecessary sleep in e2e/autoscale_test
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XS

#3280 update dep for github.com/knative/test-infra
  DEVELOPMENT.md
  Gopkg.lock
  test/e2e_flags.go
  test/upload-test-images.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/shared/prow/prow.go
Labels: approved, lgtm, size/M

#3290 Fail at compile time on unsupported go version
  cmd/activator/main.go
  pkg/goversion/go12.go
  pkg/goversion/goversion.go
Labels: approved, lgtm, size/M

#3286 Retry '503: no healthy upstream' on route creation.
  test/conformance/blue_green_test.go
  test/conformance/conformancetest_helper.go
  test/conformance/protocol_test.go
  test/conformance/resources_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/single_threaded_test.go
  test/e2e/autoscale_test.go
  test/e2e/build_pipeline_test.go
  test/e2e/build_test.go
  test/e2e/destroypod_test.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/scale.go
  test/e2e/service_to_service_test.go
  test/performance/observed_concurency_test.go
  test/performance/scale_from_zero_test.go
  test/route.go
  test/upgrade/upgrade.go
Labels: approved, lgtm, size/M

#3282 Add missing retry for conformance tests.
  test/conformance/util.go
Labels: approved, lgtm, size/XS

#3278 Un-nest activator handler chain
  cmd/activator/main.go
Labels: approved, lgtm, size/S

#3259 Remove all usages of 'MatchesAny', normalized to 'IsStatusOK'.
  test/conformance/blue_green_test.go
  test/conformance/conformancetest_helper.go
  test/conformance/protocol_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/single_threaded_test.go
  test/e2e/grpc_test.go
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/M

#3273 Clarify container-concurrency-target-default works for hpa as well.
  config/config-autoscaler.yaml
Labels: approved, lgtm, size/XS

#3242 Add conformance test to validate stdin
  docs/runtime-contract.md
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  test/conformance/file_descriptor_test.go
  test/test_images/runtime/handlers/proc.go
  test/test_images/runtime/handlers/runtime.go
  test/types/runtime.go
Labels: approved, lgtm, size/L

#3298 Fix for latency metric spurious entries
  test/crd_checks.go
Labels: approved, lgtm, size/S

#3294 fast forward the prom client from test-infra
  Gopkg.lock
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/performance.go
  test/performance/scale_from_zero_test.go
  vendor/github.com/knative/test-infra/shared/prometheus/prometheus.go
Labels: approved, lgtm, size/M

#3262 Make the Pool's concurrency assumptions more clear.
  pkg/pool/interface.go
  pkg/pool/pool.go
  pkg/pool/pool_test.go
Labels: approved, lgtm, size/M

#3295 Update environments.md
  hack/environments.md
Labels: approved, lgtm, size/XS

#2841 Cleanup Prometheus relabel configs
  config/monitoring/metrics/prometheus/100-prometheus-scrape-config.yaml
Labels: approved, lgtm, size/L

#3300 Fail stdin conformance test gracefully
  test/conformance/file_descriptor_test.go
Labels: approved, lgtm, size/XS

#3296 Cleanup 'IsStatusOK()' to 'IsStatusOK'.
  Gopkg.lock
  Gopkg.toml
  test/conformance/blue_green_test.go
  test/conformance/conformancetest_helper.go
  test/conformance/protocol_test.go
  test/conformance/resources_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/single_threaded_test.go
  test/conformance/util.go
  test/e2e/autoscale_test.go
  test/e2e/build_pipeline_test.go
  test/e2e/build_test.go
  test/e2e/destroypod_test.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/scale.go
  test/e2e/service_to_service_test.go
  test/performance/scale_from_zero_test.go
  test/upgrade/upgrade.go
  vendor/github.com/knative/pkg/metrics/exporter.go
  vendor/github.com/knative/pkg/metrics/gcp_metadata.go
  vendor/github.com/knative/pkg/metrics/metricskey/constants.go
  vendor/github.com/knative/pkg/metrics/monitored_resources.go
  vendor/github.com/knative/pkg/metrics/prometheus_exporter.go
  vendor/github.com/knative/pkg/metrics/stackdriver_exporter.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/test/request.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
Labels: approved, lgtm, size/XL

#3289 Bucketize autoscaling metrics by timeframe not by pod name.
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/L

#3167 Add http webhook server to record and return coverage for API resources.
  Gopkg.lock
  test/apicoverage.sh
  test/apicoverage/image/README.md
  test/apicoverage/image/apicoverage-webhook.yaml
  test/apicoverage/image/common/common.go
  test/apicoverage/image/kodata/ignoredfields.yaml
  test/apicoverage/image/main.go
  test/apicoverage/image/rules/coverage_rules.go
  test/apicoverage/image/rules/display_rules.go
  test/apicoverage/image/service-account.yaml
  test/apicoverage/image/webhook/webhook_server.go
  test/apicoverage/tool/main.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/coveragecalculator/README.md
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/coveragecalculator/calculator.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/coveragecalculator/coveragedata.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/coveragecalculator/ignorefields.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/README.md
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/arraykindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/node.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/otherkindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/resourceforest.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/resourcetree.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/rule.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/structkindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/test_util.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/timetypenode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/tools/README.md
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/tools/tools.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/view/README.md
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/view/coverage_display.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/view/jsontype_display.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/view/rule.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/webhook/README.md
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/webhook/webhook.go
Labels: approved, area/API, lgtm, size/XXL

#3257 Add a simple network prober to the activator.
  cmd/activator/main.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  test/e2e/grpc_test.go
Labels: approved, lgtm, size/L

#3311 Make panic propagation in timeout handler deterministic.
  pkg/queue/timeout.go
Labels: approved, lgtm, size/XS

#3315 This makes the output of the perf tests prettier.
  test/performance/observed_concurency_test.go
  test/performance/scale_from_zero_test.go
Labels: approved, lgtm, size/S

#3291 Test upgrades from 0.4.0
  test/e2e-upgrade-tests.sh
Labels: approved, lgtm, size/XS

#3222 Add activator e2e test
  test/e2e/activator_test.go
Labels: approved, lgtm, size/L

#3319 Flyby fixes for the codebase.
  pkg/activator/handler/enforce_length_handler_test.go
  pkg/activator/handler/filtering_handler_test.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/requestevent_handler_test.go
  pkg/activator/util/header_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
  pkg/queue/health/health_state_test.go
  pkg/queue/timeout_test.go
  test/e2e/destroypod_test.go
Labels: approved, lgtm, size/M

#3318 Make dev-patch script actually work
  hack/dev-patch-config-gke.sh
Labels: approved, lgtm, size/S

#3316 Update test-infra
  Gopkg.lock
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/shared/prow/prow.go
Labels: approved, lgtm, size/L
