Repository knative/serving, pull requests merged in 2019-09, with the labels that each got.

#5325 Make port name in Gateway unique by adding namespace prefix
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#5274 Enable mTLS on services in serving-tests ns when mesh is enabled for e2e test
  test/config/mtls/destinationrule.yaml
  test/config/mtls/policy.yaml
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5371 golang format tools
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, ok-to-test, size/XS

#5372 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/injection/informers/kubeinformers/batchv1beta1/cronjob/cronjob.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/batchv1beta1/cronjob/fake/fake.go
  vendor/knative.dev/pkg/metrics/gcp_metadata.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_eventing.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_serving.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/monitored_resources_serving.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5365 Validate max scale up rate and make sure we can scale up.
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#5363 Switch to use the upstream network package for forked functionality.
  cmd/activator/main.go
  pkg/network/domain.go
  pkg/network/domain_test.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/route/config/domain.go
  pkg/reconciler/route/config/domain_test.go
  pkg/reconciler/route/domains/domains.go
  pkg/reconciler/route/resources/names/names.go
  pkg/reconciler/route/table_test.go
  test/e2e/subroutes_test.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#5250 Consistent update for ObservedGeneration for ingress: update observed generation -> reconcile -> update status
  pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/route/route.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, ok-to-test, size/L

#5283 test/apicoverage: Fix apicoverage build and migrate
  Gopkg.lock
  test/apicoverage/image/README.md
  test/apicoverage/image/apicoverage-webhook.yaml
  test/apicoverage/image/rules/coverage_rules.go
  test/apicoverage/image/rules/display_rules.go
  test/apicoverage/image/webhook/webhook_server.go
  test/apicoverage/tools/main.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/coveragecalculator/README.md
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/coveragecalculator/calculator.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/coveragecalculator/coveragedata.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/coveragecalculator/ignorefields.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/README.md
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/arraykindnode.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/node.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/otherkindnode.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/resourceforest.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/resourcetree.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/rule.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/structkindnode.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/test_util.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/resourcetree/timetypenode.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/tools/README.md
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/view/README.md
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/view/html_display.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/view/rule.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/webhook/README.md
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/knative.dev/test-infra/tools/webhook-apicoverage/webhook/webhook.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#5376 golang format tools
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/ingress/ingress.go
  test/apicoverage/image/webhook/webhook_server.go
  test/apicoverage/tools/main.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#5374 Not use sed for modifying config-istio yaml
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5380 Add an ErrorHandler to the httpproxy image.
  test/test_images/httpproxy/httpproxy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5367 Fix wrong cat and kubectl usage in test script
  test/performance/tools/common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5379 Auto-update dependencies
  Gopkg.lock
  pkg/client/certmanager/injection/informers/certmanager/factory/certmanagerfactory.go
  pkg/client/certmanager/injection/informers/certmanager/factory/fake/fake.go
  pkg/client/injection/informers/autoscaling/factory/autoscalingfactory.go
  pkg/client/injection/informers/autoscaling/factory/fake/fake.go
  pkg/client/injection/informers/networking/factory/fake/fake.go
  pkg/client/injection/informers/networking/factory/networkingfactory.go
  pkg/client/injection/informers/serving/factory/fake/fake.go
  pkg/client/injection/informers/serving/factory/servingfactory.go
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/caching/pkg/client/injection/informers/caching/factory/cachingfactory.go
  vendor/knative.dev/caching/pkg/client/injection/informers/caching/factory/fake/fake.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/informers/authentication/factory/authenticationfactory.go
  vendor/knative.dev/pkg/client/injection/informers/authentication/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/informers/istio/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/informers/istio/factory/istiofactory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/knative.dev/pkg/injection/context.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/informers/apiextinformers/factory/factory.go
  vendor/knative.dev/pkg/injection/informers/apiextinformers/factory/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/factory/factory.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/factory/fake/fake.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/ghutil/fakeghutil/fakeghutil.go
  vendor/knative.dev/pkg/test/ghutil/issue.go
  vendor/knative.dev/pkg/test/ghutil/pullrequest.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/message.go
  vendor/knative.dev/pkg/test/prometheus/prometheus.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/slackutil/messaging.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#5334 Enable profiling for e2e test to make sure it is harmless
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5366 In the autoscaler store decider ptrs
  cmd/autoscaler/main.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#5386 Add a logstream within the t.Run in the s2s test.
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5385 Improve error from readiness probe validation
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#5390 Disable test until #5389 is resolved.
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5388 Remove extremely chatty log entry
  pkg/activator/handler/handler.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#5338 use the amdission controller interface for webhook
  Gopkg.lock
  cmd/webhook/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/webhook/resource_admission_controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/L

#5394 Fix tests to run with -count=2 that started failing with Go1.13
  cmd/activator/request_log_test.go
  pkg/activator/handler/metric_handler_test.go
  pkg/activator/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5384 Deflake UTs!
  pkg/reconciler/accessor/core/secret_test.go
  pkg/reconciler/accessor/networking/certificate_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/configuration/queueing_test.go
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/route/queueing_test.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/serverlessservice/global_resync_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#5011 Podip forwarding
  cmd/activator/main.go
  pkg/activator/activator.go
  pkg/activator/activator_test.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
  pkg/activator/throttler.go
  pkg/activator/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/XXL

#5402 golang format tools
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/networking, cla: yes, lgtm, ok-to-test, size/XS

#5408 Fix analyzer for dataplane-probe benchmark
  test/performance/dataplane-probe/sla.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5409 Try GC collection threshold of 500%
  config/activator.yaml
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#5400 Add UT changes to address missing scenario related to metric
  pkg/apis/autoscaling/v1alpha1/metric_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/metric_validation_test.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/pa_validation.go
  pkg/apis/autoscaling/v1alpha1/pa_validation_test.go
  pkg/apis/autoscaling/v1alpha1/register_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#5413 golang format tools
  pkg/apis/autoscaling/v1alpha1/metric_validation_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, ok-to-test, size/XS

#5244 Add an e2e test for RPS based autoscaling
  test/e2e/autoscale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5398 Work with go1.13 by simply deleting explicit flag parsing
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5411 Route cluster-local visibility should take precedence over placeholder Services
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#5418 Fix test bug in websocket_test.go due to activator scale up.
  test/e2e/websocket_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5417 Still sendUpdate from checkDests after ClusterIP is up.
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#5395 Add and update metric status
  pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/metric_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/metric_types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/collector.go
  pkg/autoscaler/collector_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
  pkg/reconciler/metric/metric.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#5407 Import latest knative.dev/pkg
  Gopkg.lock
  test/conformance/runtime/util.go
  test/e2e/helloworld_test.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/calculator.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/coveragedata.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/aggregate_coverage.html
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/html_display.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/type_coverage.html
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/knative.dev/pkg/websocket/connection.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5001 proposed change to RTC: relaxing the definition of container activeness
  docs/runtime-contract.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4463 Create wildcard certificates (#4058)
  cmd/networking/nscert/kodata/HEAD
  cmd/networking/nscert/kodata/LICENSE
  cmd/networking/nscert/kodata/VENDOR-LICENSE
  cmd/networking/nscert/main.go
  config/networking-ns-cert.yaml
  pkg/apis/networking/register.go
  pkg/reconciler/nscert/config/store.go
  pkg/reconciler/nscert/controller.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/nscert/resources/names/names.go
  pkg/reconciler/nscert/resources/names/names_test.go
  pkg/reconciler/nscert/resources/wildcard_certificate.go
  pkg/reconciler/nscert/resources/wildcard_certificate_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/testing/v1alpha1/listers.go
  pkg/testing/v1alpha1/route.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XXL

#5412 Move validation of autoscaling.knative.dev/metric to RevisionTemplateSpec
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/autoscaling/v1alpha1/pa_validation.go
  pkg/apis/autoscaling/v1alpha1/pa_validation_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#5421 Some fixes and improved test coverage for the BRM
  pkg/activator/net/helpers.go
  pkg/activator/net/helpers_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5420 Revise our cold start latency SLAs to 10s (from 15s)
  test/performance/load-test/sla.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5428 Improve the logger situation in metrics collection
  cmd/autoscaler/main.go
  pkg/autoscaler/collector.go
  pkg/autoscaler/collector_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#5414 Update prometheus importing path, update test-infra and pkg
  Gopkg.lock
  test/performance/README.md
  test/performance/performance.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/prometheus/prometheus.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/coveragedata.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/html_display.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/tracing/http.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/shared/prometheus/prometheus.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5424 Activator cleanup step 2.
  cmd/activator/main.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#5438 Simplify the endpoint handling logic.
  pkg/activator/net/revision_backends.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5446 Format markdown
  docs/runtime-contract.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5447 golang format tools
  test/e2e/autoscale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#5437 Normally compute and propagate metric status
  pkg/reconciler/metric/metric.go
  pkg/reconciler/metric/metric_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#5440 Assorted linting fixes
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#5441 Use a WaitGroup instead of simulating one.
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#5439 Add sleeps to the tests that panic in the logger.
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/configuration/queueing_test.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#5460 Remove the params that are never used
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#5449 Add more detailed logging in the activator.
  pkg/activator/net/throttler.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5461 Fix 500s during cold start.
  pkg/activator/net/throttler.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5464 Add json inline annotation
  pkg/apis/autoscaling/v1alpha1/pa_types.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#5445 Use Gateway endpoint for external access test without resolvable domain
  test/e2e/service_to_service_test.go
  test/test_images/httpproxy/httpproxy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5345 Call MarkCertificateNotOwned() when getting NotOwnResource error
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/testing/v1alpha1/route.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#5470 Remove sleeps from the tests now that they are no longer required.
  Gopkg.lock
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/configuration/queueing_test.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/revision/revision_test.go
  vendor/knative.dev/pkg/controller/controller.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#5476 Use tag.MustNewKey instead tag.NewKey
  pkg/activator/stats_reporter.go
  pkg/autoscaler/stats_reporter.go
  pkg/queue/stats/stats_reporter.go
  pkg/reconciler/stats_reporter.go
  pkg/reconciler/stats_reporter_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#5478 Delete duplicated code
  test/v1alpha1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5466 Always pass Healthy dests to the throttler
  pkg/activator/handler/handler_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5479 Remove useless strings.Split
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5471 Stagger the shutdown of the activator.
  cmd/activator/main.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#5477 Make k8schain work with repository-level config
  Gopkg.lock
  Gopkg.toml
  hack/1996.patch
  vendor/github.com/google/go-containerregistry/pkg/authn/helper.go
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/k8schain.go
  vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/authn/multikeychain.go
  vendor/github.com/google/go-containerregistry/pkg/internal/retry/retry.go
  vendor/github.com/google/go-containerregistry/pkg/internal/retry/wait/kubernetes_apimachinery_wait.go
  vendor/github.com/google/go-containerregistry/pkg/logs/logs.go
  vendor/github.com/google/go-containerregistry/pkg/name/ref.go
  vendor/github.com/google/go-containerregistry/pkg/name/repository.go
  vendor/github.com/google/go-containerregistry/pkg/v1/empty/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/empty/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/empty/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/hash.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/mutate.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/rebase.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/uncompressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/with.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/delete.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/descriptor.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/retry.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/stream/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/types/types.go
  vendor/github.com/google/go-containerregistry/pkg/v1/v1util/zip.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#5481 Add the public interface to the new scale down rate functionality in Autoscaler
  config/config-autoscaler.yaml
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
  pkg/autoscaler/multiscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#5482 Use a proper logkey and log on overload.
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5474 rename the variable for resource validation webhook
  Gopkg.lock
  cmd/webhook/main.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/source_stats_reporter.go
  vendor/knative.dev/pkg/metrics/utils.go
  vendor/knative.dev/pkg/webhook/resource_admission_controller.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/L

#5491 Add a missing res.Body.Close() that @tcnghia found.
  pkg/queue/health/probe.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#5467 Propagate ingress label from route label
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#5494 Revert #5241 to rule our resource problem for 503s.
  third_party/istio-1.1.13/istio-lean.yaml
  third_party/istio-1.1.13/values-lean.yaml
  third_party/istio-1.2.4/istio-lean.yaml
  third_party/istio-1.2.4/values-lean.yaml
Labels: approved, cla: yes, lgtm, size/M

#5492 Fix another test bug relating to activator HPA.
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
  test/e2e/grpc_test.go
  test/e2e/websocket_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5493 Return error type from queue breaker
  cmd/queue/main.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
  pkg/queue/breaker.go
  pkg/queue/breaker_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#5500 Add podIP check short circuit when all are healthy in RBM
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5499 Dont tick RBM when using clusterIP
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#5501 Fixes the bug that isAggressive is used as isNotAggressive
  pkg/queue/health/health_state.go
  pkg/queue/health/health_state_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5373 Add nscert yaml to generate-yamls.sh
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#5497 More deflakes in the unit tests
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#5532 Scale crash looping Revisions with minScale to zero.
  pkg/reconciler/revision/resources/pa.go
  pkg/reconciler/revision/resources/pa_test.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#5531 Use gateway endpoints instead of pods in the status prober.
  pkg/reconciler/clusteringress/clusteringress.go
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/status.go
  pkg/reconciler/ingress/status_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#5535 Use Gateway port instead of Endpoints port
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/status.go
  pkg/reconciler/ingress/status_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#5536 Split the throttler test in two and make sure we don't depend on order.
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5533 Updating pkg to latest for 0.9 release.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_eventing.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/metrics/source_stats_reporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/knative.dev/pkg/test/helpers/error.go
  vendor/knative.dev/pkg/test/helpers/run.go
  vendor/knative.dev/pkg/test/mako/alerter/alerter.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/message.go
  vendor/knative.dev/pkg/test/slackutil/fakeslackutil/fakeslackutil.go
  vendor/knative.dev/pkg/test/slackutil/http.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/test/slackutil/message_write.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/calculator.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/aggregate_coverage.html
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/html_display.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/html_template.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/xml_display.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/xml_template.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/boskos/fake/fake.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/zipkin.go
Labels: approved, cla: yes, lgtm, size/XXL

#5537 More test cleanups in activator
  pkg/activator/handler/handler_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5518 Reorder display fields for consistency across CRD
  config/300-pa.yaml
Labels: approved, cla: yes, lgtm, size/S

#5545 Add port filtering for the SKS to keep only the serving port.
  pkg/reconciler/serverlessservice/global_resync_test.go
  pkg/reconciler/serverlessservice/resources/services.go
  pkg/reconciler/serverlessservice/resources/services_test.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  pkg/testing/functional.go
  test/e2e/e2e.go
  test/e2e/service_to_service_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#5540 Expose QueueAdminPort to private Service of the Revision
  pkg/reconciler/serverlessservice/resources/services.go
  pkg/reconciler/serverlessservice/resources/services_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#5547 Reconcile Configuration first when using named Revisions
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
  pkg/testing/v1alpha1/service.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#5550 Add a test that verifies that the requests, when pod is destroyed succeed
  test/e2e/destroypod_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5558 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/shared/common/common.go
  vendor/knative.dev/test-infra/shared/gcs/gcs.go
  vendor/knative.dev/test-infra/shared/junit/junit.go
  vendor/knative.dev/test-infra/shared/prow/prow.go
  vendor/knative.dev/test-infra/shared/testgrid/testgrid.go
  vendor/knative.dev/test-infra/shared/testgrid/yaml.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#5548 Cleanup outdated or moved content
  docs/client-conventions.md
  docs/images/kibana-discover-tab-annotated.png
  docs/images/kibana-landing-page-configure-index.png
  docs/roadmap/monitoring.md
  docs/roadmap/scaling-2018.md
  docs/spec/README.md
  docs/spec/errors.md
  docs/spec/images/auto_rollout.png
  docs/spec/images/build_example.png
  docs/spec/images/build_function.png
  docs/spec/images/initial_creation.png
  docs/spec/images/release_mode.png
  docs/spec/motivation.md
  docs/spec/normative_examples.md
  docs/spec/overview.md
  docs/spec/spec.md
  hack/README.md
  hack/diagnose-me.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#5561 One more rewrite of the loop
  pkg/activator/net/revision_backends.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5562 Limit our use of PrependGenerateNameReactor.
  pkg/reconciler/testing/v1alpha1/factory.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#5512 Remove duplicated response time reporting
  pkg/activator/handler/handler.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#5563 This breaks off a handful of changes needed for 1.15 k8s libs to work.
  pkg/activator/handler/handler_test.go
  pkg/activator/net/revision_backends_test.go
  pkg/reconciler/ingress/resources/gateway_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#5455 test/apicoverage: Created Junit xml result file for apicoverage builds
  test/apicoverage.sh
  test/apicoverage/image/webhook/webhook_server.go
  test/apicoverage/tools/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5568 Format markdown
  docs/client-conventions.md
  docs/spec/errors.md
  docs/spec/normative_examples.md
  docs/spec/overview.md
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5569 golang format tools
  pkg/testing/v1/configuration.go
  pkg/testing/v1/route.go
  pkg/testing/v1/service.go
  test/apicoverage/tools/main.go
  test/conformance/api/v1/blue_green_test.go
  test/conformance/api/v1/configuration_test.go
  test/conformance/api/v1/errorcondition_test.go
  test/conformance/api/v1/generatename_test.go
  test/conformance/api/v1/migration_test.go
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/service_test.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1/volumes_test.go
  test/v1/configuration.go
  test/v1/crd.go
  test/v1/revision.go
  test/v1/route.go
  test/v1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#5571 Unpin serving from release-0.9
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/client.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_eventing.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/workqueue.go
  vendor/knative.dev/pkg/reconciler/testing/generate_name_reactor.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/knative.dev/pkg/testutils/clustermanager/boskos/fake/fake.go
  vendor/knative.dev/pkg/testutils/clustermanager/client.go
  vendor/knative.dev/pkg/testutils/clustermanager/doc.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
Labels: approved, cla: yes, lgtm, size/XL

#5564 Remove the generate name from the SKS private service code
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/serverlessservice/global_resync_test.go
  pkg/reconciler/serverlessservice/resources/services.go
  pkg/reconciler/serverlessservice/resources/services_test.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  pkg/reconciler/testing/v1alpha1/factory.go
  pkg/testing/functional.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#5577 Cleanup a lingering Apps() reference
  test/e2e/autoscale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5575 Kail will be present in the testing image, so don't install it during testing if possible
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5565 Retry route inconsistencies on 'TestDestroyPodWithRequests'.
  test/e2e/destroypod_test.go
  test/v1alpha1/route.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5580 Fix wrong expected body output in TestDestroyPodInflight
  test/e2e/destroypod_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5468 Make ingress skip copying over last-applied-configuration annotation from Route
  pkg/reconciler/route/resources/certificate.go
  pkg/reconciler/route/resources/certificate_test.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#5585 Make network config key and default template const
  pkg/network/network.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#5552 Resolve the Gateway's listening ports via a lookup in the Service definition.
  pkg/reconciler/clusteringress/clusteringress.go
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/status.go
  pkg/reconciler/ingress/status_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#5587 Fix a transposed resource block in the default tests.
  pkg/apis/serving/v1/revision_defaults_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#5588 Replace quoted %s with %q where applicable.
  pkg/autoscaler/http_scrape_client_test.go
  test/conformance/api/v1/errorcondition_test.go
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/errorcondition_test.go
  test/conformance/api/v1alpha1/route_test.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/errorcondition_test.go
  test/conformance/api/v1beta1/route_test.go
  test/conformance/api/v1beta1/util.go
  test/e2e/destroypod_test.go
  test/e2e/helloworld_test.go
  test/e2e/image_pull_error_test.go
  test/e2e/namespace_test.go
  test/e2e/pod_schedule_error_test.go
  test/upgrade/upgrade.go
Labels: approved, area/autoscale, area/test-and-release, cla: yes, lgtm, size/M

#5578 patch kube-dns-autoscaler configmap
  test/performance/tools/common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5592 Improve performance develop document
  test/performance/dev.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5346 Add MarkResourceNotOwned to PodAutoscaler when metrics is not owned
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/reconciler.go
  pkg/testing/functional.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/M

#5581 config/v1 is missed in cleanup section.
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5543 Stop handling the revision with throttler when it was removed
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5593 Improve the throttler code with injected informers.
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5591 Update our dialer to use new helpers.
  pkg/network/transports.go
  pkg/network/transports_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#5595 Use the v1 API for all test yamls.
  test/performance/dataplane-probe/dataplane-probe-setup.yaml
  test/performance/deployment-probe/kodata/basic-template.yaml
  test/performance/load-test/load-test-setup.yaml
  test/test_images/autoscale/service.yaml
  test/test_images/failing/service.yaml
  test/test_images/grpc-ping/service.yaml
  test/test_images/hellovolume/service.yaml
  test/test_images/helloworld/helloworld.yaml
  test/test_images/helloworld/service.yaml
  test/test_images/httpproxy/service.yaml
  test/test_images/observed-concurrency/service.yaml
  test/test_images/pizzaplanetv2/service.yaml
  test/test_images/runtime/service.yaml
  test/test_images/singlethreaded/service.yaml
  test/test_images/timeout/service.yaml
  test/test_images/wsserver/service.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5277 Profile queue-proxy
  cmd/queue/main.go
  pkg/apis/serving/k8s_validation.go
  pkg/metrics/config.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  test/performance/profiling.md
Labels: approved, area/API, area/monitoring, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#5574 Assorted linting fixes.
  cmd/activator/main.go
  pkg/apis/serving/v1beta1/revision_lifecycle.go
  pkg/autoscaler/stats_reporter.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  pkg/reconciler/stats_reporter.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/S

#5601 Format markdown
  test/performance/dev.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#5600 golang format tools
  test/conformance/api/v1alpha1/blue_green_test.go
  test/upgrade/probe_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#5596 Revert "Disable downgrade testing. (#3819)"
  test/e2e-upgrade-tests.sh
  test/upgrade/README.md
  test/upgrade/service_postdowngrade_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5597 Deduplicate error logging for the stats scraper.
  cmd/autoscaler/main.go
  pkg/autoscaler/collector.go
  pkg/autoscaler/collector_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#5603 Upgrade 1.1 and 1.2 Istio to latest.
  third_party/istio-1.1-latest
  third_party/istio-1.1.15/README.md
  third_party/istio-1.1.15/download-istio.sh
  third_party/istio-1.1.15/istio-crds.yaml
  third_party/istio-1.1.15/istio-knative-extras.yaml
  third_party/istio-1.1.15/istio-lean.yaml
  third_party/istio-1.1.15/istio.yaml
  third_party/istio-1.1.15/namespace.yaml.patch
  third_party/istio-1.1.15/prestop-sleep.yaml.patch
  third_party/istio-1.1.15/values-extras.yaml
  third_party/istio-1.1.15/values-lean.yaml
  third_party/istio-1.1.15/values.yaml
  third_party/istio-1.2-latest
  third_party/istio-1.2.6/README.md
  third_party/istio-1.2.6/download-istio.sh
  third_party/istio-1.2.6/istio-crds.yaml
  third_party/istio-1.2.6/istio-knative-extras.yaml
  third_party/istio-1.2.6/istio-lean.yaml
  third_party/istio-1.2.6/istio.yaml
  third_party/istio-1.2.6/namespace.yaml.patch
  third_party/istio-1.2.6/prestop-sleep.yaml.patch
  third_party/istio-1.2.6/values-extras.yaml
  third_party/istio-1.2.6/values-lean.yaml
  third_party/istio-1.2.6/values.yaml
Labels: approved, cla: yes, lgtm, size/L

#5598 Remove redundant errors
  pkg/reconciler/accessor/core/secret.go
  pkg/reconciler/accessor/istio/virtualservice.go
  pkg/reconciler/accessor/networking/certificate.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#5604 Start testing using Istio 1.3.
  third_party/istio-1.3-latest
  third_party/istio-1.3.0/README.md
  third_party/istio-1.3.0/download-istio.sh
  third_party/istio-1.3.0/istio-crds.yaml
  third_party/istio-1.3.0/istio-knative-extras.yaml
  third_party/istio-1.3.0/istio-lean.yaml
  third_party/istio-1.3.0/istio.yaml
  third_party/istio-1.3.0/namespace.yaml.patch
  third_party/istio-1.3.0/values-extras.yaml
  third_party/istio-1.3.0/values-lean.yaml
  third_party/istio-1.3.0/values.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#5607 Clean the rest of the activator code to use injected logger and informers
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5609 Remove the Istio sidecar prestop hook (no longer needed).
  third_party/istio-1.2.6/download-istio.sh
  third_party/istio-1.2.6/istio.yaml
  third_party/istio-1.2.6/prestop-sleep.yaml.patch
Labels: approved, cla: yes, lgtm, size/S

#5572 Fix an oudated comment and some left-over code
  pkg/queue/readiness/probe.go
  pkg/reconciler/route/traffic/traffic.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, ok-to-test, size/XS

#5594 Remove the configuration split now that 1.14 is the minimum version.
  DEVELOPMENT.md
  config/300-configuration.yaml
  config/300-revision.yaml
  config/300-route.yaml
  config/300-service.yaml
  config/v1alpha1/300-configuration.yaml
  config/v1alpha1/300-revision.yaml
  config/v1alpha1/300-route.yaml
  config/v1alpha1/300-service.yaml
  hack/generate-yamls.sh
  hack/update-codegen.sh
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5613 Rename decider option to be local, since it is local only.
  pkg/reconciler/autoscaling/kpa/resources/decider_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#5223 Handle HTTPS redirect, HTTPS, HTTP2 & custom ports in VirtualService probing
  Gopkg.lock
  pkg/reconciler/clusteringress/clusteringress.go
  pkg/reconciler/clusteringress/clusteringress_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/status.go
  pkg/reconciler/ingress/status_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XXL

#5621 Revert 1aa8425 "Remove the istio sidecar prestop hook, it's no longer needed."
  third_party/istio-1.2.6/download-istio.sh
  third_party/istio-1.2.6/istio.yaml
  third_party/istio-1.2.6/prestop-sleep.yaml.patch
  third_party/istio-1.3.0/download-istio.sh
  third_party/istio-1.3.0/istio.yaml
  third_party/istio-1.3.0/prestop-sleep.yaml.patch
Labels: approved, cla: yes, lgtm, size/M

#5201 Downward http scheme only when httproto is enabled on autoTLS.
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#5608 Hide internals of the RBM and Throttler.
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5610 More removals of dead code from the activator handler
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5623 Do not install config/v1 for performance testing setup
  test/performance/tools/common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5625 Hide the RBM in the private package part.
  cmd/activator/main.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#5620 Adjust for breaking changes in knative/pkg.
  Gopkg.lock
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/resources/decider.go
  pkg/reconciler/clusteringress/clusteringress.go
  pkg/reconciler/ingress/ingress.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/configmap/static_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/mako/alerter/alerter.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/config.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/config.yaml
  vendor/knative.dev/pkg/test/mako/alerter/slack/message.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/mako/config/configmap.go
  vendor/knative.dev/pkg/test/mako/config/environment.go
  vendor/knative.dev/pkg/test/mako/config/testdata/config-mako.yaml
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/version/version.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#5524 Merge 8022/health to 8012/8013
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/queue/health/health_state.go
  pkg/queue/health/health_state_test.go
  pkg/queue/readiness/probe.go
  pkg/reconciler/revision/resources/queue.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#5628 Final passes over the throttler and RBM code
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#5576 Remove reviewer who has left the team
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5617 Consistently handle invalid resource key errors.
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/gc/gc.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/metric/metric.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/route/route.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/service/service.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#5642 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/configmap/filter.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/knative.dev/pkg/webhook/config_validation_controller.go
  vendor/knative.dev/pkg/webhook/resource_admission_controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5612 Skip creating certificate and ingressTLS for cluster-local service
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#5627 Remove handling Kubelet probe in queue-proxy
  cmd/queue/main.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#5643 Remove remaining redundant errors in reconcilers
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#5583 Skip tag uniqeness check if no traffic target tag was provided
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
Labels: approved, area/API, cla: yes, kind/bug, lgtm, ok-to-test, size/S

#5636 Do not create wildcard certs when autoTLS is disabled
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#5644 Change `User-Agent` for probe requests from Activator and Queue-proxy
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/testing/roundtripper.go
  pkg/network/network.go
  pkg/queue/health/probe.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#5647 Print error from waitForActivatorEndpoints in e2e test
  test/e2e/autoscale_test.go
  test/e2e/grpc_test.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5649 Fix logstream setup for autoscale test.
  test/e2e/autoscale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS
