Repository knative/serving, pull requests merged in 2019-03, with the labels that each got.

#3336 Update pkg and test-infra deps
  Gopkg.lock
  Gopkg.toml
  test/e2e/helloworld_shell_test.go
  test/e2e_flags.go
  test/performance/performance.go
  vendor/github.com/knative/pkg/test/cleanup.go
  vendor/github.com/knative/pkg/test/clients.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/test/request.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/doc.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
  vendor/github.com/knative/test-infra/shared/prometheus/prometheus.go
Labels: approved, lgtm, size/L

#3344 Remove Lameduck field from Stat
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
Labels: approved, lgtm, size/XS

#3305 Tabularize service-to-service test to test shorter internal domain names
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/L

#3352 fix typo Configuraiton -> Configuration
  docs/runtime-contract.md
Labels: approved, lgtm, size/XS

#3284 Update Istio template to 1.0.6
  DEVELOPMENT.md
  hack/generate-yamls.sh
  third_party/istio-1.0.2/istio-pilot-hpa.yaml
  third_party/istio-1.0.6/README.md
  third_party/istio-1.0.6/conn-timeout.yaml.patch
  third_party/istio-1.0.6/download-istio.sh
  third_party/istio-1.0.6/istio-crds.yaml
  third_party/istio-1.0.6/istio-lean.yaml
  third_party/istio-1.0.6/istio.yaml
  third_party/istio-1.0.6/namespace.yaml.patch
  third_party/istio-1.0.6/prestop-sleep.yaml.patch
Labels: approved, lgtm, size/XL

#3354 The test loggers were not cleared, prohibiting `-count=X>1` execution
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
Labels: approved, lgtm, size/XS

#3320 [RELEASE 0.3] Unbreak the release-0.3 CI flow
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  test/cluster.sh
Labels: approved, lgtm, size/S

#3215 Replace DOCKER_REPO_OVERRIDE by KO_DOCKER_REPO
  DEVELOPMENT.md
  test/README.md
Labels: approved, lgtm, size/M

#3363 Change Age to Generation
  config/300-clusteringress.yaml
  config/300-configuration.yaml
  config/300-kpa.yaml
  config/300-revision.yaml
  config/300-route.yaml
  config/300-service.yaml
Labels: approved, lgtm, size/M

#3361 Simplify activator test, add body to failure output.
  test/e2e/activator_test.go
Labels: approved, lgtm, size/M

#3360 Remove several pieces of code we no longer need.
  cmd/activator/main.go
  pkg/activator/activator.go
  pkg/activator/handler/enforce_length_handler.go
  pkg/activator/handler/enforce_length_handler_test.go
  pkg/activator/handler/filtering_handler.go
  pkg/activator/handler/filtering_handler_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/probe_handler_test.go
  pkg/activator/util/header.go
  pkg/activator/util/transports.go
  pkg/activator/util/transports_test.go
Labels: approved, lgtm, size/XL

#3345 Fix the sugared logger usage
  pkg/autoscaler/statserver/server.go
  pkg/autoscaler/statserver/server_test.go
  pkg/reconciler/stats.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/service/service.go
  test/e2e/autoscale_test.go
  test/reconciler/build/build.go
Labels: approved, lgtm, size/M

#3339 Stop executing Hook actions after WaitForHooks has finished.
  pkg/reconciler/testing/hooks.go
  pkg/reconciler/testing/hooks_test.go
Labels: approved, lgtm, size/M

#3358 Use a value for empty strings in stats reporter
  pkg/activator/handler/handler.go
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
  pkg/autoscaler/stats_reporter.go
  pkg/autoscaler/stats_reporter_test.go
Labels: approved, lgtm, size/M

#3366 test-infra dep package update.
  Gopkg.lock
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/resourcetree.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/webhook/apicoverage_recorder.go
Labels: approved, lgtm, size/M

#3375 Fixing the path to apicoverage tools directory
  test/apicoverage/tools/main.go
Labels: approved, lgtm, size/XS

#3380 Assorted test fixes discovered experimenting with #3371
  test/conformance/util.go
  test/e2e/activator_test.go
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/S

#3377 golang format tools
  pkg/activator/handler/handler.go
  pkg/activator/stats_reporter_test.go
  pkg/autoscaler/stats_reporter_test.go
  test/apicoverage/image/common/common.go
  test/apicoverage/image/main.go
  test/apicoverage/image/rules/coverage_rules.go
  test/apicoverage/image/rules/display_rules.go
  test/apicoverage/image/webhook/webhook_server.go
  test/apicoverage/tools/main.go
  test/crd_checks.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#3379 Static analysis fixes
  cmd/activator/main.go
  cmd/autoscaler/main.go
  cmd/queue/main.go
  pkg/activator/revision.go
  pkg/activator/throttler_test.go
  pkg/apis/networking/v1alpha1/clusteringress_types.go
  pkg/apis/networking/v1alpha1/clusteringress_types_test.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/multiscaler_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
  pkg/autoscaler/statserver/server.go
  pkg/autoscaler/statserver/server_test.go
  pkg/queue/stats_reporter.go
  pkg/queue/stats_reporter_test.go
  pkg/reconciler/reconciler_test.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/config/store_test.go
  pkg/reconciler/v1alpha1/configuration/config/store_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/labeler/labeler_test.go
  pkg/reconciler/v1alpha1/revision/config/store_test.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/config/store_test.go
  pkg/reconciler/v1alpha1/route/queueing_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/service/resources/route_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
Labels: approved, lgtm, size/L

#3249 Refactor resource requirements to be shared with unit tests
  pkg/reconciler/v1alpha1/service/resources/shared_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
  pkg/reconciler/v1alpha1/testing/service.go
  test/conformance/revision_timeout_test.go
  test/conformance/volumes_test.go
  test/crd.go
  test/e2e/scale.go
Labels: approved, lgtm, size/L

#3372 Add an e2e test to verify pods shut down timely.
  test/e2e/destroypod_test.go
Labels: approved, lgtm, size/M

#3386 Remove hardcoded NodePorts on istio-ingressgateway.
  third_party/istio-1.0.6/download-istio.sh
  third_party/istio-1.0.6/istio-lean.yaml
  third_party/istio-1.0.6/istio.yaml
Labels: approved, lgtm, size/S

#3388 Fix the ugly test to be pretty
  pkg/reconciler/v1alpha1/service/resources/route_test.go
  pkg/reconciler/v1alpha1/service/resources/shared_test.go
Labels: approved, lgtm, size/M

#3391 Some tests slipped out. So prettify them as well.
  pkg/reconciler/v1alpha1/service/resources/route_test.go
Labels: approved, lgtm, size/L

#3390 Remove ServiceEntry with one-word host name.
  config/monitoring/metrics/stackdriver/100-stackdriver-serviceentry.yaml
Labels: approved, lgtm, size/S

#3285 Convert TestSingleConcurrency to use Service.
  test/conformance/single_threaded_test.go
Labels: approved, lgtm, size/M

#3381 Make reporter tests more reliable.
  pkg/autoscaler/stats_reporter_test.go
Labels: approved, lgtm, size/L

#3397 easy typo: min->max
  pkg/apis/autoscaling/register.go
Labels: approved, lgtm, size/XS

#3343 add test for websocket connection through activator
  test/e2e/e2e.go
  test/e2e/grpc_test.go
  test/e2e/websocket_test.go
Labels: approved, lgtm, size/L

#3357 Make reconciler stop the watches, when terminated.
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
Labels: approved, lgtm, size/S

#3395 Remove last occurrence of 'MatchesAny'.
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/XS

#3293 Attempt at fixing scale from 0 to 50 test.
  test/crd_checks.go
  test/performance/scale_from_zero_test.go
  test/performance/scale_test.go
  test/service.go
Labels: approved, lgtm, size/M

#3404 Improve error reporting of ScaleToN tests.
  test/e2e/scale.go
Labels: approved, lgtm, size/XS

#3402 Format markdown
  DEVELOPMENT.md
  docs/runtime-contract.md
  hack/environments.md
  test/README.md
  test/apicoverage/image/README.md
  test/test_images/wsserver/README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#3401 Update the breaker test.
  pkg/queue/breaker_test.go
Labels: approved, lgtm, size/M

#3398 Support both host and host:<any-port> as :authority header
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
  test/e2e/grpc_test.go
Labels: approved, lgtm, size/M

#3410 [release-0.4] Support both host and host:<any-port> as :authority header (#3398)
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
  test/e2e/grpc_test.go
Labels: approved, lgtm, size/M

#3385 Remove scale to 100 perf test as it fails consistently
  test/performance/scale_test.go
Labels: approved, lgtm, size/XS

#3347 Remove endpoint `/quitquitquit` from admin server
  cmd/queue/main.go
  pkg/queue/constants.go
  pkg/queue/health/health_state.go
  pkg/queue/health/health_state_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/queue_test.go
Labels: approved, lgtm, size/L

#3413 fix the comment
  pkg/activator/activator.go
Labels: approved, lgtm, size/XS

#3403 golang format tools
  pkg/reconciler/v1alpha1/route/queueing_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3396 Consistently log the full response on errors in tests.
  Gopkg.lock
  Gopkg.toml
  test/e2e/activator_test.go
  test/e2e/autoscale_test.go
  test/prober.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/controller/stats_reporter.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/metrics/config.go
  vendor/github.com/knative/pkg/metrics/exporter.go
  vendor/github.com/knative/pkg/metrics/metricskey/constants.go
  vendor/github.com/knative/pkg/metrics/prometheus_exporter.go
  vendor/github.com/knative/pkg/metrics/record.go
  vendor/github.com/knative/pkg/metrics/stackdriver_exporter.go
  vendor/github.com/knative/pkg/test/monitoring/doc.go
  vendor/github.com/knative/pkg/test/monitoring/monitoring.go
  vendor/github.com/knative/pkg/test/request.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/doc.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
  vendor/github.com/knative/pkg/webhook/certs.go
Labels: approved, lgtm, size/XL

#3332 Set memory limit
  config/monitoring/metrics/prometheus/300-prometheus.yaml
  config/monitoring/tracing/zipkin-in-mem/100-zipkin.yaml
  config/monitoring/tracing/zipkin/100-zipkin.yaml
Labels: approved, lgtm, size/XS

#3412 Fix GCP project name vs id for gcloud
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#3417 Activator autoscaler main brushup
  cmd/activator/main.go
  cmd/autoscaler/main.go
  pkg/autoscaler/statserver/server.go
  pkg/autoscaler/statserver/server_test.go
Labels: approved, lgtm, size/M

#3418 Refactor main autoscaler function.
  cmd/activator/main.go
  cmd/autoscaler/main.go
Labels: approved, lgtm, size/L

#3369 development.md: show override PROJECT_ID
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#3322 Distinguish config-logging
  cmd/activator/main.go
  cmd/autoscaler/main.go
  cmd/controller/main.go
  cmd/webhook/main.go
  config/activator.yaml
  config/autoscaler.yaml
  config/controller.yaml
  config/webhook.yaml
  pkg/logging/config.go
  pkg/logging/config_test.go
  pkg/reconciler/v1alpha1/revision/config/store.go
  pkg/reconciler/v1alpha1/revision/config/store_test.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
Labels: approved, lgtm, size/M

#3432 Fix activator forwarding bug.
  cmd/queue/main.go
  pkg/activator/activator.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/probe_handler.go
  pkg/queue/constants.go
Labels: approved, lgtm, size/M

#3400 Use metrics.Record instead of stats.Record
  Gopkg.lock
  Gopkg.toml
  config/config-observability.yaml
  pkg/activator/stats_reporter.go
  pkg/autoscaler/stats_reporter.go
  pkg/reconciler/stats_reporter.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1/metrics.pb.go
  vendor/github.com/knative/pkg/metrics/record.go
  vendor/github.com/knative/pkg/test/request.go
Labels: approved, lgtm, size/XXL

#3189 Initial framework of reconciling Istio Gateway based on ClusterIngressTLS
  cmd/controller/main.go
  config/200-clusterrole.yaml
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/gateway.go
  pkg/reconciler/v1alpha1/clusteringress/resources/gateway_test.go
  pkg/reconciler/v1alpha1/testing/listers.go
Labels: approved, lgtm, size/XL

#3438 Probe with name
  cmd/queue/main.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/probe_handler.go
  pkg/activator/handler/probe_handler_test.go
  pkg/queue/constants.go
Labels: approved, lgtm, size/M

#3433 Test/APICoverage Tool updates
  Gopkg.lock
  Gopkg.toml
  test/apicoverage/image/rules/display_rules.go
  test/apicoverage/tools/main.go
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/performance.go
  test/performance/scale_from_zero_test.go
  vendor/github.com/knative/pkg/test/monitoring/monitoring.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/shared/prometheus/prometheus.go
  vendor/github.com/knative/test-infra/shared/testgrid/testgrid.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/coveragecalculator/calculator.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/arraykindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/node.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/otherkindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/resourcetree.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/structkindnode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/resourcetree/timetypenode.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/tools/tools.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/view/README.md
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/view/coverage_display.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/view/html_display.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/view/jsontype_display.go
  vendor/github.com/knative/test-infra/tools/webhook-apicoverage/webhook/apicoverage_recorder.go
Labels: approved, lgtm, size/XL

#3440 Add labels to our OWNERS files by area.
  cmd/activator/OWNERS
  cmd/autoscaler/OWNERS
  cmd/controller/OWNERS
  cmd/queue/OWNERS
  config/monitoring/OWNERS
  docs/scaling/OWNERS
  hack/OWNERS
  pkg/activator/OWNERS
  pkg/apis/OWNERS
  pkg/apis/autoscaling/OWNERS
  pkg/apis/networking/OWNERS
  pkg/autoscaler/OWNERS
  pkg/http/h2c/OWNERS
  pkg/logging/OWNERS
  pkg/metrics/OWNERS
  pkg/network/OWNERS
  pkg/pool/OWNERS
  pkg/queue/OWNERS
  pkg/reconciler/OWNERS
  pkg/reconciler/v1alpha1/autoscaling/OWNERS
  pkg/reconciler/v1alpha1/clusteringress/OWNERS
  pkg/reconciler/v1alpha1/route/OWNERS
  test/OWNERS
  third_party/OWNERS
  third_party/config/monitoring/OWNERS
Labels: approved, lgtm, size/M

#3443 Update link to docs folder for serving
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3441 Drop unnecessary interface.
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/M

#3444 Embed a common Status duck type.
  Gopkg.lock
  Gopkg.toml
  pkg/activator/revision_test.go
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/networking/v1alpha1/clusteringress_types.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/configuration_types_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/route_types_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/helpers_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
  pkg/reconciler/v1alpha1/testing/listers.go
  test/apis/testing/v1alpha1/build_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/client/clientset/versioned/fake/register.go
  vendor/github.com/knative/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/XXL

#3356 Verify revision identity before scale-up E2E test
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/XS

#3414 Stop the probing manager before fatally exiting test.
  test/e2e/scale.go
  test/prober.go
Labels: approved, lgtm, size/XS

#3445 Split the lifecycle management methods off of `_types.go` files.
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/networking/v1alpha1/clusteringress_lifecycle.go
  pkg/apis/networking/v1alpha1/clusteringress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/clusteringress_types.go
  pkg/apis/serving/v1alpha1/configuration_lifecycle.go
  pkg/apis/serving/v1alpha1/configuration_lifecycle_test.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/revision_lifecycle.go
  pkg/apis/serving/v1alpha1/revision_lifecycle_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/route_lifecycle.go
  pkg/apis/serving/v1alpha1/route_lifecycle_test.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_lifecycle.go
  pkg/apis/serving/v1alpha1/service_lifecycle_test.go
  pkg/apis/serving/v1alpha1/service_types.go
Labels: approved, area/API, area/autoscale, area/networking, lgtm, size/XXL

#3437 Cleanup around revision and kpa
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler.go
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/helpers.go
  pkg/reconciler/v1alpha1/revision/helpers_test.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/revision.go
Labels: approved, lgtm, size/M

#3451 Remove SetConditions and GetConditions for ClusterIngress
  pkg/apis/networking/v1alpha1/clusteringress_lifecycle.go
Labels: approved, area/API, area/networking, lgtm, size/S

#3449 Various fixes to the codebase
  pkg/activator/handler/handler_test.go
  pkg/activator/revision_test.go
  pkg/apis/autoscaling/v1alpha1/pa_validation.go
  pkg/apis/networking/v1alpha1/clusteringress_validation.go
  pkg/autoscaler/autoscaler_test.go
  pkg/http/h2c/h2c.go
  pkg/reconciler/testing/tracker.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/resolve.go
  pkg/reconciler/v1alpha1/revision/resources/constants.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/config/domain.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
  test/conformance/filesystem_perm_test.go
  test/controller/main.go
  test/crd.go
  test/e2e/activator_test.go
  test/e2e/e2e.go
  test/route.go
  test/states.go
  test/test_images/autoscale/autoscale.go
  test/test_images/environment/environment.go
  test/test_images/httpproxy/httpproxy.go
  test/types/runtime.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, lgtm, size/L

#3430 Wait for traffic generation to have stopped before ending the test.
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/M

#3409 Construct a better resolver transport
  pkg/reconciler/v1alpha1/revision/resolve.go
Labels: approved, lgtm, size/S

#3460 Add @vagababov to serving approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3292 Add conformance tests for .metadata.generateName.
  test/conformance/generatename_test.go
  test/service.go
Labels: approved, area/test-and-release, lgtm, size/L

#3459 FF Pkg to see if the network retries reduce flakes in the integration tests
  Gopkg.lock
  Gopkg.toml
  test/conformance/blue_green_test.go
  test/conformance/errorcondition_test.go
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/conformance/util.go
  test/crd.go
  test/e2e/helloworld_shell_test.go
  test/e2e_flags.go
  test/upgrade/service_postdowngrade_test.go
  test/upgrade/service_postupgrade_test.go
  test/util.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/test/clients.go
  vendor/github.com/knative/pkg/test/crd.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
Labels: approved, area/test-and-release, lgtm, size/L

#3439 golang format tools
  cmd/activator/main.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
Labels: approved, lgtm, size/XS

#3325 Drop functional dependency on 'configurationMetadataGeneration' label
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
Labels: approved, lgtm, size/S

#3454 Set istio trace sampling back to 100%
  third_party/istio-1.0.6/download-istio.sh
  third_party/istio-1.0.6/istio-lean.yaml
  third_party/istio-1.0.6/istio.yaml
Labels: approved, lgtm, size/XS

#3455 Fix the deploy script
  hack/deploy.sh
Labels: approved, area/test-and-release, lgtm, size/XS

#3465 Reject revision template spec name
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
Labels: approved, area/API, lgtm, size/S

#3383 Fix typos in doc
  docs/scaling/DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#3464 Fix broken link in scaling documentation.
  docs/scaling/DEVELOPMENT.md
Labels: approved, area/autoscale, lgtm, size/XS

#3306 Allow for the format of Routes of a Service to be configurable
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
Labels: approved, lgtm, size/L

#3469 Remove the typed pipelines clients.
  Gopkg.lock
  Gopkg.toml
  test/clients.go
  test/e2e/build_pipeline_test.go
  vendor/github.com/knative/build-pipeline/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/bash/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/controller/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/creds-init/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/git-init/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/gsutil/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/kubeconfigwriter/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/nop/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/webhook/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/register.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/cluster_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/cluster_task_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/cluster_task_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/doc.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/gcs_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/git_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/image_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/metadata_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_defaults.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipelineresource_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/register.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/resource_defaults.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/resource_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/result_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/storage_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/task_defaults.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/task_interface.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/task_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/task_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/taskrun_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/doc.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/clustertask.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/doc.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/generated_expansion.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipeline.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipeline_client.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipelineresource.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipelinerun.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/task.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/taskrun.go
  vendor/github.com/knative/build-pipeline/pkg/reconciler/v1alpha1/taskrun/list/diff.go
  vendor/github.com/knative/build-pipeline/test/logs/kodata/LICENSE
Labels: approved, area/test-and-release, lgtm, size/XXL

#3474 Let the ClusterIngress webhook do defaulting.
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
Labels: approved, area/API, area/networking, lgtm, size/M

#3462 Surface events for all reconciliation failures.
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/service/service_test.go
Labels: approved, area/API, area/autoscale, area/networking, lgtm, size/L

#3473 Cleanup ClusterIngress comments and add more test coverage.
  pkg/apis/networking/v1alpha1/certificate_lifecycle_test.go
  pkg/apis/networking/v1alpha1/certificate_types.go
  pkg/apis/networking/v1alpha1/clusteringress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/clusteringress_types.go
Labels: approved, area/API, area/networking, lgtm, size/M

#3476 Favor context.Background() over context.TODO()
  cmd/activator/main.go
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
  pkg/reconciler/testing/table.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/resources/metric_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  test/controller/main.go
  test/e2e/destroypod_test.go
  test/e2e/grpc_test.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, lgtm, size/M

#3458 Installing monitoring components in perf test scripts (#3446)
  test/e2e-common.sh
  test/performance-tests.sh
Labels: approved, area/test-and-release, lgtm, size/M

#3489 Point to ko repo in development docs
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#3488 Add webhook registration and rbacs
  cmd/webhook/main.go
  config/200-clusterrole.yaml
Labels: approved, lgtm, size/XS

#3494 Remove unnecessary functionality from the activator's codebase.
  cmd/activator/main.go
  pkg/activator/activator.go
  pkg/activator/dedupe.go
  pkg/activator/dedupe_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/revision.go
  pkg/activator/revision_test.go
Labels: approved, area/networking, lgtm, size/XXL

#3500 Updated outdated comment about *_OVERRIDE vars
  test/e2e-tests.sh
Labels: approved, area/test-and-release, lgtm, size/XS

#3502 the rbac crds must be in plural
  config/200-clusterrole.yaml
Labels: approved, lgtm, size/XS

#3505 Share the definition of shared fields
  pkg/apis/serving/v1alpha1/configuration_lifecycle_test.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_lifecycle.go
  pkg/apis/serving/v1alpha1/service_lifecycle_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/labeler/labeler_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, area/API, area/networking, lgtm, size/L

#3495 Pick up factored out 'GetIngressEndpoint' logic.
  Gopkg.lock
  Gopkg.toml
  test/e2e/grpc_test.go
  test/e2e/websocket_test.go
  test/performance/latency_test.go
  vendor/github.com/knative/pkg/test/ingress/ingress.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
Labels: approved, area/test-and-release, lgtm, size/L

#3501 Add context to logs in the activator where possible.
  pkg/activator/activator.go
  pkg/activator/handler/handler.go
  pkg/activator/throttler.go
Labels: approved, area/networking, lgtm, size/M

#3503 Reduces the boilerplate of our controller binaries.
  Gopkg.lock
  Gopkg.toml
  cmd/autoscaler/main.go
  cmd/controller/main.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/controller/controller.go
Labels: approved, area/API, area/autoscale, lgtm, size/L

#3496 Remove extra f-calls wherein no formatting is performed
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/service/service.go
  test/test_images/runtime/main.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, lgtm, size/S

#3509 Add a helper to reduce boilerplate in Informer setup.
  pkg/reconciler/handler.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/labeler/labeler.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/service/service.go
Labels: approved, area/API, area/autoscale, area/networking, lgtm, size/L

#3507 Pick up the GetCondition method from knative/pkg
  test/e2e/build_pipeline_test.go
Labels: approved, area/API, area/autoscale, area/test-and-release, lgtm, size/S

#3513 Format markdown
  DEVELOPMENT.md
  README.md
  docs/scaling/DEVELOPMENT.md
Labels: approved, area/autoscale, lgtm, needs-ok-to-test, size/S

#3498 Only add KPA label to a K8S service of a revision if KPA is used
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  pkg/reconciler/v1alpha1/revision/resources/service.go
  pkg/reconciler/v1alpha1/revision/resources/service_test.go
Labels: approved, area/API, lgtm, size/M

#3478 Fix broken links to docs repo
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#3335 Remove migration of deprecated generation labels and annotation
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, lgtm, size/L

#3504 1997 api2
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/autoscaling/v1alpha1/pa_validation.go
  pkg/apis/autoscaling/v1alpha1/pa_validation_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_types.go
  pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  pkg/apis/networking/v1alpha1/serverlessservice_validation_test.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
Labels: approved, area/API, area/autoscale, area/networking, lgtm, size/L

#3517 golang format tools
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
Labels: approved, area/API, lgtm, needs-ok-to-test, size/XS

#3519 Tie Activator health to the readiness of the metrics socket.
  Gopkg.lock
  Gopkg.toml
  cmd/activator/main.go
  config/activator.yaml
  pkg/activator/handler/healthz_handler.go
  pkg/activator/handler/healthz_handler_test.go
  vendor/github.com/knative/pkg/websocket/connection.go
Labels: approved, area/networking, lgtm, size/L

#3522 Always install istio from HEAD for upgrade tests
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, lgtm, size/XS

#3461 Document scale annotations lifetime
  docs/scaling/README.md
Labels: approved, area/autoscale, lgtm, size/XS

#3528 Disallow unknown fields (again)
  Gopkg.lock
  Gopkg.toml
  cmd/webhook/main.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/S

#3529 Move our resource requirement defaulting into the webhook.
  pkg/apis/serving/v1alpha1/configuration_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults_test.go
  pkg/apis/serving/v1alpha1/service_defaults_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/resources/constants.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/testing/service.go
Labels: approved, area/API, lgtm, size/L

#3479 Clean up Istio Servers of a ClusterIngress when deleting the ClusterIngress
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/gateway.go
  pkg/reconciler/v1alpha1/clusteringress/resources/gateway_test.go
Labels: approved, area/API, area/networking, lgtm, size/L

#3530 Append routeFinalizer into route.Finalizers to keep the finalizer order
  pkg/reconciler/v1alpha1/route/route.go
Labels: approved, area/API, area/networking, lgtm, size/XS

#3533 Format markdown
  docs/scaling/README.md
Labels: approved, area/autoscale, lgtm, needs-ok-to-test, size/XS

#3536 Only default to MaxConcurrency if there are endpoints available.
  pkg/activator/throttler.go
  pkg/activator/throttler_test.go
Labels: approved, area/networking, lgtm, size/S

#3516 Reduce the amount of CPU needed by cgroup test.
  test/conformance/cgroup_test.go
Labels: approved, area/test-and-release, lgtm, size/S

#3532 Reduce the load excerted by the activator overload test.
  test/e2e/activator_test.go
Labels: approved, area/test-and-release, lgtm, size/S

#3477 Add a new stat metric in queue to prevent double counting
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
  pkg/network/network.go
  pkg/queue/stats.go
  pkg/queue/stats_reporter.go
  pkg/queue/stats_reporter_test.go
  pkg/queue/stats_test.go
Labels: approved, area/autoscale, area/networking, lgtm, size/XL

#3539 fix output error for table test
  pkg/reconciler/testing/table.go
Labels: approved, area/API, lgtm, size/XS

#3531 Move the ProtocolType from serving to networking.
  pkg/activator/activator.go
  pkg/activator/activator_test.go
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/autoscaling/v1alpha1/pa_validation_test.go
  pkg/apis/networking/generic_types.go
  pkg/apis/networking/v1alpha1/serverlessservice_types.go
  pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  pkg/apis/networking/v1alpha1/serverlessservice_validation_test.go
  pkg/apis/serving/v1alpha1/revision_lifecycle.go
  pkg/apis/serving/v1alpha1/revision_lifecycle_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/reconciler/v1alpha1/revision/resources/service.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, area/API, area/autoscale, area/networking, lgtm, size/L

#3542 Drop unnecessary else
  pkg/reconciler/v1alpha1/revision/config/controller.go
Labels: approved, area/API, lgtm, size/XS

#3545 Further leverage aggregated ClusterRole to split off Istio RBAC.
  config/200-clusterrole.yaml
Labels: approved, lgtm, size/S

#3457 Generate istio with helm 2.13
  third_party/istio-1.0.6/istio-lean.yaml
  third_party/istio-1.0.6/istio.yaml
Labels: approved, lgtm, size/L

#3423 Add conformance test for setting user
  test/configuration.go
  test/conformance/user_test.go
  test/crd.go
  test/test_images/runtime/handlers/runtime.go
  test/test_images/runtime/handlers/user.go
  test/test_images/runtime/service.yaml
  test/types/runtime.go
Labels: approved, area/test-and-release, lgtm, size/L

#3523 Don't retry 503s in test.RetryingRouteInconsistency
  test/route.go
Labels: approved, area/test-and-release, lgtm, size/XS

#3546 Plumb through configurable defaulting in the webhook.
  Gopkg.lock
  Gopkg.toml
  cmd/webhook/main.go
  config/config-defaults.yaml
  hack/update-codegen.sh
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/apis/config/doc.go
  pkg/apis/config/store.go
  pkg/apis/config/store_test.go
  pkg/apis/config/testdata/config-defaults.yaml
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/serving/v1alpha1/configuration_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults_test.go
  pkg/apis/serving/v1alpha1/service_defaults_test.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, area/API, area/test-and-release, lgtm, size/XL

#3551 The comment and the usage were right, but the config name was wrong.
  config/config-defaults.yaml
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/serving/v1alpha1/revision_defaults.go
Labels: approved, area/API, lgtm, size/S

#3471 Add additional container constraint conformance tests
  test/conformance/container_test.go
Labels: approved, area/test-and-release, lgtm, size/L

#3557 Update deployments to be on apps/v1
  Gopkg.lock
  Gopkg.toml
  test/crd_checks.go
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/spoof/error_checks.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, area/test-and-release, lgtm, size/L

#3560 Add serving-approvers to the serving/test OWNERS.
  test/OWNERS
Labels: approved, area/test-and-release, lgtm, size/XS

#3563 Return 'BadRequest' if a probe request doesn't match.
  cmd/queue/main.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/probe_handler.go
  pkg/activator/handler/probe_handler_test.go
Labels: approved, area/networking, lgtm, size/S

#3578 Update TestTimeToServing metrics unit to be ms
  test/performance/latency_test.go
Labels: approved, area/test-and-release, lgtm, size/XS

#3561 Write request logs from queue proxy
  cmd/queue/main.go
  config/config-observability.yaml
  pkg/activator/handler/handler.go
  pkg/http/response_recorder.go
  pkg/http/response_recorder_test.go
  pkg/queue/request_log.go
  pkg/queue/request_log_test.go
  pkg/reconciler/v1alpha1/revision/config/observability.go
  pkg/reconciler/v1alpha1/revision/config/observability_test.go
  pkg/reconciler/v1alpha1/revision/resources/deploy.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/queue_test.go
  pkg/utils/sync_file_writer.go
  pkg/utils/sync_file_writer_test.go
Labels: approved, area/API, area/networking, lgtm, size/XL

#3541 Use Prometheus client lib directly instead of OpenCensus in queue proxy
  cmd/queue/main.go
  pkg/queue/prometheus_stats_reporter.go
  pkg/queue/prometheus_stats_reporter_test.go
  pkg/queue/stats_reporter.go
  pkg/queue/stats_reporter_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/XL

#3564 Cleanup the scraper interface and its implementation.
  cmd/autoscaler/main.go
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#3411 Update spec.md to clarify v1.Container fields
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/M

#3526 Add URL to TrafficTarget Status
  docs/spec/spec.md
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/route_validation.go
  pkg/apis/serving/v1alpha1/route_validation_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/testing/functional.go
  test/conformance/blue_green_test.go
  test/conformance/service_test.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#3589 Separate / Simplify image cache creation.
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/resources/imagecache.go
  pkg/reconciler/v1alpha1/revision/resources/imagecache_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#3559 Add a K8s Job to configure a default domain.
  DEVELOPMENT.md
  cmd/default-domain/main.go
  config/post-install/100-istio-default-domain.yaml
  test/config/100-istio-default-domain.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e/grpc_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3592 Add a label knative.dev/crd-install to CRDs to allow installing CRDs in a separate pass.
  config/300-certificate.yaml
  config/300-clusteringress.yaml
  config/300-configuration.yaml
  config/300-kpa.yaml
  config/300-revision.yaml
  config/300-route.yaml
  config/300-service.yaml
  config/300-sks.yaml
Labels: approved, cla: yes, lgtm, size/S

#3480 Add instruction to authenticate image repository when using docker hub
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#3549 Update normative examples
  docs/spec/normative_examples.md
Labels: approved, lgtm, size/XS

#3595 Label Istio things so that users can choose whether to install.
  config/200-clusterrole.yaml
  config/202-gateway.yaml
  config/203-local-gateway.yaml
  config/config-istio.yaml
  config/post-install/100-istio-default-domain.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3590 Address pkg struct renaming
  Gopkg.lock
  Gopkg.toml
  pkg/queue/health/probe_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
  test/apicoverage/image/webhook/webhook_server.go
  test/e2e/service_to_service_test.go
  test/test_images/httpproxy/README.md
  test/test_images/httpproxy/httpproxy.go
  vendor/github.com/knative/pkg/apis/istio/authentication/v1alpha1/policy_types.go
  vendor/github.com/knative/pkg/apis/istio/authentication/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/destinationrule_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/gateway_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/L
