Repository knative/serving, pull requests merged in 2019-01, with the labels that each got.

#2787 Rename autoscaler-service port name from 'websocket' to 'http'
  config/autoscaler-service.yaml
Labels: approved, lgtm, size/XS

#2831 Change request logs to be written only for HTTP and GRPC calls
  config/monitoring/logging/elasticsearch/100-istio-requestlogs.yaml
  config/monitoring/logging/stackdriver/100-istio-requestlogs.yaml
Labels: approved, lgtm, size/XS

#2818 Reduce a deployments selector to only match the revision uid
  pkg/reconciler/v1alpha1/revision/cruds.go
  pkg/reconciler/v1alpha1/revision/resources/deploy_test.go
  pkg/reconciler/v1alpha1/revision/resources/meta.go
  pkg/reconciler/v1alpha1/revision/resources/meta_test.go
Labels: approved, lgtm, size/M

#2765 Don't use spec.generation when garbage collecting revisions
  pkg/apis/serving/register.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  test/states.go
Labels: approved, lgtm, size/L

#2832 Update knative/caching and run update-deps.sh
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/caching/Gopkg.lock
  vendor/github.com/knative/caching/config/image.yaml
  vendor/github.com/knative/caching/hack/boilerplate/add-boilerplate.sh
  vendor/github.com/knative/caching/hack/boilerplate/boilerplate.sh.txt
  vendor/github.com/knative/caching/hack/update-codegen.sh
  vendor/github.com/knative/caching/hack/update-deps.sh
  vendor/github.com/knative/caching/hack/verify-codegen.sh
  vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/image_types.go
  vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/image_validation.go
  vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/caching/test/presubmit-tests.sh
  vendor/istio.io/fortio/LICENSE
  vendor/istio.io/fortio/fhttp/http_client.go
  vendor/istio.io/fortio/fhttp/http_server.go
  vendor/istio.io/fortio/fhttp/http_utils.go
  vendor/istio.io/fortio/fhttp/httprunner.go
  vendor/istio.io/fortio/fnet/network.go
  vendor/istio.io/fortio/log/logger.go
  vendor/istio.io/fortio/periodic/periodic.go
  vendor/istio.io/fortio/stats/stats.go
  vendor/istio.io/fortio/version/version.go
Labels: approved, lgtm, size/XXL

#2830 Set to lameduck metric to 1 if the pod is lameducked
  pkg/queue/stats_reporter.go
  pkg/queue/stats_reporter_test.go
Labels: approved, lgtm, size/XS

#2714 Update runtime contract to reflect current behavior
  docs/runtime-contract.md
Labels: approved, lgtm, size/XS

#2839 Format markdown
  docs/debugging/application-debugging-guide.md
  docs/spec/normative_examples.md
  docs/spec/spec.md
  install/CONFIG.md
  test/test_images/environment/README.md
  vendor/github.com/prometheus/procfs/fixtures/26231/exe
Labels: approved, lgtm, size/L

#2716 Make test README compatible with a Dockerhub based setup.
  test/cluster.sh
  test/e2e-tests.sh
  test/e2e_flags.go
  test/upload-test-images.sh
Labels: approved, lgtm, size/S

#2833 Propagate label changes from Service to child Route and Config.
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/M

#2834 Various cleanups around the system, while learning the system.
  pkg/reconciler/testing/hooks.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/service/service.go
Labels: approved, lgtm, size/M

#2844 Fix a few test README's
  test/adding_tests.md
  test/performance/README.md
Labels: approved, lgtm, size/S

#2829 Make use of the status subresource for our custom resources
  config/200-clusterrole.yaml
  config/300-clusteringress.yaml
  config/300-configuration.yaml
  config/300-kpa.yaml
  config/300-revision.yaml
  config/300-route.yaml
  config/300-service.yaml
  pkg/apis/serving/register.go
  pkg/reconciler/testing/table.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/resources/build.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/L

#2848 Wait for informers to start to fix test flakes.
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/queueing_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
Labels: approved, lgtm, size/S

#2853 Some minor nits, I noticed in the pull/2829.
  pkg/reconciler/testing/table.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
Labels: approved, lgtm, size/M

#2854 Temporarily increase cluster size for serving tests.
  test/cluster.sh
Labels: approved, lgtm, size/XS

#2811 Expose 9090 of revision service for metrics from queue proxy
  cmd/queue/main.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/reconciler/v1alpha1/revision/resources/constants.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
  pkg/reconciler/v1alpha1/revision/resources/service.go
Labels: approved, lgtm, size/M

#2855 fix broken link and use relative url
  docs/setting-up-ingress-static-ip.md
Labels: approved, lgtm, size/XS

#2847 Format markdown
  docs/runtime-contract.md
  test/adding_tests.md
  test/performance/README.md
Labels: approved, lgtm, size/S

#2845 Activator-service should be of type ClusterIP
  config/400-activator-service.yaml
Labels: approved, lgtm, size/XS

#2863 Format markdown
  docs/setting-up-ingress-static-ip.md
Labels: approved, lgtm, size/XS

#2865 Add performance tag to build tests
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#2867 Increase default and max revision timeout.
  pkg/apis/networking/v1alpha1/clusteringress_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
Labels: approved, lgtm, size/XS

#2866 Prohibit multiple entries for the same route name.
  pkg/apis/serving/v1alpha1/route_validation.go
  pkg/apis/serving/v1alpha1/route_validation_test.go
Labels: approved, lgtm, size/M

#2825 Dump state if final call to WaitForXXXState functions fails.
  test/crd_checks.go
Labels: approved, lgtm, size/M

#2880 This change removes the stutter from the traffic.TrafficConfig name.
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/reconcile_resources_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, lgtm, size/L

#2875 Fix checkMapKeysNotPresent to checkNoKeysPresent and log the offending keys
  test/conformance/configuration_test.go
Labels: approved, lgtm, size/S

#2862 webhook can read kube config out of cluster
  cmd/activator/main.go
  cmd/webhook/main.go
Labels: approved, lgtm, size/S

#2870 Add 'WaitForCacheSync' to another flaky test.
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
Labels: approved, lgtm, size/XS

#2871 Print more information when creating a revision
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
Labels: approved, lgtm, size/XS

#2883 Fix race condition in TestScaleToX.
  test/e2e/scale_test.go
Labels: approved, lgtm

#2881 Pull in knative/pkg to re-org the webhook
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/metrics/exporter.go
  vendor/github.com/knative/pkg/metrics/metricskey/constants.go
  vendor/github.com/knative/pkg/metrics/monitored_resources.go
  vendor/github.com/knative/pkg/webhook/certs.go
Labels: approved, lgtm, size/L

#2905 Harden semaphore tests, take out sleeps.
  pkg/queue/breaker_test.go
Labels: approved, lgtm, size/M

#2896 Linter and code cleanups for the service types, service test and utils.
  pkg/apis/serving/v1alpha1/service_types.go
  test/conformance/service_test.go
  test/conformance/util.go
Labels: approved, lgtm, size/L

#2842 Remove broken symlinks when updating deps
  hack/update-deps.sh
  vendor/github.com/docker/docker/hack/make/.build-deb/docker-engine.docker.default
  vendor/github.com/docker/docker/hack/make/.build-deb/docker-engine.docker.init
  vendor/github.com/docker/docker/hack/make/.build-deb/docker-engine.docker.upstart
  vendor/github.com/docker/docker/hack/make/.build-deb/docker-engine.udev
  vendor/github.com/docker/docker/project/CONTRIBUTORS.md
  vendor/github.com/google/go-containerregistry/cmd/ko/test/kodata/kenobi
  vendor/github.com/knative/build/cmd/controller/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/cmd/creds-init/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/cmd/git-init/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/cmd/logs/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/cmd/nop/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/cmd/webhook/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/config/300-imagecache.yaml
  vendor/github.com/knative/build/test/panic/kodata/VENDOR-LICENSE
  vendor/github.com/knative/build/test/workingdir/kodata/VENDOR-LICENSE
  vendor/github.com/prometheus/procfs/fixtures/26231/exe
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/0
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/1
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/10
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/2
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/3
  vendor/github.com/prometheus/procfs/fixtures/26231/ns/mnt
  vendor/github.com/prometheus/procfs/fixtures/26231/ns/net
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/0
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/1
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/2
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/3
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/4
  vendor/k8s.io/kubernetes/.bazelrc
  vendor/k8s.io/kubernetes/.kazelcfg.json
  vendor/k8s.io/kubernetes/BUILD.bazel
  vendor/k8s.io/kubernetes/Makefile
  vendor/k8s.io/kubernetes/Makefile.generated_files
  vendor/k8s.io/kubernetes/WORKSPACE
  vendor/k8s.io/kubernetes/cluster/gce/cos
  vendor/k8s.io/kubernetes/cluster/gce/custom
  vendor/k8s.io/kubernetes/cluster/gce/ubuntu
  vendor/k8s.io/kubernetes/cluster/juju/layers/kubernetes-master/actions/namespace-delete
  vendor/k8s.io/kubernetes/cluster/juju/layers/kubernetes-master/actions/namespace-list
Labels: approved, lgtm, size/M

#2908 Fix upload-test-images.sh
  test/cluster.sh
  test/upload-test-images.sh
Labels: approved, lgtm, size/M

#2895 Change view reporting period to one second in queue proxy
  cmd/queue/main.go
  pkg/queue/stats_reporter.go
  pkg/queue/stats_reporter_test.go
Labels: approved, lgtm, size/M

#2910 Enable websocket upgrade in Istio VirtualService.
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
Labels: approved, lgtm, size/XS

#2914 More cleanps for the traffic.go for the #2876.
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, lgtm, size/L

#2913 Clean up logging in controller main files
  cmd/activator/main.go
  cmd/autoscaler/main.go
  cmd/controller/main.go
  cmd/queue/main.go
  test/controller/main.go
Labels: approved, lgtm, size/M

#2892 replacing hard coded cluster.local with variable
  cmd/queue/main.go
  pkg/activator/revision.go
  pkg/reconciler/names.go
  pkg/reconciler/v1alpha1/route/config/domain.go
  pkg/reconciler/v1alpha1/route/config/domain_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, lgtm, size/L

#2920 Minor code optimization, linter warning fixes, an error text improvement
  pkg/apis/networking/v1alpha1/clusteringress_validation.go
  pkg/apis/networking/v1alpha1/clusteringress_validation_test.go
Labels: approved, lgtm, size/M

#2922 Fix race condition in autoscale test, adjust comments for reality.
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/M

#2924 Bump knative/pkg to d3a9e54
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/verify.go
  vendor/github.com/knative/pkg/kmp/diff.go
  vendor/github.com/knative/pkg/metrics/config.go
  vendor/github.com/knative/pkg/metrics/exporter.go
  vendor/github.com/knative/pkg/test/cleanup.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
Labels: approved, lgtm, size/L

#2891 Fix timer allocation and expand timeouts in TestScaleToX.
  test/e2e/scale_test.go
Labels: approved, lgtm, size/S

#2911 Pass configuration status as a pointer around.
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/M

#2915 TCP probe the user-container from the queue-proxy before marking the pod ready.
  cmd/queue/main.go
  pkg/queue/constants.go
  pkg/queue/health/health_state.go
  pkg/queue/health/health_state_test.go
  pkg/queue/health/probe.go
  pkg/queue/health/probe_test.go
  pkg/reconciler/v1alpha1/revision/resources/queue.go
Labels: approved, lgtm, size/L

#2898 Implement verification for route readiness for the runLatest.
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
  test/conformance/service_test.go
Labels: approved, lgtm, size/L

#2923 Spec.Generation is Deprecated
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/networking/v1alpha1/clusteringress_types.go
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/configuration/queueing_test.go
  pkg/reconciler/v1alpha1/configuration/resources/build_test.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names.go
  pkg/reconciler/v1alpha1/configuration/resources/names/names_test.go
  pkg/reconciler/v1alpha1/configuration/resources/revision.go
  pkg/reconciler/v1alpha1/configuration/resources/revision_test.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/testing/functional.go
  test/conformance/configuration_test.go
Labels: approved, lgtm, size/L

#2882 Fail with "Reason: NotOwned" when a sub-resource name is taken.
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/networking/v1alpha1/clusteringress_types.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/route_types_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_types_test.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/revision/reconcile_resources.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/L

#2903 Use ResourceNames to pass imagePath more places.
  test/configuration.go
  test/conformance/configuration_test.go
  test/conformance/errorcondition_test.go
  test/conformance/revision_timeout_test.go
  test/conformance/route_test.go
  test/conformance/single_threaded_test.go
  test/crd.go
  test/e2e/autoscale_test.go
  test/e2e/build_test.go
  test/e2e/destroypod_test.go
  test/e2e/e2e.go
  test/e2e/helloworld_test.go
  test/e2e/scale_test.go
  test/e2e/service_to_service_test.go
  test/service.go
Labels: approved, lgtm, size/L

#2906 Add version check to all control-plane binaries.
  Gopkg.lock
  Gopkg.toml
  cmd/activator/main.go
  cmd/autoscaler/main.go
  cmd/controller/main.go
  cmd/webhook/main.go
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/pkg/version/version.go
  vendor/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/rogpeppe/go-internal/semver/semver.go
Labels: approved, lgtm, size/XL

#2939 Cleanup defunct yaml file.
  test/test_images/printport/printport.yaml
Labels: approved, lgtm, size/M

#2935 Bump knative/pkg to fix a flake.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/metrics/metricskey/constants.go
Labels: approved, lgtm, size/S

#2937 Fix spelling errors
  test/e2e/scale_test.go
Labels: approved, lgtm, size/XS

#2904 Add a readinessProbe and timeout to the scale test.
  test/e2e/scale_test.go
Labels: approved, lgtm, size/S

#2938 Pods are no longer hanging in Terminating state for a long time.
  cmd/queue/main.go
  third_party/istio-1.0.2/istio.yaml
  third_party/istio-1.0.2/prestop-sleep.yaml.patch
Labels: approved, lgtm, size/M

#2943 Test upgrades from 0.3.0
  test/e2e-upgrade-tests.sh
Labels: approved, lgtm, size/XS

#2936 golang format tools
  pkg/reconciler/names.go
Labels: approved, lgtm, size/XS

#2932 Update to latest test-infra
  Gopkg.lock
  hack/release.sh
  test/performance-tests.sh
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Labels: approved, lgtm, size/XL

#2944 Fix a very important typo in the comment!
  test/crd.go
Labels: approved, lgtm, size/XS

#2950 golang format tools
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/clusteringress/resources/virtual_service_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2947 Reformulate the e2e "probing" in terms of SLI/SLO.
  test/conformance/route_test.go
  test/conformance/service_test.go
  test/crd.go
  test/e2e/scale_test.go
  test/prober.go
  test/route.go
  test/service.go
Labels: approved, lgtm, size/XL

#2953 Add a simple threadpool library
  pkg/pool/OWNERS
  pkg/pool/doc.go
  pkg/pool/interface.go
  pkg/pool/pool.go
  pkg/pool/pool_test.go
Labels: approved, lgtm, size/L

#2956 Use the threadpool in scale test.
  test/e2e/scale_test.go
Labels: approved, lgtm, size/S

#2323 Add scale from zero performance test
  test/crd_checks.go
  test/e2e/autoscale_test.go
  test/performance/scale_from_zero_test.go
Labels: approved, lgtm, size/L

#2886 Minor cleanup of the webhook
  cmd/webhook/main.go
Labels: approved, lgtm, size/S

#2965 Add vagababov as a reviewer
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#2884 Only apply new route configurations if all revisions are ready.
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/reconciler/v1alpha1/route/route_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
Labels: approved, lgtm, size/L

#2952 Hide websocket connection errors for the first 10 seconds.
  cmd/queue/main.go
Labels: approved, lgtm, size/S

#2957 Share the core of the scale test as a performance test.
  test/clients.go
  test/e2e/e2e.go
  test/e2e/helloworld_test.go
  test/e2e/scale.go
  test/e2e/scale_test.go
  test/performance/scale_test.go
Labels: approved, lgtm, size/XL

#2948 Release mode processing for the route not being ready.
  pkg/reconciler/testing/table.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/L

#2984 Some more changes to the traffic.go
  pkg/reconciler/v1alpha1/route/reconcile_resources_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, lgtm, size/L

#2981 Fix lint errors in some docs
  DEVELOPMENT.md
  docs/creating-a-kubernetes-cluster.md
  test/README.md
  test/adding_tests.md
Labels: approved, lgtm, size/M

#2931 Drop stats from lameducked pods for autoscaling
  cmd/queue/main.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/queue/stats_reporter.go
  pkg/queue/stats_reporter_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler.go
Labels: approved, lgtm, size/L

#2967 TestHelloWorldFromShell can cope with ingress having hostname
  test/e2e/helloworld_shell_test.go
Labels: approved, lgtm, size/M

#2537 Dev tool for patching the network configuration on GKE
  DEVELOPMENT.md
  hack/README.md
  hack/dev-patch-config-gke.sh
Labels: approved, lgtm, size/M

#2997 Keep LameDuck in stat for a smoother migration.
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/statserver/server.go
Labels: approved, lgtm, size/XS

#2979 Scraper to scrape Revision service for metrics
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
Labels: approved, lgtm, size/L

#2983 Change some metrics from type float64 to int64
  pkg/activator/handler/handler_test.go
  pkg/activator/stats_reporter.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/stats_reporter.go
  pkg/autoscaler/stats_reporter_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
Labels: approved, lgtm, size/L

#2995 Don't use deprecated knative-ingressgateway in tests.
  Gopkg.lock
  Gopkg.toml
  test/cluster.sh
  test/e2e/helloworld_shell_test.go
  vendor/github.com/knative/pkg/metrics/metricskey/constants.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
Labels: approved, lgtm, size/L

#3007 Fix the scale from 0 to 1 test
  test/performance/scale_from_zero_test.go
Labels: approved, lgtm, size/S

#3009 Remove deprecated knative-ingressgateway from installation.
  config/202-gateway.yaml
  config/config-istio.yaml
Labels: approved, lgtm, size/L

#3011 Some further beautification to the traffic.go
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/reconcile_resources_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/route/traffic/errors_test.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, lgtm, size/L

#2999 Set envoy connection timeout to 10s
  third_party/istio-1.0.2/conn-timeout.yaml.patch
  third_party/istio-1.0.2/download-istio.sh
  third_party/istio-1.0.2/istio-lean.yaml
  third_party/istio-1.0.2/istio.yaml
Labels: approved, lgtm, size/S

#3017 Disable timeouts for perf runs
  test/performance-tests.sh
  test/performance/performance.go
  test/performance/scale_from_zero_test.go
Labels: approved, lgtm, size/XS

#3016 Fix the revision readiness tests
  pkg/activator/revision.go
  pkg/activator/revision_test.go
Labels: approved, lgtm, size/L

#3022 This fixes the name of the cluster ingress created for a Route.
  pkg/reconciler/v1alpha1/route/reconcile_resources.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress_test.go
  pkg/reconciler/v1alpha1/route/resources/names/names.go
  pkg/reconciler/v1alpha1/route/resources/names/names_test.go
  pkg/reconciler/v1alpha1/route/table_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
Labels: approved, lgtm, size/L

#3024 Format markdown
  DEVELOPMENT.md
  docs/creating-a-kubernetes-cluster.md
  test/adding_tests.md
Labels: approved, lgtm, size/M

#2955 Immediately send scale-from-zero stat from activator
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, lgtm, size/L

#3019 Strengthen our resource name validation.
  pkg/apis/autoscaling/v1alpha1/pa_validation_test.go
  pkg/apis/serving/v1alpha1/configuration_validation_test.go
  pkg/apis/serving/v1alpha1/metadata_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/route_validation_test.go
  pkg/apis/serving/v1alpha1/service_validation_test.go
Labels: approved, lgtm, size/L

#3032 Pick up the latest knative/pkg
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/apis/istio/common/v1alpha1/string.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/destinationrule_types.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/tracker/enqueue.go
Labels: approved, lgtm, size/M

#3037 Make Deprecated fields more explicit.
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/route_types.go
  pkg/apis/serving/v1alpha1/service_defaults.go
  pkg/apis/serving/v1alpha1/service_defaults_test.go
  pkg/apis/serving/v1alpha1/service_types.go
  pkg/apis/serving/v1alpha1/service_validation.go
  pkg/apis/serving/v1alpha1/service_validation_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_scaler_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa_test.go
  pkg/reconciler/v1alpha1/revision/queueing_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/service/resources/configuration.go
  pkg/reconciler/v1alpha1/service/resources/route.go
  pkg/reconciler/v1alpha1/service/resources/shared_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
  test/crd.go
  test/service.go
Labels: approved, lgtm, size/L

#2989 dependency: bump knative/build dep to v0.3.0
  Gopkg.lock
  Gopkg.toml
  pkg/apis/serving/v1alpha1/build_compat_test.go
  pkg/apis/serving/v1alpha1/configuration_validation_test.go
  pkg/reconciler/v1alpha1/configuration/resources/build_test.go
  third_party/config/build/release.yaml
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/build_template_types.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/build_template_validation.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/build_types.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/build_validation.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/target_path_validation.go
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#2980 Update Resources Overview documentation
  docs/resources-overview.md
Labels: approved, lgtm, size/M

#3038 Pull in the knative/pkg update to make Severity less scary.
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/v1alpha1/clusteringress/clusteringress_test.go
  pkg/reconciler/v1alpha1/revision/revision_test.go
  pkg/reconciler/v1alpha1/route/traffic/errors_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/test/kube_checks.go
Labels: approved, lgtm, size/M

#3018 Do limitation on scaling pod count instead of scaling rate
  pkg/autoscaler/autoscaler.go
Labels: approved, lgtm, size/M

#3036 Ignore resources when `DeletionTimestamp` is set.
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa.go
  pkg/reconciler/v1alpha1/autoscaling/hpa/hpa_test.go
  pkg/reconciler/v1alpha1/autoscaling/kpa/kpa.go
  pkg/reconciler/v1alpha1/clusteringress/clusteringress.go
  pkg/reconciler/v1alpha1/configuration/configuration.go
  pkg/reconciler/v1alpha1/configuration/configuration_test.go
  pkg/reconciler/v1alpha1/revision/revision.go
  pkg/reconciler/v1alpha1/revision/table_test.go
  pkg/reconciler/v1alpha1/route/route.go
  pkg/reconciler/v1alpha1/service/service.go
  pkg/reconciler/v1alpha1/service/service_test.go
  pkg/reconciler/v1alpha1/testing/functional.go
  test/clients.go
Labels: approved, lgtm, size/M

#2539 HTTP2 and gRPC support
  cmd/activator/main.go
  cmd/queue/main.go
  config/400-activator-service.yaml
  config/activator.yaml
  pkg/activator/activator.go
  pkg/activator/activator_test.go
  pkg/activator/handler/enforce_length_handler.go
  pkg/activator/handler/enforce_length_handler_test.go
  pkg/activator/revision.go
  pkg/activator/revision_test.go
  pkg/activator/util/io.go
  pkg/activator/util/io_test.go
  pkg/activator/util/rewinder.go
  pkg/activator/util/rewinder_test.go
  pkg/activator/util/transports_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_types_test.go
  pkg/http/h2c/h2c.go
  pkg/reconciler/v1alpha1/revision/resources/constants.go
  pkg/reconciler/v1alpha1/revision/resources/service.go
  pkg/reconciler/v1alpha1/revision/resources/service_test.go
  pkg/reconciler/v1alpha1/route/resources/cluster_ingress.go
  pkg/reconciler/v1alpha1/route/resources/service.go
  pkg/reconciler/v1alpha1/route/traffic/traffic.go
  pkg/reconciler/v1alpha1/route/traffic/traffic_test.go
Labels: approved, lgtm, size/XL

#3043 Replace the default cert path with tls.crt
  pkg/apis/networking/v1alpha1/clusteringress_defaults.go
  pkg/apis/networking/v1alpha1/clusteringress_defaults_test.go
Labels: approved, lgtm, size/XS

#3044 Add Markus Thömmes to networking-approvers.
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2996 Add serving with build-pipeline e2e tests
  Gopkg.lock
  Gopkg.toml
  config/200-clusterrole.yaml
  test/clients.go
  test/cluster.sh
  test/e2e/build_pipeline_test.go
  third_party/config/pipeline/release.yaml
  vendor/github.com/knative/build-pipeline/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/bash/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/controller/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/creds-init/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/git-init/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/gsutil/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/kubeconfigwriter/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/nop/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/cmd/webhook/kodata/LICENSE
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/register.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/cluster_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/cluster_task_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/cluster_task_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/doc.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/gcs_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/git_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/image_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/metadata_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_defaults.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipelineresource_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/register.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/resource_defaults.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/resource_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/result_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/storage_resource.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/task_defaults.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/task_interface.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/task_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/task_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/taskrun_types.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/doc.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/clustertask.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/doc.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/generated_expansion.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipeline.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipeline_client.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipelineresource.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipelinerun.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/task.go
  vendor/github.com/knative/build-pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/taskrun.go
  vendor/github.com/knative/build-pipeline/pkg/reconciler/v1alpha1/taskrun/list/diff.go
  vendor/github.com/knative/build-pipeline/test/logs/kodata/LICENSE
Labels: approved, lgtm, size/XXL

#3042 Update Istio to 1.0.5.
  DEVELOPMENT.md
  hack/generate-yamls.sh
  third_party/istio-1.0.2/istio-pilot-hpa.yaml
  third_party/istio-1.0.5/README.md
  third_party/istio-1.0.5/conn-timeout.yaml.patch
  third_party/istio-1.0.5/download-istio.sh
  third_party/istio-1.0.5/istio-crds.yaml
  third_party/istio-1.0.5/istio-lean.yaml
  third_party/istio-1.0.5/istio.yaml
  third_party/istio-1.0.5/namespace.yaml.patch
  third_party/istio-1.0.5/prestop-sleep.yaml.patch
Labels: approved, lgtm, size/XL

#3045 Add validation to the revisions provided in the revision list.
  pkg/apis/serving/v1alpha1/service_validation.go
  pkg/apis/serving/v1alpha1/service_validation_test.go
Labels: approved, lgtm, size/M

#3048 Make revisionID a public struct
  pkg/activator/activator.go
  pkg/activator/dedupe.go
  pkg/activator/dedupe_test.go
  pkg/activator/revision.go
Labels: approved, lgtm, size/M

#3031 Remove extra slash in mount
  config/monitoring/metrics/prometheus/300-prometheus.yaml
Labels: approved, lgtm, size/XS
