Repository knative/serving, pull requests merged in 2020-08, with the labels that each got.

#8876 Make sure we only return ready pods
  pkg/resources/pods.go
  pkg/resources/pods_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8875 An attempt to deflake the test
  pkg/reconciler/metric/metric_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8880 Fix GC config setting name
  pkg/gc/config.go
  pkg/gc/config_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8882 Add a log line when the labeler makes a patch
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/v2/metasync.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8883 Respect the initial scale reached status for initial scale
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#8887 Test that initScale revisions eventually scale down
  test/e2e/initial_scale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#8892 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8891 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8894 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/bufferpool.go
  vendor/knative.dev/networking/pkg/doc.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/probe_handler.go
  vendor/knative.dev/networking/pkg/stats.go
  vendor/knative.dev/networking/pkg/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#8895 Remove unused pkg network (replaced by knative.dev/networking/pkg)
  go.mod
  pkg/network/OWNERS
  pkg/network/doc.go
  pkg/network/ingress/doc.go
  pkg/network/ingress/ingress.go
  pkg/network/ingress/ingress_test.go
  pkg/network/status/status.go
  pkg/network/status/status_test.go
  vendor/knative.dev/networking/pkg/ingress/doc.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/modules.txt
Labels: approved, area/networking, cla: yes, lgtm, size/XXL

#8849 Add a community contact rotation for Serving.
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/M

#8888 Make SKS global resync test more consistent.
  pkg/reconciler/serverlessservice/global_resync_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8897 Update net-istio from nightly.
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8898 Implement a two way pod IP splitter
  pkg/resources/pods.go
  pkg/resources/pods_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8899 Dry up exec probe tests with t.Cleanup
  cmd/queue/execprobe.go
  cmd/queue/execprobe_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#8905 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8900 Fix data races in exec probe tests
  cmd/queue/execprobe_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#8834 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#8881 Add more early-exits for GC v2
  pkg/reconciler/gc/v2/gc.go
  pkg/reconciler/gc/v2/gc_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8906 [master] Format markdown
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/S

#8885 Propagate the Routes annotation from Service to Configuration
  pkg/reconciler/labeler/v2/accessors.go
  pkg/reconciler/service/controller.go
  pkg/reconciler/service/resources/configuration.go
  pkg/reconciler/service/resources/configuration_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8908 fix the incorrect memory and storage setting
  config/core/configmaps/deployment.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#8886 Labeler simplification
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/labeler_both_test.go
  pkg/reconciler/labeler/labelerv2_test.go
  pkg/reconciler/labeler/v2/accessors.go
  pkg/reconciler/labeler/v2/metasync.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8915 Fix flake in TestPodIPsSplitByAge due to non-deterministic lookup.
  pkg/resources/pods_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#8913 Revert "Update net-istio from nightly. (#8897)"
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8907 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/klog/v2/LICENSE
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/any_str.go
  vendor/github.com/json-iterator/go/config.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_optional.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/reflect_struct_encoder.go
  vendor/github.com/json-iterator/go/stream.go
  vendor/github.com/mailru/easyjson/Makefile
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/config.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/increase_level.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/utils/pointer/README.md
  vendor/k8s.io/utils/trace/README.md
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#8911 Remove the by value passing in favor of pointer
  pkg/reconciler/service/resources/shared_test.go
  pkg/testing/v1/service.go
  test/e2e/image_pull_error_test.go
  test/v1/service.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/S

#8928 Remove noise logging when there's no diff
  pkg/reconciler/service/service.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#8923 Fix a few nits in pkg/resources
  pkg/resources/endpoints.go
  pkg/resources/endpoints_test.go
  pkg/resources/pods.go
  pkg/resources/pods_test.go
  pkg/resources/scale.go
  pkg/resources/scale_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8912 Centralize logstream initialization.
  go.sum
  test/conformance.go
  test/conformance/api/v1/migration_test.go
  test/conformance/api/v1beta1/migration_test.go
  test/conformance/ingress/basic.go
  test/conformance/ingress/grpc.go
  test/conformance/ingress/headers.go
  test/conformance/ingress/hosts.go
  test/conformance/ingress/path.go
  test/conformance/ingress/percentage.go
  test/conformance/ingress/retry.go
  test/conformance/ingress/timeout.go
  test/conformance/ingress/tls.go
  test/conformance/ingress/update.go
  test/conformance/ingress/visibility.go
  test/conformance/ingress/websocket.go
  test/conformance/runtime/readiness_probe_test.go
  test/defaultsystem/system.go
  test/e2e/activator_test.go
  test/e2e/autoscale_test.go
  test/e2e/destroypod_test.go
  test/e2e/e2e.go
  test/e2e/gc/gc_test.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/image_pull_error_test.go
  test/e2e/initial_scale_test.go
  test/e2e/istio/authorization_test.go
  test/e2e/istio/probing_test.go
  test/e2e/logging_test.go
  test/e2e/minscale_readiness_test.go
  test/e2e/multicontainer/multicontainer_test.go
  test/e2e/namespace_test.go
  test/e2e/pod_schedule_error_test.go
  test/e2e/probe_whitelist_test.go
  test/e2e/rollback_byo_test.go
  test/e2e/route_service_test.go
  test/e2e/service_to_service_test.go
  test/e2e/subroutes_test.go
  test/e2e/tagheader/tag_header_based_routing_test.go
  test/e2e/websocket_test.go
  test/ha/activator_test.go
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#8914 propagate routes annotation on revision create
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/gc/v2/gc.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8930 Replace a todo and bespoke constant with a named one
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#8934 Remove the unused method.
  pkg/resources/pods.go
  pkg/resources/pods_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8936 Use type-safe atomics where possible
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
  pkg/http/response_recorder.go
  pkg/queue/breaker.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#8925 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8933 Ensure when we fail to progress we actually fail revision.
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8942 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8944 Add anti-affinity to our deployments.
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/webhook.yaml
  config/hpa-autoscaling/controller.yaml
  config/namespace-wildcard-certs/controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#8947 Import PKG and update observability CM and test
  config/core/configmaps/observability.yaml
  go.mod
  go.sum
  pkg/metrics/config_test.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, area/monitoring, cla: yes, lgtm, size/M

#8952 Make sure we don't override existing message on failed resources.
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8954 Carry the leaderelection patch.
  hack/k8s-client-go.patch
  hack/update-deps.sh
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#8955 Switch imagepull backoff not to use service
  test/e2e/image_pull_error_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8948 Fix logstream for http01
  test/config/100-namespace.yaml
  test/e2e-auto-tls-tests.sh
  test/e2e/autotls/auto_tls_test.go
  test/e2e_constants.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8956 Remove the unused 'name' elements.
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/revision.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8069 Add activator's pod IP instead of serivce IP to tag
  cmd/activator/main.go
  cmd/queue/main.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#8963 Limit the number of concurrent builds when uploading test images.
  test/upload-test-images.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8950 Improve debuggability of image pull err test
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/service/service.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XS

#8961 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8951 Add config knob MaxScale for setting default "autoscaling.knative.dev/maxScale"
  config/core/configmaps/autoscaler.yaml
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/autoscaler/config/config.go
  pkg/autoscaler/config/config_test.go
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/scaler.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#8962 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/config/defaults.go
  vendor/knative.dev/networking/pkg/apis/config/doc.go
  vendor/knative.dev/networking/pkg/apis/config/store.go
  vendor/knative.dev/networking/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/test/logstream/null.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#8964 Stabilize serving around crashing pods a bit
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/route/route.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#8747 [multi-container] Enable multi-container flag on by default
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/store_test.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1beta1/revision_validation_test.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#8966 Some minor cleanups around test
  test/conformance/api/v1/errorcondition_test.go
  test/test_images/failing/failing.go
  test/v1/revision.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8968 Remove Ingress and Cert conformance tests.
  test/conformance/certificate/README.md
  test/conformance/certificate/http01/certificate.go
  test/conformance/certificate/http01/run.go
  test/conformance/certificate/http01/run_test.go
  test/conformance/certificate/nonhttp01/certificate.go
  test/conformance/certificate/nonhttp01/run.go
  test/conformance/certificate/nonhttp01/run_test.go
  test/conformance/certificate/utils.go
  test/conformance/ingress/README.md
  test/conformance/ingress/basic.go
  test/conformance/ingress/grpc.go
  test/conformance/ingress/headers.go
  test/conformance/ingress/hosts.go
  test/conformance/ingress/path.go
  test/conformance/ingress/percentage.go
  test/conformance/ingress/retry.go
  test/conformance/ingress/rewrite.go
  test/conformance/ingress/run.go
  test/conformance/ingress/run_test.go
  test/conformance/ingress/timeout.go
  test/conformance/ingress/tls.go
  test/conformance/ingress/update.go
  test/conformance/ingress/util.go
  test/conformance/ingress/visibility.go
  test/conformance/ingress/websocket.go
  test/e2e-tests.sh
  test/e2e/autotls/auto_tls_test.go
  test/e2e/autotls/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#8932 Test Immediate GC
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/gc/gc_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8965 Use a super long KIngress timeout.
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/route_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#8214 Start testing istio 1.6 instead of 1.4
  test/config/security/peerauthentication.yaml
  test/config/security/policy.yaml
  test/e2e-common.sh
  test/e2e/probe_whitelist_test.go
  test/performance/performance-tests.sh
  third_party/istio-1.4-latest
  third_party/istio-1.4.9/README.md
  third_party/istio-1.4.9/download-istio.sh
  third_party/istio-1.4.9/drain-seconds.yaml.patch
  third_party/istio-1.4.9/istio-ci-mesh.yaml
  third_party/istio-1.4.9/istio-ci-no-mesh.yaml
  third_party/istio-1.4.9/istio-crds.yaml
  third_party/istio-1.4.9/istio-knative-extras.yaml
  third_party/istio-1.4.9/istio-minimal.yaml
  third_party/istio-1.4.9/namespace.yaml.patch
  third_party/istio-1.4.9/values-extras.yaml
  third_party/istio-1.4.9/values-lean.yaml
  third_party/istio-1.4.9/values-local.yaml
  third_party/istio-1.4.9/values.yaml
  third_party/istio-1.6.5/README.md
  third_party/istio-1.6.5/generate.sh
  third_party/istio-1.6.5/istio-ci-mesh-operator.yaml
  third_party/istio-1.6.5/istio-ci-mesh.yaml
  third_party/istio-1.6.5/istio-ci-no-mesh-operator.yaml
  third_party/istio-1.6.5/istio-ci-no-mesh.yaml
  third_party/istio-1.6.5/istio-crds.yaml
  third_party/istio-1.6.5/istio-minimal-operator.yaml
  third_party/istio-1.6.5/istio-minimal.yaml
  third_party/istio-stable
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#8926 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#8960 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8815 Add Kong to e2e test scripts
  test/e2e-common.sh
  third_party/kong-latest/README.md
  third_party/kong-latest/download-kong.sh
  third_party/kong-latest/kong.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#8924 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8972 Adjust the ContainerExiting test.
  test/conformance/api/v1/errorcondition_test.go
  test/conformance/api/v1alpha1/errorcondition_test.go
  test/conformance/api/v1beta1/errorcondition_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8967 Set pending state first (before annotation modification)
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/service/resources/configuration.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8973 update-deps for update status diff logging
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informed_watcher.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#8986 Remove unused code.
  pkg/queue/protobuf_stats_reporter_test.go
  test/e2e/autotls/util.go
Labels: approved, area/networking, area/test-and-release, cla: yes, lgtm, size/S

#8957 Make remaining sync/atomic usages type-safe
  cmd/queue/execprobe_test.go
  pkg/activator/handler/handler_test.go
  pkg/activator/testing/roundtripper.go
  pkg/queue/readiness/probe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#8974 Revert "Start testing istio 1.6 instead of 1.4 (#8214)"
  test/config/security/peerauthentication.yaml
  test/config/security/policy.yaml
  test/e2e-common.sh
  test/e2e/probe_whitelist_test.go
  test/performance/performance-tests.sh
  third_party/istio-1.4-latest
  third_party/istio-1.4.9/README.md
  third_party/istio-1.4.9/download-istio.sh
  third_party/istio-1.4.9/drain-seconds.yaml.patch
  third_party/istio-1.4.9/istio-ci-mesh.yaml
  third_party/istio-1.4.9/istio-ci-no-mesh.yaml
  third_party/istio-1.4.9/istio-crds.yaml
  third_party/istio-1.4.9/istio-knative-extras.yaml
  third_party/istio-1.4.9/istio-minimal.yaml
  third_party/istio-1.4.9/namespace.yaml.patch
  third_party/istio-1.4.9/values-extras.yaml
  third_party/istio-1.4.9/values-lean.yaml
  third_party/istio-1.4.9/values-local.yaml
  third_party/istio-1.4.9/values.yaml
  third_party/istio-1.6.5/README.md
  third_party/istio-1.6.5/generate.sh
  third_party/istio-1.6.5/istio-ci-mesh-operator.yaml
  third_party/istio-1.6.5/istio-ci-mesh.yaml
  third_party/istio-1.6.5/istio-ci-no-mesh-operator.yaml
  third_party/istio-1.6.5/istio-ci-no-mesh.yaml
  third_party/istio-1.6.5/istio-crds.yaml
  third_party/istio-1.6.5/istio-minimal-operator.yaml
  third_party/istio-1.6.5/istio-minimal.yaml
  third_party/istio-stable
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#8992 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8994 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#8993 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8958 Enable request log flag support
  cmd/activator/request_log.go
  cmd/activator/request_log_test.go
  cmd/queue/main.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, ok-to-test, size/L

#8969 Temporarily remove routetags for queue metrics
  pkg/queue/request_metric.go
  pkg/queue/request_metric_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#8998 Update test-infra to the latest
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#8997 Make helpers more useful and correct
  pkg/reconciler/revision/table_test.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#9001 Remove the redundant things in the tests
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8991 [master] Fix spelling errors
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#8995 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8987 Add Autoscaling approvers/reviewers to queue OWNERS
  cmd/queue/OWNERS
  pkg/queue/OWNERS
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#8059 Enable prober in HA tests for Controller
  test/ha/controller_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XS

#9005 Various formatting tidy-ups in activator
  pkg/activator/config/store.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/net/helpers.go
  pkg/activator/net/helpers_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
  pkg/activator/util/context.go
  pkg/activator/util/header.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9018 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9017 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9020 net-contour: Have Envoy emit debug logs
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9016 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9015 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#9004 Benchmark PodRevisionContext and bump cache a bit
  pkg/metrics/tags.go
  pkg/metrics/tags_test.go
Labels: approved, area/monitoring, cla: yes, lgtm, size/M

#9021 Pin knative.dev deps to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8945 Use net-istio install scripts and delete third_party/istio-*.
  test/e2e-common.sh
  third_party/istio-1.4-latest
  third_party/istio-1.4.9/README.md
  third_party/istio-1.4.9/download-istio.sh
  third_party/istio-1.4.9/drain-seconds.yaml.patch
  third_party/istio-1.4.9/istio-ci-mesh.yaml
  third_party/istio-1.4.9/istio-ci-no-mesh.yaml
  third_party/istio-1.4.9/istio-crds.yaml
  third_party/istio-1.4.9/istio-knative-extras.yaml
  third_party/istio-1.4.9/istio-minimal.yaml
  third_party/istio-1.4.9/namespace.yaml.patch
  third_party/istio-1.4.9/values-extras.yaml
  third_party/istio-1.4.9/values-lean.yaml
  third_party/istio-1.4.9/values-local.yaml
  third_party/istio-1.4.9/values.yaml
  third_party/istio-1.5-latest
  third_party/istio-1.5.7/README.md
  third_party/istio-1.5.7/generate.sh
  third_party/istio-1.5.7/istio-ci-mesh-operator.yaml
  third_party/istio-1.5.7/istio-ci-mesh.yaml
  third_party/istio-1.5.7/istio-ci-no-mesh-operator.yaml
  third_party/istio-1.5.7/istio-ci-no-mesh.yaml
  third_party/istio-1.5.7/istio-crds.yaml
  third_party/istio-1.5.7/istio-minimal-operator.yaml
  third_party/istio-1.5.7/istio-minimal.yaml
  third_party/istio-stable
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#9003 Move unused constants into commented section.
  pkg/queue/request_metric.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#9028 Add Autoscaling Approvers/Reviewers to cmd/activator OWNERS
  cmd/activator/OWNERS
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#9023 Make sure revision config wraps the api config
  pkg/apis/config/store.go
  pkg/reconciler/revision/config/store.go
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9029 Improve Queue Proxy MaxIdle settings
  cmd/queue/main.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#9033 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9038 Add some more debugging in the test
  test/e2e/minscale_readiness_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9014 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9036 Skip request logs e2e test if the configmap settings do not match
  test/e2e/logging_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9040 Improve conformance util.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9027 Allow configuring activator max idle connections
  cmd/activator/main.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9041 Rename TestService to have a distinct suffix.
  test/conformance/api/v1/service_test.go
  test/conformance/api/v1beta1/service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9042 update pkg with the newest patches
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9025 Yaml nit
  config/core/configmaps/gc.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9043 Move shared utilities to the version independent shared package
  test/conformance/api/shared/doc.go
  test/conformance/api/shared/util.go
  test/conformance/api/v1/blue_green_test.go
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/blue_green_test.go
  test/conformance/api/v1alpha1/revision_timeout_test.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/blue_green_test.go
  test/conformance/api/v1beta1/revision_timeout_test.go
  test/conformance/api/v1beta1/util.go
  test/conformance/runtime/readiness_probe_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#9024 Remove the impossible test and hooks
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9032 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9052 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9054 Pin `net-istio` commit to be used in E2E scripts
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9051 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#9049 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9050 [master] Fix spelling errors
  test/e2e/minscale_readiness_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9056 Update test-infra, reducing verbosity for contour-latest
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9055 Add a test to verify global resync on default CM update
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9059 revision_test.go next level cleanup
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9063 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#9064 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9065 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9066 Clean up autoscaling api types
  pkg/apis/autoscaling/v1alpha1/doc.go
  pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/autoscaling/v1alpha1/register.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#9062 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9060 Support more security context properties behind a feature flag
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9068 Further cleanup the revision test
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9079 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9080 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9081 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#9082 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9084 Use random to generate keys for the benchmark
  pkg/metrics/tags_test.go
Labels: approved, area/monitoring, cla: yes, lgtm, size/XS

#9083 Simplify oncall instructions
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/M

#9070 Fix the broken third_party/istio link in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#9085 Add more points for the benchmark.
  pkg/metrics/tags_test.go
Labels: approved, area/monitoring, cla: yes, lgtm, size/XS

#9088 [release 0.15] use the latest point release in upgrade tests (#8492)
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9089 [release 0.14] use the latest point release in upgrade tests (#8492)
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9086 Final pass over revision tests
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9093 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/M

#9096 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9091 Actually test changing custom TimeoutSeconds
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9097 [master] Format markdown
  DEVELOPMENT.md
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/S

#9095 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9076 Add script to only update checksums
  hack/update-checksums.sh
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9098 Various optimization and nits around the codebase
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/reconciler/gc/v2/gc.go
  test/performance/latency_test.go
  test/performance/performance.go
  test/performance/scale_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#9101 Replace knative-serving namespace in Kourier manifest before running e2e
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9107 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9108 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9113 Optimize pod stats collection a bit
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#9106 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9112 Fix serving performance tests
  test/e2e-basic-entrypoint.sh
  test/e2e-common.sh
  test/e2e-networking-library.sh
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9116 Avoid logging latency metrics if we're scaled to 0
  pkg/autoscaler/metrics/stats_scraper.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#9110 Mark ScaleTargetInitialized for case of upgrading an inactive ksvc pre-0.17
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/service_preupgrade_test.go
  test/upgrade/upgrade.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/M

#9117 Make sure the functions do what they say
  pkg/reconciler/route/table_test.go
  pkg/testing/v1/route.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#9119 Merge #9110 for #9105 to 0.17 branch
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/service_preupgrade_test.go
  test/upgrade/upgrade.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/M

#9100 Add short domains to ingress.spec.rules.hosts for cluster local visibility
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/route_test.go
  vendor/knative.dev/networking/pkg/ingress/doc.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/modules.txt
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#9057 Nominate ZhiminXiang for Networking WG lead.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#9058 Nominate nak3@ for Networking WG Lead.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS
