Repository knative/serving, pull requests merged in 2020-01, with the labels that each got.

#6377 Deploy Istio Galley on istio-lean to enable validation check
  third_party/istio-1.3.6/istio-lean.yaml
  third_party/istio-1.3.6/values-lean.yaml
  third_party/istio-1.4.2/istio-lean.yaml
  third_party/istio-1.4.2/values-lean.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#6391 Add split path and percent test
  test/conformance/ingress/path_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6402 Skipping flaky tests to avoid masking other failures.
  test/conformance/ingress/tls_test.go
  test/e2e/istio/probing_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6369 Update prober for upgrade test to continue probing regardless errors.
  Gopkg.lock
  test/prober.go
  vendor/knative.dev/pkg/test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6398 Perform multiple styles of update.
  test/conformance/ingress/update_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6399 Rename istio{,-lean,-local}.yaml to use {ci-mesh,ci-no-mesh,minimal}
  DEVELOPMENT.md
  config/config-istio.yaml
  test/e2e-common.sh
  test/performance/performance-tests.sh
  third_party/istio-1.3.6/README.md
  third_party/istio-1.3.6/download-istio.sh
  third_party/istio-1.3.6/istio-ci-mesh.yaml
  third_party/istio-1.3.6/istio-ci-no-mesh.yaml
  third_party/istio-1.3.6/istio-minimal.yaml
  third_party/istio-1.4.2/README.md
  third_party/istio-1.4.2/download-istio.sh
  third_party/istio-1.4.2/istio-ci-mesh.yaml
  third_party/istio-1.4.2/istio-ci-no-mesh.yaml
  third_party/istio-1.4.2/istio-minimal.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6268 Add integration tests for Ambassador 0.86.1
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
  third_party/ambassador-latest/README.md
  third_party/ambassador-latest/ambassador-rbac.yaml
  third_party/ambassador-latest/ambassador-service.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#6403 Switch to *URL in the ingress prober
  pkg/network/status/status.go
  pkg/network/status/status_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#6404 Add cert-manager 0.12.0 to third_party
  third_party/cert-manager-0.12.0/cert-manager-crds.yaml
  third_party/cert-manager-0.12.0/cert-manager.yaml
  third_party/cert-manager-0.12.0/download-cert-manager.sh
Labels: approved, cla: yes, lgtm, size/XXL

#6414 Add a missing profiling port.
  config/networking-ns-cert.yaml
Labels: approved, cla: yes, lgtm, size/XS

#6416 Name service files consistently with 400- prefix
  config/400-sutoscaler-service.yaml
Labels: approved, cla: yes, lgtm, size/XS

#6419 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/fake/fake.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
Labels: approved, cla: yes, lgtm, size/L

#6406 Fix Ingress prober bug introduced by #6233
  pkg/network/status/status.go
  test/e2e/istio/probing_test.go
Labels: approved, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#6420 Reinstate IngressTLS tests.
  test/conformance/ingress/tls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6131 Remove the duplicated env key in activator.yaml
  config/activator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#6425 Make sure to zero out holes if we miss a record.
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6427 Remove dead code
  pkg/autoscaler/aggregation/bucketing.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#6432 Normalize Deployment yamls a bit
  config/400-activator-service.yaml
  config/400-autoscaler-hpa-service.yaml
  config/400-controller-service.yaml
  config/400-sutoscaler-service.yaml
  config/400-webhook-service.yaml
  config/cert-manager/controller.yaml
  config/core/deployments/activator-service.yaml
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler-service.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller-service.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/webhook-service.yaml
  config/core/deployments/webhook.yaml
  config/hpa-autoscaling/controller-service.yaml
  config/hpa-autoscaling/controller.yaml
  config/istio-ingress/controller.yaml
  config/namespace-wildcard-certs/controller.yaml
Labels: approved, cla: yes, lgtm, size/XL

#6433 Always specify ingress.class
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6444 Format markdown
  config/README.md
  third_party/ambassador-latest/README.md
  third_party/istio-1.3.6/README.md
  third_party/istio-1.4.2/README.md
Labels: approved, cla: yes, lgtm, size/M

#6435 Add a handler benchmark for the throughput benchmarking
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6443 golang format tools
  pkg/reconciler/ingress/lister_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#6434 Try to normalize how Istio is treated in our e2e tests to align with others
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6449 Fix log format
  test/v1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6345 Update test/adding_tests.md
  test/README.md
  test/adding_tests.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#6455 Format markdown
  test/README.md
  test/adding_tests.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6456 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_serving.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/get.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/main.go
  vendor/knative.dev/pkg/version/version.go
Labels: approved, cla: yes, lgtm, size/L

#6457 Make benchmark relative to benchmark size.
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6429 Add BufferPool implementation to the activator and queue-proxy handler.
  cmd/queue/main.go
  pkg/activator/handler/handler.go
  pkg/network/bufferpool.go
  pkg/network/bufferpool_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6460 Fix the assignment with override.
  pkg/network/status/status_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#6440 Generalize and release the default-domain Job.
  DEVELOPMENT.md
  cmd/default-domain/main.go
  config/post-install/default-domain.yaml
  test/config/100-istio-default-domain.yaml
  test/conformance/ingress/util.go
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6447 Add a window total rolling computation.
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6448 Remove two pieces of dead code from the aggregation library.
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
  pkg/autoscaler/collector.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6431 Leverage the new directory structure for generating release yamls.
  hack/generate-yamls.sh
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6459 Better probing cancellation path
  pkg/network/status/status.go
  pkg/network/status/status_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#6470 Update status.ProbeTargetLister doc to match signature.
  pkg/network/status/status.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#6430 Allocate tracing transport only once.
  pkg/activator/handler/handler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6480 golang format tools
  pkg/network/status/status_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#6481 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/profiling/server.go
Labels: approved, cla: yes, lgtm, size/M

#6465 Set timeout for ingress prober
  cmd/queue/main.go
  pkg/network/status/status.go
Labels: approved, area/networking, cla: yes, lgtm, ok-to-test, size/XS

#6483 Fix data race and implement proper cancellation.
  pkg/network/status/status.go
  pkg/network/status/status_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6472 Fix data race introduced during refactoring of status.go
  pkg/network/status/status.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#6458 Specially wait for zipkin to be deleted in monitoring uninstallation
  test/e2e-smoke-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6485 Relax TestDestroyPodWithRequests test to allow it to start with more than 1 pod.
  test/e2e/destroypod_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6486 Fix the multiscaler test flake
  pkg/autoscaler/multiscaler.go
  pkg/autoscaler/multiscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6487 Return average rather than sum and integration in the collector.
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
  pkg/autoscaler/collector.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6493 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/network/prober/prober.go
Labels: approved, cla: yes, lgtm, size/S

#6495 Start the Contour CI integration.
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
  third_party/contour-latest/README.md
  third_party/contour-latest/contour.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#6497 Add more logging to the destroy pod test
  test/e2e/destroypod_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6473 Install istio before Knative Serving components
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6499 Update to latest net-contour after review feedback
  test/e2e-common.sh
  third_party/contour-latest/contour.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6506 Incorporate single-controller-pod update to net-contour
  third_party/contour-latest/contour.yaml
Labels: approved, cla: yes, lgtm, size/L

#6508 Undo part of #6495
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6513 Format markdown
  third_party/contour-latest/README.md
Labels: approved, cla: yes, lgtm, size/XS

#6514 Auto-update dependencies
  Gopkg.lock
  third_party/VENDOR-LICENSE
  vendor/contrib.go.opencensus.io/exporter/ocagent/LICENSE
  vendor/contrib.go.opencensus.io/exporter/ocagent/common.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/connection.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/nodeinfo.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_spans.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/version.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1/metrics_service.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.gw.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1/trace.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1/trace_config.pb.go
  vendor/github.com/golang/protobuf/descriptor/descriptor.go
  vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_json.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler_registry.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto2_convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/LICENSE
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/trie.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/test/gke/endpoint.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/main.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/test-infra/shared/testgrid/testgrid.go
Labels: approved, cla: yes, lgtm, size/XXL

#6498 A benchmark for the average computation.
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6512 Fix ineffective break in pool.
  pkg/pool/pool.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#6519 Updating pkg to latest for 0.12 release.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/configmap/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/gke/endpoint.go
Labels: approved, cla: yes, lgtm, size/L

#6521 Update the total computation during window update.
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6518 Add feature flag for graceful scaledown
  config/core/configmaps/autoscaler.yaml
  pkg/autoscaler/config.go
  pkg/autoscaler/config_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6522 Fix invalid error format
  pkg/reconciler/ingress/config/istio.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#6511 Fix error string capitalization and properly handle error in test.
  test/conformance/ingress/util.go
  test/e2e/websocket_test.go
  test/prober.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6525 Add kubernetes version check to autoscaler
  cmd/autoscaler/main.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#6527 Remove overhead allocations and run a parallel benchmark as well.
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6509 Only expanding hosts when cluster local gateway is set
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#6524 Add a secondary window computation.
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
  pkg/autoscaler/collector.go
  pkg/autoscaler/collector_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#6526 Update prometheus config
  config/monitoring/metrics/prometheus/100-prometheus-scrape-config.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, needs-ok-to-test, size/XS

#6515 Provide contextualized revision data on the request's context.
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/context_handler.go
  pkg/activator/handler/context_handler_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
  pkg/activator/handler/requestevent_handler.go
  pkg/activator/handler/requestevent_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6536 Check endpoint state before listing pods
  test/e2e/destroypod_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6534 Pull apart probe and proxy handler in the queue-proxy.
  cmd/queue/main.go
  cmd/queue/main_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6533 Discard all bytes read in the handler benchmark.
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6532 Set prober target port from gateway instead of endpoint
  pkg/network/status/status.go
  pkg/network/status/status_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6539 Remove the outdated go version check.
  cmd/activator/main.go
  pkg/goversion/go12.go
  pkg/goversion/goversion.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6540 Add process uptime to the queue.
  cmd/queue/main.go
  pkg/queue/prometheus_stats_reporter.go
  pkg/queue/prometheus_stats_reporter_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6439 Add Auto TLS E2E test for per ksvc Certificate provision by using local CA
  test/clients.go
  test/conformance/ingress/util.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/autotls/auto_tls_test.go
Labels: approved, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#6538 Avoid tracing allocations if tracing is disabled anyway.
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#5830 Update test for checking last pinned timestamp
  pkg/reconciler/route/reconcile_resources_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6547 Add benchmarks for the request log handler and reduce contention.
  pkg/http/request_log.go
  pkg/http/request_log_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6557 Create SKS before KPA in autoscaler GlobalResync test.
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#6559 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#6555 Call Start function so that configmapwatcher will be shut down when context is canceled.
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#6556 Use correct tickProvider in multiscaler to allow override in test.
  pkg/autoscaler/collector.go
  pkg/autoscaler/multiscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#6560 Update httpproxy with port and header, so it can be used in Ingress conformance tests without queue-proxy
  test/test_images/httpproxy/httpproxy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6561 Convert tag.Insert to tag.Upsert
  pkg/activator/stats_reporter.go
  pkg/autoscaler/stats_reporter.go
  pkg/queue/stats/stats_reporter.go
  pkg/reconciler/stats_reporter.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6563 Add parsing bit to the new process uptime metric.
  pkg/autoscaler/collector.go
  pkg/autoscaler/http_scrape_client.go
  pkg/autoscaler/http_scrape_client_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6573 Fix a bug with the rounding of the small numbers during metric computation
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
  pkg/autoscaler/collector_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6574 Actually handle revision get error.
  pkg/reconciler/route/reconcile_resources_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#6579 Clarify how to check Istio gateway is installed
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#6581 Improve readability in QP metrics and add tests
  pkg/queue/stats.go
  pkg/queue/stats_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#6578 Wait for reconcilation events in nscert tests.
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#6585 Generalize precision func and raise default to 6 digits
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#6586 Add sideEffects to webhooks
  config/core/webhooks/configmap-validation.yaml
  config/core/webhooks/defaulting.yaml
  config/core/webhooks/resource-validation.yaml
Labels: approved, cla: yes, lgtm, size/XS

#6575 Remove unused queue metrics constant.
  pkg/apis/serving/v1alpha1/revision_lifecycle.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#6544 Remove outbound network config instruction from DEVELOPMENT.md
  DEVELOPMENT.md
  hack/README.md
  hack/dev-patch-config-gke.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6576 Remove unused aggregation code.
  pkg/autoscaler/aggregation/aggregation.go
  pkg/autoscaler/aggregation/aggregation_test.go
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#6590 Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#6580 Add ingress conformance test for mixed visibility
  test/conformance/ingress/util.go
  test/conformance/ingress/visibility_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6589 Clean up VirtualService when ingress.class annotation is not istio
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6569 Reconcile ingress when annotation is updated
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/reconcile_resources_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#6476 Add podsLister to KPA and report pod state metrics
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/stats_reporter.go
  pkg/autoscaler/stats_reporter_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/testing/v1alpha1/listers.go
  pkg/resources/endpoints.go
  pkg/resources/endpoints_test.go
  pkg/resources/pods.go
  pkg/resources/pods_test.go
Labels: approved, area/API, area/autoscale, area/monitoring, cla: yes, lgtm, size/XL

#5841 move ObservabilityConfig funcs into knative.dev/pkg
  Gopkg.lock
  Gopkg.toml
  cmd/webhook/main.go
  pkg/metrics/config.go
  pkg/metrics/config_test.go
  pkg/metrics/doc.go
  pkg/metrics/zz_generated.deepcopy.go
  pkg/reconciler/revision/config/store.go
  pkg/reconciler/revision/config/store_test.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/reconciler/revision/table_test.go
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/metrics/config_observability.go
Labels: approved, area/API, area/monitoring, cla: yes, lgtm, needs-ok-to-test, size/L

#6595 Use duck.CreateBytePatch and clean up dead code
  test/e2e/subroutes_test.go
  test/util.go
  test/v1/configuration.go
  test/v1/service.go
  test/v1alpha1/configuration.go
  test/v1alpha1/service.go
  test/v1beta1/configuration.go
  test/v1beta1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6594 Fix various nits in the certificate related code.
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/route/resources/certificate.go
  pkg/reconciler/route/resources/names/names.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#6572 Update grafana config
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-efficiency.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-reconciler.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, ok-to-test, size/S

#6596 Fix the issue which kcert ends up with Failed status when cm Cert is InProgress
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6600 golang format tools
  pkg/reconciler/revision/config/store.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#6605 Fix panic in TestUpdate, ensure all probes in goroutine are canceled
  test/conformance/ingress/update_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6607 Change rbac to roles, up-level the constructs that union them.
  config/200-addressable-resolvers-clusterrole.yaml
  config/200-clusterrole-namespaced.yaml
  config/200-clusterrole.yaml
  config/200-podspecable-bindings-clusterrole.yaml
  config/200-serviceaccount.yaml
  config/201-clusterrolebinding.yaml
  config/README.md
  config/core/200-serviceaccount.yaml
  config/core/rbac/200-serviceaccount.yaml
  config/core/roles/addressable-resolvers-clusterrole.yaml
  config/core/roles/clusterrole-namespaced.yaml
  config/core/roles/clusterrole.yaml
  config/core/roles/podspecable-bindings-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M

#6609 delete old cert-manager 0.9.1
  DEVELOPMENT.md
  third_party/cert-manager-0.9.1/cert-manager-crds.yaml
  third_party/cert-manager-0.9.1/cert-manager.yaml
  third_party/cert-manager-0.9.1/download-cert-manager.sh
Labels: approved, cla: yes, lgtm, size/XXL

#6567 Update kube-state-metrics yaml
  third_party/config/monitoring/metrics/prometheus/kubernetes/kube-state-metrics.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, ok-to-test, size/XS

#6587 Set the User-Agent for Ingress conformance tests.
  test/conformance/ingress/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#6610 Add missing webhook port
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#6608 Some cleanups to the kpa code
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/resources/pods_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#6517 Update Kourier to v0.3.7
  test/e2e-common.sh
  third_party/kourier-latest/download-kourier.sh
  third_party/kourier-latest/kourier.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#6615 Format markdown
  config/README.md
Labels: approved, cla: yes, lgtm, size/XS

#6616 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/convert.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/junit/junit.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/testutils/junithelper/README.md
  vendor/knative.dev/pkg/testutils/junithelper/main.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/shared/testgrid/testgrid.go
Labels: approved, cla: yes, lgtm, size/L

#6505 add probe path for whitelisting
  pkg/activator/net/revision_backends.go
  test/config/100-namespace.yaml
  test/config/security/destinationrule.yaml
  test/config/security/policy.yaml
  test/e2e-common.sh
  test/e2e/e2e.go
  test/e2e/probe_whitelist_test.go
  test/e2e_flags.go
Labels: approved, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#6622 Update kourier-control image version to v0.3.8
  third_party/kourier-latest/download-kourier.sh
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#6603 Fix the issue which kcert ends up with Failed status when cert manager Certificate becomes Failed with Inprogress
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6633 Order virtualservices to get a stable deletion order.
  pkg/reconciler/ingress/ingress.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#6620 Add appropriate log keys to the activator's endpoint management.
  pkg/activator/net/revision_backends.go
  pkg/activator/net/throttler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6635 Rename 'ia' to 'ing' since IngressAccessor is no longer used
  pkg/reconciler/ingress/ingress.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#6637 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
Labels: approved, cla: yes, lgtm, size/S

#6636 Use static test setup for static config tests in nscert.
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#6643 Add the actual # of endpoints observed.
  pkg/autoscaler/autoscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#6626 Final change to exclude young pods from stats computations.
  pkg/autoscaler/sample_size.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#6629 Refactor Auto TLS E2E test
  test/config/autotls/certmanager/selfsigned/config-certmanager.yaml
  test/config/autotls/certmanager/selfsigned/issuer.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/autotls/auto_tls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6641 Correct API group name for cert manager in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#6650 Add default-domain job to our release yamls.
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6649 Thread in Metric.Spec.StableWindow as the young pod cutoff time.
  pkg/autoscaler/collector.go
  pkg/autoscaler/collector_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/autoscaler/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6655 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/test/mako/alerter/alerter.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, cla: yes, lgtm, size/M

#6656 Remove a bunch of deadcode and move constants into tests where applicable.
  pkg/activator/handler/context_handler.go
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
  pkg/autoscaler/stats_scraper.go
  pkg/reconciler/revision/resources/constants.go
  pkg/reconciler/revision/resources/deploy_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/S

#6647 Some pre-spring cleaning in the scaler code
  pkg/reconciler/autoscaling/kpa/scaler.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#6654 Correctly pass in probe frequency in revision backend manager.
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6658 Remove randomness from the test
  pkg/autoscaler/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#6542 Include roundtrip tests of our external types via JSON and the apis.Convertible interface
  Gopkg.lock
  pkg/apis/serving/v1/configuration_lifecycle.go
  pkg/apis/serving/v1/configuration_types.go
  pkg/apis/serving/v1/fuzzer.go
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_types.go
  pkg/apis/serving/v1/roundtrip_test.go
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/apis/serving/v1/route_types.go
  pkg/apis/serving/v1/service_lifecycle.go
  pkg/apis/serving/v1/service_types.go
  pkg/apis/serving/v1alpha1/configuration_conversion.go
  pkg/apis/serving/v1alpha1/revision_conversion.go
  pkg/apis/serving/v1alpha1/roundtrip_test.go
  pkg/apis/serving/v1alpha1/route_conversion.go
  pkg/apis/serving/v1alpha1/service_conversion.go
  pkg/apis/serving/v1beta1/configuration_conversion.go
  pkg/apis/serving/v1beta1/revision_conversion.go
  pkg/apis/serving/v1beta1/roundtrip_test.go
  pkg/apis/serving/v1beta1/route_conversion.go
  pkg/apis/serving/v1beta1/service_conversion.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/compatibility.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
Labels: approved, area/API, cla: yes, lgtm, size/XXL

#6664 Improve error reporting in the probe handling
  pkg/queue/readiness/probe.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#6678 Fix some typos in comments
  pkg/apis/autoscaling/register.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#6667 Use manual ticker throughout multiscaler test to deflake them.
  pkg/autoscaler/multiscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6614 WaitForEndpointState in ObservedConcurrencyTest
  test/performance/observed_concurency_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6668 Wait for Service to be ready in Auto TLS test
  test/e2e/autotls/auto_tls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#6675 Assorted linter fixes.
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler_test.go
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6676 Auto-update dependencies
  Gopkg.lock
  third_party/VENDOR-LICENSE
  vendor/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/rogpeppe/go-internal/semver/semver.go
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XL

#6679 Fix the outdated comment
  test/e2e/scale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6662 Remove prober status cache eviction logic
  pkg/network/status/status.go
  pkg/network/status/status_test.go
  pkg/reconciler/ingress/controller.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#6631 E2E test for namespace cert for Auto TLS
  test/e2e/autotls/auto_tls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6684 Update the SLO for scale test and permit more resources
  test/e2e/scale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6426 Simplify development instructions
  DEVELOPMENT.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6545 Tests for creating a new service after upgrade and downgrade
  test/upgrade/service_postdowngrade_test.go
  test/upgrade/service_postupgrade_test.go
  test/upgrade/upgrade.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6686 Improve logging in the autoscale integation test.
  test/e2e/autoscale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS
