Repository knative/serving, pull requests merged in 2020-05, with the labels that each got.

#7803 Use a higher timeout for conformance/ingress tests.
  go.mod
  go.sum
  test/conformance/ingress/util.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7808 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7809 [master] Auto-update dependencies
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, cla: yes, lgtm, size/XS

#7811 Bump TCP retry to even higher for conformance/ingress test.
  test/conformance/ingress/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7814 Use new go1.14 lib func for header values
  pkg/http/header.go
  pkg/http/header_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#7804 Actual implementation of direct pod scraping
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#7817 Revert pull/7756
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/certificate/controller.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/service/controller.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#7810 Use net-certmanager YAML for E2E tests
  hack/generate-yamls.sh
  test/e2e-common.sh
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#7815 Add logging to the stats scraper
  cmd/autoscaler/main.go
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#7784 bump go.mod to go 1.14
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#7828 Minor syntax tweak so value can be reused
  pkg/reconciler/revision/revision.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#7829 Rename deprecated functions and small linting nits.
  pkg/http/request_log.go
  pkg/reconciler/configuration/controller.go
  pkg/reconciler/gc/controller.go
  pkg/reconciler/nscert/controller.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/service/controller.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#7757 Fix flake in TestPathAndPercentageSplit
  test/conformance/ingress/path_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7830 Add controller type filter everywhere and collapse code.
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/service/controller.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#7837 Update release badge to show latest release sorted by semver
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#7582 Add crd-install step to dev instructions
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#7832 Remove broken symlinks to cert-manager yamls
  config/200-clusterrole-certmanager.yaml
  config/config-certmanager.yaml
  config/networking-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7795 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7838 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7841 Fix some nits in the revision lifecycle and other places
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/network/probe_handler_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#7842 Attempt to not use retry in KIngress.
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#7843 Fix #7446 and just keep the default CM in LE
  config/core/configmaps/leader-election.yaml
  pkg/leaderelection/config_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#7845 Simplify and unify the metric aggreggation when computing averages.
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/stats_scraper.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#7800 remove dep-collector and licenseclassifier
  go.mod
  hack/tools.go
  vendor/github.com/google/licenseclassifier/.travis.yml
  vendor/github.com/google/licenseclassifier/CHANGELOG
  vendor/github.com/google/licenseclassifier/CONTRIBUTING.md
  vendor/github.com/google/licenseclassifier/LICENSE
  vendor/github.com/google/licenseclassifier/README.md
  vendor/github.com/google/licenseclassifier/classifier.go
  vendor/github.com/google/licenseclassifier/file_system_resources.go
  vendor/github.com/google/licenseclassifier/forbidden.go
  vendor/github.com/google/licenseclassifier/internal/sets/sets.go
  vendor/github.com/google/licenseclassifier/internal/sets/stringset.go
  vendor/github.com/google/licenseclassifier/license_type.go
  vendor/github.com/google/licenseclassifier/stringclassifier/CONTRIBUTING.md
  vendor/github.com/google/licenseclassifier/stringclassifier/LICENSE
  vendor/github.com/google/licenseclassifier/stringclassifier/README.md
  vendor/github.com/google/licenseclassifier/stringclassifier/classifier.go
  vendor/github.com/google/licenseclassifier/stringclassifier/internal/pq/priority.go
  vendor/github.com/google/licenseclassifier/stringclassifier/searchset/searchset.go
  vendor/github.com/google/licenseclassifier/stringclassifier/searchset/tokenizer/tokenizer.go
  vendor/github.com/sergi/go-diff/AUTHORS
  vendor/github.com/sergi/go-diff/CONTRIBUTORS
  vendor/github.com/sergi/go-diff/LICENSE
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
  vendor/knative.dev/test-infra/tools/dep-collector/README.md
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
  vendor/knative.dev/test-infra/tools/dep-collector/main.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#7846 Update Istio version to 1.5.2 for CI
  third_party/istio-1.5-latest
  third_party/istio-1.5.2/README.md
  third_party/istio-1.5.2/generate.sh
  third_party/istio-1.5.2/istio-ci-mesh-operator.yaml
  third_party/istio-1.5.2/istio-ci-mesh.yaml
  third_party/istio-1.5.2/istio-ci-no-mesh-operator.yaml
  third_party/istio-1.5.2/istio-ci-no-mesh.yaml
  third_party/istio-1.5.2/istio-crds.yaml
  third_party/istio-1.5.2/istio-minimal-operator.yaml
  third_party/istio-1.5.2/istio-minimal.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#7798 Make sure all pods run in leader-elected mode in HA tests
  test/e2e-tests.sh
  test/ha/ha.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7849 Deprecation notice for tick-interval CM setting
  config/core/configmaps/autoscaler.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7850 Fix wrong env value GATEWAY_NAMESPACE to GATEWAY_NAMESPACE_OVERRIDE
  test/e2e-auto-tls-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7854 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7851 Align panic threshold with configuration knob.
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
  pkg/autoscaler/scaling/multiscaler.go
  pkg/reconciler/autoscaling/kpa/resources/decider.go
  pkg/reconciler/autoscaling/kpa/resources/decider_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#7833 [RELEASE-0.13] Backport KPA and Ingress bug fixes.
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/testing/functional.go
  pkg/testing/v1/route.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#7816 Fix the bug to create dns record for Auto TLS E2E test
  test/e2e/autotls/config/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7857 Wait for static IP to be correctly setup in e2e-common.sh
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7592 Update the location where to retrieve net-istio
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7860 Reset metrics in tests between runs.
  pkg/autoscaler/scaling/autoscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#7861 Fix go lint warning and consistent naming.
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#7863 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7865 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#7868 Make error message more true
  pkg/autoscaler/config/config.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#7840 Add JRBANCEL to networking-approvers.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#7859 No need to lock the panic state
  pkg/autoscaler/scaling/autoscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#7862 Update autoscaler package doc comment
  pkg/autoscaler/doc.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#7864 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7867 Use ClusterIP for our monitoring services so we can still access them using kubectl proxy
  config/monitoring/metrics/prometheus/100-grafana.yaml
  config/monitoring/metrics/prometheus/300-prometheus.yaml
  third_party/config/monitoring/logging/elasticsearch/kibana.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, size/M

#7870 update deps
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#7872 Try to deal with logging in activator/net
  pkg/activator/net/revision_backends.go
  pkg/activator/net/throttler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#7678 Add service initial scale annotation and validation
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/metric_validation.go
  pkg/apis/autoscaling/v1alpha1/pa_validation.go
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/service_validation.go
  pkg/apis/serving/v1alpha1/configuration_validation.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/route_validation.go
  pkg/apis/serving/v1alpha1/service_validation.go
  pkg/apis/serving/v1beta1/configuration_validation.go
  pkg/apis/serving/v1beta1/revision_validation.go
  pkg/apis/serving/v1beta1/route_validation.go
  pkg/apis/serving/v1beta1/service_validation.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#7875 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#7880 Implement krshaped for autoscaling
  pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/metric_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/metric_types.go
  pkg/apis/autoscaling/v1alpha1/metric_types_test.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/autoscaling/v1alpha1/pa_types_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#7873 A bit overboard logging fixes
  cmd/queue/main.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#7876 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7877 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7885 Add dummy.go files to enable vendoring our configs
  config/core/configmaps/dummy.go
  config/core/deployments/dummy.go
  config/core/dummy.go
  config/core/resources/dummy.go
  config/core/roles/dummy.go
  config/core/webhooks/dummy.go
  config/hpa-autoscaling/dummy.go
  config/namespace-wildcard-certs/dummy.go
  config/post-install/dummy.go
Labels: approved, cla: yes, lgtm, size/L

#7883 Add log stream to the HA tests
  test/ha/activator_test.go
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7886 Update README.md
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#7882 Remove /var/log symlink logic from the queue proxy
  cmd/queue/main.go
  cmd/queue/main_test.go
  config/monitoring/logging/elasticsearch/100-fluentd-configmap.yaml
  config/monitoring/logging/stackdriver/100-fluentd-configmap.yaml
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/reconciler/revision/revision_test.go
  test/test_images/varlog/service.yaml
  test/test_images/varlog/varlog.go
Labels: approved, area/API, area/monitoring, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#7866 Order ContainerStatuses the same as spec.Containers
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7884 Update outdated doc link to errors
  test/conformance/api/v1/errorcondition_test.go
  test/conformance/api/v1alpha1/errorcondition_test.go
  test/conformance/api/v1beta1/errorcondition_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7891 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7879 Implement krshaped for networking
  pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  pkg/apis/networking/v1alpha1/certificate_lifecycle_test.go
  pkg/apis/networking/v1alpha1/certificate_types.go
  pkg/apis/networking/v1alpha1/certificate_types_test.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/ingress_types_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_lifecycle.go
  pkg/apis/networking/v1alpha1/serverlessservice_lifecycle_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_types.go
  pkg/apis/networking/v1alpha1/serverlessservice_types_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#7890 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7869 Fix the failing postsubmit jobs by import perf-tests tool
  hack/tools.go
  vendor/google.golang.org/api/container/v1beta1/container-api.json
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/knative.dev/pkg/test/gke/addon.go
  vendor/knative.dev/pkg/test/gke/client.go
  vendor/knative.dev/pkg/test/gke/endpoint.go
  vendor/knative.dev/pkg/test/gke/location.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/test/gke/wait.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/main.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#7893 Remove RevisionConcurrencyModel from serving.
  pkg/activator/net/throttler.go
  pkg/apis/serving/v1alpha1/configuration_validation_test.go
  pkg/apis/serving/v1alpha1/revision_defaults.go
  pkg/apis/serving/v1alpha1/revision_defaults_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/service_validation_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#7894 Increase number of requests for activator HA test to ensure enough stats
  test/ha/activator_test.go
Labels: approved, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/XS

#7896 Remove the build related stuff from v1alpha1 API
  pkg/apis/serving/v1alpha1/configuration_validation.go
  pkg/apis/serving/v1alpha1/configuration_validation_test.go
  pkg/apis/serving/v1alpha1/revision_conversion.go
  pkg/apis/serving/v1alpha1/revision_conversion_test.go
  pkg/apis/serving/v1alpha1/revision_lifecycle.go
  pkg/apis/serving/v1alpha1/revision_lifecycle_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/revision_validation.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#7898 Add desired pods as well to the log string.
  pkg/reconciler/autoscaling/kpa/kpa.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#7900 Fix flake in TestVisibilitySplit
  test/conformance/ingress/visibility_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7899 Fix updated endpoints updated message
  pkg/activator/net/throttler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#7902 Import the latest pkg and add probes
  config/core/deployments/webhook.yaml
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#7901 Make sure we wait for things to run their course
  pkg/reconciler/autoscaling/hpa/hpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#7904 Fix flake in TestPercentage
  test/conformance/ingress/percentage_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7907 Remove unnecessary small window settings.
  test/e2e/istio/authorization_test.go
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7909 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7913 Initial config setting for the last pod retention
  config/core/configmaps/autoscaler.yaml
  pkg/autoscaler/config/config.go
  pkg/autoscaler/config/config_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#7914 Remove knative-build namespace from grafana-dash-knative-efficiency
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-efficiency.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, size/S

#7855 Clean up resources by using yaml path which has the replaced namespace
  test/e2e-auto-tls-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7921 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7922 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#7783 Fix some dead links in the runtime contract document
  docs/runtime-contract.md
Labels: approved, cla: yes, lgtm, size/XS

#7889 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7917 Move HPA E2E tests to a separate package.
  test/e2e-tests.sh
  test/e2e/autoscale.go
  test/e2e/autoscale_test.go
  test/e2e/hpa/hpa_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#7697 Update knative.dev/pkg to generate controllers with custom controller agent names.
  pkg/reconciler/gc/controller.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#7918 [RELEASE-0.13] Add validation check to tag name
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#7930 Add new helper for the InactiveTime
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#7931 Final implementation of the last pod retention
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#7919 [RELEASE-0.14] Add validation check to tag name
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#7940 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7941 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7934 Rename operation name for activator's proxy span and queue-proxy's span
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#7943 [RELEASE-0.13] Drop 'no longer exist' line to DEBUG.
  Gopkg.lock
  Gopkg.toml
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#7944 [RELEASE-0.14] Drop 'no longer exist' line to DEBUG.
  Gopkg.lock
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#7780 Create strict mode for dryrun validation
  pkg/webhook/podspec_dryrun.go
  pkg/webhook/podspec_dryrun_test.go
  pkg/webhook/validate_service.go
  test/e2e/service_validation_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#7942 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#7945 Fix import issue for metrics
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/configuration/queueing_test.go
  pkg/reconciler/metric/metric_test.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/serverlessservice/global_resync_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/S

#7947 No need to pass map by pointer
  test/performance/benchmarks/deployment-probe/continuous/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7939 Update Istio version to 1.5.4 and 1.4.9 for CI
  third_party/istio-1.4-latest
  third_party/istio-1.4.9/README.md
  third_party/istio-1.4.9/download-istio.sh
  third_party/istio-1.4.9/drain-seconds.yaml.patch
  third_party/istio-1.4.9/istio-ci-mesh.yaml
  third_party/istio-1.4.9/istio-ci-no-mesh.yaml
  third_party/istio-1.4.9/istio-crds.yaml
  third_party/istio-1.4.9/istio-knative-extras.yaml
  third_party/istio-1.4.9/istio-minimal.yaml
  third_party/istio-1.4.9/namespace.yaml.patch
  third_party/istio-1.4.9/values-extras.yaml
  third_party/istio-1.4.9/values-lean.yaml
  third_party/istio-1.4.9/values-local.yaml
  third_party/istio-1.4.9/values.yaml
  third_party/istio-1.5-latest
  third_party/istio-1.5.4/README.md
  third_party/istio-1.5.4/generate.sh
  third_party/istio-1.5.4/istio-ci-mesh-operator.yaml
  third_party/istio-1.5.4/istio-ci-mesh.yaml
  third_party/istio-1.5.4/istio-ci-no-mesh-operator.yaml
  third_party/istio-1.5.4/istio-ci-no-mesh.yaml
  third_party/istio-1.5.4/istio-crds.yaml
  third_party/istio-1.5.4/istio-minimal-operator.yaml
  third_party/istio-1.5.4/istio-minimal.yaml
  third_party/istio-stable
Labels: approved, cla: yes, lgtm, size/L

#7949 One more instance of metric import
  test/v1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7946 Set timeouts on admission webhooks
  config/core/webhooks/configmap-validation.yaml
  config/core/webhooks/defaulting.yaml
  config/core/webhooks/resource-validation.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7948 Increase Activator probe failure threshold from 30s to 2min.
  config/core/deployments/activator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7932 Add allow-container-concurrency-zero configmap property
  config/core/configmaps/defaults.yaml
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#7953 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7952 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7954 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/utils.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/test_util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#7956 Remove duplicate test
  pkg/autoscaler/scaling/autoscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#7958 Use mako image from knative-tests
  test/performance/Benchmarks.md
  test/performance/benchmarks/dataplane-probe/continuous/dataplane-probe.yaml
  test/performance/benchmarks/deployment-probe/continuous/benchmark.yaml
  test/performance/benchmarks/load-test/continuous/load-test.yaml
  test/performance/benchmarks/scale-from-zero/continuous/scale-from-zero.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7961 Gave the collector code a good scrub.
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#7960 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7964 Clean up double imports to make staticcheck happier
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/service/service.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#7962 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7966 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#7968 Migrate off the deprecated config map watch function
  cmd/activator/main.go
  cmd/autoscaler/main.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#7969 Unify the constants across binaries
  cmd/activator/main.go
  cmd/queue/main.go
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, area/networking, cla: yes, lgtm, size/S

#7963 Use graceful shutdowns in the activator HA test.
  test/ha/activator_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7970 Use panic window for EBC computation
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#7935 Use configmap parser library from pkg.
  pkg/apis/config/defaults.go
  pkg/autoscaler/config/config.go
  pkg/deployment/config.go
  pkg/gc/config.go
  pkg/network/network.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#7971 Get rid of quote escaping where possible.
  pkg/apis/serving/k8s_validation_test.go
  pkg/queue/forwarded_shim_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#7972 Replace pkg/pool by knative.dev/pkg/pool
  go.mod
  go.sum
  pkg/pool/OWNERS
  pkg/pool/pool_test.go
  test/conformance/ingress/path_test.go
  test/conformance/ingress/percentage_test.go
  test/conformance/ingress/visibility_test.go
  test/e2e/scale.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/pool/doc.go
  vendor/knative.dev/pkg/pool/interface.go
  vendor/knative.dev/pkg/pool/pool.go
  vendor/modules.txt
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#7973 update e2e documentation with v1 examples
  test/adding_tests.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7976 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7977 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7978 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#7732 Add e2e tests for service initial scale
  test/e2e-tests.sh
  test/e2e/initial_scale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#7878 Implement KRShaped for serving v1
  pkg/apis/serving/v1/configuration_lifecycle.go
  pkg/apis/serving/v1/configuration_lifecycle_test.go
  pkg/apis/serving/v1/configuration_types.go
  pkg/apis/serving/v1/configuration_types_test.go
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/apis/serving/v1/revision_types.go
  pkg/apis/serving/v1/revision_types_test.go
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/apis/serving/v1/route_lifecycle_test.go
  pkg/apis/serving/v1/route_types.go
  pkg/apis/serving/v1/route_types_test.go
  pkg/apis/serving/v1/service_lifecycle.go
  pkg/apis/serving/v1/service_lifecycle_test.go
  pkg/apis/serving/v1/service_types.go
  pkg/apis/serving/v1/service_types_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#7975 Simplify mutexes in collector state.
  pkg/autoscaler/metrics/collector.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#7982 Modernize the route service test
  pkg/reconciler/route/resources/service_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#7928 Use the generated reconciler to handle observed generation for Networking
  pkg/apis/networking/v1alpha1/certificate_types.go
  pkg/apis/networking/v1alpha1/certificate_types_test.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/ingress_types_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_types.go
  pkg/apis/networking/v1alpha1/serverlessservice_types_test.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/reconciler/serverlessservice/serverlessservice.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#7981 Fix the lower bound check in metadata test and other nits
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1beta1/revision_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7989 Revert "Update the location where to retrieve net-istio (#7592)"
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7988 Update dependencies and fix changed error message.
  go.mod
  go.sum
  pkg/leaderelection/config_test.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/modules.txt
Labels: approved, area/API, cla: yes, lgtm, size/L

#7965 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7992 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8001 Raise WebHook timeout since they seem to fail often on prow
  config/core/webhooks/configmap-validation.yaml
  config/core/webhooks/defaulting.yaml
  config/core/webhooks/resource-validation.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7996 [RELEASE] Pin knative.dev/{pkg,test-infra} to release-0.15
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7983 Import 05/18 nightly of net-certmanager for testing
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/L

#7163 Propagate status from KCert to Route
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/apis/serving/v1/route_lifecycle_test.go
  pkg/apis/serving/v1alpha1/route_lifecycle.go
  pkg/apis/serving/v1alpha1/route_lifecycle_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/testing/v1/route.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#7986 Clean PA lifecycle test
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/serving/k8s_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#8003 Don't create the scraper if we are not going to use one.
  cmd/autoscaler/main.go
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#7990 Make throttler test more robust.
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#7987 Fail configMap if the queue image key is empty.
  pkg/deployment/config.go
  pkg/deployment/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#8010 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#7991 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8014 Include nightly certmanager into the release again.
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8011 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8017 Add the processing for the last pod timeout annotation
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#8023 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8026 Clean up stats.go
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/queue/stats.go
  pkg/queue/stats_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#8018 Fix the min max scale validation
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/autoscaling/v1alpha1/pa_validation_test.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1beta1/revision_validation_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#8025 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8029 As discussed in TOC meeting rationalize the owners
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/M

#8031 Final strokes for annotation drive last pod retention
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M
