Repository knative/serving, pull requests merged in 2020-09, with the labels that each got.

#9240 Small document fix
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9242 Add back the quick-mode check
  test/e2e/autoscale.go
  test/e2e/grpc_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9243 Cleanup route tests
  pkg/reconciler/route/resources/labels/labels.go
  pkg/reconciler/route/resources/labels/labels_test.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/visibility/visibility.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#9246 Disable TestInitScaleZero
  test/e2e/initial_scale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9019 Reimplement semaphore using packaged integer.
  pkg/queue/breaker.go
  pkg/queue/breaker_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#9248 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9251 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9253 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9250 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9252 [master] Update GitHub Actions
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9255 Retry the test since it's racy internally to avoid flakes
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/route/route_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9256 Remove the code for dealing with multiple private services.
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9239 validateDomains should check (not wait) for the expected text.
  go.mod
  go.sum
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9257 Remove the field which is not set by the test clients
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#9215 Make the liveness check failureThreshold higher than the readiness check.
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/webhook.yaml
  config/post-install/default-domain.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, ok-to-test, size/M

#9249 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9258 Don't mark resources available false if ServiceName not populated
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/reconciler/revision/table_test.go
  test/e2e/initial_scale_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#9233 Forwarder can forward metrics via IP address
  pkg/autoscaler/statforwarder/forwarder.go
  pkg/autoscaler/statforwarder/forwarder_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#9261 Tidy up autoscaler config_test a bit
  pkg/autoscaler/config/config_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#9262 Avoid using Cleanup in reconciler test to fix races
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/metric/metric_test.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#9263 Remove unused test helper.
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9268 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9269 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#9270 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9271 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#9254 Add a golangci-lint action to increase code hygiene.
  .github/workflows/knative-lint.yaml
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9276 Fix a few things in throttler test
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9278 Some brushover the traffic file
  pkg/reconciler/route/traffic/traffic.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#9279 Fix the confusing comment for CPU and memeory request and limit
  config/core/configmaps/defaults.yaml
Labels: approved, cla: yes, lgtm, size/S

#9267 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9282 Simplify autoscale tests a bit by reducing options.
  test/e2e/autoscale.go
  test/e2e/autoscale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9283 Document existence of update-checksums script
  DEVELOPMENT.md
  hack/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9284 Clean up concurrency reporter tests and fix benchmark.
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9288 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9290 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9292 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#9287 Reduce surface area of write lock in concurrency report.
  pkg/activator/handler/concurrency_reporter.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9291 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#9293 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9280 Bump golangci-lint action version and make it apply to the entire codebase.
  .github/workflows/knative-lint.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9286 Make secret accessor test consistent.
  pkg/reconciler/accessor/core/secret_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#9289 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#9295 Fix some nits in the resolve test
  pkg/reconciler/revision/resolve_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9013 Use networking.knative.dev/visibility instead of serving.knative.dev/visibility
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/configuration_validation_test.go
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
  pkg/apis/serving/v1/service_validation.go
  pkg/apis/serving/v1/service_validation_test.go
  pkg/apis/serving/v1beta1/configuration_validation.go
  pkg/apis/serving/v1beta1/configuration_validation_test.go
  pkg/apis/serving/v1beta1/route_validation.go
  pkg/apis/serving/v1beta1/route_validation_test.go
  pkg/apis/serving/v1beta1/service_validation.go
  pkg/apis/serving/v1beta1/service_validation_test.go
  pkg/reconciler/route/config/domain.go
  pkg/reconciler/route/domains/domains.go
  pkg/reconciler/route/domains/domains_test.go
  pkg/reconciler/route/resources/filters.go
  pkg/reconciler/route/resources/filters_test.go
  pkg/reconciler/route/resources/labels/labels.go
  pkg/reconciler/route/resources/labels/labels_test.go
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/visibility/visibility_test.go
  test/e2e/route_service_test.go
  test/e2e/service_to_service_test.go
  test/e2e/subroutes_test.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#9299 Update the throttler code a bit:
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9297 Close existing WS connection when Lease change
  pkg/autoscaler/statforwarder/forwarder.go
  pkg/autoscaler/statforwarder/forwarder_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#9302 Use SchemeGroupVersion.WithResource rather than manual ctor
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/gc/v1/gc_test.go
  pkg/reconciler/gc/v2/gc_test.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9298 Refactor the gRPC e2e test
  test/e2e/grpc_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9260 Add warnings to features that cannot safely be disabled again.
  config/core/configmaps/features.yaml
Labels: approved, cla: yes, lgtm, size/M

#9304 Use context in helpers to save some boilerplate and improve logging
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
  test/e2e/grpc_test.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9305 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9307 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9308 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#9309 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/websocket/connection.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9313 Use const value for the value of KubeletProbeHeaderName
  cmd/queue/main.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/S

#9314 Add 'kind.local' to registries skipping tag resolution.
  DEVELOPMENT.md
  config/core/configmaps/deployment.yaml
  pkg/deployment/config.go
  pkg/deployment/config_test.go
Labels: approved, cla: yes, lgtm, size/S

#9321 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9322 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9324 Fix the build after update
  go.mod
  go.sum
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/modules.txt
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9325 Fix intermittent 404 in TestServiceWithTrafficSplit
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9171 Create separate store for configuration and labeler
  pkg/reconciler/configuration/config/doc.go
  pkg/reconciler/configuration/config/store.go
  pkg/reconciler/configuration/config/store_test.go
  pkg/reconciler/configuration/config/testdata/config-defaults.yaml
  pkg/reconciler/configuration/config/testdata/config-features.yaml
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/controller.go
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/labelerv2_test.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/L

#9328 Remove occurrences of 'whitelist' and 'master'.
  pkg/resources/pods_test.go
  test/e2e/autotls/config/disablenscert/main.go
  test/e2e/probe_whitelist_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/S

#9331 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#9300 Update Istio deployment commands
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#9332 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#9333 Move golangci config into configfile to be used by IDEs etc.
  .github/workflows/knative-lint.yaml
  .golangci.yaml
Labels: approved, cla: yes, lgtm, size/S

#9306 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9330 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9335 Move responsive-gc feature to allowed
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/service/resources/configuration.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#9338 Use envconfig to parse all env vars in activator
  cmd/activator/main.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#9342 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9341 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9339 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9340 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9344 Refactor activator/autoscaler main to reuse helpers.
  cmd/activator/main.go
  cmd/autoscaler/main.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#9343 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9281 Close the WS connection if the Server is not the owner of a bucket
  cmd/autoscaler/main.go
  pkg/autoscaler/bucket/bucket.go
  pkg/autoscaler/bucket/bucket_test.go
  pkg/autoscaler/bucket/doc.go
  pkg/autoscaler/statserver/server.go
  pkg/autoscaler/statserver/server_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#9346 Drop remaining copied master flag to server replacement.
  cmd/default-domain/main.go
Labels: approved, cla: yes, lgtm, size/XS

#9348 Update test-infra and fix the breaking change
  go.mod
  go.sum
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9349 Retry WaitFor and Check Get calls.
  go.mod
  go.sum
  test/v1/configuration.go
  test/v1/route.go
  test/v1/service.go
  test/v1alpha1/configuration.go
  test/v1alpha1/route.go
  test/v1alpha1/service.go
  test/v1beta1/configuration.go
  test/v1beta1/route.go
  test/v1beta1/service.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/test/ghutil/pullrequest.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9336 Refactor StatForwarder
  pkg/autoscaler/statforwarder/forwarder.go
  pkg/autoscaler/statforwarder/forwarder_test.go
  pkg/autoscaler/statforwarder/processor.go
  pkg/autoscaler/statforwarder/processor_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#9351 Retry mutations as well
  test/v1/configuration.go
  test/v1/route.go
  test/v1/service.go
  test/v1alpha1/configuration.go
  test/v1alpha1/route.go
  test/v1alpha1/service.go
  test/v1beta1/configuration.go
  test/v1beta1/route.go
  test/v1beta1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9347 Finish the test refactor to use the constant keys from pkg
  cmd/activator/request_log_test.go
  pkg/metrics/config_test.go
  test/e2e/logging_test.go
Labels: approved, area/autoscale, area/monitoring, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#9353 Print indexes of invalid responses in conformance tests
  test/conformance/api/shared/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9352 Remove stray occurrence of whitelist.
  test/performance/dev.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9356 Drop a few unused exported constants.
  pkg/apis/autoscaling/register.go
  pkg/metrics/key.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/testing/v1/listers.go
  pkg/testing/functional.go
  test/crd.go
  test/e2e_constants.go
Labels: approved, area/API, area/autoscale, area/monitoring, area/test-and-release, cla: yes, lgtm, size/M

#9329 Unpluralize ContainerStatuses type
  pkg/apis/serving/v1/revision_types.go
  pkg/apis/serving/v1/zz_generated.deepcopy.go
  pkg/apis/serving/v1alpha1/revision_conversion.go
  pkg/apis/serving/v1alpha1/revision_conversion_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/imagecache_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#9359 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9361 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9362 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9363 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9360 [master] Fix spelling errors
  pkg/autoscaler/statserver/server.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#9364 Fix usage of ErrInvalidKeyName for window validation.
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#9365 Pass low resource requirements to minScale test.
  test/e2e/minscale_readiness_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9366 Rename probing test to make its intent clearer.
  test/e2e/activator_probe_permitted_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9370 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9371 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9369 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9385 Try raising the scale test to 200
  test/e2e-tests.sh
  test/scale/scale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9294 Not run SetDefaults when updating revision
  pkg/apis/serving/v1/revision_defaults.go
  pkg/apis/serving/v1/revision_defaults_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9386 Since perf tests never have been run automatically
  go.mod
  go.sum
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
  test/performance/performance.go
  test/performance/scale_test.go
  vendor/knative.dev/pkg/test/junit/junit.go
  vendor/knative.dev/pkg/test/performance/performance.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#9389 Change the way worker timeout is handled.
  test/e2e/scale.go
  test/scale/scale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9390 Revert "Set imagePullPolicy to always (#4486)"
  test/conformance/runtime/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9391 Explicitly use imagePullPolicy: IfNotPresent
  test/v1/configuration.go
  test/v1alpha1/configuration.go
  test/v1beta1/configuration.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9368 Reenable graceful activator HA test.
  test/ha/activator_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9374 Swap support time tcnghia <-> julz.
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#9394 Remove unnecessary occurrences of divisive language.
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/reconciler/revision/resources/pa.go
  pkg/webhook/podspec_dryrun.go
  test/e2e/autoscale.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/S

#9396 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9398 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9399 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9401 Remove downstream usage of spoof.Interface
  test/conformance/api/shared/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9402 Throttle CheckDistribution in conformance.
  test/conformance/api/shared/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9403 Import changes to make spoof support NodePort services.
  go.mod
  go.sum
  test/e2e/autoscale.go
  test/e2e/grpc_test.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9392 Do not require digest resolution for side-loaded images.
  pkg/deployment/config_test.go
  test/conformance/api/shared/util.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9395 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9408 Make function checking nonblocking in metric test.
  pkg/reconciler/metric/metric_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9410 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9412 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9413 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#9406 Do not send request to cluster local domain with ResolvableDomain
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9418 Give the test more time to complete.
  pkg/reconciler/serverlessservice/global_resync_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9414 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9411 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9419 Add new ConfigMap field for max-max-scale
  pkg/autoscaler/config/config.go
  pkg/autoscaler/config/config_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#9421 Remove Stackdriver ServiceEntry.
  config/monitoring/metrics/stackdriver/100-stackdriver-serviceentry.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, size/M

#9264 Add support for serviceAccountToken in projected volumes
  go.mod
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  test/conformance/api/v1/volumes_test.go
  test/test_images/hellovolume/service.yaml
  vendor/modules.txt
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#9427 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9354 Resolve image digests in the background
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/reconciler/revision/background.go
  pkg/reconciler/revision/background_test.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XL

#9430 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9417 fill out remaining 2020 schedule
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/S

#9425 Remove unnecessary 'WithContext' and align parallelism with networking.
  test/conformance/api/shared/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9433 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9429 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9439 Call Done after resolving digest
  pkg/reconciler/revision/background.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9437 Try to restrict a bit the limits and requests we have for AS tests
  test/e2e/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9441 Increase the cluster size for auto-tls and upgrade test legs
  test/e2e-auto-tls-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9435 Attempt at fixing the race in the statforwarded UT
  pkg/autoscaler/statforwarder/forwarder.go
  pkg/autoscaler/statforwarder/forwarder_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#9443 Separate the initscale zero test
  test/e2e-tests.sh
  test/e2e/e2e.go
  test/e2e/initial_scale_test.go
  test/e2e/initscale/initial_scale_zero_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9440 Remove duplicate function from autotls tests
  go.mod
  go.sum
  test/e2e/autotls/auto_tls_test.go
  test/e2e/autotls/util.go
  test/e2e_flags.go
  vendor/knative.dev/networking/test/cleanup.go
  vendor/knative.dev/networking/test/clients.go
  vendor/knative.dev/networking/test/conformance.go
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/hosts.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/rewrite.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/crd.go
  vendor/knative.dev/networking/test/defaultsystem/system.go
  vendor/knative.dev/networking/test/e2e-common.sh
  vendor/knative.dev/networking/test/e2e-tests.sh
  vendor/knative.dev/networking/test/e2e_constants.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/knative.dev/networking/test/ingress.go
  vendor/knative.dev/networking/test/presubmit-tests.sh
  vendor/knative.dev/networking/test/prober.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/proto/ping.pb.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/proto/ping.proto
  vendor/knative.dev/networking/test/types/runtime.go
  vendor/knative.dev/networking/test/upload-test-images.sh
  vendor/knative.dev/networking/test/util.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#9447 Fix performance test setup by installing the missing networking-istio
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9449 Make sure to Clear after errors in digest resolution
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#9426 Rename MaxMaxScale with MaxScaleLimit
  pkg/autoscaler/config/config.go
  pkg/autoscaler/config/config_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#9455 Add configurable timeout for digest resolution
  config/core/configmaps/deployment.yaml
  pkg/deployment/config.go
  pkg/deployment/config_test.go
  pkg/reconciler/revision/revision.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9428 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9456 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9458 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9459 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#9460 Drop pointless imagePaths array
  test/conformance/api/v1/blue_green_test.go
  test/conformance/api/v1alpha1/blue_green_test.go
  test/conformance/api/v1beta1/blue_green_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9462 Remove now duplicated action.
  .github/workflows/knative-lint.yaml
Labels: approved, cla: yes, lgtm, size/M

#9358 Validate autoscaling annotations on Services and Configs.
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/configuration_validation_test.go
  pkg/apis/serving/v1/service_validation.go
  pkg/apis/serving/v1/service_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L
