Repository knative/serving, pull requests merged in 2020-10, with the labels that each got.

#9640 swap weeks with vagababov
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#9641 Satisfy the proper go naming
  test/e2e/autotls/README.md
  test/e2e/autotls/auto_tls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9643 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#9644 Remove unnecessary helper function
  pkg/reconciler/route/visibility/visibility_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#9645 Remove unnecessary usages of the 'log' package
  pkg/reconciler/route/traffic/traffic_test.go
  pkg/reconciler/route/visibility/visibility_test.go
  test/ha/activator_test.go
  test/upgrade/probe_test.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/S

#9648 [Automated] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/L

#9649 [Automated] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#9623 Wait for route terminal conditions to clear annotations
  pkg/reconciler/labeler/labelerv1_test.go
  pkg/reconciler/labeler/labelerv2_test.go
  pkg/reconciler/labeler/v1/labels.go
  pkg/reconciler/labeler/v2/metasync.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9650 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/L

#9651 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#9652 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#9654 Remove panic and other nits
  pkg/reconciler/route/traffic/traffic_test.go
  pkg/reconciler/route/visibility/visibility_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9471 Enable Istio in Kind GitHub Action.
  .github/workflows/kind-e2e.yaml
  test/e2e-networking-library.sh
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9655 Cleanup mako configs a bit
  test/performance/benchmarks/dataplane-probe/dev.config
  test/performance/benchmarks/deployment-probe/dev.config
  test/performance/benchmarks/load-test/dev.config
  test/performance/benchmarks/rollout-probe/dev.config
  test/performance/benchmarks/rollout-probe/prod.config
  test/performance/benchmarks/scale-from-zero/dev.config
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9656 Replace deprecated Policy by PeerAuthentication.
  test/config/security/peerauthentication.yaml
  test/config/security/policy.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9657 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9659 Remove manual lint comment from PR template
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/XS

#9662 Use the correct set implementation in labeler accessors
  pkg/reconciler/labeler/v2/accessors.go
  third_party/VENDOR-LICENSE/k8s.io/kube-openapi/pkg/util/proto/LICENSE
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9666 Fix a couple copy pasta doc errors
  pkg/gc/doc.go
  pkg/reconciler/gc/config/doc.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9663 Update K8s deps script and remove unnecessary dependency
  go.mod
  go.sum
  hack/update-k8s-deps.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9496 Validate MaxScale against max-scale-limit
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/v1/revision_validation.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#9669 [Automated] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9670 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9577 Update autoscaler CM example block for max-scale-limit
  config/core/configmaps/autoscaler.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9661 Give Webhook time to have a leader elected and reconcile the TLS certificate.
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#9667 [Automated] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9668 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9674 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#9472 Support forwarding metrics via SVC when there's mesh
  pkg/autoscaler/statforwarder/forwarder.go
  pkg/autoscaler/statforwarder/forwarder_test.go
  pkg/autoscaler/statforwarder/processor.go
  pkg/autoscaler/statforwarder/processor_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#9678 Just use config.Config...
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9681 Set the default in the deploy.go and propagate config to build pod spec
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/webhook/podspec_dryrun.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#9680 Creates new e2e to validate http2 behavior and help developing http2/gRPC autodetection
  test/conformance.go
  test/e2e/http2_test.go
  test/test_images/hellohttp2/README.md
  test/test_images/hellohttp2/hellohttp2.go
  test/test_images/hellohttp2/service.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9684 Fix the defaulting of the tristate flag
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#9686 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#9687 Add RetryingRouteInconsistency to TestHelloHttp2WithEmptyPortName
  test/e2e/http2_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9688 Some more minor cleanups of formatting
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/queue/handler_test.go
  pkg/queue/readiness/probe_test.go
  pkg/reconciler/gc/v1/gc_test.go
  pkg/reconciler/gc/v2/gc_test.go
  pkg/resources/endpoints_test.go
  test/conformance/api/v1/resources_test.go
  test/e2e/destroypod_test.go
  test/performance/benchmarks/deployment-probe/continuous/main.go
  test/performance/benchmarks/rollout-probe/continuous/main.go
  test/performance/benchmarks/scale-from-zero/continuous/main.go
  test/performance/performance.go
  test/scale/scale_test.go
  test/test_images/grpc-ping/main.go
  test/test_images/hellovolume/hellovolume.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#9694 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9697 Make forceUpgrade annotation handling consistent with others
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/register.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9696 Bump timeouts to avoid flakes
  pkg/autoscaler/statforwarder/forwarder_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#9693 Cleanup certificate unit test
  pkg/reconciler/accessor/networking/certificate_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9685 Disable service links by default in knative services.
  config/core/configmaps/defaults.yaml
  pkg/apis/config/defaults.go
  pkg/apis/serving/v1/configuration_defaults_test.go
  pkg/apis/serving/v1/revision_defaults.go
  pkg/apis/serving/v1/revision_defaults_test.go
  pkg/apis/serving/v1/service_defaults_test.go
  pkg/reconciler/revision/resources/deploy_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9698 Add logging to aid with debugging
  pkg/reconciler/autoscaling/kpa/scaler.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#9689 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9690 [Automated] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9700 Move more tests to pkg/queue and separate files from main.go
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/queue/health/handler.go
  pkg/queue/health/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#9701 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9675 clean up composition of revisions config store
  pkg/apis/config/store.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/reconciler/revision/config/observability.go
  pkg/reconciler/revision/config/store.go
  pkg/reconciler/revision/config/store_test.go
  pkg/reconciler/revision/config/testdata/config-features.yaml
  pkg/reconciler/revision/config/zz_generated.deepcopy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9706 Drop unnecessary wrapper functions
  cmd/webhook/main.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9707 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/helpers/dryrun.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/mako/config/environment.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/main.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9691 [Automated] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9692 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/M

#9664 Link feature flag docs from configmap
  config/core/configmaps/features.yaml
Labels: approved, cla: yes, lgtm, size/S

#9703 Also log reachability state in the scaler
  pkg/reconciler/autoscaling/kpa/scaler.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#9705 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9259 Add autoscaling Sustaining e2e tests for upgrade/downgrade
  test/e2e-upgrade-tests.sh
  test/e2e/autoscale.go
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
  test/e2e/grpc_test.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
  test/upgrade/autoscaler_test.go
  test/upgrade/probe_test.go
  test/upgrade/upgrade.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9682 Enable leader election for autoscaler
  cmd/autoscaler/main.go
  config/core/deployments/autoscaler.yaml
  pkg/autoscaler/bucket/bucket.go
  pkg/autoscaler/bucket/bucket_test.go
  test/e2e-common.sh
Labels: approved, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#9708 Http -> HTTP since the test helper is fixed not to generate long names
  test/e2e/http2_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9709 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/binding_types.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#9723 add codecov badge
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#9719 Reconcile Ingress when label was different from desired
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#9716 [Automated] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9718 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9712 Refactor autoscaling test helpers
  test/e2e/autoscale.go
  test/e2e/autoscale_test.go
  test/e2e/grpc_test.go
  test/upgrade/autoscaler_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9717 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9726 move all fuzz stuff to _test files
  pkg/apis/serving/v1/fuzzer.go
  pkg/apis/serving/v1/roundtrip_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9724 Remove strange cluster-local label from unit test
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#9729 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/mako/analyzer.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#9728 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#9732 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9734 [Automated] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9739 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9735 Reconcile DomainMappings to Ingress
  cmd/domain-mapping/main.go
  config/domain-mapping/controller.yaml
  pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  pkg/apis/serving/v1alpha1/domainmapping_types.go
  pkg/reconciler/domainmapping/controller.go
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/resources/ingress.go
  pkg/reconciler/domainmapping/resources/ingress_test.go
  pkg/reconciler/domainmapping/table_test.go
  pkg/reconciler/testing/v1/listers.go
Labels: approved, area/API, cla: yes, lgtm, size/XL

#9733 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#9745 Support non-default cluster domains in DomainMapping
  pkg/reconciler/domainmapping/resources/ingress.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9746 Merge equal targets together
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9749 Use no ::set-env
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#9744 Make docs about cluster local domains more accurate
  config/core/configmaps/domain.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9751 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#9704 [Automated] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9753 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9754 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9755 [Automated] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9757 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9758 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#9743 Populate the bucket ownership from StatForwarder to StatServer
  cmd/autoscaler/main.go
  pkg/autoscaler/statforwarder/forwarder.go
  pkg/autoscaler/statforwarder/forwarder_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#9759 Add negative test for config clumping with different tags
  pkg/reconciler/route/traffic/traffic_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9771 Remove hard-coded occurences of .svc.cluster.local in pkg dir
  pkg/activator/handler/testdata/config-tracing.yaml
  pkg/reconciler/domainmapping/resources/ingress_test.go
  pkg/reconciler/revision/config/testdata/config-tracing.yaml
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/route/domains/domains_test.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/resources/names/names_test.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/visibility/visibility_test.go
  pkg/testing/v1/route.go
  pkg/testing/v1/service.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#9772 Use pkg/network.GetServiceHostname instead of GetClusterDomain
  pkg/reconciler/route/resources/ingress_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#9777 Raise the timeout to 3 minutes.
  test/e2e/minscale_readiness_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9741 Update cert-manager to 1.0.0 version
  test/e2e-common.sh
  third_party/cert-manager-0.12.0/cert-manager-crds.yaml
  third_party/cert-manager-0.12.0/cert-manager.yaml
  third_party/cert-manager-0.12.0/owner-ref.patch
  third_party/cert-manager-latest/cert-manager.yaml
  third_party/cert-manager-latest/download-cert-manager.sh
  third_party/cert-manager-latest/net-certmanager.yaml
  third_party/cert-manager-latest/owner-ref.patch
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#9779 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/knative.dev/networking/test/prober.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#9783 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9784 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9785 Adhere to recommended docs
  pkg/activator/net/lb_policy.go
  pkg/queue/health/probe.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#9786 Increase the number of replicas for Istio deployments in performance testing
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9767 This is the first iteration of the API for the progressive rollout
  pkg/reconciler/route/traffic/rollout.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9752 Propagate Ingress status to DomainMapping
  pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  pkg/apis/serving/v1alpha1/domainmapping_lifecycle_test.go
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/resources/ingress_test.go
  pkg/reconciler/domainmapping/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9782 [Automated] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9747 Change autoscale lease holder identify from <IP> to <POD-NAME>_<IP>
  cmd/autoscaler/main.go
  pkg/autoscaler/bucket/bucket.go
  pkg/autoscaler/bucket/bucket_test.go
  pkg/autoscaler/statforwarder/forwarder.go
  pkg/autoscaler/statforwarder/forwarder_test.go
  pkg/autoscaler/statforwarder/processor.go
  test/config/chaosduck.yaml
Labels: approved, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#9788 Use the new helper from pkg for mem stats
  cmd/activator/main.go
  cmd/autoscaler/main.go
  cmd/queue/main.go
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#9789 Optimize code: pass by pointer
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/service_validation.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#9774 Use a local Docker registry
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#9768 fix some deprecated methods
  cmd/activator/main.go
  cmd/autoscaler/main.go
  test/e2e/autotls/config/disablenscert/main.go
  test/performance/benchmarks/scale-from-zero/continuous/main.go
Labels: approved, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#9793 Re-introduce maxprocs (but quieter) for queue proxy
  cmd/queue/main.go
  go.mod
  vendor/modules.txt
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#9794 Fix nil-pointer on accessing condition in autoscaler
  pkg/reconciler/autoscaling/kpa/kpa.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#9797 Add bash v4 to requirements
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#9795 Remove no-op deepcopy
  pkg/autoscaler/config/doc.go
  pkg/autoscaler/config/zz_generated.deepcopy.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#9798 Move negation of resource available condition
  pkg/apis/serving/v1/revision_lifecycle.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9730 [RELEASE-0.17] Reconcile Ingress when label was different from desired (#9719)
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#9731 [RELEASE-0.18] Reconcile Ingress when label was different from desired (#9719)
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#9802 Remove no-op deepcopy in gc/config
  pkg/reconciler/gc/config/doc.go
  pkg/reconciler/gc/config/store.go
  pkg/reconciler/gc/config/zz_generated.deepcopy.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9796 Introduce DomainMapping ConfigStore and allow configuring IngressClass
  pkg/reconciler/domainmapping/config/doc.go
  pkg/reconciler/domainmapping/config/store.go
  pkg/reconciler/domainmapping/config/store_test.go
  pkg/reconciler/domainmapping/config/testdata/config-network.yaml
  pkg/reconciler/domainmapping/controller.go
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9803 [Automated] Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#9740 Name revisions consistently to avoid creating the same revision twice
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#9799 [Automated] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9800 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#9683 add /var/log volume mount only when EnableVarLogCollection is true
  docs/runtime-contract.md
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  test/types/runtime.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#9710 Move responsive gc to enabled by default
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/reconciler/service/resources/configuration.go
  pkg/reconciler/service/resources/configuration_test.go
  pkg/reconciler/service/service_test.go
  test/conformance/api/v1/util.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/S

#9806 Fix one more theoretical NPE
  pkg/reconciler/configuration/configuration.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9808 Some MakeIngress cleanups
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#9809 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#9812 Skip logging check if request logs are disabled
  test/e2e/logging_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#9810 Remove createWithOptions shim for dry-run functionality
  pkg/webhook/create_options.go
  pkg/webhook/create_options_test.go
  pkg/webhook/podspec_dryrun.go
  pkg/webhook/podspec_dryrun_test.go
  pkg/webhook/validate_unstructured_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#9811 Reenable generation check in postupgrade tests
  test/upgrade/service_postupgrade_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9813 [Automated] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9816 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9818 Update to k8s.Interface, new test/KubeClient from pkg.
  cmd/default-domain/main.go
  go.mod
  go.sum
  test/adding_tests.md
  test/clients.go
  test/conformance/api/v1/volumes_test.go
  test/e2e/autoscale.go
  test/e2e/autoscale_test.go
  test/e2e/autotls/config/disablenscert/main.go
  test/e2e/destroypod_test.go
  test/e2e/e2e.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/initial_scale_test.go
  test/e2e/logging_test.go
  test/e2e/minscale_readiness_test.go
  test/e2e/namespace_test.go
  test/e2e/service_to_service_test.go
  test/e2e/subroutes_test.go
  test/e2e/websocket.go
  test/ha/activator_test.go
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
  test/ha/ha.go
  test/performance/benchmarks/scale-from-zero/continuous/main.go
  test/util.go
  vendor/knative.dev/networking/test/clients.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/util.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9819 Fix the nit and the update
  go.mod
  go.sum
  pkg/metrics/config_test.go
  test/e2e/logging_test.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, area/monitoring, area/test-and-release, cla: yes, lgtm, size/S

#9820 Remove the test that no longer makes sense
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9807 drop the monitoring bundle and it's references
  DEVELOPMENT.md
  config/README.md
  config/core/configmaps/observability.yaml
  config/monitoring/100-namespace.yaml
  config/monitoring/OWNERS
  config/monitoring/README.md
  config/monitoring/logging/elasticsearch/100-fluentd-configmap.yaml
  config/monitoring/logging/elasticsearch/200-fluentd.yaml
  config/monitoring/logging/stackdriver/100-fluentd-configmap.yaml
  config/monitoring/logging/stackdriver/200-fluentd.yaml
  config/monitoring/metrics/prometheus/100-grafana-custom-config.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-efficiency.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-reconciler.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative.yaml
  config/monitoring/metrics/prometheus/100-grafana.yaml
  config/monitoring/metrics/prometheus/100-prometheus-scrape-config.yaml
  config/monitoring/metrics/prometheus/200-kube-controller-metrics.yaml
  config/monitoring/metrics/prometheus/300-prometheus.yaml
  config/monitoring/tracing/jaeger/105-zipkin-service.yaml
  config/monitoring/tracing/jaeger/elasticsearch/100-jaeger.yaml
  config/monitoring/tracing/jaeger/memory/100-jaeger.yaml
  config/monitoring/tracing/zipkin-in-mem/100-zipkin.yaml
  config/monitoring/tracing/zipkin/100-zipkin.yaml
  hack/generate-yamls.sh
  pkg/metrics/config_test.go
  pkg/reconciler/revision/config/store_test.go
  pkg/reconciler/revision/revision.go
  test/e2e-common.sh
  third_party/config/monitoring/OWNERS
  third_party/config/monitoring/logging/elasticsearch/LICENSE
  third_party/config/monitoring/logging/elasticsearch/elasticsearch.yaml
  third_party/config/monitoring/logging/elasticsearch/kibana.yaml
  third_party/config/monitoring/metrics/prometheus/kubernetes/LICENSE
  third_party/config/monitoring/metrics/prometheus/kubernetes/kube-state-metrics.yaml
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/LICENSE
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/NOTICE
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/deployment-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/kubernetes-capacity-planning-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/kubernetes-cluster-health-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/kubernetes-cluster-status-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/kubernetes-control-plane-status-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/kubernetes-resource-requests-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/nodes-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/pods-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/statefulset-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/node-exporter.yaml
Labels: approved, area/API, area/monitoring, area/test-and-release, cla: yes, lgtm, size/XXL

#9823 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9822 Use the well known constants/funcs rather than bespoke strings
  pkg/activator/handler/handler_test.go
  pkg/logging/config_test.go
Labels: approved, area/autoscale, area/monitoring, area/networking, cla: yes, lgtm, size/S

#9790 Add Autoscaler HA test
  test/e2e/autoscale.go
  test/ha/autoscaler_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#9826 Replace non-standard context import with correct import
  pkg/reconciler/revision/resolve_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#9833 Use placeholder.go for placeholder files
  config/core/200-roles/placeholder.go
  config/core/300-resources/placeholder.go
  config/core/configmaps/placeholder.go
  config/core/deployments/placeholder.go
  config/core/placeholder.go
  config/core/webhooks/placeholder.go
  config/hpa-autoscaling/placeholder.go
  config/namespace-wildcard-certs/placeholder.go
  config/post-install/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS

#9827 Remove explicit dependency on UUID
  go.mod
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/route/route_test.go
  vendor/modules.txt
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#9830 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9805 Minor grammar fixes for development file
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#9828 Simplify test server creation through pkg helpers
  go.mod
  test/util.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9829 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#9821 Initial version of the rollout logic — capture existing state
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/traffic/rollout.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XL

#9831 [Automated] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#9838 Remove registry bits from matrix
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/M

#9840 Print response error for debugging
  test/e2e/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#9387 Add conformance test for multi container feature
  test/conformance/api/v1/service_test.go
  test/conformance/api/v1/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9841 Support `nil` target for merging
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#9837 Run v1alpha1 tests (and deploy DomainMapping component) in github actions
  .github/workflows/kind-e2e.yaml
  test/conformance/api/v1alpha1/placeholder.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#9843 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/e2e_constants.go
  vendor/knative.dev/networking/test/types/runtime.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#9848 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9846 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S
