Repository knative/serving, pull requests merged in 2020-02, with the labels that each got.

#6701 Step 1 in refactoring the stats reporter
  Gopkg.lock
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/autoscaler/stats_reporter.go
  pkg/autoscaler/stats_reporter_test.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/record.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#6710 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/.gitignore
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
Labels: approved, cla: yes, lgtm, size/L

#6552 Use DownwardAPI to populate pod label into Queue-Proxy
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/apis/autoscaling/register.go
  pkg/reconciler/revision/config/store.go
  pkg/reconciler/revision/config/store_test.go
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6709 Use a real reporter in handler benchmark to surface allocations.
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#6695 Consider NotReadyAddresses for routing in the activator.
  pkg/activator/net/helpers.go
  pkg/activator/net/helpers_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6707 Gate readiness probes
  pkg/queue/readiness/probe.go
  pkg/queue/readiness/probe_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#6708 Remove 'initialized' from all reporters and prove initialization statically.
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
  pkg/autoscaler/stats_reporter.go
  pkg/autoscaler/stats_reporter_test.go
  pkg/queue/stats/stats_reporter.go
  pkg/queue/stats/stats_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6699 Delete activator hpa and disable activator deployment in performance test setup
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6713 Run AutoTLS E2E tests last
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6718 Normalize selector building to SelectorFromSet.
  pkg/activator/net/revision_backends.go
  pkg/reconciler/autoscaling/reconciler.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/gc/gc.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/serverlessservice/serverlessservice.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6712 Split the metrics reporter in two parts.
  Gopkg.lock
  pkg/autoscaler/stats_reporter.go
  pkg/autoscaler/stats_reporter_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/stats_reporter.go
  third_party/VENDOR-LICENSE
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/main.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/internal/types.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/internal/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/testing/factory.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XXL

#6566 Conversion Webhook Support
  Gopkg.lock
  cmd/webhook/main.go
  config/core/resources/configuration.yaml
  config/core/resources/revision.yaml
  config/core/resources/route.yaml
  config/core/resources/service.yaml
  pkg/apis/serving/register.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XXL

#6725 Fix go1.14 issue
  test/e2e/subroutes_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6722 golang format tools
  pkg/reconciler/revision/resources/deploy.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#6720 Remove arbitrary Try timeout in the activator.
  pkg/activator/handler/handler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#6719 Preallocate tags and reuse them throughout a request.
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6706 stop waiting for cert to be ready when cert is failed
  test/e2e/autotls/auto_tls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6728 Fix typo 'configureation' -> 'configuration'.
  pkg/reconciler/ingress/resources/gateway.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#6606 Add e2e to validate the graceful scaledown behavior
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
  test/e2e/websocket.go
  test/e2e/websocket_test.go
  test/test_images/wsserver-hostname/README.md
  test/test_images/wsserver-hostname/main.go
  test/test_images/wsserver-hostname/service.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6732 Refactor traffic target visibility logic into its own pkg
  pkg/reconciler/route/domains/domains.go
  pkg/reconciler/route/domains/domains_test.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
  pkg/reconciler/route/visibility/doc.go
  pkg/reconciler/route/visibility/visibility.go
  pkg/reconciler/route/visibility/visibility_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XL

#6734 Store created metrics contexts in a LRU cache.
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/stats_reporter.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#6741 Separate visibility of cluster local and public domain
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6742 Allow revision watcher to probe multiple times before failing.
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#6737 golang format tools
  test/e2e/autoscale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6745 Fix the load test scale to 0 logic
  test/performance/benchmarks/load-test/continuous/load-test.yaml
  test/performance/benchmarks/load-test/continuous/main.go
  test/performance/performance.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6746 Add one more logging field
  pkg/autoscaler/autoscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#5927 Use cluster admin role for perf tests
  test/performance/benchmarks/dataplane-probe/continuous/dataplane-probe.yaml
  test/performance/benchmarks/deployment-probe/continuous/benchmark.yaml
  test/performance/benchmarks/load-test/continuous/load-test.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6613 Modify AutoscalingQueueMetricsPortName as per istio naming convention
  pkg/apis/serving/v1alpha1/revision_lifecycle.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/XS

#6735 Remove 'num_tries' tag from activator metrics.
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
  pkg/metrics/key.go
Labels: approved, area/autoscale, area/monitoring, area/networking, cla: yes, lgtm, size/S

#6755 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeclient.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeduck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/namesystems.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XXL

#6711 Update pull-request-template.md
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/XS

#6748 Add a benchmark for the metric handler in the activator.
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6759 Fix indentation of activator-hpa yaml
  config/core/deployments/activator-hpa.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#6764 Vary the name of the private service.
  test/conformance/ingress/visibility_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6744 Create VS name with `-ingress` suffix
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/names/names.go
  pkg/reconciler/ingress/resources/names/names_test.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#6758 Use nightly Contour build from knative.dev/net-contour
  test/e2e-common.sh
  third_party/contour-latest/README.md
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#6762 Fix the error message in the test
  test/e2e/websocket_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6751 Consolidate reporter calls into the metric handler.
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6768 Format markdown
  third_party/contour-latest/README.md
Labels: approved, cla: yes, lgtm, size/S

#6771 Revert the Activator daemon set, since it is not ready for its prime time
  config/activator-ds.yaml
  config/core/activator-ds.yaml
  config/core/deployments/activator-hpa.yaml
  config/core/deployments/activator.yaml
  test/e2e-common.sh
Labels: approved, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#6657 Use retries from knative/pkg and add UTs to reconcilers that use retries
  Gopkg.lock
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/reconciler.go
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/metric/metric.go
  pkg/reconciler/metric/metric_test.go
  pkg/reconciler/retry.go
  pkg/reconciler/retry_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6774 Finish the metric refactoring in autoscaling
  cmd/autoscaler/main.go
  pkg/autoscaler/metrics/stats_reporter_test.go
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
  pkg/autoscaler/scaling/stats_reporter.go
  pkg/autoscaler/scaling/stats_reporter_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#6756 make some switch statements more idiomatic
  pkg/apis/serving/v1alpha1/revision_lifecycle.go
  pkg/apis/serving/v1alpha1/route_lifecycle.go
  pkg/apis/serving/v1alpha1/service_lifecycle.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6769 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/caching/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#6779 Revert "Delete activator hpa and diable activator deployment (#6699)"
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6782 Minor cleanup in the AutoTLS e2e test
  test/e2e/autotls/auto_tls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6786 Deflake the metrics test in the autoscaler.
  pkg/autoscaler/scaling/multiscaler_test.go
  pkg/autoscaler/scaling/stats_reporter_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6468 Provide option to run e2e and conformance tests with HTTPS
  test/conformance/api/v1alpha1/blue_green_test.go
  test/conformance/api/v1alpha1/generatename_test.go
  test/conformance/api/v1alpha1/resources_test.go
  test/conformance/api/v1alpha1/service_test.go
  test/conformance/api/v1alpha1/single_threaded_test.go
  test/conformance/api/v1alpha1/volumes_test.go
  test/conformance/runtime/readiness_probe_test.go
  test/conformance/runtime/util.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e/activator_test.go
  test/e2e/autoscale_test.go
  test/e2e/destroypod_test.go
  test/e2e/egress_traffic_test.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/istio/probing_test.go
  test/e2e/namespace_test.go
  test/e2e/rollback_byo_test.go
  test/e2e/service_to_service_test.go
  test/e2e/subroutes_test.go
  test/e2e/websocket_test.go
  test/performance/latency_test.go
  test/performance/observed_concurency_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6794 golang format tools
  pkg/reconciler/service/service_test.go
  test/e2e/autotls/auto_tls_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/S

#6795 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#6663 Remove duplicate NS in yamls
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6797 Add benchmark for network probe handler
  pkg/network/probe_handler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6798 Remove Istio clients from base serving reconciler.
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/reconciler.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#6800 Move the SKS to use genreconciler.
  Gopkg.lock
  pkg/apis/networking/v1alpha1/serverlessservice_types.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/stub/reconciler.go
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6799 Move the context manipulation to util.
  pkg/activator/handler/context_handler.go
  pkg/activator/handler/context_handler_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
  pkg/activator/handler/requestevent_handler.go
  pkg/activator/handler/requestevent_handler_test.go
  pkg/activator/util/context.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6730 Select only the Pod CPU usage metrics
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, size/XS

#6802 Add benchmark for request metric handler
  pkg/activator/handler/handler.go
  pkg/network/probe_handler_test.go
  pkg/queue/request_metric_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6806 Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/stub/reconciler.go
  third_party/VENDOR-LICENSE
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#6809 Fix network probe benchmark
  pkg/network/probe_handler_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6805 golang format tools
  test/performance/observed_concurency_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#6770 Switch revision reconciler to use V1 APIs
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/env_var.go
  pkg/reconciler/revision/resources/imagecache.go
  pkg/reconciler/revision/resources/imagecache_test.go
  pkg/reconciler/revision/resources/meta.go
  pkg/reconciler/revision/resources/meta_test.go
  pkg/reconciler/revision/resources/names/names_test.go
  pkg/reconciler/revision/resources/pa.go
  pkg/reconciler/revision/resources/pa_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/serverlessservice/resources/services.go
  pkg/reconciler/serverlessservice/resources/services_test.go
  pkg/reconciler/testing/v1/factory.go
  pkg/reconciler/testing/v1/listers.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/XXL

#6813 Migrate the GC controller to genreconciler
  pkg/apis/serving/v1alpha1/configuration_types.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/stub/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/stub/reconciler.go
  pkg/reconciler/gc/controller.go
  pkg/reconciler/gc/gc.go
  pkg/reconciler/gc/gc_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6814 Add serving-approvers as approvers to pkg/metrics
  pkg/metrics/OWNERS
Labels: approved, area/monitoring, cla: yes, lgtm, size/XS

#6804 Move metric context constructors to a general place and enable caching everywhere.
  cmd/autoscaler/main.go
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
  pkg/autoscaler/scaling/metrics.go
  pkg/metrics/tags.go
  pkg/metrics/tags_test.go
  pkg/queue/stats/stats_reporter.go
  pkg/queue/stats/stats_reporter_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/metrics.go
Labels: approved, area/API, area/autoscale, area/monitoring, area/networking, cla: yes, lgtm, size/L

#6812 Migrate the metrics controller to genreconciler.
  pkg/apis/autoscaling/v1alpha1/metric_types.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/stub/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/stub/reconciler.go
  pkg/reconciler/metric/controller.go
  pkg/reconciler/metric/metric.go
  pkg/reconciler/metric/metric_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#6815 Remove the RevID from the param list
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#6644 Set the network prober User-Agent.
  pkg/network/network.go
  pkg/network/status/status.go
  pkg/reconciler/autoscaling/kpa/scaler.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, ok-to-test, size/S

#6820 Removing some unused and unreachable code, touching up idioms.
  cmd/queue/main_test.go
  pkg/reconciler/metric/metric.go
  pkg/reconciler/route/table_test.go
  test/conformance/ingress/timeout_test.go
  test/e2e/grpc_test.go
  test/performance/performance.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/S

#6821 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/test-infra/scripts/README.md
Labels: approved, cla: yes, lgtm, size/L

#6783 Verify ready replicas in e2e test TestMinScale
  test/e2e/minscale_readiness_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#6796 Add benchmark for queue proxy
  cmd/queue/main_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6818 v1alpha1.Revision constants now alias their v1 counterpart
  pkg/apis/serving/v1alpha1/revision_lifecycle.go
  pkg/apis/serving/v1alpha1/revision_types.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6823 Add AugmentWithResponse to our context factory and unify usages.
  pkg/activator/stats_reporter.go
  pkg/metrics/key.go
  pkg/metrics/tags.go
  pkg/metrics/tags_test.go
  pkg/queue/request_metric_test.go
  pkg/queue/stats/stats_reporter.go
  pkg/queue/stats/stats_reporter_test.go
Labels: approved, area/autoscale, area/monitoring, area/networking, cla: yes, lgtm, size/L

#6822 Move autoscaler config to subpackage
  cmd/webhook/main.go
  hack/update-codegen.sh
  pkg/autoscaler/config/config.go
  pkg/autoscaler/config/config_test.go
  pkg/autoscaler/config/doc.go
  pkg/autoscaler/config/testdata/config-autoscaler.yaml
  pkg/autoscaler/config/zz_generated.deepcopy.go
  pkg/reconciler/autoscaling/config/store.go
  pkg/reconciler/autoscaling/config/store_test.go
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/autoscaling/hpa/resources/hpa_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/resources/decider.go
  pkg/reconciler/autoscaling/kpa/resources/decider_test.go
  pkg/reconciler/autoscaling/resources/metric.go
  pkg/reconciler/autoscaling/resources/metric_test.go
  pkg/reconciler/autoscaling/resources/target.go
  pkg/reconciler/autoscaling/resources/target_test.go
  pkg/reconciler/revision/config/store.go
  pkg/reconciler/revision/config/store_test.go
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#6828 Migrate reconcilers to use configstore from generated reconcilers.
  Gopkg.lock
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/stub/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/stub/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/stub/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/stub/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/stub/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/stub/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/stub/reconciler.go
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/reconciler.go
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/gc/controller.go
  pkg/reconciler/gc/gc.go
  pkg/reconciler/gc/gc_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  third_party/VENDOR-LICENSE
  vendor/gomodules.xyz/jsonpatch/LICENSE
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/XXL

#6830 Fix the GR test flake
  pkg/reconciler/serverlessservice/global_resync_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6833 Attempt to deflake the KPA test
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/reconciler.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#6834 Migrate the Revision controller to genreconciler.
  pkg/apis/serving/v1/revision_types.go
  pkg/client/injection/reconciler/serving/v1/revision/controller.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/stub/controller.go
  pkg/client/injection/reconciler/serving/v1/revision/stub/reconciler.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#6835 Migrate the certificate reconciler to genreconciler.
  pkg/apis/networking/v1alpha1/certificate_types.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/stub/reconciler.go
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/controller.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6836 Drop primary-key listers.
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/reconciler.go
  pkg/reconciler/gc/controller.go
  pkg/reconciler/gc/gc.go
  pkg/reconciler/gc/gc_test.go
  pkg/reconciler/metric/controller.go
  pkg/reconciler/metric/metric.go
  pkg/reconciler/metric/metric_test.go
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#6838 Move BucketSize constant back in to autoscaler config
  pkg/autoscaler/config/config.go
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
  pkg/reconciler/autoscaling/resources/metric.go
  pkg/reconciler/autoscaling/resources/metric_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#6825 the revision controller's child informers now ignore resource version
  pkg/reconciler/revision/controller.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#6839 Silence error logs of probe errors.
  pkg/queue/readiness/probe.go
  pkg/queue/readiness/probe_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#6826 Configuration controller uses v1 API
  pkg/apis/serving/v1/configuration_lifecycle.go
  pkg/apis/serving/v1/configuration_lifecycle_test.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/controller.go
  pkg/reconciler/configuration/queueing_test.go
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/gc/gc_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
  pkg/testing/v1/configuration.go
  pkg/testing/v1alpha1/route.go
  pkg/testing/v1alpha1/service.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XL

#6843 Remove extra types and use batch metric recording in the activator.
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
  pkg/activator/handler/metrics.go
  pkg/activator/stats_reporter.go
  pkg/activator/stats_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XL

#6845 Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/shared/testgrid/yaml.go
Labels: approved, cla: yes, lgtm, size/M

#6844 golang format tools
  cmd/queue/main_test.go
  pkg/reconciler/route/route.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#6850 Fast forward pkg.
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/tracker/enqueue.go
Labels: approved, cla: yes, lgtm, size/M

#6849 Migrate Configuration controller to genreconciler.
  pkg/apis/serving/v1/configuration_types.go
  pkg/client/injection/reconciler/serving/v1/configuration/controller.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/stub/controller.go
  pkg/client/injection/reconciler/serving/v1/configuration/stub/reconciler.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/controller.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#6854 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
Labels: approved, cla: yes, lgtm, size/S

#6852 Clean up metric reporting in the queue proxy.
  cmd/queue/main.go
  pkg/queue/request_metric.go
  pkg/queue/request_metric_test.go
  pkg/queue/stats.go
  pkg/queue/stats/stats_reporter.go
  pkg/queue/stats/stats_reporter_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/XL

#6859 Return 504 on error and other sweeps
  cmd/queue/main.go
  pkg/queue/timeout.go
  pkg/queue/timeout_test.go
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1alpha1/revision_timeout_test.go
  test/conformance/api/v1beta1/revision_timeout_test.go
Labels: approved, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#6858 Improve the revision timeout test
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1alpha1/revision_timeout_test.go
  test/conformance/api/v1beta1/revision_timeout_test.go
  test/test_images/timeout/timeout.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6851 Upstream filter.go to pkg
  Gopkg.lock
  pkg/activator/net/revision_backends.go
  pkg/activator/net/throttler.go
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/certificate/controller.go
  pkg/reconciler/filter_test.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/nscert/controller.go
  pkg/reconciler/serverlessservice/controller.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6855 Route controller uses v1 APIs
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/apis/serving/v1/route_lifecycle_test.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/domains/domains.go
  pkg/reconciler/route/domains/domains_test.go
  pkg/reconciler/route/queueing_test.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/resources/certificate.go
  pkg/reconciler/route/resources/certificate_test.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/traffic/errors.go
  pkg/reconciler/route/traffic/errors_test.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
  pkg/reconciler/route/visibility/visibility.go
  pkg/reconciler/route/visibility/visibility_test.go
  pkg/testing/v1/configuration.go
  pkg/testing/v1/route.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/XXL

#6875 Fix racy behavior in collector tests.
  pkg/reconciler/metric/metric_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#6874 Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#6879 Fix the flake in global reconcile test.
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#6880 Don't specify IngressTLS prematurely.
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6867 Migrate Route to genreconciler
  pkg/apis/serving/v1/route_types.go
  pkg/client/injection/reconciler/serving/v1/route/controller.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/stub/controller.go
  pkg/client/injection/reconciler/serving/v1/route/stub/reconciler.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6881 Ridiculously small nits in the KPA tests
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#6882 Fix #6878: move the constants around
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/configuration_validation_test.go
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
  pkg/apis/serving/v1/service_validation.go
  pkg/apis/serving/v1/service_validation_test.go
  pkg/apis/serving/v1beta1/configuration_validation.go
  pkg/apis/serving/v1beta1/configuration_validation_test.go
  pkg/apis/serving/v1beta1/route_validation.go
  pkg/apis/serving/v1beta1/route_validation_test.go
  pkg/apis/serving/v1beta1/service_validation.go
  pkg/apis/serving/v1beta1/service_validation_test.go
  pkg/reconciler/route/config/domain.go
  pkg/reconciler/route/domains/domains.go
  pkg/reconciler/route/domains/domains_test.go
  pkg/reconciler/route/resources/filters.go
  pkg/reconciler/route/resources/filters_test.go
  pkg/reconciler/route/resources/labels/labels.go
  pkg/reconciler/route/resources/labels/labels_test.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/visibility/visibility_test.go
  test/e2e/service_to_service_test.go
  test/e2e/subroutes_test.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#6886 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
Labels: approved, cla: yes, lgtm, size/S

#6883 Fix timing issues in pool unit tests.
  pkg/pool/pool.go
  pkg/pool/pool_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6893 Fix some formatter issues in our code.
  cmd/queue/main_test.go
  pkg/activator/net/revision_backends_test.go
  pkg/apis/autoscaling/v1alpha1/metric_validation_test.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1alpha1/revision_validation_test.go
  pkg/apis/serving/v1beta1/revision_validation_test.go
  pkg/autoscaler/metrics/http_scrape_client_test.go
  pkg/autoscaler/metrics/stats_scraper_test.go
  pkg/queue/breaker_test.go
  pkg/queue/health/health_state_test.go
  pkg/queue/health/probe_test.go
  pkg/queue/readiness/probe_encoding_test.go
  pkg/reconciler/accessor/errors_test.go
  test/conformance/runtime/cgroup_test.go
  test/test_images/pizzaplanetv1/main.go
  test/test_images/pizzaplanetv2/main.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#6892 Add util for Auto TLS E2E tests
  Gopkg.lock
  test/e2e/autotls/config/disablenscert/main.go
  test/e2e/autotls/config/dnscleanup/main.go
  test/e2e/autotls/config/dnssetup/main.go
  test/e2e/autotls/config/util.go
  vendor/google.golang.org/api/dns/v1/dns-gen.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#6873 Make sure the ingress namespace is same with service
  pkg/apis/networking/v1alpha1/ingress_validation.go
  pkg/apis/networking/v1alpha1/ingress_validation_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, needs-ok-to-test, size/M

#6894 Fix the nits that I sent too late for review.
  test/e2e/autotls/config/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6640 Set defaults for reconciliation objects and update semantic equal comparison
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
  pkg/testing/v1alpha1/service.go
  test/upgrade/service_postupgrade_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#6888 Add pod and container tags back to the activator metrics.
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
  pkg/metrics/tags.go
  pkg/metrics/tags_test.go
  pkg/queue/request_metric.go
Labels: approved, area/autoscale, area/monitoring, area/networking, cla: yes, lgtm, size/L

#6899 Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/.gitignore
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/test/example/register.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/doc.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/foo_types.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/test/pub/register.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/bar_types.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/doc.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/update-test-codegen.sh
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/shared/testgrid/yaml.go
Labels: approved, cla: yes, lgtm, size/XL

#6901 Fix the reported metric
  pkg/autoscaler/scaling/autoscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#6898 golang format tools
  pkg/reconciler/service/service_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#6900 Adopt the new `// +genreconciler:class` style for PA and Certificate.
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/networking/v1alpha1/certificate_types.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/stub/controller.go
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/controller.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/nscert/resources/wildcard_certificate.go
  pkg/reconciler/nscert/resources/wildcard_certificate_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6905 Cleanup some SkipNamespaceValidation settings
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#6651 Add Auto TLS E2E test for HTTP01 challenge and set up test environment for running it
  test/config/autotls/certmanager/http01/issuer.yaml
  test/e2e-auto-tls.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/autotls/README.md
  test/e2e/autotls/auto_tls_test.go
  test/e2e/autotls/config/disablenscert/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#6910 Fix the graceful scaledown test setup
  test/e2e/autoscale_test.go
  test/e2e/websocket.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#6907 Modify logging for better debuggability
  pkg/autoscaler/scaling/autoscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#6906 Simplify stats reporter and the activator main, by removing the report ticker channel from args
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6842 Move queue health path probe to after sugared logger initialization and use default logger for error handling
  cmd/queue/main.go
  cmd/queue/main_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#6914 Format markdown
  test/e2e/autotls/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#6920 Drop the use of Base from the GC Reconciler.
  pkg/reconciler/gc/controller.go
  pkg/reconciler/gc/gc.go
  pkg/reconciler/gc/gc_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6921 Drop the use of Base from the metrics reconciler
  pkg/reconciler/metric/controller.go
  pkg/reconciler/metric/metric.go
  pkg/reconciler/metric/metric_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#6923 Drop Base from the PA reconcilers.
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/reconciler.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#6925 Drop Base from the Route reconciler.
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6922 Drop Base from the cert reconciler.
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/controller.go
Labels: approved, area/API, lgtm, size/M

#6929 Shortcut the change window for inactive revisions.
  pkg/autoscaler/aggregation/bucketing.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#6927 Drop Base from Revision reconciler
  pkg/reconciler/revision/controller.go
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6933 Switch the labeler to v1 types
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/labeler_test.go
  pkg/reconciler/labeler/labels.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6919 point to the new pkg.go.dev website for api docs
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#6926 Drop Base from SKS reconciler
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6918 Update pkg, fix MarkTrue unit test issue
  Gopkg.lock
  pkg/apis/serving/v1alpha1/revision_lifecycle_test.go
  test/README.md
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/logr.go
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/conditions/fake/fake.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XXL

#6924 Drop Base from the Configuration reconciler.
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/controller.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6931 Store the first write time (and update it from time to time)
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
  pkg/autoscaler/metrics/collector_test.go
Labels: approved, area/autoscale, area/test-and-release, cla: yes, lgtm, size/M

#6928 Delete namespace kcert when disabling namespace-cert feature
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#6941 Add OWNERS file for nscert
  pkg/reconciler/nscert/OWNERS
Labels: approved, area/API, cla: yes, lgtm, size/S

#6939 Delete the Serving stats reporter.
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
  pkg/reconciler/stats_reporter.go
  pkg/reconciler/stats_reporter_test.go
  pkg/reconciler/testing/v1/factory.go
  pkg/reconciler/testing/v1alpha1/factory.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#6916 Updated kourier version to v0.3.9
  third_party/kourier-latest/download-kourier.sh
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#6824 Move webhooks onto new sharedmain methods
  Gopkg.lock
  cmd/webhook/main.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#6949 Migrate service reconciler to use v1 APIs
  pkg/apis/serving/v1/service_lifecycle.go
  pkg/apis/serving/v1/service_lifecycle_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/service/controller.go
  pkg/reconciler/service/resources/configuration.go
  pkg/reconciler/service/resources/configuration_test.go
  pkg/reconciler/service/resources/names/names_test.go
  pkg/reconciler/service/resources/route.go
  pkg/reconciler/service/resources/route_test.go
  pkg/reconciler/service/resources/shared_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
  pkg/testing/v1/configuration.go
  pkg/testing/v1/service.go
  test/v1/service.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XXL

#6912 Add Unit Tests that verify stats reporting in autoscaler
  pkg/autoscaler/fake/fake_metric_client.go
  pkg/autoscaler/scaling/autoscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, ok-to-test, size/M

#6937 Split HTTP server and HTTPS server reconcilation when reconciling Istio Gateway
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#6948 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#6950 revision garbage collection now uses v1 APIs
  pkg/reconciler/gc/controller.go
  pkg/reconciler/gc/gc.go
  pkg/reconciler/gc/gc_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#6953 Have the activator use v1 APIs
  cmd/activator/main.go
  cmd/activator/request_log.go
  cmd/activator/request_log_test.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/context_handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler_test.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
  pkg/activator/util/context.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#6959 drop v1alpha1 usage in serverless service reconciler
  pkg/reconciler/serverlessservice/global_resync_test.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#6956 missed a v1alpha1 usage in route reconciler
  pkg/reconciler/route/resources/names/names_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#6889 Update ingress reconciler to use generate reconciler
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/stub/reconciler.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#6954 Fix the problem with double reporting from Activator.
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#6960 Uses v1 testing package in various reconcilers
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/XS
