Repository knative/serving, pull requests merged in 2020-07, with the labels that each got.

#8526 Remove unused context
  pkg/reconciler/labeler/labels.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#8528 Pin knative.dev/{pkg,test-infra,networking,caching} to release-0.16
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#8529 Fix nits in the multicontainer test
  test/e2e/multicontainer/multicontainer_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8535 Fix inconsistency in TestContainerErrorMsg.
  test/conformance/api/v1/errorcondition_test.go
  test/conformance/api/v1alpha1/errorcondition_test.go
  test/conformance/api/v1beta1/errorcondition_test.go
  test/v1/service.go
  test/v1alpha1/service.go
  test/v1beta1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#8533 Add StaticTimeoutFunc handler and speed up timeout handler tests.
  cmd/queue/main.go
  pkg/http/handler/timeout.go
  pkg/http/handler/timeout_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#8536 Clean the cert reconciler test
  pkg/reconciler/accessor/networking/certificate_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8538 Also refinish the secret test
  pkg/reconciler/accessor/core/secret_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8532 Harden activator HA test.
  test/ha/activator_test.go
  test/ha/ha.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#8534 Undo #7999: no longer wrap activator in timeout handler
  cmd/activator/main.go
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1alpha1/revision_timeout_test.go
  test/conformance/api/v1beta1/revision_timeout_test.go
Labels: approved, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#8551 Add the namespace knative-monitoring
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8558 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#8553 add comment about Kibana SERVER_BASEPATH env
  third_party/config/monitoring/logging/elasticsearch/kibana.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, needs-ok-to-test, size/XS

#8561 Remove unnecessary nil pointer check.
  test/conformance/ingress/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8514 Run storage migration job prior to upgrading
  config/post-install/storage-version-migration.yaml
  hack/generate-yamls.sh
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8531 Remove CreateWithOptions patch
  hack/patches/README.md
  hack/patches/dryruncreate.patch
  hack/update-deps.sh
  pkg/webhook/create_options.go
  pkg/webhook/create_options_test.go
  pkg/webhook/podspec_dryrun.go
  pkg/webhook/podspec_dryrun_test.go
  pkg/webhook/validate_service_test.go
  vendor/k8s.io/client-go/kubernetes/typed/core/v1/fake/fake_pod.go
  vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#8557 Increase prometheus mem limit to prevent crashing
  config/monitoring/metrics/prometheus/300-prometheus.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, ok-to-test, size/XS

#8554 Add knative-monitoring namespace to monitoring.yaml release
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#8565 drop use of unsupported resource locks from the leaderelection example config
  config/core/configmaps/leader-election.yaml
  pkg/leaderelection/config_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8285 return unexpected apply traffic error
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, ok-to-test, size/M

#8519 Track referenced traffic targets with tracker in the labeler.
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/labeler_test.go
  pkg/reconciler/labeler/labels.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8552 Separate the labeler logic into a package
  pkg/reconciler/labeler/accessors.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/v1/accessors.go
  pkg/reconciler/labeler/v1/labels.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8516 remove dependency on config map in conformance test
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/revision_timeout_test.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/revision_timeout_test.go
  test/conformance/api/v1beta1/util.go
  test/conformance/runtime/readiness_probe_test.go
  test/e2e/autoscale_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#8103 Add a `tag` label to the requests metrics of queue-proxy
  pkg/metrics/key.go
  pkg/metrics/tags.go
  pkg/queue/request_metric.go
  pkg/queue/request_metric_test.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, area/monitoring, area/networking, cla: yes, lgtm, ok-to-test, size/L

#8568 Change transport of direct client for customized MaxIdleConns
  pkg/autoscaler/metrics/stats_scraper.go
Labels: approved, area/autoscale, cla: yes, lgtm, ok-to-test, size/XS

#8574 Assorted linting fixes.
  pkg/queue/request_metric_test.go
  pkg/reconciler/route/traffic/traffic_test.go
  pkg/webhook/create_options.go
  pkg/webhook/podspec_dryrun_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#8405 Use valid FieldRef in test
  pkg/apis/serving/k8s_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#8578 Fix hanging TestChangeDefaultDomain|TestUpdateDomainTemplate.
  pkg/reconciler/nscert/nscert_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#8564 Add ResponsiveRevisionGC feature flag.
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/M

#8556 Support protobuf format in QP's metrics exchange
  cmd/queue/main.go
  pkg/autoscaler/metrics/http_scrape_client.go
  pkg/autoscaler/metrics/http_scrape_client_test.go
  pkg/network/network.go
  pkg/queue/prometheus_stats_reporter_test.go
  pkg/queue/protobuf_stats_reporter.go
  pkg/queue/protobuf_stats_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, ok-to-test, size/XL

#8569 Propagate HasBeenActive to a terminal condition as "ScaleTargetInitialized".
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
  pkg/testing/functional.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#8583 Switch to a common hash func in pkg
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/subsetter_test.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/modules.txt
Labels: approved, area/API, cla: yes, lgtm, size/L

#8587 Remove redundant tests
  pkg/autoscaler/metrics/http_scrape_client_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#8577 Fix race condition between Revision and PodAutoscaler readiness.
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/M

#8580 Update the job name and label into storage-version-migration-serving
  config/post-install/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8573 Create v1 version of GC logic
  pkg/reconciler/gc/reconciler.go
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/gc/v1/gc.go
  pkg/reconciler/gc/v1/gc_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8572 Create v2 labeler
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/labelerv1_test.go
  pkg/reconciler/labeler/labelerv2_test.go
  pkg/reconciler/labeler/v2/accessors.go
  pkg/reconciler/labeler/v2/labels.go
Labels: approved, area/API, cla: yes, lgtm, size/XL

#8589 Create v2 GC
  pkg/reconciler/gc/reconciler.go
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/gc/v2/gc.go
  pkg/reconciler/gc/v2/gc_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XL

#8483 Add new annotation for routingState and modified
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_helpers_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8403 Service initial scale (excluding initialScale == 0 or initialScale < minScale use case)
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/resources/decider.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  test/e2e/initial_scale_test.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#8593 Name fields in test structs
  cmd/autoscaler/main_test.go
  pkg/queue/breaker_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, ok-to-test, size/M

#8586 Reuse cluster IP When updating k8s service
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, ok-to-test, size/S

#8595 we don't need to delete the migration job since it uses generateName now
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8596 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#8600 Skip probing if TBC=-1
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#8598 Prepare our HA tests for new leaderelection.
  go.mod
  go.sum
  test/e2e-tests.sh
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
  vendor/golang.org/x/crypto/pkcs12/pkcs12.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/google.golang.org/api/container/v1beta1/container-api.json
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/google.golang.org/api/dns/v1/dns-gen.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/option/internaloption/internaloption.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/trace.pb.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/tracing.pb.go
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#8590 Ensure all yaml checksums are quoted
  config/core/configmaps/defaults.yaml
  config/core/configmaps/deployment.yaml
  config/core/configmaps/domain.yaml
  config/core/configmaps/features.yaml
  config/core/configmaps/gc.yaml
  config/core/configmaps/leader-election.yaml
  config/core/configmaps/logging.yaml
  config/core/configmaps/network.yaml
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
Labels: approved, area/API, cla: yes, lgtm, size/S

#8601 Change GC Sort Order
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/gc/v2/gc.go
  pkg/reconciler/gc/v2/gc_test.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#8591 Move labeler patch creation behind Accessor implementations
  pkg/reconciler/labeler/labelerv2_test.go
  pkg/reconciler/labeler/v2/accessors.go
  pkg/reconciler/labeler/v2/labels.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8607 Widen collector test timeouts and some cleansing.
  pkg/autoscaler/metrics/collector_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#8606 Make sorting consistent in GC test.
  pkg/reconciler/gc/v2/gc_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#8611 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ducktypes/ducktypes.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1_tests.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1_tests.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#8324 Add route consistency retry to new logging E2E test.
  test/e2e/logging_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#8612 Handle InitialScale != 1 when creating multiScaler and some tidy-ups
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/multiscaler.go
  pkg/autoscaler/scaling/multiscaler_test.go
  pkg/reconciler/autoscaling/kpa/scaler.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#8616 Remove endpoints from KPA as well.
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#8619 Assorted fixes to enable chaos duck.
  test/e2e-common.sh
  test/e2e-tests.sh
  test/ha/activator_test.go
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8622 Statserver test cleanup and benchmark enhancement.
  pkg/autoscaler/statserver/server_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#8623 Bump activator terminationGracePeriodSeconds to match DefaultMaxRevisionTimeoutSeconds
  config/core/configmaps/defaults.yaml
  config/core/deployments/activator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8624 Add WireStatMessage[s] types and convertes for protobuf compatibility.
  pkg/autoscaler/metrics/stat.pb.go
  pkg/autoscaler/metrics/stat.proto
  pkg/autoscaler/metrics/stat_conversions.go
  pkg/autoscaler/metrics/stat_conversions_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XL

#8620 Remove the resource lock from serving
  go.mod
  go.sum
  pkg/leaderelection/config_test.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1_tests.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/binding_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1_tests.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, area/API, cla: yes, lgtm, size/L

#8615 Create v2 GC settings
  config/core/configmaps/gc.yaml
  pkg/gc/config.go
  pkg/gc/config_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8630 Various nits around the code.
  pkg/activator/net/revision_backends.go
  pkg/apis/serving/k8s_validation.go
  pkg/autoscaler/metrics/stat.pb.go
  pkg/autoscaler/metrics/stat.proto
  pkg/autoscaler/metrics/stat_conversions.go
  pkg/autoscaler/metrics/stat_conversions_test.go
  pkg/network/ingress/ingress.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/route.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  test/conformance/ingress/headers.go
  test/e2e/e2e.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#8594 Improve tests for stat reporters
  pkg/queue/prometheus_stats_reporter_test.go
  pkg/queue/protobuf_stats_reporter_test.go
Labels: approved, area/networking, cla: yes, lgtm, ok-to-test, size/L

#8604 Populate the routingState label and modified annotation in the Labeler
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/reconciler/gc/v2/gc_test.go
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/labelerv2_test.go
  pkg/reconciler/labeler/v2/accessors.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8626 Accept protobuf encoded messages in the statserver.
  pkg/autoscaler/statserver/server.go
  pkg/autoscaler/statserver/server_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#8635 Use buffer pool in request log handler
  pkg/activator/handler/probe_handler.go
  pkg/http/request_log.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#8633 Encode stats as protobuf in the activator.
  cmd/activator/main.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#8640 Set a high terminationGracePeriodSeconds on webhook
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8582 Move PodSpec DryRun to enabled by default
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/S

#8636 Make comment in network configmap more true
  config/core/configmaps/network.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8614 Preserve Annotation to Prevent GC
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/register.go
  pkg/reconciler/gc/v2/gc.go
  pkg/reconciler/gc/v2/gc_test.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#8634 Move common functions to e2e-common.sh
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8603 Run the chaosduck component during our e2e testing.
  hack/tools.go
  test/config/chaosduck.yaml
  test/e2e-common.sh
  vendor/knative.dev/pkg/kflag/doc.go
  vendor/knative.dev/pkg/kflag/set.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/modules.txt
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#8643 Move pkg to head to include logstream changes
  go.mod
  go.sum
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#8642 Unit test to cover defaults == example for observability config
  config/core/configmaps/observability.yaml
  pkg/metrics/config_test.go
Labels: approved, area/monitoring, cla: yes, lgtm, size/S

#8647 Explain reasoning behind pool implementation to avoid future confusion.
  pkg/network/bufferpool.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#8608 Add a byte pool for scraping
  pkg/autoscaler/metrics/http_scrape_client.go
  pkg/autoscaler/metrics/http_scrape_client_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, ok-to-test, size/M

#8666 Add helpers to approx equate the int32.
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#8670 Follow redirects when looking for releases from GitHub API.
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7738 Remove parallel 1 option from Istio 1.5 tests
  test/conformance/ingress/tls.go
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#8668 Scale controlplane for autotls test leg.
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8673 Bump to 30s the wait for CM propagation
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8055 Simplify istio 1.5 installation manifest
  third_party/istio-1.5-latest
  third_party/istio-1.5.4/istio-ci-no-mesh-operator.yaml
  third_party/istio-1.5.7/README.md
  third_party/istio-1.5.7/generate.sh
  third_party/istio-1.5.7/istio-ci-mesh-operator.yaml
  third_party/istio-1.5.7/istio-ci-mesh.yaml
  third_party/istio-1.5.7/istio-ci-no-mesh-operator.yaml
  third_party/istio-1.5.7/istio-ci-no-mesh.yaml
  third_party/istio-1.5.7/istio-crds.yaml
  third_party/istio-1.5.7/istio-minimal-operator.yaml
  third_party/istio-1.5.7/istio-minimal.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#8632 Updates to V2 GC Settings
  config/core/configmaps/gc.yaml
  pkg/gc/config.go
  pkg/gc/config_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8677 Harden global resync domain update test.
  pkg/reconciler/route/route_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#8645 Add feature flags for affinity/nodeSelector/tolerations
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/config/store.go
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/L

#8686 Merge pkg to serving
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/doc.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#8669 Include RoutingState when making a new Revision
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_helpers_test.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/controller.go
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/gc/v1/gc_test.go
  pkg/reconciler/gc/v2/gc_test.go
  pkg/reconciler/service/service_test.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#8699 Disable the chaos duck in upgrade tests.
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#8696 Use 2-lane queue in the reconciler
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#8709 Use integer suffixes rather than uuids when generating container names for multiple containers
  pkg/apis/serving/v1/revision_defaults.go
  pkg/apis/serving/v1/revision_defaults_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8680 Clarify documentation
  config/core/configmaps/features.yaml
Labels: approved, cla: yes, lgtm, size/XS

#8710 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#8714 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#8717 Disable chaos for networking components.
  test/config/chaosduck.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8713 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8716 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8719 Drop example block from test config
  pkg/logging/config_test.go
  pkg/logging/testdata/test-config-logging.yaml
  test/config/config-logging.yaml
Labels: approved, area/monitoring, area/test-and-release, cla: yes, lgtm, size/L

#8723 Remove double imports
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/gc/v1/gc_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#8720 Enable chaos for net-contour controller.
  test/config/chaosduck.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8729 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.mod
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/test/logging/logger_writer.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/test_util.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#8724 Add a Timeout to Image Digest resolution
  go.mod
  go.sum
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/resolve.go
  pkg/reconciler/revision/resolve_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/rebase.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/catalog.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/check.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/delete.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/descriptor.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/modules.txt
Labels: approved, area/API, cla: yes, lgtm, size/L

#8621 Implementation of the new v2 garbage collector
  pkg/gc/config.go
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/gc/v2/gc.go
  pkg/reconciler/gc/v2/gc_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XL

#8597 conformance tests should support different feature states
  test/conformance/ingress/run.go
  test/e2e-tests.sh
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8732 Some nits and other file cleanups
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/resolve_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8721 Pull in chaos w/ jitter
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#8728 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8727 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8733 Eliminate array allocations
  pkg/reconciler/gc/v2/gc.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8734 Use github action for managing stale issues/PRs
  .github/workflows/stale.yaml
Labels: approved, cla: yes, lgtm, size/M

#8745 A little more bikeshed on the GC code 😄
  pkg/reconciler/gc/v2/gc.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#8722 Import slow lane for global resync
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#8746 Tidy lint complaints in queue and activator
  cmd/queue/main.go
  pkg/activator/config/store.go
  pkg/queue/protobuf_stats_reporter.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#8754 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8753 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8759 Optimize positive pod count a bit
  pkg/resources/pods.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#8757 Disable lastPinned patching when v2 GC enabled
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#8756 Ensure new GC is run for allowed state
  pkg/reconciler/gc/reconciler.go
  pkg/reconciler/labeler/labeler.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8760 Introduce a generic getter that gives all the pods broken down by state
  pkg/resources/pods.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8762 Optimize pod counting in KPA
  pkg/reconciler/autoscaling/kpa/kpa.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#8764 Fix network probing for kingress conformance.
  test/test_images/runtime/handlers/handler.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8768 Fix a few nits
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/metadata_validation.go
  pkg/reconciler/labeler/v1/accessors.go
  pkg/reconciler/labeler/v2/accessors.go
  pkg/reconciler/labeler/v2/labels.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#8773 Fix script to grep correct leader in e2e-common.sh
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8770 Fail test immediately when important setup failed
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#8784 Add a benchmark for the concurrency reporter.
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#8755 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/state.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/state.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/state.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/state.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/state.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/state.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/knative.dev/networking/pkg/apis/config/defaults.go
  vendor/knative.dev/networking/pkg/apis/config/doc.go
  vendor/knative.dev/networking/pkg/apis/config/store.go
  vendor/knative.dev/networking/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/knative.dev/pkg/test/logging/logger_writer.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#8785 [master] Update net-certmanager nightly
  third_party/cert-manager-0.12.0/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#8771 Add julz to autoscaling approvers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#8772 Disable chaos on webhook for now.
  test/config/chaosduck.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#8786 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#8790 Use loggers with keys.
  pkg/network/status/status.go
  pkg/network/status/status_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#8788 Add logstream to the kingress conformance tests.
  test/conformance/ingress/basic.go
  test/conformance/ingress/grpc.go
  test/conformance/ingress/headers.go
  test/conformance/ingress/hosts.go
  test/conformance/ingress/path.go
  test/conformance/ingress/percentage.go
  test/conformance/ingress/retry.go
  test/conformance/ingress/timeout.go
  test/conformance/ingress/tls.go
  test/conformance/ingress/update.go
  test/conformance/ingress/visibility.go
  test/conformance/ingress/websocket.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#8787 Refactor the concurrency reporter into callable functions.
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#8796 Move stat reporting out of the locked section.
  pkg/activator/handler/concurrency_reporter.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#8797 Replace request event handler with concurrency reporter handler.
  cmd/activator/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/requestevent_handler.go
  pkg/activator/handler/requestevent_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#8803 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#8805 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#8800 Add a benchmark for report and optimize it further.
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#8806 Update the flush interval to be a small constant delay.
  cmd/queue/main.go
  pkg/activator/handler/handler.go
  pkg/network/network.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#8798 Propagate labels and annotations from Route to placeholder service
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/resources/service_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#8807 [master] Fix spelling errors
  pkg/network/network.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#8808 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#8789 Filter GC labels/annotations from propagating to created resources
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1alpha1/revision_lifecycle.go
  pkg/apis/serving/v1alpha1/revision_lifecycle_test.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/imagecache.go
  pkg/reconciler/revision/resources/meta.go
  pkg/reconciler/revision/resources/meta_test.go
  pkg/reconciler/revision/resources/pa.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#8810 Thread the new transport method which permits setting idle conns
  pkg/activator/handler/handler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#8799 Allow more than 1000 concurrent revisions when CC!=0
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
  pkg/queue/breaker.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#8809 Add new KPA status for dependencies
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/revision/table_test.go
  pkg/testing/functional.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#8813 Remove duplicate helpers and simplify one
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/revision/table_test.go
  pkg/testing/functional.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#8814 Do not propagate the visibility label from Route
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/resources/service_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#8817 Remove unnecessary append calls.
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#8816 Benchmark the actual concurrency reporting handler.
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#8818 Clear map rather than re-allocating
  pkg/activator/handler/concurrency_reporter.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS
