Repository knative/serving, pull requests merged in 2020-04, with the labels that each got.

#7438 Append script name to k8s.log.txt
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7447 Harden the SKS Global resync test even more.
  pkg/reconciler/serverlessservice/global_resync_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7460 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7461 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7462 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#7436 Add tests that validate actual and example config for the leaderelection
  pkg/leaderelection/config_test.go
  pkg/leaderelection/testdata/config-leader-election.yaml
Labels: approved, area/API, cla: yes, lgtm, size/L

#7397 Replace the default NS knative-serving with a generated NS for e2e
  test/apicoverage.sh
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
  test/e2e/istio/probing_test.go
  test/e2e_flags.go
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
  test/ha/ha.go
  test/performance/benchmarks/dataplane-probe/continuous/main.go
  test/performance/performance-tests.sh
  test/system.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#7445 Add common probe path in autoscaler, networking and activator
  pkg/activator/net/revision_backends.go
  pkg/network/status/status.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  test/config/security/policy.yaml
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/S

#7463 Return cumulative errors when deleting test resources
  test/clients.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7467 Remove usages of md5, replace with sha256
  pkg/network/ingress/ingress.go
  pkg/network/ingress/ingress_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#7466 Fix the default CM as well.
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/leaderelection/config.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7472 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7473 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/performance/performance.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
Labels: approved, cla: yes, lgtm, size/L

#7475 Remove insert probe which is no longer used
  pkg/network/ingress/ingress.go
  pkg/network/ingress/ingress_test.go
  pkg/network/status/status_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#7470 Ensure prober is canceled before last ingress in TestUpdate
  test/conformance/ingress/update_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7480 Revert "Remove insert probe which is no longer used"
  pkg/network/ingress/ingress.go
  pkg/network/ingress/ingress_test.go
  pkg/network/status/status_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/L

#7481 Add a comment to make sure we don't delete it anymore
  pkg/network/ingress/ingress.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#7477 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7483 Revert changes to perf tests setup script
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7479 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#7452 Simplify annotation generation in autoscale tests.
  test/e2e/autoscale_test.go
  test/e2e/grpc_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7490 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7491 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7431 Change metrics scraping based on TBC
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#7509 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7510 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7511 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/delete.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/knative.dev/pkg/testutils/metahelper/main.go
Labels: approved, cla: yes, lgtm, size/L

#7513 Fix the race in #7030
  pkg/reconciler/route/route_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#7514 Reconcile on all private service events in KPA.
  pkg/reconciler/autoscaling/kpa/controller.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#7506 Replace deprecated 'Track' with 'TrackReference'.
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/route/route.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#7516 Results of update-deps
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/L

#7494 Subsetting algorithm implementation
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/serverlessservice/subsetter.go
  pkg/reconciler/serverlessservice/subsetter_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#7518 Support default-domain when gateway has a hostname instead of IP
  cmd/default-domain/main.go
Labels: approved, cla: yes, lgtm, size/S

#7517 Raise universe by x2, raise test coverage, unskip the test
  pkg/reconciler/serverlessservice/subsetter.go
  pkg/reconciler/serverlessservice/subsetter_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7521 Remove unused ErrActivatorOverload
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/net/throttler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#7520 Remove unused fields from PA base reconciler.
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/reconciler.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#7526 Preparing for v0.14 release, point pkg to release-0.14.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/images/Knative-Duck0.png
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
Labels: approved, cla: yes, lgtm, size/XXL

#7522 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7523 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7528 use https style vs. ssh
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#7525 Propagate Metric status changes to the API.
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
  pkg/reconciler/metric/controller.go
  pkg/reconciler/metric/metric.go
  pkg/reconciler/metric/metric_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#7519 Use buffer to build strings for hashing to noticeably improve the time and memory.
  pkg/reconciler/serverlessservice/subsetter.go
  pkg/reconciler/serverlessservice/subsetter_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7532 Split apart deployment podspec functions
  pkg/reconciler/revision/resources/deploy.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7537 Nit: fix out-of-date comment to reference correct handler
  cmd/queue/main.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS

#7542 Re-enable the Post-Upgrade generation check.
  test/upgrade/service_postupgrade_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7543 Delete obsolete comment
  pkg/reconciler/revision/resources/deploy.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#7535 Simplify queue stats test and relax process uptime boundary.
  pkg/queue/prometheus_stats_reporter_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#7531 Implement subsetting function in SKS
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  pkg/testing/functional.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#7541 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/L

#7545 Remove strconv.Itoa to be more consistent with `j` usage.
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#7540 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7546 Validate the example config map values
  pkg/reconciler/revision/config/store_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7547 Cover n=0 case, where 0 means all.
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#7417 CleanupOnInterrupt() call multiple cleanup functions only once
  test/cleanup.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7553 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7484 HA tests - create services after electing the leader
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7555 Print the SKS num activators field in kubectl
  config/core/resources/serverlessservice.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7534 Do not append port to IngressEndpoint in ingress conformance test
  test/conformance/ingress/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7499 Include a job to help operators migrate their storage version
  DEVELOPMENT.md
  config/core/roles/clusterrole.yaml
  config/post-install/storage-version-migration.yaml
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7558 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7559 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#7560 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7379 Activator HA test
  test/e2e-tests.sh
  test/ha/activator_test.go
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
  test/ha/ha.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#7562 Add more detailed comments for the config map values so it is clearer.
  config/core/configmaps/autoscaler.yaml
  test/performance/benchmarks/deployment-probe/continuous/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7563 Add some logging to help with e2e test debugging
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/revision/revision.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#7564 Quadruple number of samples during traffic split.
  test/conformance.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7351 change metric pod_name and container_name to pod and container
  config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  config/monitoring/metrics/prometheus/100-grafana-dash-knative.yaml
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/deployment-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/pods-dashboard.json
  third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/statefulset-dashboard.json
Labels: approved, area/monitoring, cla: yes, lgtm, size/M

#7500 Remove istio sidecar injection from default namespace
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7414 Use istioctl to generate istio manifests for istio 1.5+
  test/e2e-common.sh
  test/e2e-tests.sh
  third_party/istio-1.4.6/download-istio.sh
  third_party/istio-1.4.6/istio-ci-mesh.yaml
  third_party/istio-1.4.6/istio-ci-no-mesh.yaml
  third_party/istio-1.4.6/istio-crds.yaml
  third_party/istio-1.4.6/istio-knative-extras.yaml
  third_party/istio-1.4.6/istio-minimal.yaml
  third_party/istio-1.4.6/values-lean.yaml
  third_party/istio-1.4.6/values.yaml
  third_party/istio-1.5-latest
  third_party/istio-1.5.0/README.md
  third_party/istio-1.5.0/download-istio.sh
  third_party/istio-1.5.0/drain-seconds.yaml.patch
  third_party/istio-1.5.0/istio-ci-mesh.yaml
  third_party/istio-1.5.0/istio-ci-no-mesh.yaml
  third_party/istio-1.5.0/istio-crds.yaml
  third_party/istio-1.5.0/istio-knative-extras.yaml
  third_party/istio-1.5.0/istio-minimal.yaml
  third_party/istio-1.5.0/namespace.yaml.patch
  third_party/istio-1.5.0/values-extras.yaml
  third_party/istio-1.5.0/values-lean.yaml
  third_party/istio-1.5.0/values-local.yaml
  third_party/istio-1.5.0/values.yaml
  third_party/istio-1.5.1/README.md
  third_party/istio-1.5.1/generate.sh
  third_party/istio-1.5.1/istio-ci-mesh-operator.yaml
  third_party/istio-1.5.1/istio-ci-mesh.yaml
  third_party/istio-1.5.1/istio-ci-no-mesh-operator.yaml
  third_party/istio-1.5.1/istio-ci-no-mesh.yaml
  third_party/istio-1.5.1/istio-crds.yaml
  third_party/istio-1.5.1/istio-minimal-operator.yaml
  third_party/istio-1.5.1/istio-minimal.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#7570 nit: Update directory name to istio-1.4.7
  third_party/istio-1.4-latest
  third_party/istio-1.4.7/README.md
  third_party/istio-1.4.7/download-istio.sh
  third_party/istio-1.4.7/drain-seconds.yaml.patch
  third_party/istio-1.4.7/istio-ci-mesh.yaml
  third_party/istio-1.4.7/istio-ci-no-mesh.yaml
  third_party/istio-1.4.7/istio-crds.yaml
  third_party/istio-1.4.7/istio-knative-extras.yaml
  third_party/istio-1.4.7/istio-minimal.yaml
  third_party/istio-1.4.7/namespace.yaml.patch
  third_party/istio-1.4.7/values-extras.yaml
  third_party/istio-1.4.7/values-lean.yaml
  third_party/istio-1.4.7/values-local.yaml
  third_party/istio-1.4.7/values.yaml
  third_party/istio-stable
Labels: approved, cla: yes, lgtm, size/XS

#7573 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7572 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/M

#7574 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
Labels: approved, cla: yes, lgtm, size/S

#7578 Point test-infra to release-0.14 in prep for 0.14 release
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#7577 Add a span to show queue waiting on tracing
  cmd/queue/main.go
  cmd/queue/main_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#7581 Cleanup span usage to track wait time.
  cmd/queue/main.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#7508 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/L

#7584 Fix flake in TestUpdateDomainConfigMap.
  pkg/reconciler/route/route_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#7586 Remove vastly outdated autoscaler/activator documentation.
  pkg/activator/README.md
  pkg/activator/images/activator_activeRevision.png
  pkg/activator/images/activator_reserveRevision.png
  pkg/activator/images/routeTraffic.png
  pkg/autoscaler/README.md
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#7588 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7536 Bring back logstreams during tests.
  test/apicoverage.sh
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
  test/e2e/istio/probing_test.go
  test/e2e_flags.go
  test/ha/activator_test.go
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
  test/ha/ha.go
  test/performance/benchmarks/dataplane-probe/continuous/main.go
  test/system.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#7587 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7585 Remove vastly outdated route documentation.
  pkg/reconciler/route/README.md
  pkg/reconciler/route/doc/images/active_revisions.svg
  pkg/reconciler/route/doc/images/inactive_revision.svg
  pkg/reconciler/route/doc/images/inactive_revisions.svg
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#7548 Actually apply the suggestion to the public endpoints
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  test/e2e/e2e.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#7591 Actually verify the contents of resource.Quantity.
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/pa_test.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#7594 Microfixes to autoscale.go
  test/test_images/autoscale/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7530 Support disable wildcard cert label without 'internal'
  pkg/apis/networking/register.go
  pkg/reconciler/nscert/controller.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
  test/e2e/autotls/config/disablenscert/main.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#7595 Expand the comment for grace time to scale to 0
  config/core/configmaps/autoscaler.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7602 Fix license formatting in a few files.
  test/e2e/websocket_test.go
  test/system.go
  test/test_images/grpc-ping/main.go
  test/test_images/runtime/handlers/args.go
  test/test_images/runtime/handlers/cgroup.go
  test/test_images/runtime/handlers/env.go
  test/test_images/runtime/handlers/file.go
  test/test_images/runtime/handlers/handler.go
  test/test_images/runtime/handlers/mount.go
  test/test_images/runtime/handlers/request.go
  test/test_images/runtime/handlers/runtime.go
  test/test_images/runtime/main.go
  test/types/runtime.go
  test/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#7600 Removes write access to the internal resources from aggregated cluserroles
  config/core/roles/clusterrole-namespaced.yaml
Labels: approved, cla: yes, lgtm, size/S

#7603 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7605 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7604 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7606 Propagate Ingress status once ObservedGenerated matches generation.
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/testing/functional.go
  pkg/testing/v1/route.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#7608 HA tests - wait for the service to be ready before sending requests
  test/ha/ha.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7610 Wait for the route propagation to kill the flakes.
  pkg/reconciler/route/route_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#7611 Remove some redundancy in the code
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/serverlessservice/global_resync_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#7609 Improve the Scale API
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
  pkg/autoscaler/scaling/multiscaler.go
  pkg/autoscaler/scaling/multiscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#7614 Rename TestServiceToServiceCallViaActivator TestSvcToSvcViaActivator
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7616 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7618 [master] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#7617 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7619 Make number of activators 15
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7598 Add a label to e2e test resources
  test/e2e_constants.go
  test/util.go
  test/v1/configuration.go
  test/v1/route.go
  test/v1/service.go
  test/v1alpha1/configuration.go
  test/v1alpha1/route.go
  test/v1alpha1/service.go
  test/v1beta1/configuration.go
  test/v1beta1/route.go
  test/v1beta1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7622 Ignore the impossible situation
  pkg/autoscaler/scaling/multiscaler.go
  pkg/autoscaler/scaling/multiscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#7626 Add hacky workaround to pass tests for release-0.11
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7597 Backport `Best effort Istio probing` to 0.11
  pkg/reconciler/ingress/status.go
  pkg/reconciler/ingress/status_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#7629 Wait for capacity change in multiple activators test.
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#7634 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7635 nit: Fix comment for the scaling size of activator
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7627 Wait for status update in global resync test.
  pkg/reconciler/route/route_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#7632 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7628 Remove unused, unreachable and ineffective code and fix deprecations in tests.
  test/e2e/autotls/auto_tls_test.go
  test/e2e/autotls/config/disablenscert/main.go
  test/e2e/autotls/config/util.go
  test/e2e/grpc_test.go
  test/e2e/websocket_test.go
  test/v1alpha1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#7569 Add validation check to tag name
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#7607 Remove some stray cluster ingress references.
  pkg/apis/config/defaults.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#7637 Add #activator dimension to the load test.
  test/performance/benchmarks/load-test/continuous/main.go
  test/performance/benchmarks/load-test/dev.config
  test/performance/benchmarks/load-test/prod.config
  test/performance/metrics/runtime.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7631 Use actual number of activators for condition check if it is smaller than NumActivators
  test/e2e/e2e.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#7639 Fix more of the throttler tests
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#7647 Add support for Labels in DomainTemplate
  config/core/configmaps/network.yaml
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/network/zz_generated.deepcopy.go
  pkg/reconciler/route/domains/domains.go
  pkg/reconciler/route/domains/domains_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#7654 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7649 Add a new config-deployment parameter
  config/core/configmaps/deployment.yaml
  pkg/deployment/config.go
  pkg/deployment/config_test.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/revision/resources/constants.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#7656 Add pkg/deployment OWNERS file
  pkg/deployment/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#7638 Fix an issue with pods becoming non-ready.
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#7373 Add ImageDigests for multi container support
  pkg/apis/serving/v1/revision_types.go
  pkg/apis/serving/v1/zz_generated.deepcopy.go
  pkg/apis/serving/v1alpha1/revision_conversion.go
  pkg/apis/serving/v1alpha1/revision_conversion_test.go
  pkg/apis/serving/v1alpha1/revision_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/revision/queueing_test.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/imagecache.go
  pkg/reconciler/revision/resources/imagecache_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
  pkg/testing/v1/revision.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#7655 Add more detailed logging to queue-proxy shutdown.
  cmd/queue/main.go
  test/e2e/destroypod_test.go
Labels: approved, area/networking, area/test-and-release, cla: yes, lgtm, size/S

#7366 Add enable-certificate-owner-ref option to cert-manager's controller
  third_party/cert-manager-0.12.0/cert-manager.yaml
  third_party/cert-manager-0.12.0/download-cert-manager.sh
  third_party/cert-manager-0.12.0/owner-ref.patch
Labels: approved, cla: yes, lgtm, size/S

#7580 Stabilize Activator HA tests
  test/e2e-tests.sh
  test/ha/activator_test.go
  test/ha/ha.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7589 Updating pkg to master post 0.14 release.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#7653 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7663 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7633 [master] Update net-istio nightly
  third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#7667 Fixes the nits in the store for revision.
  pkg/reconciler/revision/config/store.go
  pkg/reconciler/revision/config/store_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#7640 Remove NodePort exposure from Grafana, Prometheus and Kibana
  config/monitoring/metrics/prometheus/100-grafana.yaml
  config/monitoring/metrics/prometheus/300-prometheus.yaml
  third_party/config/monitoring/logging/elasticsearch/kibana.yaml
Labels: approved, area/monitoring, cla: yes, lgtm, ok-to-test, size/M

#7669 Remove redundant request check in testProxyToHelloworld()
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7676 [master] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7620 Include storage migration job in upgrade test & disable gen checks
  test/e2e-upgrade-tests.sh
  test/upgrade/service_postupgrade_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7668 Add deployment-config CM to the autoscaler.
  pkg/deployment/config.go
  pkg/deployment/config_test.go
  pkg/reconciler/autoscaling/config/store.go
  pkg/reconciler/autoscaling/config/store_test.go
  pkg/reconciler/autoscaling/config/testdata/config-autoscaler.yaml
  pkg/reconciler/autoscaling/config/testdata/config-deployment.yaml
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#7671 Fix flake in TestMetricCollectorScraper.
  pkg/autoscaler/metrics/collector_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#7675 [master] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7677 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/caching/Gopkg.lock
  vendor/knative.dev/pkg/DEVELOPMENT.md
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/cached.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#7416 Add doc on how to run Ingress conformance tests.
  test/conformance/ingress/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#7544 Validate Revision templates with K8s Dry-Run
  cmd/webhook/main.go
  pkg/webhook/OWNERS
  pkg/webhook/podspec_dryrun.go
  pkg/webhook/podspec_dryrun_test.go
  pkg/webhook/validate_service.go
  pkg/webhook/validate_service_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#7683 Actually use the new field in the deploy config
  pkg/deployment/config.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#7684 Fix some nits in the network_test.go
  pkg/network/network_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/M

#7666 Add ingress conformance test for visibility + paths
  test/conformance/ingress/visibility_test.go
Labels: approved, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#7688 Remove outdated comment from route controller.
  pkg/reconciler/route/controller.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#7686 Fix flake in nonhttp01.TestSecret
  test/conformance/certificate/nonhttp01/certificate_test.go
  test/conformance/certificate/utils.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#7680 Job templates are immutable so we shouldn't include variant label values
  config/post-install/default-domain.yaml
  config/post-install/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7681 Add 'julz' as an autoscaling reviewer.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#7660 Harden parallel probing test.
  pkg/queue/readiness/probe_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/XS
