Repository knative/serving, pull requests merged in 2021-05, with the labels that each got.

#11282 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11287 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11288 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11290 Make sure the decider state is settled in test
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#11298 Change magic DNS to sslip.io
  config/post-install/default-domain.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11300 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11302 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11301 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11279 Increase digest resolution rate limit
  go.mod
  go.sum
  pkg/reconciler/revision/controller.go
  vendor/modules.txt
Labels: approved, area/API, cla: yes, lgtm, size/S

#11292 Update go-containerregistry to v0.5.0
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/google/go-containerregistry/LICENSE
  vendor/github.com/containerd/stargz-snapshotter/estargz/go.mod
  vendor/github.com/google/go-containerregistry/internal/and/and_closer.go
  vendor/github.com/google/go-containerregistry/internal/estargz/estargz.go
  vendor/github.com/google/go-containerregistry/internal/gzip/zip.go
  vendor/github.com/google/go-containerregistry/internal/redact/redact.go
  vendor/github.com/google/go-containerregistry/internal/retry/retry.go
  vendor/github.com/google/go-containerregistry/internal/retry/wait/kubernetes_apimachinery_wait.go
  vendor/github.com/google/go-containerregistry/internal/verify/verify.go
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/go.sum
  vendor/github.com/google/go-containerregistry/pkg/name/ref.go
  vendor/github.com/google/go-containerregistry/pkg/v1/hash.go
  vendor/github.com/google/go-containerregistry/pkg/v1/manifest.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/mutate.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/compressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/uncompressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/descriptor.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/multi_write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/logger.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/retry.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/layer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm

#11293 Make digest resolution idempotent
  pkg/reconciler/revision/background.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#11303 ensure our temp files has a yaml extension - otherwise ytt will ignore it
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11304 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#11259 Do not toggle configuration in e2e when unnecessary
  test/e2e-tests.sh
  test/e2e/multicontainer_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11311 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11306 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11318 Do not call GetIngressEndpoint() when --resolvabledomain is enabled
  test/e2e/websocket.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11312 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11315 Disable webhook for net-certmanager-webhook
  test/config/chaosduck.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11309 Remove responsive-revision-gc config from config-features
  config/core/configmaps/features.yaml
  pkg/apis/config/features_test.go
Labels: approved, area/API, cla: yes, kind/cleanup, lgtm, size/S

#11319 Use test options for feature tests and ha tests
  test/e2e-tests.sh
  test/ha/activator_test.go
  test/ha/ha.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#11305 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10795 Add Domainmapping AutoTLS e2e test
  test/e2e/autotls/domain_mapping_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11327 Fix markdown
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11310 change type of revision status replicas
  go.mod
  go.sum
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/apis/serving/v1/revision_types.go
  pkg/apis/serving/v1/zz_generated.deepcopy.go
  test/e2e/minscale_readiness_test.go
  vendor/modules.txt
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#11330 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11334 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11328 Add test for periodSeconds>0
  test/conformance/runtime/readiness_probe_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#11188 Add an e2e hpa test
  test/e2e-tests.sh
  test/e2e/autoscale.go
  test/e2e/autoscale_hpa_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11333 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11332 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11336 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#11338 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#11342 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11343 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11341 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11348 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11350 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11358 Fix invalid link for support.rotation
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#11349 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11359 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11360 Use UID rather than name in label to avoid hitting character limits
  pkg/apis/serving/register.go
  pkg/reconciler/domainmapping/resources/certificate.go
  pkg/reconciler/domainmapping/resources/certificate_test.go
  pkg/reconciler/domainmapping/resources/ingress.go
  pkg/reconciler/domainmapping/resources/ingress_test.go
  pkg/reconciler/domainmapping/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#11361 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11363 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11364 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11362 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11367 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#11369 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11366 Replace golint with revive
  .golangci.yaml
  pkg/autoscaler/config/config.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/nscert/nscert.go
  pkg/webhook/podspec_dryrun.go
  pkg/webhook/validate_unstructured.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#11368 Add enable-alpha and enable-beta flag to autotls tests
  test/e2e-auto-tls-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11374 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11378 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#11377 Use NetworkingFlags to enable alpha feature in autotls
  test/e2e/autotls/domain_mapping_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11370 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11382 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11379 Use regex to disable chaos for all webhooks dynamically
  test/config/chaosduck.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11381 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11344 allow dropping securityContext capabilities
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/M

#11391 Validate features configmap
  cmd/webhook/main.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#11394 Adding securityContext.capabilities.drop to schemas
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
Labels: approved, cla: yes, lgtm, size/M

#11392 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11399 Set spec.HTTPOption in Ingress created from DomainMapping
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/resources/ingress.go
  pkg/reconciler/domainmapping/resources/ingress_test.go
  pkg/reconciler/domainmapping/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#11398 Add readiness test image
  test/test_images/readiness/README.md
  test/test_images/readiness/readiness.go
  test/test_images/readiness/service.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11375 Move activator count computation into KPA
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
  pkg/autoscaler/scaling/multiscaler.go
  pkg/autoscaler/scaling/multiscaler_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#11401 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/M

#11396 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11400 Regenerate schemas to pick up capabilities addition
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
Labels: approved, cla: yes, lgtm, size/M

#11403 Allow the autoscale upgrade test traffic to settle before upgrading
  test/upgrade/autoscaler.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11406 Update schema generator as a bug has been fixed
  hack/update-schemas.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11405 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11384 Have our e2e tests use K8s 1.19 again
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11408 Remove myself following-up knative/community#628
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#11397 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11402 Test that readiness is not reported early in HTTP probe test
  test/conformance.go
  test/conformance/runtime/readiness_probe_test.go
  test/test_images/runtime/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#11417 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11418 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/depcheck/heavy.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/testing/zipkin.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#11420 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11421 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11419 fix typo and redundant code
  pkg/queue/breaker.go
  pkg/queue/breaker_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#11415 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11424 Use cert-manager API version to v1 for test resources
  test/config/autotls/certmanager/caissuer/issuer.yaml
  test/config/autotls/certmanager/http01/issuer.yaml
  test/config/autotls/certmanager/http01/mesh-issuer.yaml
  test/config/autotls/certmanager/selfsigned/issuer.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11414 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11426 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11427 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11433 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta1/horizontalpodautoscaler/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta1/horizontalpodautoscaler/horizontalpodautoscaler.go
  vendor/knative.dev/pkg/client/injection/kube/informers/coordination/v1/lease/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/coordination/v1/lease/lease.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#11430 Fix PerItem test flake
  pkg/reconciler/revision/background_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#11425 Improve readiness tests for exec case
  test/conformance/runtime/readiness_probe_test.go
  test/test_images/readiness/readiness.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11434 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11436 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11438 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#11437 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11435 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S
