Repository knative/serving, pull requests merged in 2021-02, with the labels that each got.

#10666 Use consistent alias for autoscaler v1alpha1 everywhere
  cmd/autoscaler/main.go
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
  pkg/autoscaler/scaling/multiscaler.go
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/resources/decider.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/autoscaling/reconciler.go
  pkg/reconciler/autoscaling/resources/sks.go
  pkg/reconciler/autoscaling/resources/sks_test.go
  pkg/reconciler/metric/metric_test.go
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/resources/pa.go
  pkg/reconciler/revision/resources/pa_test.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/testing/v1/listers.go
  pkg/resources/scale.go
  pkg/testing/functional.go
  test/performance/benchmarks/deployment-probe/continuous/main.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/L

#10669 Remove the service name from the internal traffic target object.
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#10671 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10670 Perform some test helper cleanup
  pkg/testing/v1/revision.go
  test/conformance/api/v1/route_test.go
  test/v1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10673 Allow kpa to work with timeout in context
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  pkg/resources/scale.go
  pkg/resources/scale_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#10675 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10677 Use lister instead of client to directly get ClusterDomainClaim
  pkg/reconciler/domainmapping/controller.go
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/table_test.go
  pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/clusterdomainclaim/clusterdomainclaim.go
  vendor/modules.txt
Labels: approved, area/API, cla: yes, lgtm, size/M

#10685 Temporarily disable auto TLS test with HTTP01 challenge
  test/e2e-auto-tls-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10682 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#10679 Improve debuggability of SKS logs
  pkg/reconciler/serverlessservice/serverlessservice.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#10684 Remove the unsed struct items
  pkg/activator/net/throttler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#10672 Allow to specify build platform for test images
  test/README.md
  test/upload-test-images.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#10678 Remove various vestiges and single use helpers
  pkg/testing/v1/configuration.go
  pkg/testing/v1/service.go
  test/conformance/api/v1/blue_green_test.go
  test/conformance/api/v1/configuration_test.go
  test/conformance/api/v1/generatename_test.go
  test/conformance/api/v1/resources_test.go
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/service_test.go
  test/conformance/api/v1/single_threaded_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#10687 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10683 Move TestServiceCreateWithMultipleContainers test to Beta
  test/conformance/api/v1/service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10691 Avoid adding gzip-encoding to requests implicitly
  cmd/activator/main.go
  cmd/queue/main.go
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10655 Unpin the istio version and temporarily disable the error rate check analyzer
  test/performance/benchmarks/load-test/continuous/sla.go
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10686 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/L

#10676 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10698 [Automated] Format markdown
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10696 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10697 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#10674 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10695 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10702 Some nits in e2e test error reporting
  test/e2e/e2e.go
Labels: approved, area/autoscale, area/test-and-release, cla: yes, lgtm, size/XS

#10699 bump k8s min in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#10704 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10705 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10700 Apply k8s default values for readiness probe
  pkg/apis/serving/v1/revision_defaults.go
  pkg/apis/serving/v1/revision_defaults_test.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/M

#10709 Fix the analyzer config for load-testing benchmark since it must have a value
  test/performance/benchmarks/load-test/continuous/sla.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10713 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#10706 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10719 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/go.opencensus.io/.travis.yml
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/go.opencensus.io/metric/metricexport/reader.go
  vendor/go.opencensus.io/trace/basetypes.go
  vendor/go.opencensus.io/trace/spanstore.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/go.opencensus.io/trace/trace_api.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/SECURITY.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_util.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/internal/grpcutil/target.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/resolver/config_selector.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#10715 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10720 Optimize the execution path around logging
  pkg/reconciler/route/traffic/rollout.go
  pkg/reconciler/route/traffic/rollout_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10722 Split the reconcile rollout into its own function
  pkg/reconciler/route/reconcile_resources.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#10725 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10723 Fix the logic to delete kail log files if the tests pass
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10724 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10728 Accept 'head' as a parameter for istio version
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10730 Also log the actual diff for easier debugging
  pkg/reconciler/route/reconcile_resources_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10731 Start moving towards k8s standard `Clock` object
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#10732 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/stats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10729 Avoid deleting a stat if a request raced the reporter
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10733 Only log about service scraping on first transition.
  pkg/autoscaler/metrics/stats_scraper.go
Labels: approved, area/autoscale, cla: yes, lgtm, ok-to-test, size/XS

#10727 Drop jwt dependency and match token via regex
  go.mod
  test/conformance/api/v1/volumes_test.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#10735 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10716 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10734 Guarantee that incoming and outgoing request are measured by the same stat
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10739 Refactor: remove labeler v2 package
  pkg/reconciler/labeler/accessors.go
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/labeler_test.go
  pkg/reconciler/labeler/metasync.go
  pkg/reconciler/service/resources/configuration.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10736 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10742 Restrict the Clock interface to the passive where possible.
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_helpers_test.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/controller.go
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/gc/v2/gc_test.go
  pkg/reconciler/labeler/accessors.go
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/labeler/labeler_test.go
  pkg/reconciler/revision/table_test.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#10743 Change interface to accept time rather than clock
  pkg/apis/serving/v1/revision_helpers.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/labeler/accessors.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#10744 Remove the `test` helper since there's just a single GC v2 now.
  pkg/reconciler/configuration/configuration_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#10745 Deep cleaning of the time manipulation in config and revision and other fixes to the codebase
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_helpers_test.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/gc/v2/gc_test.go
  pkg/reconciler/service/service_test.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#10746 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#10748 [RELEASE-0.20] Avoid deleting a stat if a request raced the reporter
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10737 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10753 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10752 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10754 Relax the grace period minival vaue to be any positive value
  config/core/configmaps/autoscaler.yaml
  pkg/autoscaler/config/config.go
  pkg/autoscaler/config/config_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#10755 Hide the things that are private now in effect
  pkg/reconciler/labeler/accessors.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/labeler/metasync.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10757 Update the docs for the traffic package.
  pkg/reconciler/route/traffic/doc.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10756 Clean up the code in the service test
  pkg/reconciler/service/service_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10758 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#10762 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10760 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10768 Remove v2 gc folder. There can be only one.
  pkg/reconciler/gc/gc.go
  pkg/reconciler/gc/gc_test.go
  pkg/reconciler/gc/reconciler.go
  pkg/reconciler/gc/reconciler_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10761 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10759 Resume HTTP01 challenge E2E tests
  test/e2e-auto-tls-tests.sh
  test/e2e/autotls/config/dnssetup/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#10774 Temporarily disable HTTP01 E2E tests
  test/e2e-auto-tls-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10775 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10766 Refactor scrape client to actually take an HTTP request
  pkg/autoscaler/metrics/http_scrape_client.go
  pkg/autoscaler/metrics/http_scrape_client_test.go
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#10778 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/L

#10779 Fix up health state tests
  pkg/queue/health/health_state.go
  pkg/queue/health/health_state_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#10777 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#10780 A few touchups around the autoscaling tests
  test/e2e/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10781 Fix race in health state
  cmd/queue/main.go
  pkg/queue/health/health_state.go
  pkg/queue/health/health_state_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10784 Unexport some methods
  pkg/queue/health/health_state.go
  pkg/queue/health/health_state_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#10782 Drop outdated HPA code regarding concurrency and RPS
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/autoscaling/hpa/resources/hpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#10785 We removed the possibility of traffic target % being nil
  pkg/reconciler/route/traffic/traffic.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10786 Monday off cleanup: minor brush up of the traffic.go
  pkg/reconciler/route/traffic/traffic.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10787 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#10788 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10789 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10790 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10794 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#10797 Remove the last check for percentage to be nil (which it can't anymore).
  pkg/reconciler/route/traffic/traffic.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#10796 Reflow the code to follow a better builder pattern.
  pkg/reconciler/route/traffic/traffic.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10798 Validate domain mapping is not a cluster local name
  pkg/apis/serving/v1alpha1/domainmapping_validation.go
  pkg/apis/serving/v1alpha1/domainmapping_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#10799 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10800 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10801 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10804 Remove outdated todo's
  pkg/reconciler/route/traffic/traffic.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#10807 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10811 swap path for domainmapping kingress for kourier
  pkg/reconciler/domainmapping/resources/ingress.go
  pkg/reconciler/domainmapping/resources/ingress_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10813 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10806 Update docs for revision timeoutSeconds field
  pkg/apis/serving/v1/revision_types.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#10793 Remove unused TimeoutFunc stuff and revert to simple duration
  cmd/queue/main.go
  pkg/http/handler/timeout.go
  pkg/http/handler/timeout_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10803 Implement exponential decay algorithm for average computation
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#10817 Remove the User-Agent inline constant with standard constant from pkg
  pkg/activator/handler/healthz_handler_test.go
  pkg/autoscaler/statserver/server_test.go
  pkg/http/proxy.go
  pkg/http/proxy_test.go
  pkg/queue/health/probe_test.go
  test/test_images/runtime/handlers/handler.go
Labels: approved, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#10827 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10829 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10830 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10828 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10808 Drop some label constraints for our top level resources
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/configuration_validation_test.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
  pkg/apis/serving/v1/service_validation.go
  pkg/apis/serving/v1/service_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#10823 Brush up the test to avoid redundant work
  pkg/queue/health/probe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10831 Switch single item switch statements to if statements
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/XS

#10832 Make Route table_test more palatable
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#10833 Fix the helpers in the service to be more readable.
  pkg/reconciler/route/resources/service.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10824 Add the same decoding Revision logic to request_log as context_handler
  cmd/activator/request_log.go
  cmd/activator/request_log_test.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/context.go
  pkg/activator/handler/context_handler.go
  pkg/activator/handler/context_handler_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, needs-ok-to-test, size/M

#10834 Backfill some test coverage for service validation
  pkg/apis/serving/v1/service_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10836 Use Revision from context in request log
  cmd/activator/main.go
  cmd/activator/request_log.go
  cmd/activator/request_log_test.go
  pkg/activator/handler/context.go
  pkg/activator/handler/context_handler.go
  pkg/activator/handler/context_handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#10839 More deep cleaning of the Route reconciler it needed for some time.
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/route_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#10809 bump k8s versions for kind e2e
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/M

#10820 Fix KeepAlives for HTTPProbe
  pkg/queue/health/probe.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, ok-to-test, size/XS

#10837 Relax annotation constraints & some cleanup
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/service_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10843 Update the setup of HTTP01 challenge tests
  test/config/autotls/certmanager/http01/issuer.yaml
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10840 Add the annotation for averaging algorithm selection.
  pkg/apis/autoscaling/register.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#10842 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10849 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10846 Add algorithm possible values and annotation validation.
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/metric_types.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#10853 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/L

#10847 Don't validate autoscaling annotations where they're not allowed
  pkg/apis/autoscaling/v1alpha1/metric_validation.go
  pkg/apis/autoscaling/v1alpha1/pa_validation.go
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/service_validation.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#10850 Thread the metric aggregation algorithm through collector.
  pkg/apis/autoscaling/v1alpha1/metric_types.go
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/L

#10628 Introduces h2c auto-detection support in health prober
  cmd/queue/main.go
  config/core/configmaps/features.yaml
  go.mod
  pkg/apis/config/features.go
  pkg/queue/health/probe.go
  pkg/queue/health/probe_test.go
  pkg/queue/readiness/probe.go
  pkg/queue/readiness/probe_test.go
  pkg/reconciler/revision/resources/queue.go
  vendor/modules.txt
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/L
