Repository knative/serving, pull requests merged in 2021-04, with the labels that each got.

#11093 Add leeway for deployment rollouts in autoscale upgrade tests
  test/e2e/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#11095 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11096 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11068 preparation for Revision api change
  pkg/apis/serving/v1/revision_types.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#11104 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11031 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/M

#11108 Redo 10615 - add UID labels
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#11114 dont add labels with empty values
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#11119 Expand support rotation
  support/support.rotation
Labels: approved, cla: yes, lgtm, size/S

#11038 Revision return replicas
  config/core/300-resources/revision.yaml
  go.mod
  go.sum
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  test/e2e/minscale_readiness_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#11123 Use similar rollout check to kubectl in autoscale test
  test/e2e/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#11129 Remove JRBANCEL from support rotation.
  support/COMMUNITY_CONTACTS.md
  support/support.rotation
Labels: approved, cla: yes, lgtm, size/XS

#11130 Drop extra revision check from MinScale test
  test/e2e/minscale_readiness_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11127 run kind e2e in release branches
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11103 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
  cmd/activator/OWNERS
  cmd/autoscaler-hpa/OWNERS
  cmd/autoscaler/OWNERS
  cmd/controller/OWNERS
  cmd/networking/OWNERS
  cmd/queue/OWNERS
  cmd/webhook/OWNERS
  config/OWNERS
  docs/scaling/OWNERS
  hack/OWNERS
  pkg/activator/OWNERS
  pkg/apis/OWNERS
  pkg/apis/autoscaling/OWNERS
  pkg/autoscaler/OWNERS
  pkg/deployment/OWNERS
  pkg/gc/OWNERS
  pkg/http/OWNERS
  pkg/leaderelection/OWNERS
  pkg/logging/OWNERS
  pkg/metrics/OWNERS
  pkg/queue/OWNERS
  pkg/reconciler/OWNERS
  pkg/reconciler/autoscaling/OWNERS
  pkg/reconciler/nscert/OWNERS
  pkg/reconciler/route/OWNERS
  pkg/resources/OWNERS
  pkg/testing/OWNERS
  pkg/webhook/OWNERS
  test/OWNERS
  third_party/OWNERS
Labels: approved, area/API, area/autoscale, area/monitoring, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#11131 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/M

#11141 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#11052 Thread network config into the activator
  pkg/activator/config/store.go
  pkg/activator/config/store_test.go
  pkg/activator/config/zz_generated.deepcopy.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/tracing_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#11143 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11145 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11144 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11156 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11158 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11157 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11163 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11164 Fix a few wrong logs in tests and make them consistent
  pkg/autoscaler/metrics/stats_scraper_test.go
  pkg/reconciler/accessor/networking/certificate_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#11162 Override Host in activator's main handler if option is set
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#11165 Cleanup deepcopygen annotations and calls
  hack/update-codegen.sh
  pkg/activator/config/doc.go
  pkg/activator/config/store.go
  pkg/activator/config/zz_generated.deepcopy.go
  pkg/autoscaler/config/autoscalerconfig/autoscalerconfig.go
  pkg/gc/zz_generated.deepcopy_test.go
  pkg/reconciler/autoscaling/config/doc.go
  pkg/reconciler/autoscaling/config/store.go
  pkg/reconciler/configuration/config/doc.go
  pkg/reconciler/configuration/config/store.go
  pkg/reconciler/nscert/config/store.go
  pkg/reconciler/revision/config/doc.go
  pkg/reconciler/revision/config/store.go
  pkg/reconciler/revision/config/zz_generated.deepcopy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#11166 Update the CLUSTER_DOMAIN in the right file
  test/e2e-networking-library.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11168 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/state.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/state.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/state.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/state.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/state.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/state.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/state.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11173 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11161 Connect the networking config with stats scraping
  cmd/autoscaler/main.go
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S

#11174 Be more discerning about which errors cause mesh fall-back
  pkg/autoscaler/metrics/http_scrape_client.go
  pkg/autoscaler/metrics/http_scrape_client_test.go
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#11149 Subdomain url from traffic status
  test/conformance/api/v1/service_test.go
  test/conformance/api/v1/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11176 Add a private service name helper and use throughout
  pkg/activator/handler/handler.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/serverlessservice/resources/names/names.go
  pkg/reconciler/serverlessservice/resources/names/names_test.go
  pkg/reconciler/serverlessservice/resources/services.go
  pkg/reconciler/serverlessservice/resources/services_test.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/testing/functional.go
Labels: approved, area/API, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#11172 Use passthrough loadbalancing in activator state keeping
  cmd/activator/main.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#11169 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11179 Move comment above referenced code
  pkg/activator/net/revision_backends.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#11177 Don't require ActivatorOverloadTest to scale to 0
  test/e2e/activator_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11178 Remove private service listing
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  test/e2e/autoscale_test.go
Labels: approved, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#11185 Revert "Thread network config into the autoscaler (#11056)"
  pkg/reconciler/autoscaling/config/store.go
  pkg/reconciler/autoscaling/config/store_test.go
  pkg/reconciler/autoscaling/config/testdata/config-network.yaml
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#11186 Add test for existing queue probe behaviour
  pkg/queue/health/health_state_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#11167 fix broken link
  docs/spec/errors.md
Labels: approved, cla: yes, lgtm, size/XS

#11181 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11187 bump kind e2e to use go1.15
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11204 Fix couple of nits in scale tests
  test/conformance/runtime/container_test.go
  test/e2e/scale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11191 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11063 Add specific port to instruct istio to open correct listener
  pkg/reconciler/serverlessservice/resources/services.go
  pkg/reconciler/serverlessservice/resources/services_test.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#11202 Excluse domainmapping-webhook from chaos
  test/config/chaosduck.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10590 Set useragent for digest resolver
  pkg/reconciler/revision/controller.go
  pkg/reconciler/revision/resolve.go
  pkg/reconciler/revision/resolve_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#11206 Force ci gke cluster to be 1.18 until we figure out 1.19 failures
  test/e2e-auto-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10693 Add addressable-resolver role for serving controller
  config/core/200-roles/addressable-resolvers-clusterrole.yaml
  config/core/200-serviceaccount.yaml
Labels: approved, cla: yes, lgtm, size/M

#11213 Replace all copies of autoscaling annotations with constants
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  test/e2e/scale.go
  test/performance/benchmarks/rollout-probe/continuous/main.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/S

#11182 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11189 Don't hardcode replica count in the Activator HA test
  test/ha/activator_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11184 Statically configure passthrough lb in the activator
  cmd/activator/main.go
  pkg/activator/config/store.go
  pkg/activator/config/store_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/main_test.go
  pkg/activator/handler/tracing_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#11203 Fix activator index update log
  pkg/activator/net/throttler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#11180 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11217 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11209 Allow for more overscale in tests if the deployment is being rolled
  test/e2e/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11221 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11224 Drop unnecessary parsing from/to string in probe
  cmd/queue/execprobe.go
  cmd/queue/execprobe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#11220 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11219 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11230 drop unused e2e test flag
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11227 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#11229 don't use vendor in ko:// path
  config/post-install/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11234 Use new helper to detect potential mesh errors
  go.mod
  go.sum
  pkg/autoscaler/metrics/http_scrape_client.go
  pkg/autoscaler/metrics/http_scrape_client_test.go
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, area/autoscale, cla: yes, lgtm, size/L

#11232 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11233 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11235 Use OnDeletionInterface to drop potentially racy direct usages of DeleteFunc
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/metric/controller.go
  pkg/reconciler/metric/metric.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/revision/revision.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#11240 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11241 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11242 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11214 don't specify patch and build for gke version
  test/e2e-auto-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#11238 Add API doc generation to codegen
  docs/serving-api.md
  go.mod
  go.sum
  hack/reference-docs-gen-config.json
  hack/tools.go
  hack/update-codegen.sh
  hack/update-reference-docs.sh
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.gitignore
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.goreleaser.yml
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.travis.yml
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/LICENSE
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/README.md
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/example-config.json
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/go.mod
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/go.sum
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/main.go
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/template/members.tpl
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/template/pkg.tpl
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/template/placeholder.go
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/template/type.tpl
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/go.mod
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/github.com/shurcooL/sanitized_anchor_name/.travis.yml
  vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  vendor/github.com/shurcooL/sanitized_anchor_name/README.md
  vendor/github.com/shurcooL/sanitized_anchor_name/go.mod
  vendor/github.com/shurcooL/sanitized_anchor_name/main.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#11246 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11249 Lower the drain sleep in queue-proxy to previous value
  cmd/queue/main.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#11252 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#11208 Don't fall back to cluster IP when error is not mesh-related
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#11260 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11262 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11263 Add myself to support rotation of 04-26
  support/support.rotation
Labels: approved, cla: yes, lgtm, size/XS

#11264 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11254 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11255 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11247 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11253 Update visibility label comment in config-domain
  config/core/configmaps/domain.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11256 Actually use the rate limited queue
  pkg/reconciler/revision/background.go
  pkg/reconciler/revision/background_test.go
  pkg/reconciler/revision/controller.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#11266 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11268 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11269 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#11271 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#11265 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11272 Only print deployment state in error cases
  test/e2e/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11140 Make sure deployments never underscale on rollouts
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#11273 Use non-pointer workItem in digest resolution
  pkg/reconciler/revision/background.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#11277 Drop ingressClass and certificateClass flags from serving test
  test/README.md
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#11274 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11275 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11280 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11281 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11267 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11244 Add complete schemas to all CRDs
  config/core/300-resources/configuration.yaml
  config/core/300-resources/metric.yaml
  config/core/300-resources/podautoscaler.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/route.yaml
  config/core/300-resources/service.yaml
  hack/update-schemas.sh
  pkg/apis/serving/v1/revision_types.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XXL

#11278 Implement per-item rate limits for digest resolution
  pkg/reconciler/revision/background.go
  pkg/reconciler/revision/background_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#11284 Make KO_FLAGS flexible for e2e-tests
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#11285 remove duplicate additionalPrinterColumns
  config/core/300-resources/metric.yaml
Labels: approved, cla: yes, lgtm, size/XS
