Repository knative/serving, pull requests merged in 2021-07, with the labels that each got.

#11612 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#11613 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/S

#11614 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11619 Remove unused varlog and observed-concurrency images
  test/test_images/observed-concurrency/README.md
  test/test_images/observed-concurrency/observed_concurrency.go
  test/test_images/observed-concurrency/service.yaml
  test/test_images/varlog/service.yaml
  test/test_images/varlog/varlog.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11620 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11616 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11628 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11615 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11627 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11622 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11631 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#11632 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11606 Allow setting runAsNotRoot without the feature flag
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/XS

#11633 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11637 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11639 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11630 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11642 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11641 Remove dead code for scale-to-zero
  test/conformance/api/v1/revision_timeout_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#11649 Use lister to get ClusterDomainClaim
  pkg/reconciler/domainmapping/reconciler.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#11646 Update comment line for config store
  pkg/reconciler/nscert/config/store.go
  pkg/reconciler/route/config/store.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/XS

#11654 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#11638 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11609 Allow for running conformance tests by users with reduced privileges
  test/README.md
  test/config/ytt/core/cluster-resources.yaml
  test/config/ytt/core/conformance-resources.yaml
  test/conformance.go
  test/conformance/api/shared/util.go
  test/conformance/api/v1/volumes_test.go
  test/e2e-common.sh
  test/e2e/autoscale.go
  test/e2e/autoscale_hpa_test.go
  test/e2e/autoscale_test.go
  test/e2e/autotls/auto_tls_test.go
  test/e2e/autotls/config/disablenscert/main.go
  test/e2e/autotls/domain_mapping_test.go
  test/e2e/destroypod_test.go
  test/e2e/domainmapping/domain_mapping_test.go
  test/e2e/e2e.go
  test/e2e/initial_scale_test.go
  test/e2e/minscale_readiness_test.go
  test/e2e/namespace_test.go
  test/e2e/subroutes_test.go
  test/e2e_constants.go
  test/e2e_flags.go
  test/ha/activator_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11651 Use more specific error when Domain Claim does not exist
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#11656 Remove the unused flag reuse-test-namespace
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11648 Use tmpfs for etcd storage in Kind-e2e
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#11658 Drop the use of serving specific metric keys declared in knative.dev/pkg
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/metric_handler_test.go
  pkg/activator/handler/metrics.go
  pkg/autoscaler/scaling/autoscaler_test.go
  pkg/metrics/key.go
  pkg/metrics/tags.go
  pkg/metrics/tags_test.go
  pkg/queue/request_metric.go
  pkg/queue/request_metric_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, area/monitoring, area/networking, cla: yes, lgtm, size/L

#11659 drop stackdriver exporter support
  cmd/queue/main.go
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
  pkg/metrics/config_test.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, area/autoscale, area/monitoring, area/networking, cla: yes, lgtm, size/L

#11660 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/gobuffalo/flect/plural_rules.go
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/buffered_write_syncer.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/typeparams/doc.go
  vendor/golang.org/x/tools/internal/typeparams/notypeparams.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#11643 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/M

#11667 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11666 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11665 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11657 allow conformance test setup to be done without ytt
  test/README.md
  test/config/chaosduck/chaosduck.yaml
  test/config/cluster-resources.yaml
  test/config/test-resources.yaml
  test/config/ytt/core/cluster-resources.yaml
  test/config/ytt/core/overlay-serving-namespace.yaml
  test/config/ytt/overlay-system-namespace.yaml
  test/config/ytt/rename-namespaces.yaml
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11678 Fix order of parameters in conformance README
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11675 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11676 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11677 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11679 drop use of knative.dev/pkg metricskey in tests
  pkg/metrics/key.go
  pkg/metrics/tags_test.go
Labels: approved, area/monitoring, cla: yes, lgtm, size/M

#11683 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11684 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11685 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11669 Add support for emptyDir volume type
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  config/core/configmaps/features.yaml
  hack/schemapatch-config.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/reconciler/route/resources/service_test.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#11689 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11690 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11691 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11697 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11696 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11700 add tests for kubernetes.containerspec-addcapabilities feature flag
  pkg/apis/config/features_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#11702 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11703 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11704 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11701 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#11707 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11711 drop duplicate test
  pkg/metrics/config_test.go
Labels: approved, area/monitoring, cla: yes, lgtm, size/L

#11698 Bump to Go 1.16
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#11655 Add `app.kubernetes.io` labels
  config/core/100-namespace.yaml
  config/core/200-roles/addressable-resolvers-clusterrole.yaml
  config/core/200-roles/clusterrole-namespaced.yaml
  config/core/200-roles/clusterrole.yaml
  config/core/200-roles/podspecable-bindings-clusterrole.yaml
  config/core/200-serviceaccount.yaml
  config/core/999-cache.yaml
  config/core/configmaps/autoscaler.yaml
  config/core/configmaps/defaults.yaml
  config/core/configmaps/deployment.yaml
  config/core/configmaps/domain.yaml
  config/core/configmaps/features.yaml
  config/core/configmaps/gc.yaml
  config/core/configmaps/leader-election.yaml
  config/core/configmaps/logging.yaml
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
  config/core/deployments/activator-hpa.yaml
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
  config/core/deployments/domainmapping-webhook.yaml
  config/core/deployments/webhook-hpa.yaml
  config/core/deployments/webhook.yaml
  config/core/webhooks/configmap-validation.yaml
  config/core/webhooks/defaulting.yaml
  config/core/webhooks/domainmapping-validation.yaml
  config/core/webhooks/resource-validation.yaml
  config/core/webhooks/secret.yaml
  config/hpa-autoscaling/controller.yaml
  config/namespace-wildcard-certs/200-clusterrole.yaml
  config/namespace-wildcard-certs/controller.yaml
  config/post-install/default-domain.yaml
  config/post-install/storage-version-migration.yaml
  hack/README.md
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11705 Add support for emptydir rw access and e2e testing
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/apis/serving/v1/revision_defaults.go
  test/conformance.go
  test/e2e-tests.sh
  test/e2e/emptydir_test.go
  test/test_images/emptydir/emptydir.go
  test/test_images/emptydir/service.yaml
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#11682 Add v1beta1 version of DomainMapping crd
  cmd/domain-mapping-webhook/main.go
  config/core/300-resources/domain-mapping.yaml
  config/core/webhooks/domainmapping-defaulting.yaml
  config/core/webhooks/domainmapping-validation.yaml
  docs/serving-api.md
  hack/update-codegen.sh
  pkg/apis/serving/v1beta1/README.md
  pkg/apis/serving/v1beta1/conversion_error.go
  pkg/apis/serving/v1beta1/conversion_error_test.go
  pkg/apis/serving/v1beta1/doc.go
  pkg/apis/serving/v1beta1/domainmapping_defaults.go
  pkg/apis/serving/v1beta1/domainmapping_defaults_test.go
  pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  pkg/apis/serving/v1beta1/domainmapping_lifecycle_test.go
  pkg/apis/serving/v1beta1/domainmapping_types.go
  pkg/apis/serving/v1beta1/domainmapping_types_test.go
  pkg/apis/serving/v1beta1/domainmapping_validation.go
  pkg/apis/serving/v1beta1/domainmapping_validation_test.go
  pkg/apis/serving/v1beta1/register.go
  pkg/apis/serving/v1beta1/register_test.go
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/doc.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/domainmapping.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/fake/fake_domainmapping.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/fake/fake_serving_client.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/serving_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/serving/interface.go
  pkg/client/informers/externalversions/serving/v1beta1/domainmapping.go
  pkg/client/informers/externalversions/serving/v1beta1/interface.go
  pkg/client/injection/informers/serving/v1beta1/domainmapping/domainmapping.go
  pkg/client/injection/informers/serving/v1beta1/domainmapping/fake/fake.go
  pkg/client/injection/informers/serving/v1beta1/domainmapping/filtered/domainmapping.go
  pkg/client/injection/informers/serving/v1beta1/domainmapping/filtered/fake/fake.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/controller.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/state.go
  pkg/client/listers/serving/v1beta1/domainmapping.go
  pkg/client/listers/serving/v1beta1/expansion_generated.go
  test/clients.go
  test/conformance/api/v1beta1/domain_mapping_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/XXL

#11714 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11715 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11716 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11713 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#11718 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#11719 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11720 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11726 Add limits and proper security context to jobs
  config/post-install/default-domain.yaml
  config/post-install/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/S

#11727 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11731 Correct typo in a few places and include error in log
  cmd/autoscaler/main.go
  pkg/autoscaler/bucket/bucket.go
  pkg/autoscaler/statforwarder/leases.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#11723 Allow setting spec.template.spec.automountServiceAccountToken in PodSpec
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  hack/schemapatch-config.yaml
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/k8s_validation_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/S

#11744 Use io and os packages in preference to ioutil
  cmd/queue/execprobe.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/main_test.go
  pkg/apis/config/defaults.go
  pkg/autoscaler/metrics/http_scrape_client_test.go
  pkg/http/request_log_test.go
  pkg/logging/sync_file_writer_test.go
  pkg/queue/health/probe.go
  pkg/queue/protobuf_stats_reporter_test.go
  pkg/reconciler/revision/resolve.go
  pkg/reconciler/revision/resolve_test.go
  test/e2e/autotls/config/util.go
  test/e2e/autotls/util_test.go
  test/e2e/websocket.go
  test/performance/benchmarks/deployment-probe/continuous/main.go
  test/test_images/emptydir/emptydir.go
  test/test_images/hellovolume/hellovolume.go
  test/test_images/multicontainer/servingcontainer/servingcontainer.go
  test/test_images/runtime/handlers/cgroup.go
  test/test_images/runtime/handlers/file_access_attempt.go
Labels: approved, area/API, area/autoscale, area/monitoring, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#11743 Adding test for automountServiceAccountToken=true
  pkg/apis/serving/k8s_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#11739 Adding section to DEVELOPMENT.md on updating schemas when iterating
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#11750 Change label and annotation key names in tests from camelCase to lowercase with dash
  test/conformance/api/v1/configuration_test.go
  test/conformance/api/v1/service_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#11740 Use update API instead of patch API in conformance tests
  pkg/testing/v1/service.go
  test/conformance/api/v1/blue_green_test.go
  test/conformance/api/v1/service_test.go
  test/e2e/autotls/auto_tls_test.go
  test/e2e/subroutes_test.go
  test/e2e/tagheader/tag_header_based_routing_test.go
  test/e2e/websocket_test.go
  test/upgrade/postupgrade.go
  test/v1/service.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#11746 Allow setting priorityClassName in pod spec
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/table_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, ok-to-test, size/L
