Repository knative/serving, pull requests merged in 2021-01, with the labels that each got.

#10463 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10465 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10466 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10464 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10473 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10366 Only upload the kail log file when the e2e test flow fails
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10472 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#10471 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10474 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10476 Reduce the stable window for autoscaling tests.
  test/e2e/autoscale.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10216 Migrate upgrade tests to the new framework
  hack/generate-yamls.sh
  test/e2e-common.sh
  test/e2e-networking-library.sh
  test/e2e-upgrade-tests.sh
  test/e2e/autoscale.go
  test/e2e/autoscale_test.go
  test/e2e/grpc_test.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
  test/ha/autoscaler_test.go
  test/prober.go
  test/upgrade/README.md
  test/upgrade/autoscaler.go
  test/upgrade/autoscaler_test.go
  test/upgrade/continual.go
  test/upgrade/installation/shell.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
  test/upgrade/probe.go
  test/upgrade/probe_test.go
  test/upgrade/upgrade.go
  test/upgrade/upgrade_test.go
  third_party/VENDOR-LICENSE/knative.dev/hack/shell/LICENSE
  vendor/knative.dev/hack/shell/executor.go
  vendor/knative.dev/hack/shell/fail-example.sh
  vendor/knative.dev/hack/shell/prefixer.go
  vendor/knative.dev/hack/shell/project.go
  vendor/knative.dev/hack/shell/types.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/knative.dev/pkg/test/upgrade/vars.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#10479 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10480 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10481 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10467 Add reconciler logic for DomainMapping AutoTLS
  pkg/reconciler/domainmapping/controller.go
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/reconciler_test.go
  pkg/reconciler/domainmapping/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/XL

#10484 Patch config-istio after the configmap is actually created
  test/e2e-networking-library.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10478 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#10485 Optimize the get by tag to use binary search
  pkg/reconciler/route/traffic/rollout.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10487 Fallback to HTTP if allowed when Certificate isn't Ready
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/table_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10488 update podIPTrackers to podTrackers in comments for it has been renamed in code
  pkg/activator/net/throttler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, ok-to-test, size/XS

#10493 Update COMMUNITY_CONTACTS.md
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#10489 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10491 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10494 Remove broken observability links.
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#10448 Propagate and keep w3c header up to date
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/activator/handler/handler.go
  test/conformance/runtime/header_test.go
Labels: approved, area/autoscale, area/networking, area/test-and-release, cla: yes, lgtm, size/XS

#10497 [Automated] Format markdown
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#10496 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#10495 Match the progress deadline to that of k8s
  .github/workflows/kind-e2e.yaml
  config/core/configmaps/deployment.yaml
  pkg/deployment/config.go
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10498 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10501 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10502 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10504 Use pointers rather than values for rollouts for configs
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/traffic/rollout.go
  pkg/reconciler/route/traffic/rollout_test.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, ok-to-test, size/L

#10500 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10508 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10510 Swap weeks with vagababov
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#10509 Use test/config for test setup.
  .github/workflows/kind-e2e.yaml
  test/config/config-deployment.yaml
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#10506 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10490 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10507 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#10514 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10513 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#10515 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10512 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10522 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10523 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/XS

#10518 Report first and second revision metrics separately and deleted old rev.
  test/performance/benchmarks/rollout-probe/continuous/main.go
  test/performance/benchmarks/rollout-probe/dev.config
  test/performance/metrics/runtime.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#10531 Improve performance a bit by using binary search
  pkg/reconciler/route/resources/ingress.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10524 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10532 Ensure step size is validated and add tests
  pkg/reconciler/route/traffic/rollout.go
  pkg/reconciler/route/traffic/rollout_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#10533 Sanitize probe header value before response
  pkg/activator/handler/probe_handler.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#10534 Remove backwards compatibility check in KPA
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/M

#10535 Simplify and optimise proxy header pruning
  cmd/queue/main.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/util/header.go
  pkg/activator/util/header_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/L

#10538 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10529 swap support dates with tcnghia
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#10542 Remove comment about recreation of the autoscaler pod in config-logging
  config/core/configmaps/logging.yaml
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, cla: yes, lgtm, size/XS

#10545 Use explicit revID parameter in Throttler
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#10543 Fix wrong file permission
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, cla: yes, lgtm, size/XS

#10548 Cut down queue-probe test time from 3s to .5s
  cmd/queue/execprobe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#10549 Un-export WithRevID, RevIDFrom, WithRevision, RevisionFrom
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/activator/handler/context.go
  pkg/activator/handler/context_handler.go
  pkg/activator/handler/context_handler_test.go
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/metric_handler.go
  pkg/activator/handler/metric_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10553 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10551 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10557 Remove activator/util package
  cmd/queue/main.go
  pkg/activator/activator.go
  pkg/activator/handler/handler.go
  pkg/http/proxy.go
  pkg/http/proxy_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10541 Move the functions that have only single use to the private package
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/revision_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#10558 Nits in the code formatting
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/service_validation.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#10559 Remove the old constant since the new one has been since August 2020
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/configuration_validation_test.go
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/service_validation.go
  pkg/reconciler/route/config/domain.go
  pkg/reconciler/route/config/domain_test.go
  pkg/reconciler/route/domains/domains.go
  pkg/reconciler/route/resources/filters.go
  pkg/reconciler/route/resources/labels/labels.go
  pkg/reconciler/route/resources/service.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/M

#10544 Shutdown processor to avoid log races
  pkg/autoscaler/statforwarder/processor_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#10562 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10555 Widen sleep for TestProbeQueueTimeout to harden it
  cmd/queue/execprobe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#10546 Cut down the probe test runtime from 18s to 3s
  pkg/queue/readiness/probe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#10556 Cut down queue health tests from 2s to basically nothing
  pkg/queue/health/probe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#10550 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10552 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10568 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#10564 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10565 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10569 Fixed comment about autoscaler logging config override
  config/core/configmaps/logging.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#10563 Be consistent in reading revision headers
  cmd/activator/request_log.go
  pkg/http/header.go
  pkg/http/header_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10570 Drop logger annotations
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/controller.go
  pkg/client/injection/reconciler/serving/v1/configuration/controller.go
  pkg/client/injection/reconciler/serving/v1/revision/controller.go
  pkg/client/injection/reconciler/serving/v1/route/controller.go
  pkg/client/injection/reconciler/serving/v1/service/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/controller.go
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/configuration/controller.go
  pkg/reconciler/gc/controller.go
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/logger.go
  pkg/reconciler/metric/controller.go
  pkg/reconciler/nscert/controller.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/service/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, ok-to-test, size/L

#10561 Add the new annotation for the rollout duration and its validation
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/service_validation.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10539 Add serviceUID/configUID labels to pods & deployments, serviceUID label to configs
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
  pkg/reconciler/service/resources/configuration.go
  pkg/reconciler/service/resources/configuration_test.go
  pkg/reconciler/service/resources/shared_test.go
  pkg/testing/v1/service.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/M

#10574 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#10560 Allow setting ReadOnlyRootFilesystem
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
Labels: approved, area/API, cla: yes, lgtm, ok-to-test, size/S

#10576 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10572 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10573 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10579 rename configUID to configurationUID to be consistent with the other labels
  pkg/apis/serving/register.go
Labels: approved, area/API, cla: yes, lgtm, size/XS

#10580 Use more consistent constant name
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#10577 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10581 Add validation to the route and service annotations for rollout duration
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
  pkg/apis/serving/v1/service_validation.go
  pkg/apis/serving/v1/service_validation_test.go
Labels: approved, area/API, cla: yes, lgtm, size/L

#10578 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10582 [] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/autoscaling/v1alpha1/metric/filtered/fake/fake.go
  pkg/client/injection/informers/autoscaling/v1alpha1/metric/filtered/metric.go
  pkg/client/injection/informers/autoscaling/v1alpha1/podautoscaler/filtered/fake/fake.go
  pkg/client/injection/informers/autoscaling/v1alpha1/podautoscaler/filtered/podautoscaler.go
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/serving/v1/configuration/filtered/configuration.go
  pkg/client/injection/informers/serving/v1/configuration/filtered/fake/fake.go
  pkg/client/injection/informers/serving/v1/revision/filtered/fake/fake.go
  pkg/client/injection/informers/serving/v1/revision/filtered/revision.go
  pkg/client/injection/informers/serving/v1/route/filtered/fake/fake.go
  pkg/client/injection/informers/serving/v1/route/filtered/route.go
  pkg/client/injection/informers/serving/v1/service/filtered/fake/fake.go
  pkg/client/injection/informers/serving/v1/service/filtered/service.go
  pkg/client/injection/informers/serving/v1alpha1/domainmapping/filtered/domainmapping.go
  pkg/client/injection/informers/serving/v1alpha1/domainmapping/filtered/fake/fake.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#10584 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10585 Backfill missing test
  pkg/activator/net/helpers_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/S

#10583 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10589 Don't propagate the rollout duration annotation to Configurations and Revisions
  pkg/reconciler/service/resources/configuration.go
  pkg/reconciler/service/resources/configuration_test.go
  pkg/reconciler/service/resources/route_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10592 Add an accessor to the route to get rollout duration
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/apis/serving/v1/route_lifecycle_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10593 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#10594 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10588 Remove the benchmarks that don't make much sense
  test/performance/benchmarks/rollout-probe/continuous/rollout-probe-setup.yaml
  test/performance/benchmarks/rollout-probe/continuous/rollout-probe.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#10595 Update documentation for DomainMapping ref field
  pkg/apis/serving/v1alpha1/domainmapping_types.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#10596 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10602 Add the code to use the annotation value, if provided, for rollout duration
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/reconcile_resources_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#10603 Add more tests to cover various durations.
  pkg/reconciler/route/reconcile_resources_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#10605 Make TestHTTPProbeTimeoutFailure more reliable
  pkg/queue/health/probe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#10606 Add julz to API reviewers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#10608 Replace arbitrary short sleeps with short-circuited long sleeps
  cmd/queue/execprobe_test.go
  pkg/queue/readiness/probe_test.go
  pkg/reconciler/revision/background_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10598 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10607 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10604 Remove some -1 here and there and compute it once.
  pkg/reconciler/route/traffic/rollout.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/S

#10609 Rever the 100ms to 1ms change, since it flakes a lot
  cmd/queue/execprobe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#10615 don't add the UID labels since it breaks downgrading
  pkg/reconciler/configuration/resources/revision.go
  pkg/reconciler/configuration/resources/revision_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10611 Improve test flow
  test/e2e/route_service_test.go
  test/e2e/service_validation_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#10610 Implement e2e test for the gradual rollout.
  test/e2e/rollout_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#10621 The year was 2021..
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/S

#10620 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/caching/pkg/client/listers/caching/v1alpha1/image.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/serverlessservice.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#10623 Fix some annoying nits in the route e2e tests
  test/e2e/route_service_test.go
  test/e2e/subroutes_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#10627 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#10624 Make the singlethreaded code simpler by using boolean guard
  test/e2e/subroutes_test.go
  test/test_images/singlethreaded/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10626 At 100ms we still see failures on prow
  cmd/queue/execprobe_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/XS

#10625 Improve rollout test to check duration
  test/e2e/rollout_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#10618 Remove naked returns
  pkg/activator/net/helpers.go
  pkg/activator/net/throttler.go
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/v1/configuration_validation.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/service_validation.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/testing/v1/factory.go
  pkg/resources/pods.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10629 chore: Set background to white for autoscaling diagrams ...
  docs/scaling/SYSTEM.md
  docs/scaling/images/scale-from-0.png
  docs/scaling/images/scale-to-0.png
  docs/scaling/images/scale-up-down.png
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#10599 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#10619 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10597 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10632 Remove the propagation from SKS->PA->Rev.Status of the K8s service
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/route/queueing_test.go
  pkg/reconciler/route/route_test.go
  pkg/testing/v1/revision.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/L

#10633 Deprecate the service name on the revision.
  pkg/apis/serving/v1/revision_types.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/testing/v1/revision.go
  test/e2e/autoscale_test.go
  test/e2e/e2e.go
Labels: approved, area/API, area/networking, area/test-and-release, cla: yes, lgtm, size/M

#10634 fix the broken doc's link
  test/performance/config/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#10637 Remove unused constants and make some other small tidy-ups
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_helpers_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#10635 Export MESH env value in test script
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10636 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#10631 Updating the HPAs to v2beta2 API usage
  config/core/deployments/activator-hpa.yaml
  config/core/deployments/webhook-hpa.yaml
Labels: approved, cla: yes, lgtm, size/M

#10638 Make route stop using the `DeprecatedServiceName` field
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
Labels: approved, area/API, area/networking, cla: yes, lgtm, size/L

#10643 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10644 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#10646 Do not pass context to the scale, but logger instead
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
  pkg/autoscaler/scaling/multiscaler.go
  pkg/autoscaler/scaling/multiscaler_test.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/M

#10645 Remove the time computation
  test/e2e/rollout_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#10647 Add support for decoding Revision from Host.
  pkg/activator/handler/context_handler.go
  pkg/activator/handler/context_handler_test.go
Labels: approved, area/autoscale, area/networking, cla: yes, lgtm, size/M

#10648 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#10652 Hide implementation detail inside a function
  pkg/autoscaler/scaling/multiscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#10654 Nitpicking for lunch: fix logging of errors in stats scraper
  pkg/autoscaler/metrics/stats_scraper.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/XS

#10653 Further remove usage of the context in the scale runner
  pkg/autoscaler/scaling/multiscaler.go
Labels: approved, area/autoscale, cla: yes, lgtm, size/S

#10657 Remove context from MakeDecider
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/resources/decider.go
  pkg/reconciler/autoscaling/kpa/resources/decider_test.go
Labels: approved, area/API, area/autoscale, cla: yes, lgtm, size/S
