Repository knative/serving, pull requests merged in 2021-11, with the labels that each got.

#12201 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12202 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#12204 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12205 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12211 update fetching the latest istio release
  test/e2e-common.sh
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#12210 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#12207 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#12220 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#12223 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12203 Tidy up probePodIPs a bit
  pkg/activator/net/revision_backends.go
Labels: size/M, lgtm, area/networking, area/autoscale, approved, cla: yes

#12222 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#12224 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12168 Freeze pod after startup if container-freezer enabled
  cmd/queue/main.go
  pkg/queue/concurrency_state.go
Labels: size/S, lgtm, area/networking, area/autoscale, approved, cla: yes

#12033 user pkg drain for draining in queue proxy
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/queue/health/handler.go
  pkg/queue/health/handler_test.go
  pkg/queue/health/health_state.go
  pkg/queue/health/health_state_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#12227 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#12208 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/M, lgtm, approved, cla: yes

#12233 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12234 Fix linting error from new version
  pkg/apis/autoscaling/register.go
Labels: area/API, size/XS, lgtm, area/autoscale, approved, cla: yes

#12225 Allow probes to explicitly set the port to the containerPort (#8288)
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/apis/serving/v1/revision_validation_test.go
Labels: area/API, size/L, lgtm, approved, ¯\_(ツ)_/¯, cla: yes

#12236 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12237 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#12229 Add requestLogHandler to user container as well as health check
  cmd/queue/main.go
Labels: size/XS, lgtm, area/networking, area/autoscale, approved, cla: yes

#12239 Tidy up comment and loop a bit
  pkg/apis/serving/k8s_validation.go
Labels: area/API, size/S, lgtm, approved, cla: yes

#12226 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#12228 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12232 Aligns the last istio-net version with serving
  test/e2e-common.sh
Labels: size/S, lgtm, approved, area/test-and-release, cla: yes, ok-to-test

#12240 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12155 Add init container defaults
  config/core/configmaps/defaults.yaml
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/apis/serving/v1/revision_defaults.go
  pkg/apis/serving/v1/revision_defaults_test.go
Labels: area/API, size/L, lgtm, approved, cla: yes, ok-to-test

#12245 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12243 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12247 Update k8s app labels
  config/core/100-namespace.yaml
  config/core/200-roles/addressable-resolvers-clusterrole.yaml
  config/core/200-roles/clusterrole-namespaced.yaml
  config/core/200-roles/clusterrole.yaml
  config/core/200-roles/podspecable-bindings-clusterrole.yaml
  config/core/200-serviceaccount.yaml
  config/core/300-resources/configuration.yaml
  config/core/300-resources/domain-mapping.yaml
  config/core/300-resources/metric.yaml
  config/core/300-resources/podautoscaler.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/route.yaml
  config/core/300-resources/service.yaml
  config/core/999-cache.yaml
  config/core/configmaps/autoscaler.yaml
  config/core/configmaps/defaults.yaml
  config/core/configmaps/deployment.yaml
  config/core/configmaps/domain.yaml
  config/core/configmaps/features.yaml
  config/core/configmaps/gc.yaml
  config/core/configmaps/leader-election.yaml
  config/core/configmaps/logging.yaml
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
  config/core/deployments/activator-hpa.yaml
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
  config/core/deployments/domainmapping-webhook.yaml
  config/core/deployments/webhook-hpa.yaml
  config/core/deployments/webhook.yaml
  config/core/webhooks/configmap-validation.yaml
  config/core/webhooks/defaulting.yaml
  config/core/webhooks/domainmapping-defaulting.yaml
  config/core/webhooks/domainmapping-secret.yaml
  config/core/webhooks/domainmapping-validation.yaml
  config/core/webhooks/resource-validation.yaml
  config/core/webhooks/secret.yaml
  config/hpa-autoscaling/controller.yaml
  config/post-install/default-domain.yaml
  config/post-install/storage-version-migration.yaml
Labels: size/L, lgtm, approved, cla: yes

#12248 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12251 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12253 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12254 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved, cla: yes

#12256 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/config/image.yaml
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12258 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/M, lgtm, approved, cla: yes

#12252 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12262 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12265 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12263 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12259 Drop goroutine leak test for statsserver
  go.mod
  go.sum
  pkg/autoscaler/statserver/server_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/glide.yaml
  vendor/go.uber.org/goleak/go.mod
  vendor/go.uber.org/goleak/go.sum
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/modules.txt
Labels: size/XL, lgtm, area/autoscale, approved, cla: yes

#12261 Drop unneeded if blocks from validation
  pkg/apis/serving/k8s_validation.go
Labels: area/API, size/XS, lgtm, approved, cla: yes

#12152 Support image resolution for init containers
  config/core/300-resources/revision.yaml
  docs/serving-api.md
  pkg/apis/serving/v1/revision_types.go
  pkg/apis/serving/v1/zz_generated.deepcopy.go
  pkg/reconciler/revision/background.go
  pkg/reconciler/revision/background_test.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/resources/imagecache_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/testing/v1/factory.go
  pkg/testing/v1/revision.go
  test/e2e/e2e.go
  test/e2e/image_pull_error_test.go
  test/e2e/initcontainers/initcontainers_test.go
  test/e2e/pod_schedule_error_test.go
Labels: area/API, size/L, lgtm, approved, area/test-and-release, cla: yes

#12250 Disable activator probe optimisation when exec probe is specified
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#12267 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved, cla: yes

#12271 [release-1.0] bump knative.dev/hack
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved, area/test-and-release, cla: yes

#12269 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12268 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12273 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12274 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12276 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12275 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12278 HPA v2beta2
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/autoscaling/hpa/resources/hpa_test.go
  pkg/reconciler/testing/v1/listers.go
  test/e2e/autoscale_hpa_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta2/horizontalpodautoscaler/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta2/horizontalpodautoscaler/horizontalpodautoscaler.go
  vendor/modules.txt
Labels: area/API, size/L, lgtm, area/autoscale, approved, area/test-and-release, cla: yes, ok-to-test

#12283 Fix TestRouteCreation to be consistent
  test/conformance/api/v1/route_test.go
Labels: size/S, lgtm, approved, area/test-and-release, cla: yes

#12284 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12285 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12291 use networking constants vs hardcoding
  pkg/reconciler/domainmapping/resources/certificate_test.go
  pkg/reconciler/domainmapping/resources/ingress_test.go
Labels: area/API, size/S, lgtm, approved, cla: yes

#12292 drop use of networking.DisableWildcardCertLabelKey
  pkg/reconciler/nscert/nscert_test.go
Labels: area/API, size/S, lgtm, area/networking, approved, cla: yes

#12293 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12297 Update comment referencing now-deleted exec probe
  pkg/reconciler/revision/resources/queue.go
Labels: area/API, size/XS, lgtm, approved, cla: yes

#12298 Drop now-unneeded unix socket from queue proxy
  cmd/queue/main.go
Labels: size/M, lgtm, area/networking, area/autoscale, approved, cla: yes

#12301 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12303 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, cla: yes

#12279 handling retries within pause/resume functions
  cmd/queue/main.go
  pkg/queue/concurrency_state.go
  pkg/queue/concurrency_state_test.go
Labels: size/M, lgtm, area/networking, area/autoscale, approved, cla: yes

#12304 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12302 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved, cla: yes

#12306 Drop myself from the support roster
  support/COMMUNITY_CONTACTS.md
  support/support.rotation
Labels: size/XS, lgtm, approved, cla: yes

#12305 Drop kong and ambassador from CI
  test/config/ytt/ingress/ambassador/ambassador-ingress-class.yaml
  test/config/ytt/ingress/ambassador/ambassador-replicas.yaml
  test/config/ytt/ingress/kong/kong-ingress-class.yaml
  test/config/ytt/ingress/kong/kong-replicas.yaml
  test/config/ytt/kind/ingress/ambassador-kind.yaml
  test/config/ytt/kind/ingress/kong-kind.yaml
  test/e2e-common.sh
  test/e2e-networking-library.sh
  third_party/ambassador-latest/README.md
  third_party/ambassador-latest/ambassador-crds.yaml
  third_party/ambassador-latest/ambassador-namespace.yaml
  third_party/ambassador-latest/ambassador-rbac.yaml
  third_party/ambassador-latest/ambassador-service.yaml
  third_party/kong-latest/README.md
  third_party/kong-latest/download-kong.sh
  third_party/kong-latest/kong.yaml
Labels: size/XXL, lgtm, approved, area/test-and-release, cla: yes

#12307 use annotation helpers
  go.mod
  go.sum
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/route.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: area/API, size/M, lgtm, area/networking, approved, cla: yes

#12308 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#12290 Add default cluster-side min-scale
  config/core/configmaps/autoscaler.yaml
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/autoscaler/config/autoscalerconfig/autoscalerconfig.go
  pkg/autoscaler/config/config.go
  pkg/autoscaler/config/config_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: area/API, size/M, lgtm, area/autoscale, approved, cla: yes

#12309 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12311 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12312 Convert freezer request methods to pointer receivers
  pkg/queue/concurrency_state.go
Labels: size/S, lgtm, area/networking, area/autoscale, approved, cla: yes

#12310 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12315 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#12317 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12318 Refactor request log handler chain in queue proxy
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/queue/health/handler.go
  pkg/queue/health/handler_test.go
Labels: size/M, lgtm, area/networking, area/autoscale, approved, cla: yes

#12321 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12320 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#12325 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#12286 Hpa stabilization window
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/autoscaling/hpa/resources/hpa_test.go
Labels: area/API, size/M, lgtm, area/autoscale, approved, cla: yes, ok-to-test

#12327 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved, cla: yes

#12328 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12326 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12333 [release-0.24] Pull in release script fixes
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12331 [release-0.26] Pull in release script fixes
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: area/API, size/S, lgtm, area/networking, area/autoscale, approved, area/test-and-release, cla: yes

#12319 Unfreeze containers on TERM so shutdown can occur
  cmd/queue/main.go
  pkg/queue/concurrency_state.go
Labels: size/S, lgtm, area/networking, area/autoscale, approved, cla: yes

#12332 [release-0.25] Pull in release script fixes
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12334 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12336 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12337 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12338 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12313 don't propagate kebab-case annotations to internal networking types
  pkg/reconciler/domainmapping/resources/ingress.go
  pkg/reconciler/route/resources/certificate.go
  pkg/reconciler/route/resources/filters.go
  pkg/reconciler/route/resources/ingress.go
Labels: area/API, size/S, lgtm, area/networking, approved, cla: yes

#12329 Support kebab-case annotations
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/serving/metadata_validation.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/autoscaler/metrics/collector.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/reconciler/service/resources/configuration.go
  test/e2e/helloworld_test.go
Labels: area/API, size/L, lgtm, area/autoscale, approved, area/test-and-release, cla: yes

#12340 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12343 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12347 Add v1beta1 test to Kind test
  .github/workflows/kind-e2e.yaml
Labels: size/S, lgtm, approved, cla: yes

#12350 Do not append the port to authority
  test/e2e/grpc_test.go
Labels: size/S, lgtm, approved, area/test-and-release, cla: yes

#12344 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12346 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12352 Tidy metrics methods
  pkg/metrics/tags.go
  pkg/metrics/tags_test.go
Labels: size/M, lgtm, area/monitoring, approved, cla: yes

#12359 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12360 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12361 Don't run tests in parallel in kind
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved, cla: yes

#12362 Bump golangci-lint timeout to prevent errors in actions
  .golangci.yaml
Labels: size/XS, lgtm, approved, cla: yes

#12363 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#12365 Pass ko flags to podspeed preparation step
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#12368 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12369 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved, cla: yes

#12357 Add net-gateway-api
  .github/workflows/kind-e2e.yaml
  test/config/ytt/ingress/gateway-api/ingress-class.yaml
  test/e2e-common.sh
  test/e2e-networking-library.sh
  test/e2e-tests.sh
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/XXL, lgtm, approved, area/test-and-release, cla: yes
