Repository knative/serving, pull requests merged in 2021-08, with the labels that each got.

#11741 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11749 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11754 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#11752 Update the pull request workflow link on DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#11757 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11756 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11759 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#11699 Adding config to enable setting concurrencyStateEndpoint
  cmd/queue/main.go
  config/core/configmaps/deployment.yaml
  pkg/deployment/config.go
  pkg/deployment/config_test.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, area/autoscale, area/networking, cla: yes, lgtm, size/M

#11763 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11764 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11762 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11765 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#11772 Use zero value in default case to clean up tests
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#11774 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11775 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11776 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11760 Always set `ENABLE_HTTP2_AUTO_DETECTION` envvar
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, area/API, cla: yes, lgtm, size/M

#11766 Add a benchmark for the TimeToFirstByteTimeoutHandler
  pkg/http/handler/timeout_test.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#11773 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11771 Reduce allocations from the timeout handler by pooling the timers
  pkg/http/handler/timeout.go
Labels: approved, area/networking, cla: yes, lgtm, size/S

#11668 add memory metrics for hpa
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/register.go
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/autoscaling/hpa/resources/hpa_test.go
Labels: approved, area/API, area/autoscale, area/test-and-release, cla: yes, lgtm, size/M

#11777 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#11751 Fix TestContainerErrorMsg failures against DockerHub
  test/conformance/api/v1/errorcondition_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#11781 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: approved, cla: yes, lgtm, size/S

#11779 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#11780 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: approved, cla: yes, lgtm, size/S

#11782 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/S

#11768 Add test for readiness behaviour after startup when periodSeconds is 0
  test/conformance/runtime/readiness_probe_test.go
  test/test_images/readiness/readiness.go
Labels: size/L, lgtm, approved, area/test-and-release, cla: yes

#11778 Fix scrape_time metric registration
  pkg/autoscaler/metrics/stats_scraper.go
Labels: size/XS, lgtm, area/autoscale, approved, cla: yes

#11788 Uses shorter name for some tests
  test/conformance/api/v1/revision_timeout_test.go
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#11800 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#11803 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11804 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11807 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11808 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11784 Makes conformance test for error condition more genernal
  test/conformance/api/v1/errorcondition_test.go
Labels: size/L, lgtm, approved, area/test-and-release, cla: yes

#11769 Adds a flag to skip conformance tests against non-required API
  test/conformance/api/v1/configuration_test.go
  test/conformance/api/v1/generatename_test.go
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/service_account_test.go
  test/conformance/api/v1/service_test.go
  test/conformance/api/v1/volumes_test.go
  test/conformance/runtime/envpropagation_test.go
  test/conformance/runtime/readiness_probe_test.go
  test/conformance/runtime/user_test.go
  test/e2e_flags.go
  test/v1/configuration.go
Labels: size/M, lgtm, approved, area/test-and-release, cla: yes

#11817 Remove deprecated ServiceName field
  config/core/300-resources/revision.yaml
  docs/serving-api.md
  pkg/apis/serving/v1/revision_types.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/route/queueing_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
  pkg/testing/v1/revision.go
Labels: area/API, size/L, lgtm, area/networking, approved, area/test-and-release, cla: yes

#11815 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11816 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11825 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11824 Update deps and fix deprecations
  cmd/queue/main.go
  go.mod
  go.sum
  pkg/activator/handler/handler.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/configuration/queueing_test.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/route/queueing_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/serverlessservice/global_resync_test.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/knative.dev/pkg/tracing/testing/zipkin.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#11814 Add conformance test for periodSeconds>0 case
  test/conformance/runtime/readiness_probe_test.go
Labels: size/L, lgtm, approved, area/test-and-release, cla: yes

#11830 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/autoscaling/v1alpha1/metric/filtered/metric.go
  pkg/client/injection/informers/autoscaling/v1alpha1/metric/metric.go
  pkg/client/injection/informers/autoscaling/v1alpha1/podautoscaler/filtered/podautoscaler.go
  pkg/client/injection/informers/autoscaling/v1alpha1/podautoscaler/podautoscaler.go
  pkg/client/injection/informers/serving/v1/configuration/configuration.go
  pkg/client/injection/informers/serving/v1/configuration/filtered/configuration.go
  pkg/client/injection/informers/serving/v1/revision/filtered/revision.go
  pkg/client/injection/informers/serving/v1/revision/revision.go
  pkg/client/injection/informers/serving/v1/route/filtered/route.go
  pkg/client/injection/informers/serving/v1/route/route.go
  pkg/client/injection/informers/serving/v1/service/filtered/service.go
  pkg/client/injection/informers/serving/v1/service/service.go
  pkg/client/injection/informers/serving/v1alpha1/domainmapping/domainmapping.go
  pkg/client/injection/informers/serving/v1alpha1/domainmapping/filtered/domainmapping.go
  pkg/client/injection/informers/serving/v1beta1/domainmapping/domainmapping.go
  pkg/client/injection/informers/serving/v1beta1/domainmapping/filtered/domainmapping.go
  vendor/knative.dev/caching/pkg/client/injection/client/client.go
  vendor/knative.dev/caching/pkg/client/injection/informers/caching/v1alpha1/image/image.go
  vendor/knative.dev/networking/pkg/client/injection/client/client.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/certificate/certificate.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/clusterdomainclaim/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/ingress/ingress.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/serverlessservice/serverlessservice.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta1/horizontalpodautoscaler/horizontalpodautoscaler.go
  vendor/knative.dev/pkg/client/injection/kube/informers/coordination/v1/lease/lease.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved, cla: yes

#11837 Remove deprecated loadbalancer status
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/route_test.go
Labels: area/API, size/M, lgtm, area/networking, approved, cla: yes

#11836 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#11839 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11840 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11838 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11847 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/controller.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/controller.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/controller.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/controller.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/controller.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/reconciler.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#11845 serviceAccountName validation uses helper backwards
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  test/conformance/api/v1/service_account_test.go
Labels: area/API, size/XS, lgtm, approved, area/test-and-release, cla: yes, ok-to-test

#11849 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11850 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11794 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#11841 Simplify emptyDir image behavior
  test/test_images/emptydir/emptydir.go
Labels: size/M, lgtm, approved, area/test-and-release, cla: yes

#11853 Use the `controller.Impl` tracker.
  pkg/reconciler/domainmapping/controller.go
  pkg/reconciler/domainmapping/table_test.go
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/route/controller.go
Labels: area/API, size/S, lgtm, area/networking, approved, kind/cleanup, cla: yes

#11858 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11856 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11859 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11857 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#11860 Clean up build tags in .golangci.yaml
  .golangci.yaml
Labels: size/XS, lgtm, approved, cla: yes

#11861 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#11863 Drop relatively useless logging
  pkg/reconciler/configuration/controller.go
  pkg/reconciler/domainmapping/controller.go
  pkg/reconciler/gc/controller.go
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/metric/controller.go
  pkg/reconciler/nscert/controller.go
  pkg/reconciler/revision/controller.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/service/controller.go
Labels: area/API, size/S, lgtm, area/networking, approved, kind/cleanup, cla: yes

#11865 Add missing RootCA additions to checks
  test/e2e/scale.go
  test/upgrade/upgrade.go
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#11867 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11868 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11886 Allow for additional delete calls without hanging in KPA test
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: area/API, size/XS, lgtm, area/autoscale, approved, cla: yes

#11879 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11880 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11893 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#11799 TestServiceWithTrafficSplit test changes
  test/conformance/api/v1/service_test.go
Labels: size/S, lgtm, approved, area/test-and-release, cla: yes

#11876 Update go-containerregistry to 0.6.0
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/cloud-provider/credentialconfig/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/legacy-cloud-providers/LICENSE
  vendor/github.com/google/go-containerregistry/internal/verify/verify.go
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/go.mod
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/go.sum
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/k8schain.go
  vendor/github.com/google/go-containerregistry/pkg/v1/manifest.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/mutate.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/catalog.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/descriptor.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/ping.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/zz_deepcopy_generated.go
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/README.md
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/aws/aws_credentials.go
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/azure/azure_credentials.go
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/config.go
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/gcp/metadata.go
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/go.mod
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/go.sum
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/keyring.go
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/provider.go
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/secrets/secrets.go
  vendor/github.com/vdemeester/k8s-pkg-credentialprovider/sync.sh
  vendor/k8s.io/cloud-provider/LICENSE
  vendor/k8s.io/cloud-provider/credentialconfig/registry.go
  vendor/k8s.io/legacy-cloud-providers/azure/auth/azure_auth.go
  vendor/k8s.io/legacy-cloud-providers/gce/gcpcredential/credentialutil.go
  vendor/k8s.io/legacy-cloud-providers/gce/gcpcredential/gcpcredential.go
  vendor/k8s.io/legacy-cloud-providers/gce/gcpcredential/registry_marshal.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved, cla: yes

#11680 change wait calls for check calls in tests
  test/conformance/api/v1/blue_green_test.go
  test/conformance/api/v1/generatename_test.go
  test/conformance/api/v1/resources_test.go
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/single_threaded_test.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1/volumes_test.go
  test/conformance/api/v1alpha1/domain_mapping_test.go
  test/conformance/api/v1beta1/domain_mapping_test.go
  test/conformance/runtime/readiness_probe_test.go
  test/conformance/runtime/util.go
  test/e2e/activator_test.go
  test/e2e/autoscale.go
  test/e2e/autoscale_hpa_test.go
  test/e2e/autotls/auto_tls_test.go
  test/e2e/destroypod_test.go
  test/e2e/domainmapping/domain_mapping_test.go
  test/e2e/egress_traffic_test.go
  test/e2e/emptydir_test.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/http2_test.go
  test/e2e/logging_test.go
  test/e2e/multicontainer_test.go
  test/e2e/namespace_test.go
  test/e2e/pod_schedule_error_test.go
  test/e2e/scale.go
  test/e2e/service_to_service_test.go
  test/e2e/tagheader/tag_header_based_routing_test.go
  test/ha/ha.go
  test/upgrade/upgrade.go
Labels: size/L, lgtm, approved, area/test-and-release, cla: yes
