Repository knative/serving, pull requests merged in 2021-09, with the labels that each got.

#11888 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11897 Improve error messages on probe failure
  pkg/activator/net/revision_backends.go
Labels: size/XS, lgtm, area/networking, area/autoscale, approved, cla: yes

#11783 Tracking request counts in queue proxy
  cmd/queue/main.go
  pkg/queue/concurrency_state.go
  pkg/queue/concurrency_state_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#11901 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#11905 [release-0.25] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#11907 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#11894 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11882 Support configuring HTTPOption per ksvc
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
Labels: area/API, size/M, lgtm, area/networking, approved, cla: yes

#11912 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11902 Fix indentation in e2e-tests.sh
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#11915 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#11918 [release-0.24] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#11920 [release-0.22] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#11919 [release-0.23] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#11887 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/L, lgtm, approved, cla: yes

#11911 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11908 Speed up TestRateLimitPerItem
  pkg/reconciler/revision/background_test.go
Labels: area/API, size/S, lgtm, approved, cla: yes

#11791 Add idle timeout to queue proxy
  cmd/queue/main.go
  pkg/http/handler/timeout.go
  pkg/http/handler/timeout_test.go
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved, area/test-and-release, cla: yes, ok-to-test

#11931 Drop all usages of EventuallyMatchesBody
  test/adding_tests.md
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/util.go
  test/e2e/domainmapping/domain_mapping_test.go
  test/e2e/namespace_test.go
  test/e2e/service_to_service_test.go
  test/ha/ha.go
  test/upgrade/upgrade.go
Labels: size/S, lgtm, approved, area/test-and-release, cla: yes

#11866 Teach resources/queue to allow no readiness probe
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
Labels: area/API, size/M, lgtm, approved, cla: yes

#11932 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#11913 Allow directly setting mesh compatibility mode on/off in stat scraper
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
Labels: size/L, lgtm, area/autoscale, approved, cla: yes

#11930 Drop unnecessary spoof.Retrying call
  test/e2e/service_to_service_test.go
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#11927 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11928 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#11929 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11899 roles: Don't specify rules when using aggregationRules.
  config/core/200-roles/addressable-resolvers-clusterrole.yaml
  config/core/200-serviceaccount.yaml
Labels: size/XS, lgtm, approved, cla: yes, ok-to-test

#11934 Widen checks in TestRateLimitPerItem to allow for slow systems
  pkg/reconciler/revision/background_test.go
Labels: area/API, size/XS, lgtm, approved, cla: yes

#11755 Add e2e test for #11668
  test/e2e-tests.sh
  test/e2e/autoscale_hpa_test.go
Labels: area/API, size/M, lgtm, area/autoscale, approved, area/test-and-release, cla: yes

#11925 Adding simple conformance test for Service list and delete
  test/conformance/api/v1/service_test.go
  test/v1/service.go
Labels: size/M, lgtm, approved, area/test-and-release, cla: yes, ok-to-test

#11933 Drop unnecessary RetryingRouteInconsistency helper
  test/conformance/api/v1/blue_green_test.go
  test/conformance/api/v1/generatename_test.go
  test/conformance/api/v1/resources_test.go
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/single_threaded_test.go
  test/conformance/api/v1/util.go
  test/conformance/api/v1/volumes_test.go
  test/conformance/api/v1alpha1/domain_mapping_test.go
  test/conformance/api/v1beta1/domain_mapping_test.go
  test/conformance/runtime/readiness_probe_test.go
  test/conformance/runtime/util.go
  test/e2e/activator_test.go
  test/e2e/autoscale.go
  test/e2e/autoscale_hpa_test.go
  test/e2e/destroypod_test.go
  test/e2e/egress_traffic_test.go
  test/e2e/emptydir_test.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/http2_test.go
  test/e2e/logging_test.go
  test/e2e/multicontainer_test.go
  test/e2e/namespace_test.go
  test/e2e/scale.go
  test/e2e/service_to_service_test.go
  test/e2e/tagheader/tag_header_based_routing_test.go
  test/ha/ha.go
  test/upgrade/upgrade.go
  test/v1/route.go
Labels: size/M, lgtm, approved, area/test-and-release, cla: yes

#11943 [release-0.23] fix upgrade tests
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: size/S, lgtm, approved, area/test-and-release, cla: yes

#11937 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11936 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#11945 Skip TestHPAAutoscaleUpDownUpMem because of excessive flakiness
  test/e2e/autoscale_hpa_test.go
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#11946 Stabilize TestIdleTimeoutHandler
  pkg/http/handler/timeout_test.go
Labels: size/S, lgtm, area/networking, approved, cla: yes

#11938 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11952 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11903 Run podspeed as part of CI
  test/e2e-tests.sh
Labels: size/S, lgtm, approved, area/test-and-release, cla: yes

#11935 Remove unused isAggressive parameter
  cmd/queue/main.go
  cmd/queue/main_test.go
  pkg/queue/health/handler.go
  pkg/queue/health/handler_test.go
  pkg/queue/readiness/probe.go
Labels: size/S, lgtm, area/networking, area/autoscale, approved, cla: yes

#11951 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11953 Touch up TestIdleTimeoutHandler some more
  pkg/http/handler/timeout_test.go
Labels: size/M, lgtm, area/networking, approved, cla: yes

#11950 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#11910 Speed up concurrency state handler tests
  pkg/queue/concurrency_state_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#11942 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/state.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/state.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/state.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/state.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/state.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/state.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/state.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/state.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/state.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, cla: yes

#11959 Add more logging to background digest resolver
  pkg/reconciler/revision/background.go
  pkg/reconciler/revision/background_test.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/revision/revision_test.go
Labels: area/API, size/M, lgtm, approved, cla: yes

#11960 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11961 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11962 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#11963 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11970 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#11968 Drop the label check in `WaitForServiceLatestRevision` func
  test/v1/service.go
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#11981 Add Kubernetes 1.22 to CI
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved, cla: yes

#11973 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11974 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#11975 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11957 Introduce a flag to set memory used in the resource limit test
  test/conformance/api/v1/resources_test.go
  test/e2e_flags.go
Labels: size/M, lgtm, approved, area/test-and-release, cla: yes

#11798 Delete orphaned tag certificates after tag deletion
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
Labels: area/API, size/L, lgtm, area/networking, approved, cla: yes, ok-to-test

#11909 Speed up concurrency state implementation
  pkg/queue/concurrency_state.go
  pkg/queue/concurrency_state_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#11965 Drop redundant queue-proxy startup probe
  cmd/queue/execprobe.go
  cmd/queue/execprobe_test.go
  cmd/queue/main.go
  pkg/queue/health/probe.go
  pkg/queue/health/probe_test.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  test/e2e/logging_test.go
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved, area/test-and-release, cla: yes

#11976 Teach activator about mesh compatibility modes
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/autoscaler/metrics/stats_scraper.go
Labels: size/M, lgtm, area/networking, area/autoscale, approved, cla: yes

#11984 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#11948 adding revisions test for get and list
  test/conformance/api/v1/revision_test.go
  test/v1/revision.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved, area/test-and-release, cla: yes, ok-to-test

#11820 Add serviceAccountToken via projected volume when concurrency state endpoint set
  config/core/configmaps/deployment.yaml
  pkg/queue/concurrency_state.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved, cla: yes

#11990 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11995 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, cla: yes

#11996 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#11993 Copy healthyPods set to avoid concurrent map access
  pkg/activator/net/revision_backends.go
Labels: size/XS, lgtm, area/networking, area/autoscale, approved, cla: yes

#12000 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#11989 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12001 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11991 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11998 Drop K8s 1.19 as it's no longer supported
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved, cla: yes

#11972 Adding Route GET and LIST Conformance test
  test/conformance/api/v1/route_test.go
  test/v1/route.go
Labels: size/M, lgtm, approved, area/test-and-release, cla: yes, ok-to-test

#11883 Add details when bad service account names are used
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  test/conformance/api/v1/service_account_test.go
Labels: area/API, size/S, lgtm, approved, area/test-and-release, cla: yes

#12005 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, lgtm, approved, cla: yes

#12004 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, cla: yes

#12008 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#11994 drop deprecated imageDigest property
  config/core/300-resources/revision.yaml
  docs/serving-api.md
  pkg/apis/serving/v1/revision_types.go
  pkg/reconciler/revision/resources/imagecache_test.go
  pkg/reconciler/revision/revision.go
Labels: area/API, size/M, lgtm, approved, cla: yes

#12002 Rework timeout handler tests with a fake clock
  pkg/http/handler/timeout.go
  pkg/http/handler/timeout_test.go
Labels: size/L, lgtm, area/networking, approved, cla: yes

#12007 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#12009 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12012 Remove TODO comment for #1178
  test/conformance/api/v1/route_test.go
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#11999 Wire up MeshCompatibilityMode to ConfigMap property
  cmd/activator/main.go
  cmd/autoscaler/main.go
  pkg/activator/net/revision_backends.go
  pkg/activator/net/revision_backends_test.go
  pkg/activator/net/throttler.go
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/autoscaler/metrics/stats_scraper_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#12013 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12018 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#12020 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#12021 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#12003 Allow users to set containers[*].securityContext.runAsGroup
  config/core/configmaps/features.yaml
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/k8s_validation_test.go
Labels: area/API, size/S, lgtm, approved, cla: yes

#12026 fix gc annotation prefix
  config/core/configmaps/gc.yaml
Labels: size/XS, lgtm, approved, cla: yes

#12028 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#11802 Add endpoint call for pod freezer
  cmd/queue/main.go
  config/core/configmaps/deployment.yaml
  pkg/queue/concurrency_state.go
  pkg/queue/concurrency_state_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#12030 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12031 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#12029 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12025 More helpful error on invalid port
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
Labels: area/API, size/M, lgtm, approved, cla: yes

#12034 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#12035 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: size/S, lgtm, approved, cla: yes

#12039 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12040 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes

#12016 Adding Configuration GET and LIST Conformance test
  test/conformance/api/v1/configuration_test.go
  test/v1/configuration.go
Labels: size/M, lgtm, approved, area/test-and-release, cla: yes

#12037 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, cla: yes

#12038 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, cla: yes

#12051 Bumping up golang min version
  DEVELOPMENT.md
Labels: size/XS, lgtm, approved, cla: yes

#12043 fix broken link in Development readme
  DEVELOPMENT.md
Labels: size/S, lgtm, approved, cla: yes

#12053 Use resolvabledomain flag in TestHPAAutoscaleUpDownUp
  test/e2e/autoscale_hpa_test.go
Labels: size/XS, lgtm, approved, area/test-and-release, cla: yes

#12052 update support rotation
  support/COMMUNITY_CONTACTS.md
  support/support.rotation
Labels: size/M, lgtm, approved, cla: yes

#12047 Renaming COC doc to ALLCAPS
  CODE-OF-CONDUCT.md
Labels: size/S, lgtm, approved, cla: yes, kind/documentation

#12054 fix dates
  support/support.rotation
Labels: size/XS, lgtm, approved, cla: yes

#11917 Pass serviceAccountToken to freezer service
  cmd/queue/main.go
  pkg/queue/concurrency_state.go
  pkg/queue/concurrency_state_test.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved, cla: yes

#12055 Cleaning up freezer package constants
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/queue.go
Labels: area/API, size/XS, lgtm, approved, cla: yes

#12056 Fix date ordering
  support/support.rotation
Labels: size/XS, lgtm, approved, cla: yes

#12059 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, cla: yes

#12066 Use constants for test image names
  test/conformance.go
  test/conformance/api/v1/volumes_test.go
  test/e2e/activator_test.go
  test/e2e/autotls/auto_tls_test.go
  test/e2e/autotls/domain_mapping_test.go
  test/e2e/destroypod_test.go
  test/e2e/egress_traffic_test.go
  test/e2e/gc/gc_test.go
  test/e2e/grpc_test.go
  test/e2e/helloworld_test.go
  test/e2e/http2_test.go
  test/e2e/initial_scale_test.go
  test/e2e/initscale/initial_scale_zero_test.go
  test/e2e/logging_test.go
  test/e2e/minscale_readiness_test.go
  test/e2e/pod_schedule_error_test.go
  test/e2e/rollback_byo_test.go
  test/e2e/scale.go
  test/e2e/service_to_service_test.go
  test/e2e/subroutes_test.go
Labels: size/M, lgtm, approved, area/test-and-release, cla: yes

#12067 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, approved, cla: yes
