Repository knative/serving, pull requests merged in 2022-09, with the labels that each got.

#13232 add e2e test for timeout with websocket
  test/e2e/domainmapping/domain_mapping_websocket_test.go
  test/e2e/websocket.go
  test/e2e/websocket_test.go
  test/test_images/wsserver/echo.go
Labels: size/L, lgtm, approved, area/test-and-release

#13266 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13267 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13269 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13268 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13263 Tests for encryption with Kourier local gateway
  .github/workflows/kind-e2e.yaml
  test/config/tls/cert-secret.yaml
  test/config/tls/generate.sh
  test/e2e-common.sh
  test/e2e/service_to_service_test.go
  test/test_images/httpproxy/httpproxy.go
Labels: size/L, lgtm, approved, area/test-and-release

#13272 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/interface.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13279 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13282 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13281 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13283 Update setup-ko action to v0.6
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#13287 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13288 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13290 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13289 use GKE 1.23 clusters in CI
  test/e2e-auto-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance/performance-tests-mako.sh
  test/performance/performance-tests.sh
Labels: size/S, lgtm, approved, area/test-and-release

#13291 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13294 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13295 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13297 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13300 Use new k8s.io/util/clock package
  go.mod
  pkg/http/handler/timeout.go
  pkg/http/handler/timeout_test.go
Labels: size/M, lgtm, area/networking, approved

#13296 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13301 Update to use k8s.io/utils/clock package
  pkg/autoscaler/fake/fakes.go
  pkg/autoscaler/metrics/collector.go
  pkg/autoscaler/metrics/collector_test.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/configuration/controller.go
  pkg/reconciler/gc/gc_test.go
  pkg/reconciler/gc/reconciler_test.go
  pkg/reconciler/labeler/accessors.go
  pkg/reconciler/labeler/controller.go
  pkg/reconciler/labeler/labeler_test.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/route/controller.go
  pkg/reconciler/route/reconcile_resources_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/route/table_test.go
  pkg/testing/v1/revision.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#13302 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13306 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13307 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13239 Fix LatestReadyRevision semantics - it only advances forward
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/configuration/configuration_test.go
  pkg/reconciler/route/traffic/traffic.go
  pkg/reconciler/route/traffic/traffic_test.go
  test/e2e/rollback_byo_test.go
Labels: area/API, size/L, lgtm, area/networking, approved, area/test-and-release

#13315 Update kapp module name in e2e tests
  test/e2e-common.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#13314 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13313 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13311 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13312 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13324 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13322 [skip-dot-release] [release 1.4] fix CI issue in release branch
  test/e2e-common.sh
  test/upgrade/upgrade.go
Labels: size/XS, lgtm, approved, area/test-and-release

#13319 [skip-dot-release] [release 1.6] fix CI issue in release branch
  .github/workflows/kind-e2e.yaml
  test/e2e-common.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#13320 [skip-dot-release] [release 1.5] fix CI issue in release branch
  .github/workflows/kind-e2e.yaml
  test/e2e-common.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#13326 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13328 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13330 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13323 Fix: Raise the reconciliation timeout from 10 to 30s.
  cmd/controller/main.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/configuration/configuration.go
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/gc/reconciler.go
  pkg/reconciler/labeler/labeler.go
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/route/route.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/service/service.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved

#13335 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#13336 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#13339 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13340 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13341 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13342 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13344 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13346 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13345 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13347 Use kebab-case in config for queue sidecar image key
  config/core/configmaps/deployment.yaml
  pkg/deployment/config_test.go
  pkg/reconciler/autoscaling/config/store_test.go
  pkg/reconciler/revision/config/store_test.go
Labels: area/API, size/S, lgtm, area/autoscale, approved

#13348 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: size/M, lgtm, approved
