Repository knative/serving, pull requests merged in 2022-03, with the labels that each got.

#12685 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved

#12690 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#12689 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved

#12682 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved

#12687 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#12683 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved

#12694 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved

#12698 Fixes validation bug for autoscaling/target
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
Labels: area/API, size/XS, lgtm, area/autoscale, approved

#12695 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved

#12696 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved

#12703 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#12702 Removing no longer needed todo
  pkg/apis/serving/metadata_validation.go
Labels: area/API, size/XS, lgtm, approved

#12606 Probe port different than container port
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  test/conformance/runtime/container_test.go
  test/e2e/readinessport_test.go
  test/test_images/readiness/README.md
  test/test_images/readiness/readiness.go
Labels: area/API, size/L, lgtm, approved, area/test-and-release, ok-to-test

#12704 Adds detail to initialScale validation error msgs
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/serving/metadata_validation_test.go
  pkg/apis/serving/v1/revision_validation_test.go
Labels: area/API, size/S, lgtm, area/autoscale, approved

#12705 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved

#12706 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved

#12643 Fix TestProbeRuntimeAfterStartup/periodSeconds=0 flake
  test/conformance/runtime/readiness_probe_test.go
Labels: size/S, lgtm, approved, area/test-and-release

#12708 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved

#12714 Enable istio access logging during e2e
  test/config/ytt/ingress/istio/istio-enable-access-logging.yaml
Labels: size/S, lgtm, approved, area/test-and-release

#12709 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved

#12710 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved

#12711 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved

#12716 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#12730 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#12725 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved

#12736 Fix PVC test service name
  test/test_images/volumes/service-pvc.yaml
Labels: size/XS, lgtm, approved, area/test-and-release

#12724 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved

#12727 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved

#12721 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#12723 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved

#12742 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved

#12741 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved

#12745 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#12740 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved

#12744 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved

#12747 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved

#12757 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: size/M, lgtm, approved

#12715 Add support for topology spread constraint
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/k8s_validation_test.go
Labels: area/API, size/L, lgtm, area/networking, approved, area/test-and-release, ok-to-test

#12750 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved

#12733 Add unit tests for custom item rate limiter
  pkg/reconciler/revision/background_test.go
  pkg/reconciler/revision/rate_limiter.go
  pkg/reconciler/revision/rate_limiter_test.go
Labels: area/API, size/L, lgtm, approved, ok-to-test

#12758 use GKE 1.22 clusters in CI
  test/e2e-auto-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance/performance-tests.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#12764 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#12754 Removing deprecated serving.knative.dev/release label
  config/core/100-namespace.yaml
  config/core/200-roles/addressable-resolvers-clusterrole.yaml
  config/core/200-roles/clusterrole-namespaced.yaml
  config/core/200-roles/clusterrole.yaml
  config/core/200-roles/podspecable-bindings-clusterrole.yaml
  config/core/200-serviceaccount.yaml
  config/core/300-resources/configuration.yaml
  config/core/300-resources/domain-mapping.yaml
  config/core/300-resources/metric.yaml
  config/core/300-resources/podautoscaler.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/route.yaml
  config/core/300-resources/service.yaml
  config/core/999-cache.yaml
  config/core/configmaps/autoscaler.yaml
  config/core/configmaps/defaults.yaml
  config/core/configmaps/deployment.yaml
  config/core/configmaps/domain.yaml
  config/core/configmaps/features.yaml
  config/core/configmaps/gc.yaml
  config/core/configmaps/leader-election.yaml
  config/core/configmaps/logging.yaml
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
  config/core/deployments/activator-hpa.yaml
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
  config/core/deployments/domainmapping-webhook.yaml
  config/core/deployments/webhook-hpa.yaml
  config/core/deployments/webhook.yaml
  config/core/webhooks/configmap-validation.yaml
  config/core/webhooks/defaulting.yaml
  config/core/webhooks/domainmapping-defaulting.yaml
  config/core/webhooks/domainmapping-secret.yaml
  config/core/webhooks/domainmapping-validation.yaml
  config/core/webhooks/resource-validation.yaml
  config/core/webhooks/secret.yaml
  config/hpa-autoscaling/controller.yaml
  config/post-install/default-domain.yaml
  config/post-install/storage-version-migration.yaml
  hack/generate-yamls.sh
  pkg/reconciler/revision/config/testdata/config-tracing.yaml
  test/config/autotls/certmanager/caissuer/config-certmanager.yaml
  test/config/autotls/certmanager/http01/config-certmanager.yaml
  test/config/autotls/certmanager/selfsigned/config-certmanager.yaml
  test/config/chaosduck/chaosduck.yaml
  test/config/ytt/ingress/istio/istio-config-dedupe.yaml
Labels: area/API, size/M, lgtm, approved, area/test-and-release

#12766 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved

#12768 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved

#12748 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved

#12752 Fix gc: delete revision in correct orderer
  pkg/reconciler/gc/gc.go
  pkg/reconciler/gc/gc_test.go
Labels: area/API, size/L, lgtm, approved, ok-to-test

#12773 make the contour ttl overlay work when the field isn't present
  test/config/ytt/ingress/contour/contour-ttl.yaml
Labels: size/XS, lgtm, approved, area/test-and-release

#12726 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/L, lgtm, approved

#12774 Change default target burst capacity
  config/core/configmaps/autoscaler.yaml
  pkg/autoscaler/config/config.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: area/API, size/S, lgtm, area/autoscale, approved

#12775 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/config/image.yaml
  vendor/knative.dev/caching/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/caching_client.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/fake/fake_image.go
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#12783 Make some of the unit tests a bit more robust
  go.mod
  go.sum
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/serverlessservice/global_resync_test.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved

#12751 Adds progressDeadline annotation on per revision basis
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/service_validation.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
Labels: area/API, size/L, lgtm, area/autoscale, approved

#12784 use ctx setup by the test which has a test logger
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/domainmapping/reconciler_test.go
  pkg/reconciler/revision/revision_test.go
  pkg/reconciler/route/route_test.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved

#12780 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved

#12787 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#12795 Fix racey tests by not adding things directly to the informer cache
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/route/queueing_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/serverlessservice/global_resync_test.go
Labels: area/API, size/S, lgtm, area/networking, area/autoscale, approved

#12793 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved

#12798 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#12800 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, approved

#12803 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/XL, lgtm, approved

#12802 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved
