Repository knative/serving, pull requests merged in 2022-10, with the labels that each got.

#13356 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13357 Remove kind 1.22 testing, since min-version will be 1.23 in the next release
  .github/workflows/kind-e2e.yaml
Labels: size/S, lgtm, approved

#13360 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#13363 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13364 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13365 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#13366 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#13361 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13368 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13367 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13369 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13370 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13337 upgrade k8s HorizontalPodAutoscaler to v2
  config/core/deployments/activator-hpa.yaml
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/autoscaling/hpa/resources/hpa_test.go
  pkg/reconciler/testing/v1/listers.go
  test/e2e/autoscale_hpa_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2/horizontalpodautoscaler/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2/horizontalpodautoscaler/horizontalpodautoscaler.go
  vendor/modules.txt
Labels: area/API, size/L, lgtm, area/autoscale, approved, area/test-and-release

#13373 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13374 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13375 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13358 Add e2e test on k8s 1.25.2
  .github/workflows/kind-e2e.yaml
Labels: size/M, lgtm, approved

#13378 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13286 Make conformance tests configurable with custom resource values
  test/conformance/api/v1/resources_test.go
  test/conformance/runtime/cgroup_test.go
  test/e2e_flags.go
Labels: size/L, lgtm, approved, area/test-and-release, ok-to-test

#13380 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#13381 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13382 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13383 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13385 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13389 Adding profiling readme back
  test/performance/profiling.md
Labels: size/M, lgtm, approved, area/test-and-release

#13390 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13393 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13391 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13392 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13259 Use svc.cluster.local as default domain
  config/core/configmaps/domain.yaml
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/route/config/domain.go
  test/config/ytt/core/overlay-config-domain.yaml
Labels: area/API, size/M, lgtm, area/networking, approved, area/test-and-release

#13395 Feature: Let users set `allowPrivilegeEscalation = false` on ksvc.
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
Labels: kind/bug, area/API, size/M, lgtm, approved

#13402 Fix: Add the new `AllowPrivilegeEscalation` field to the *other* fieldmask.
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  hack/schemapatch-config.yaml
Labels: kind/bug, size/S, lgtm, approved, area/test-and-release

#13403 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13404 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13400 Fix path validation when running tests on Windows
  pkg/apis/serving/k8s_validation.go
Labels: area/API, size/S, lgtm, approved

#13405 Enable emptyDir volumes for Knative Services
  .github/workflows/kind-e2e.yaml
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/serving/k8s_validation_test.go
  test/e2e-tests.sh
  test/e2e/empty_dir_test.go
Labels: area/API, size/M, lgtm, approved, area/test-and-release

#13376 Run queue proxy with restricted profile
  pkg/reconciler/revision/resources/queue.go
Labels: area/API, size/XS, lgtm, approved

#13401 Allow setting seccompProfile to enable using restricted security profile
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
Labels: area/API, size/S, lgtm, approved

#13406 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13411 Updates HPA webhook api version
  config/core/deployments/webhook-hpa.yaml
Labels: size/XS, lgtm, approved

#13413 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13415 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13417 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13421 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13422 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13423 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13424 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13425 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13426 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
