Repository knative/serving, pull requests merged in 2022-06, with the labels that each got.

#12981 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#12982 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#12985 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#12983 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#12988 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#12993 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#12994 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#12990 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#12991 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#12992 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13001 add openssf knative badge
  README.md
Labels: size/XS, lgtm, approved

#13004 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13009 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13010 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13007 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13008 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13006 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13011 regen protobuf after bumping the versions in the prow-image
  pkg/autoscaler/metrics/stat.pb.go
  test/test_images/grpc-ping/proto/ping.pb.go
Labels: size/S, lgtm, area/autoscale, approved, area/test-and-release

#13012 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13014 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13013 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13015 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13019 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13020 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13021 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13017 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13018 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13016 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13022 Bump kind to v0.14 for e2e tests
  .github/workflows/kind-e2e.yaml
Labels: size/S, lgtm, approved

#13025 Remove the scale-to-zero checking in conformance.
  test/conformance/api/shared/util.go
  test/conformance/runtime/readiness_probe_test.go
Labels: size/M, lgtm, approved, area/test-and-release

#13026 Relax the "timeout" requirement for `TestProbeRuntimeAfterStartup`
  test/conformance/runtime/readiness_probe_test.go
Labels: size/S, lgtm, approved, area/test-and-release

#13027 Improve SKS handling for unavailable Activator.
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: area/API, size/M, lgtm, approved

#13047 skip TestHelloHTTP2WithEmptyPortName early
  test/e2e/http2_test.go
Labels: size/XS, lgtm, approved, area/test-and-release

#13052 Update link, thanks to Zhu Lei
  config/core/300-resources/podautoscaler.yaml
  docs/serving-api.md
  pkg/apis/autoscaling/v1alpha1/pa_types.go
Labels: area/API, size/XS, lgtm, area/autoscale, approved

#13048 SKS Endpoint Informer should only watch endpoints for our private services
  pkg/reconciler/serverlessservice/controller.go
Labels: area/API, size/XS, lgtm, approved

#13055 Temporarily disable flaky kind test
  .github/workflows/kind-e2e.yaml
  test/e2e/autoscale_test.go
Labels: size/XS, lgtm, approved, area/test-and-release

#13032 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13040 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13046 Allow calls to test.Setup to disable logstream
  test/conformance.go
  test/e2e/autotls/auto_tls_test.go
  test/e2e/autotls/domain_mapping_test.go
  test/e2e/autotls/http_redirect_test.go
  test/e2e/e2e.go
  test/e2e/resource_quota_error_test.go
Labels: size/M, lgtm, approved, area/test-and-release

#13062 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13063 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#13064 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13066 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13067 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13068 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13061 Fix webhook config drift issue
  config/core/webhooks/domainmapping-defaulting.yaml
  config/core/webhooks/domainmapping-validation.yaml
Labels: size/S, lgtm, approved, ok-to-test

#13070 [release-1.2] update generated protobuf & hack scripts
  go.mod
  go.sum
  pkg/autoscaler/metrics/stat.pb.go
  test/test_images/grpc-ping/proto/ping.pb.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, area/autoscale, approved, area/test-and-release

#13072 [release-1.3] update generated protobuf & hack scripts
  go.mod
  go.sum
  pkg/autoscaler/metrics/stat.pb.go
  test/test_images/grpc-ping/proto/ping.pb.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, area/autoscale, approved, area/test-and-release

#13073 [release-1.4] update generated protobuf & hack scripts
  go.mod
  go.sum
  pkg/autoscaler/metrics/stat.pb.go
  test/test_images/grpc-ping/proto/ping.pb.go
  vendor/github.com/prometheus/procfs/Makefile
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/cmdline.go
  vendor/github.com/prometheus/procfs/doc.go
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/netstat.go
  vendor/github.com/prometheus/procfs/proc_cgroup.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/procfs/zoneinfo.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/XXL, lgtm, area/autoscale, approved, area/test-and-release

#13074 [release-1.5] update generated protobuf & hack scripts
  go.mod
  go.sum
  pkg/autoscaler/metrics/stat.pb.go
  test/test_images/grpc-ping/proto/ping.pb.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, area/autoscale, approved, area/test-and-release

#13005 Support config to deploy internal certificates automatically
  cmd/activator/main.go
  cmd/controller/main.go
  cmd/queue/main.go
  config/core/300-secret.yaml
  go.mod
  go.sum
  pkg/networking/constants.go
  pkg/reconciler/autoscaling/config/store_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  test/e2e-common.sh
  test/e2e/autoscale_test.go
  test/generate-cert.sh
  test/ha/ha.go
  third_party/VENDOR-LICENSE/knative.dev/control-protocol/pkg/certificates/LICENSE
  third_party/kourier-latest/kourier.yaml
  vendor/knative.dev/control-protocol/LICENSE
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/control-protocol/pkg/certificates/constants.go
  vendor/knative.dev/control-protocol/pkg/certificates/key_pair.go
  vendor/knative.dev/control-protocol/pkg/certificates/reconciler/certificates.go
  vendor/knative.dev/control-protocol/pkg/certificates/reconciler/controller.go
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/state.go
  vendor/modules.txt
Labels: area/API, size/XXL, lgtm, area/networking, area/autoscale, approved, area/test-and-release
