Repository knative/serving, pull requests merged in 2022-08, with the labels that each got.

#13077 Add e2e test for DomainMapping working with websocket.
  .github/workflows/kind-e2e.yaml
  test/e2e/domainmapping/domain_mapping_websocket_test.go
  test/e2e/websocket.go
  test/e2e/websocket_test.go
Labels: size/L, lgtm, approved, area/test-and-release, ok-to-test

#13174 Add paul to party, update sched through 2022
  support/COMMUNITY_CONTACTS.md
  support/support.rotation
Labels: size/S, lgtm, approved

#13162 Qp options config additions only
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/queue/constants.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved

#13177 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#13179 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/L, lgtm, area/networking, approved

#13180 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13178 Make Kingress reconciled with DomainMapping when adding a new label
  pkg/reconciler/domainmapping/reconciler.go
  pkg/reconciler/domainmapping/table_test.go
Labels: area/API, size/M, lgtm, approved

#13183 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13184 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13186 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13188 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13189 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13187 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13190 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13181 Fixes resource quota test flake
  test/e2e/resource_quota_error_test.go
  test/v1/revision.go
Labels: size/S, lgtm, approved, area/test-and-release

#13195 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13194 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13196 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13198 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13146 A refactor of the queue volume constants
  pkg/queue/constants.go
  pkg/queue/sharedmain/main.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/queue.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved

#12970 Fix timeout handlers to max duration instead of time to first byte
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  config/core/configmaps/defaults.yaml
  docs/serving-api.md
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/apis/serving/v1/revision_defaults_test.go
  pkg/apis/serving/v1/revision_types.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1/zz_generated.deepcopy.go
  pkg/http/handler/timeout.go
  pkg/http/handler/timeout_test.go
  pkg/queue/sharedmain/main.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  pkg/testing/v1/configuration.go
  pkg/testing/v1/service.go
  test/e2e/timeout_test.go
Labels: area/API, size/XL, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#13203 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13205 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13206 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13212 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13213 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13202 Refactor VolumeMountPath to Directory
  pkg/queue/constants.go
  pkg/queue/sharedmain/main.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/queue.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved

#13214 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved, skip-review

#13215 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13216 Fix deprecation notices
  pkg/activator/handler/handler_test.go
  pkg/activator/handler/tracing_handler_test.go
  pkg/queue/sharedmain/main_test.go
Labels: size/XS, lgtm, area/networking, area/autoscale, approved

#13217 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13221 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13219 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13220 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13218 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13223 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13224 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13225 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13226 Properly shutdown tracer when the work is done
  cmd/activator/main.go
  pkg/queue/sharedmain/main.go
Labels: area/API, size/S, lgtm, area/networking, area/autoscale, approved

#13227 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13222 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13229 stop the queue-proxy drain if we don't receive a TERM signal
  pkg/queue/sharedmain/main.go
  test/test_images/readiness/service.yaml
Labels: size/M, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#13234 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13238 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#13236 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13240 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13244 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13241 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13242 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13246 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13255 revision request start timeout should default to revision timeout second
  config/core/configmaps/defaults.yaml
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
Labels: area/API, size/M, lgtm, approved

#13256 [release-1.7] revision request start timeout should default to revision timeout second
  config/core/configmaps/defaults.yaml
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
Labels: area/API, size/M, lgtm, approved

#13252 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13250 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13249 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13251 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13253 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13264 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13261 Add timeout handler to activator to respect the revision timeouts
  cmd/activator/main.go
  pkg/http/handler/timeout.go
  pkg/http/handler/timeout_test.go
  pkg/queue/sharedmain/main.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved
