Repository knative/serving, pull requests merged in 2022-07, with the labels that each got.

#13076 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13037 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta2/horizontalpodautoscaler/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta2/horizontalpodautoscaler/horizontalpodautoscaler.go
  vendor/knative.dev/pkg/client/injection/kube/informers/coordination/v1/lease/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/coordination/v1/lease/lease.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/state.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13030 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13080 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13081 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13085 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13086 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13087 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#13089 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/config/image.yaml
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13084 Drop EnableAlphaFeatures from TestHttpRedirect
  test/e2e/autotls/http_redirect_test.go
Labels: size/XS, lgtm, approved, area/test-and-release

#13092 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13093 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13088 Add overview for scaling doc
  docs/scaling/README.md
  docs/scaling/SYSTEM.md
Labels: size/L, lgtm, approved

#13082 Add filtering secret informer label for internal-encryption
  config/core/300-secret.yaml
Labels: area/API, size/XS, lgtm, approved, area/test-and-release

#13107 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13105 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13095 Update Knative Serving schema
  config/core/300-resources/configuration.yaml
  config/core/300-resources/domain-mapping.yaml
  config/core/300-resources/metric.yaml
  config/core/300-resources/podautoscaler.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/route.yaml
  config/core/300-resources/service.yaml
  hack/schemapatch-config.yaml
  hack/update-schemas.sh
  pkg/apis/serving/fieldmask.go
  test/conformance/runtime/container_test.go
Labels: area/API, size/XL, lgtm, approved, area/test-and-release

#13106 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13111 allow unknown fields in our webhooks since our CRD schemas are now specified
  cmd/domain-mapping-webhook/main.go
  cmd/webhook/main.go
Labels: area/API, size/S, lgtm, approved

#13113 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13115 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/XL, lgtm, area/networking, approved

#13120 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved

#13119 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/XXL, lgtm, area/networking, approved

#13124 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13117 Add test flag --ingress-class
  test/e2e-tests.sh
  test/e2e_flags.go
Labels: size/XS, lgtm, approved, area/test-and-release

#13130 Remove git files from kodata
  cmd/activator/kodata/HEAD
  cmd/activator/kodata/refs
  cmd/autoscaler-hpa/kodata/HEAD
  cmd/autoscaler-hpa/kodata/refs
  cmd/autoscaler/kodata/HEAD
  cmd/autoscaler/kodata/refs
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/refs
  cmd/queue/kodata/HEAD
  cmd/queue/kodata/refs
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/refs
  test/performance/benchmarks/dataplane-probe/continuous/kodata/HEAD
  test/performance/benchmarks/dataplane-probe/continuous/kodata/refs
  test/performance/benchmarks/deployment-probe/continuous/kodata/HEAD
  test/performance/benchmarks/deployment-probe/continuous/kodata/refs
  test/performance/benchmarks/load-test/continuous/kodata/HEAD
  test/performance/benchmarks/load-test/continuous/kodata/refs
  test/performance/benchmarks/rollout-probe/continuous/kodata/HEAD
  test/performance/benchmarks/rollout-probe/continuous/kodata/refs
  test/performance/benchmarks/scale-from-zero/continuous/kodata/HEAD
  test/performance/benchmarks/scale-from-zero/continuous/kodata/refs
Labels: area/API, size/S, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#13132 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13140 Bump go version in kind-e2e tests to v1.18
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#13141 Update `changeset.Get` according to pkg update
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  pkg/reconciler/revision/controller.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: area/API, size/L, lgtm, approved

#13137 remove defunct markdown lint and linking variables
  test/presubmit-tests.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#13143 Stop using knative.dev/pkg/pool, use errgroup instead
  go.mod
  go.sum
  test/conformance/api/shared/util.go
  test/e2e/scale.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/knative.dev/pkg/pool/doc.go
  vendor/knative.dev/pkg/pool/interface.go
  vendor/knative.dev/pkg/pool/pool.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, area/test-and-release

#13142 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/language/common.go
  vendor/golang.org/x/text/internal/language/compact.go
  vendor/golang.org/x/text/internal/language/compact/compact.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/compact/parents.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/compact/tags.go
  vendor/golang.org/x/text/internal/language/compose.go
  vendor/golang.org/x/text/internal/language/coverage.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/match.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/language/tags.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tag/tag.go
  vendor/golang.org/x/text/language/coverage.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/language/tags.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#13147 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13150 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13151 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13152 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13133 Enable refactoring queue-proxy binary with out-of-tree extensions
  cmd/queue/main.go
  pkg/queue/sharedmain/main.go
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved, area/test-and-release, ok-to-test

#13155 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13156 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13136 Add active-min-scale annotation
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
  pkg/autoscaler/scaling/multiscaler.go
  pkg/reconciler/autoscaling/kpa/resources/decider.go
  pkg/reconciler/autoscaling/kpa/resources/decider_test.go
Labels: area/API, size/L, lgtm, area/autoscale, approved

#13161 Updating name of activation-scale
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
  pkg/apis/autoscaling/register.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle_test.go
  pkg/autoscaler/scaling/autoscaler.go
  pkg/autoscaler/scaling/autoscaler_test.go
  pkg/autoscaler/scaling/multiscaler.go
  pkg/reconciler/autoscaling/kpa/resources/decider.go
  pkg/reconciler/autoscaling/kpa/resources/decider_test.go
Labels: area/API, size/M, lgtm, area/autoscale, approved

#13163 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13166 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13164 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13165 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13167 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13169 Bumping go.mod to v1.18
  go.mod
  go.sum
Labels: size/XL, lgtm, approved

#13170 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13171 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/XS, lgtm, area/networking, approved
