Repository knative/serving, pull requests merged in 2023-07, with the labels that each got.

#14131 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#14132 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14136 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14143 Drop unused ytt patch for Ingress ServiceType
  test/config/ytt/kind/ingress/istio-kind.yaml
  test/config/ytt/kind/ingress/kourier-kind.yaml
  test/e2e-common.sh
Labels: size/S, lgtm, approved, area/test-and-release

#14129 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14144 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/L, lgtm, area/networking, approved

#14151 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#14147 Implement Stringer for nil podTracker
  pkg/activator/net/throttler.go
Labels: size/XS, lgtm, area/networking, area/autoscale, approved

#14150 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#14039 Set QP resource defaults
  config/core/configmaps/deployment.yaml
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/deployment/config.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: area/API, size/L, lgtm, approved

#14082 Consolidate webhooks
  cmd/controller/main.go
  cmd/domain-mapping-webhook/main.go
  cmd/domain-mapping/main.go
  cmd/webhook/main.go
  config/core/deployments/domainmapping-controller.yaml
  config/core/deployments/domainmapping-webhook.yaml
  config/core/webhooks/defaulting.yaml
  config/core/webhooks/domainmapping-defaulting.yaml
  config/core/webhooks/domainmapping-secret.yaml
  config/core/webhooks/domainmapping-validation.yaml
  config/core/webhooks/resource-validation.yaml
  test/ha/domainmapping_test.go
  test/ha/ha.go
Labels: area/API, size/XL, lgtm, approved, area/test-and-release

#14133 Separate Activator SA
  config/core/200-roles/activator.yaml
  config/core/200-serviceaccount.yaml
  config/core/deployments/activator.yaml
Labels: size/M, lgtm, approved

#14154 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14148 Bump net-certmanager manifests and add kapp ordering overlay
  test/config/ytt/certmanager/kapp-order.yaml
  test/e2e-common.sh
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/L, lgtm, area/networking, approved, area/test-and-release

#14160 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14156 Drop workaround patch for Istio
  test/config/ytt/ingress/istio/istio-deploy-fix.yaml
Labels: size/M, lgtm, approved, area/test-and-release

#14161 Remove domainmapping config
  test/config/ytt/core/overlay-config-logging.yaml
  test/config/ytt/values.yaml
Labels: size/XS, lgtm, approved, area/test-and-release

#14164 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14165 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14169 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14172 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14174 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14173 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14158 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/M, lgtm, area/networking, approved, area/test-and-release

#14171 EnsureCleanup can skip clean up
  test/cleanup.go
  test/conformance/api/v1alpha1/domain_mapping_test.go
  test/conformance/api/v1beta1/domain_mapping_test.go
  test/e2e/autotls/domain_mapping_test.go
  test/e2e/domainmapping/domain_mapping_test.go
  test/e2e/domainmapping/domain_mapping_websocket_test.go
Labels: size/S, lgtm, approved, area/test-and-release

#14188 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14190 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved

#14191 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14192 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14194 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14193 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14195 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14198 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14205 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved
