Repository knative/serving, pull requests merged in 2023-04, with the labels that each got.

#13842 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13844 [main] Upgrade to latest dependencies
  config/core/300-resources/domain-mapping.yaml
  config/core/300-resources/route.yaml
  config/core/300-resources/service.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13851 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13850 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13849 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13852 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13853 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13860 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/control-protocol/pkg/certificates/constants.go
  vendor/knative.dev/control-protocol/pkg/certificates/reconciler/certificates.go
  vendor/knative.dev/control-protocol/pkg/certificates/reconciler/controller.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13862 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#13863 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13866 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13865 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13864 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13868 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13854 Load certificate when they are updated when internal-encryption is enabled
  cmd/activator/main.go
  pkg/activator/certificate/cache.go
  pkg/activator/certificate/cache_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/modules.txt
Labels: area/API, size/XL, lgtm, area/networking, area/autoscale, approved

#13874 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13872 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13873 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13870 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13871 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13879 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#13882 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13883 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13881 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13886 Change minimum TLS version to 1.3
  pkg/reconciler/revision/resolve.go
Labels: area/API, size/XS, lgtm, area/networking, area/autoscale, approved

#13893 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13894 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13895 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13897 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13900 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13899 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13903 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13902 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13904 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13907 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13912 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13896 add support for downwardAPI in projected volumes
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  hack/schemapatch-config.yaml
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
Labels: area/API, size/L, lgtm, approved, area/test-and-release

#13885 Deployment probe fixes
  cmd/domain-mapping-webhook/main.go
  cmd/webhook/main.go
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
Labels: area/API, size/S, lgtm, approved

#13915 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13917 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13918 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13919 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#13920 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13923 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13924 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13927 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13928 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved
