Repository knative/serving, pull requests merged in 2023-11, with the labels that each got.

#14579 [release-1.11] bump grpc to v1.56.3 (addressing CVE-2023-44487)
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#14578 Remove dead code and other fixes
  pkg/activator/net/throttler_test.go
  pkg/http/handler/timeout_test.go
  pkg/reconciler/revision/background_test.go
  pkg/reconciler/route/traffic/rollout.go
  pkg/reconciler/route/traffic/rollout_test.go
  test/conformance.go
Labels: area/API, size/S, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#14582 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14584 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14585 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14592 remove duplicate 'additionalPrinterColumns' in domain-mapping resource
  config/core/300-resources/domain-mapping.yaml
Labels: size/S, lgtm, approved

#14583 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14586 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14591 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14596 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14598 upgrade to latest dependencies with websocket v1.5.0
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/google.golang.org/api/internal/version.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#14595 Drop CI reverse compatibility for auto-tls rename
  test/e2e-auto-tls-tests.sh
  test/e2e-common.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#14590 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#14601 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#14603 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14604 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14605 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14602 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14608 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14612 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14611 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14613 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14614 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14616 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14617 fix: typo in comments
  pkg/reconciler/revision/background.go
Labels: area/API, size/XS, lgtm, approved, ok-to-test

#14619 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#14623 Create and use the Reconciler constructor for the service controller
  pkg/reconciler/service/controller.go
  pkg/reconciler/service/service.go
Labels: area/API, size/S, lgtm, approved

#14636 Add `t.Parallel` on `TestShouldHaveStdinEOF`
  test/conformance/runtime/file_descriptor_test.go
Labels: size/XS, lgtm, approved, area/test-and-release

#14629 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14630 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14628 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14639 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, lgtm, approved

#14627 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14641 Move to Golang version 1.21
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#14638 Disable flaky ambient e2e tests
  .github/workflows/kind-e2e.yaml
Labels: size/S, lgtm, approved

#14647 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14649 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14651 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14650 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14600 Respect revision timeout defaults in cm
  pkg/apis/serving/v1/revision_defaults.go
  pkg/apis/serving/v1/revision_defaults_test.go
Labels: kind/bug, area/API, size/M, lgtm, approved

#14648 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14658 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/version.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14659 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14631 Update Serving encryption documentation to the newest developments
  docs/encryption/encryption-cluster-local-domain.drawio.svg
  docs/encryption/encryption-external-domain.drawio.svg
  docs/encryption/encryption-knative-internal.drawio.svg
  docs/encryption/encryption-system-internal.drawio.svg
  docs/encryption/knative-encryption.md
Labels: size/M, lgtm, approved

#14657 Variable name updated
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/apis/serving/v1/revision_defaults.go
Labels: area/API, size/L, lgtm, approved, ok-to-test

#14661 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_helpers.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#14665 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14664 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14667 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14668 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14671 Add clotributor link to readme
  README.md
Labels: size/XS, lgtm, approved

#14666 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14674 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14673 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14564 Rename env var for http2 autodetection
  pkg/queue/sharedmain/main.go
  pkg/queue/sharedmain/main_test.go
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved

#14676 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14672 Drop K8s 1.26 in GH actions and use K8s version 1.27 in prow
  .github/workflows/kind-e2e.yaml
  test/e2e-external-domain-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance/performance-tests.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#14678 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14679 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14680 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14677 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14681 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14683 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14684 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14685 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review
