Repository knative/serving, pull requests merged in 2023-02, with the labels that each got.

#13655 Adds slack links to CNCF Knative slack channel
  README.md
  support/COMMUNITY_CONTACTS.md
  support/support.rotation
Labels: size/XS, lgtm, approved, ok-to-test

#13667 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/L, lgtm, area/networking, approved

#13668 clean up OWNER files
  OWNERS
  cmd/OWNERS
  cmd/activator/OWNERS
  cmd/queue/OWNERS
  cmd/webhook/OWNERS
  config/OWNERS
  pkg/OWNERS
  pkg/activator/OWNERS
  pkg/http/OWNERS
  pkg/logging/OWNERS
  pkg/metrics/OWNERS
  pkg/queue/OWNERS
  pkg/reconciler/nscert/OWNERS
  pkg/reconciler/route/OWNERS
  pkg/testing/OWNERS
  third_party/OWNERS
Labels: area/API, size/L, lgtm, area/monitoring, area/networking, area/autoscale, approved, area/test-and-release

#13678 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#13681 use GITHUB_TOKEN when querying net-istio releases
  .github/workflows/kind-e2e.yaml
  test/e2e-common.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#13682 Add k8s 1.26 for kind test
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#13674 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13684 fix route reconciler test flakes
  pkg/reconciler/route/resources/ingress.go
Labels: area/API, size/S, lgtm, area/networking, approved

#13673 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#13672 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13685 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13687 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13686 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13676 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13683 fix curl invocation when fetching net-istio release
  test/e2e-common.sh
Labels: size/S, lgtm, approved, area/test-and-release

#13689 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13707 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13706 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13709 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  pkg/client/injection/reconciler/serving/v1/service/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/reconciler.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13702 Fix G112: Potential Slowloris Attacks lint errs
  cmd/default-domain/main.go
  pkg/autoscaler/statserver/server.go
  pkg/queue/sharedmain/main.go
Labels: area/API, size/S, lgtm, area/networking, area/autoscale, approved, kind/cleanup

#13705 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13699 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13703 Update support rotation contacts
  support/COMMUNITY_CONTACTS.md
  support/support.rotation
Labels: size/M, lgtm, approved

#13697 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13714 Update support rotation
  support/support.rotation
Labels: size/XS, lgtm, approved

#13713 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13715 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13716 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13698 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13717 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13718 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13719 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13724 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13666 check for renewing status
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
Labels: area/API, size/L, lgtm, area/networking, approved

#13726 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/controller.go
  pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/controller.go
  pkg/client/injection/reconciler/serving/v1/configuration/controller.go
  pkg/client/injection/reconciler/serving/v1/revision/controller.go
  pkg/client/injection/reconciler/serving/v1/route/controller.go
  pkg/client/injection/reconciler/serving/v1/service/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/domainmapping/controller.go
  pkg/client/injection/reconciler/serving/v1beta1/domainmapping/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13728 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13729 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13679 TestAutoscaleSustaining scales to 8 instead of 10
  .github/workflows/kind-e2e.yaml
  test/e2e/autoscale_test.go
Labels: size/XS, lgtm, approved, area/test-and-release

#13730 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13735 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13732 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13734 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13733 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13739 [release-1.9] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13740 [release-1.8] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13751 [release-1.8] pull in e2e fixes
  .github/workflows/kind-e2e.yaml
  test/e2e-common.sh
Labels: size/S, lgtm, approved, area/test-and-release

#13752 [release-1.9] pull in e2e fixes
  .github/workflows/kind-e2e.yaml
  test/e2e-common.sh
Labels: size/S, lgtm, approved, area/test-and-release

#13757 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13758 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved
