Repository knative/serving, pull requests merged in 2023-06, with the labels that each got.

#14027 poll until timeout - don't error out if the deployment can't be found
  pkg/reconciler/revision/revision_test.go
Labels: area/API, size/S, lgtm, approved

#14042 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14046 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#14047 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14048 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14049 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13887 Change minimum TLS version to 1.3 for internal encryption (between activator and queue-proxy)
  pkg/activator/certificate/cache.go
Labels: area/API, size/XS, lgtm, area/networking, area/autoscale, approved

#14055 refactor throttler_test.go
  pkg/activator/net/throttler_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, ok-to-test

#14065 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14064 Remove deprecated internalEncryption dependency
  pkg/reconciler/autoscaling/config/store_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/resources/service_test.go
  test/e2e/autoscale_test.go
Labels: area/API, size/S, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#14067 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14071 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/certificates/reconciler/certificates.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14069 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14070 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#14072 Get certificate reconciler from `networking` instead of `control-protocol`
  cmd/controller/main.go
  config/core/300-secret.yaml
  go.mod
  go.sum
  pkg/activator/certificate/cache.go
  pkg/activator/certificate/cache_test.go
  pkg/queue/sharedmain/main.go
  pkg/reconciler/revision/reconcile_resources.go
  third_party/VENDOR-LICENSE/knative.dev/control-protocol/pkg/certificates/LICENSE
  vendor/knative.dev/control-protocol/LICENSE
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_defaults.go
  vendor/knative.dev/networking/pkg/certificates/certs.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/key_pair.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/certificates.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/controller.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/controller_impl.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/reconciler.go
  vendor/modules.txt
Labels: area/API, size/XL, lgtm, area/networking, area/autoscale, approved

#14058 Change storage version of DomainMapping to v1beta1
  config/core/300-resources/domain-mapping.yaml
  config/post-install/storage-version-migration.yaml
Labels: size/XS, lgtm, approved

#14078 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14080 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#14081 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14086 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14087 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#14088 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14091 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14095 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/options.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/options.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#14098 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14018 Add chainguard-dev/actions for creating kind cluster
  .github/workflows/kind-e2e.yaml
Labels: size/L, lgtm, approved

#14079 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/L, lgtm, area/networking, approved

#14104 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14105 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#14106 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14107 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14022 fix: requests are sent to all pods even if cc=1 and the parity of activatorCount and podTracker is different
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: size/L, lgtm, area/networking, area/autoscale, approved, ok-to-test

#14101 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: size/S, lgtm, approved

#14110 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14109 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14112 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14116 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14119 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14125 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14038 Allow to set QP resources per service
  pkg/apis/serving/register.go
  pkg/apis/serving/v1/revision_validation.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: area/API, size/L, lgtm, approved

#14128 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14130 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved
