Repository knative/serving, pull requests merged in 2023-10, with the labels that each got.

#14472 Update certificates and SANs used in Serving
  cmd/activator/main.go
  go.mod
  go.sum
  pkg/activator/certificate/cache.go
  pkg/activator/certificate/cache_test.go
  pkg/reconciler/autoscaling/config/store_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/resources/service_test.go
  test/e2e-common.sh
  test/e2e/autoscale_test.go
  third_party/kourier-latest/kourier.yaml
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/fake/fake_image.go
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/certificates.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/controller.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/controller_impl.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/reconciler.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_realm.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_serverlessservice.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#14478 Update overlay-config for tests
  test/config/ytt/core/overlay-config-deployment.yaml
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#14092 internal encryption e2e tests
  pkg/activator/config/store.go
  pkg/activator/config/store_test.go
  test/e2e-common.sh
  test/e2e-internal-encryption-tests.sh
  test/e2e-tests.sh
  test/e2e/systeminternaltls/README.md
  test/e2e/systeminternaltls/system_internal_tls_test.go
Labels: area/API, size/L, lgtm, area/monitoring, area/networking, area/autoscale, approved, area/test-and-release

#14485 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14489 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14491 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14492 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14483 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14493 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14497 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, skip-review

#14503 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14502 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14505 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14500 [release-1.11] Rebuild using Go 1.20.10 (to address CVEs)
  go.mod
Labels: size/XS, lgtm, approved

#14501 [release-1.10] Rebuild using Go 1.20.10 (to address CVEs)
  go.mod
Labels: size/XS, lgtm, approved

#14512 bump x/net to v1.17
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14504 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14519 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14520 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14515 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/google.golang.org/api/internal/version.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14521 don't run internal encryption tests with contour
  test/e2e/systeminternaltls/system_internal_tls_test.go
Labels: size/XS, lgtm, approved, area/test-and-release

#14518 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14523 Bound buffer for reading stats
  pkg/autoscaler/metrics/http_scrape_client.go
  pkg/autoscaler/metrics/http_scrape_client_test.go
Labels: size/S, lgtm, area/autoscale, approved

#14526 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#14495 Shell executor logs through testing.T in upgrade tests
  test/upgrade/installation/shell.go
  third_party/VENDOR-LICENSE/knative.dev/hack/shell/LICENSE
  vendor/knative.dev/pkg/test/upgrade/shell/executor.go
  vendor/knative.dev/pkg/test/upgrade/shell/fail-example.sh
  vendor/knative.dev/pkg/test/upgrade/shell/prefixer.go
  vendor/knative.dev/pkg/test/upgrade/shell/project.go
  vendor/knative.dev/pkg/test/upgrade/shell/types.go
  vendor/modules.txt
Labels: size/L, lgtm, area/networking, approved, area/test-and-release

#14452 Trust DataPlaneUserSAN from Activator to Queue-Proxy
  cmd/activator/main.go
  go.mod
  go.sum
  pkg/activator/certificate/tls_context.go
  pkg/activator/certificate/tls_context_test.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/test/upgrade/shell/executor.go
  vendor/modules.txt
Labels: area/API, size/L, lgtm, area/networking, area/autoscale, approved

#14534 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14535 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14533 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14494 Test istio with system-internal-tls enabled
  .github/workflows/kind-e2e.yaml
  test/e2e/systeminternaltls/system_internal_tls_test.go
Labels: size/S, lgtm, approved, area/test-and-release

#14529 Fix sec context and resources for performance jobs
  test/performance/benchmarks/dataplane-probe/dataplane-probe-activator.yaml
  test/performance/benchmarks/dataplane-probe/dataplane-probe-deployment.yaml
  test/performance/benchmarks/dataplane-probe/dataplane-probe-queue.yaml
  test/performance/benchmarks/load-test/load-test-0-direct.yaml
  test/performance/benchmarks/load-test/load-test-200-direct.yaml
  test/performance/benchmarks/load-test/load-test-always-direct.yaml
  test/performance/benchmarks/real-traffic-test/real-traffic-test.yaml
  test/performance/benchmarks/reconciliation-delay/reconciliation-delay.yaml
  test/performance/benchmarks/rollout-probe/rollout-probe-activator-direct-lin.yaml
  test/performance/benchmarks/rollout-probe/rollout-probe-activator-direct.yaml
  test/performance/benchmarks/rollout-probe/rollout-probe-queue-proxy-direct.yaml
  test/performance/benchmarks/scale-from-zero/scale-from-zero-1.yaml
  test/performance/benchmarks/scale-from-zero/scale-from-zero-100.yaml
  test/performance/benchmarks/scale-from-zero/scale-from-zero-25.yaml
  test/performance/benchmarks/scale-from-zero/scale-from-zero-5.yaml
Labels: size/L, lgtm, approved, area/test-and-release

#14544 Add security policy reference in serving
  SECURITY.md
Labels: size/XS, lgtm, approved

#14531 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/gateway-api.yaml
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/XXL, lgtm, area/networking, approved

#14496 Bubble up KCertificate Status Message when its not ready
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/apis/serving/v1/route_lifecycle_test.go
  pkg/reconciler/route/route.go
  pkg/testing/v1/route.go
Labels: area/API, size/M, lgtm, area/networking, approved, area/test-and-release

#14545 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14550 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14549 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14546 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14551 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14552 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14555 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#14558 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14556 Replace the deprecated func with wait.PollUntilContextTimeout
  cmd/autoscaler/main.go
Labels: area/API, size/XS, lgtm, area/autoscale, approved

#14561 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#14562 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14559 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14570 Clean up feature keys
  pkg/webhook/podspec_dryrun_test.go
  pkg/webhook/validate_unstructured.go
  pkg/webhook/validate_unstructured_test.go
  test/e2e/service_validation_test.go
Labels: area/API, size/S, lgtm, approved, area/test-and-release
