Repository knative/serving, pull requests merged in 2023-01, with the labels that each got.

#13584 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, skip-review

#13559 Add setup script for internal-encryption e2e test
  test/e2e-internal-encryption-tests.sh
Labels: size/S, lgtm, approved, area/test-and-release

#13573 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/logger.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#13588 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13577 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13578 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/M, lgtm, area/networking, approved

#13593 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#13598 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13595 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13596 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13597 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13599 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13594 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13265 consistent label selector for Service - include app label
  config/core/deployments/domainmapping-webhook.yaml
  config/core/deployments/webhook.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#13604 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#13606 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved, skip-review

#13608 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved, skip-review

#13607 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved, skip-review

#13613 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13612 show an error when curling the istio release
  test/e2e-common.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#13614 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#13615 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/XXL, lgtm, area/networking, approved

#13535 Advancing pvc e2e test to beta
  test/e2e/pvc/pvc_test.go
Labels: area/API, size/XS, lgtm, approved, area/test-and-release, ok-to-test

#13585 Ensure the autoscaler only has a single elector
  cmd/autoscaler/leaderelection.go
  cmd/autoscaler/main.go
Labels: area/API, size/L, lgtm, area/autoscale, approved, area/test-and-release

#13565 Don't default Revision values when BYO name is unchanged.
  pkg/apis/serving/v1/configuration_defaults.go
  pkg/apis/serving/v1/configuration_defaults_test.go
  pkg/apis/serving/v1/service_defaults.go
Labels: area/API, size/M, lgtm, approved

#13616 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13619 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13620 DomainMapping: Set Certificate.Spec.Domain
  pkg/reconciler/domainmapping/resources/certificate.go
  pkg/reconciler/domainmapping/resources/certificate_test.go
  pkg/reconciler/domainmapping/table_test.go
Labels: area/API, size/XS, lgtm, approved

#13625 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, area/networking, approved

#13623 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13626 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13399 Add validation to warn about insecure SecurityContext defaults
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/apis/serving/v1/configuration_validation_test.go
  pkg/apis/serving/v1/revision_validation_test.go
  pkg/apis/serving/v1/service_validation_test.go
Labels: area/API, size/L, lgtm, approved

#13624 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13618 Refactor autoscaler TestContext
  test/e2e/autoscale.go
  test/e2e/autoscale_hpa_test.go
  test/e2e/autoscale_test.go
  test/e2e/grpc_test.go
  test/e2e/service_to_service_test.go
  test/e2e/websocket_test.go
  test/ha/autoscaler_test.go
  test/upgrade/autoscaler.go
Labels: size/L, lgtm, approved, area/test-and-release

#13627 Don't explicitly require a service account key for autotls dns tests
  go.mod
  test/e2e/autotls/config/dnscleanup/main.go
  test/e2e/autotls/config/dnssetup/main.go
  test/e2e/autotls/config/util.go
Labels: size/M, lgtm, approved, area/test-and-release

#13628 Clean up `go_run` functions
  test/e2e-common.sh
  test/performance/performance-tests.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#13633 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13632 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13635 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13634 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#13637 Allow challenges for hosts that don't match the route's host
  pkg/reconciler/domainmapping/resources/ingress.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/table_test.go
Labels: area/API, size/M, lgtm, area/networking, approved

#13636 Change HTTP01 test DNS entry to *.{custom-domain}
  test/e2e-auto-tls-tests.sh
Labels: size/XS, lgtm, approved, area/test-and-release

#13398 Add secure-pod-defaults flag to default Pods to 'restricted' profile by default
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  config/core/configmaps/features.yaml
  hack/schemapatch-config.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
  pkg/apis/serving/v1/revision_defaults.go
  pkg/apis/serving/v1/revision_defaults_test.go
  test/e2e-tests.sh
  test/e2e/securedefaults/secure_pod_defaults_test.go
Labels: area/API, size/L, lgtm, approved, area/test-and-release

#13642 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13641 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#13644 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13643 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13646 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13648 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13649 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13650 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13654 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13656 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved
