Repository knative/serving, pull requests merged in 2023-05, with the labels that each got.

#13933 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13934 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#13925 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13929 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13926 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13939 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13940 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#13941 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13942 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13943 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#13945 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13944 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13949 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13950 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#13951 Install ko using setup-ko, from ko-build
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#13960 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#13961 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13958 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13962 TLS minimum version for tag to digest defaults to 1.2 again and is configurable
  pkg/reconciler/revision/resolve.go
  pkg/reconciler/revision/resolve_test.go
Labels: area/API, size/L, lgtm, approved

#13959 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13972 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#13976 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13975 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, lgtm, area/networking, approved

#13978 Autoscaler metric annotations work with global class config
  pkg/apis/autoscaling/annotation_validation.go
  pkg/apis/autoscaling/annotation_validation_test.go
Labels: area/API, size/S, lgtm, area/autoscale, approved

#13964 Set default domain to cluster's domain
  pkg/reconciler/route/config/domain.go
Labels: area/API, size/XS, lgtm, area/networking, approved

#13974 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13988 Update cluster-version to 1.25
  test/e2e-auto-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance/performance-tests-mako.sh
  test/performance/performance-tests.sh
Labels: size/S, lgtm, approved, area/test-and-release

#13992 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#13991 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#13990 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#13993 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14007 Remove 1.24 kind version
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#13998 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14008 Bump kind to 0.19
  .github/workflows/kind-e2e.yaml
Labels: size/S, lgtm, approved

#14010 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved

#14009 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14003 [Automated] Update net-gateway-api nightly
  test/e2e-networking-library.sh
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved, area/test-and-release

#14013 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14016 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved

#14025 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14004 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved

#14019 Fix metrics reporting period
  config/core/configmaps/observability.yaml
  pkg/queue/sharedmain/main.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved

#14028 RandomChoice 2 policy wasn't random when the number of targets is 2 (with equal weight)
  pkg/activator/net/lb_policy.go
  pkg/activator/net/lb_policy_test.go
Labels: size/M, lgtm, area/networking, area/autoscale, approved

#14031 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#14035 drop safe to evict annotations
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
  config/core/deployments/domainmapping-webhook.yaml
  config/core/deployments/webhook.yaml
  config/hpa-autoscaling/controller.yaml
Labels: size/S, lgtm, approved

#14040 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/S, lgtm, area/networking, approved

#14041 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved

#14043 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: size/M, lgtm, approved
