Repository knative/serving, pull requests merged in 2024-05, with the labels that each got.

#15172 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15175 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15173 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15176 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15179 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15178 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15177 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15183 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15185 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15189 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#15186 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15187 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/google.golang.org/api/dns/v1/dns-api.json
  vendor/google.golang.org/api/dns/v1/dns-gen.go
  vendor/google.golang.org/api/internal/gensupport/params.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/encoding/tag/tag.go
  vendor/google.golang.org/protobuf/internal/errors/errors.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/placeholder.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_enum.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_extension.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_file.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/messageset.go
  vendor/google.golang.org/protobuf/proto/size.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#15180 Tests for multi-container readiness and liveness probes
  pkg/apis/serving/k8s_validation.go
  pkg/testing/v1/service.go
  test/conformance/api/v1/service_test.go
  test/conformance/runtime/liveness_probe_test.go
  test/conformance/runtime/readiness_probe_test.go
  test/e2e/e2e.go
  test/e2e/minscale_readiness_test.go
  test/e2e/multicontainer_test.go
  test/e2e/multicontainerprobing/multicontainer_readiness_test.go
  test/e2e/readiness_test.go
  test/test_images/grpc-ping/main.go
  test/test_images/multicontainer/servingcontainer/servingcontainer.go
  test/test_images/readiness/readiness.go
Labels: size/XL, lgtm, approved

#15193 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15192 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15195 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15184 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15194 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15197 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15199 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15198 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15196 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15188 Add e2e test for Contour when CORS policy is enabled
  test/e2e-tests.sh
  test/e2e/corspolicy/cors_policy_test.go
Labels: size/L, lgtm, approved

#15209 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15206 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15212 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, skip-review

#15214 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15215 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, skip-review

#15170 change private K8s service to be a headless service
  pkg/reconciler/serverlessservice/resources/services.go
  pkg/reconciler/serverlessservice/resources/services_test.go
Labels: size/XS, lgtm, approved

#15213 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15220 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15218 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15219 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15224 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/genproto/googleapis/rpc/code/code.pb.go
  vendor/google.golang.org/genproto/googleapis/rpc/errdetails/error_details.pb.go
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/google.golang.org/grpc/CONTRIBUTING.md
  vendor/google.golang.org/grpc/MAINTAINERS.md
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codegen.sh
  vendor/google.golang.org/grpc/codes/codes.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/config.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/gracefulswitch.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcutil/compressor.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/peer/peer.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/stream_interfaces.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#15228 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15233 Add pod anti affinity rules to activator component
  config/core/deployments/activator.yaml
Labels: size/S, lgtm, approved

#15227 Cleanup resources from DeploymentFailure upgrade test
  test/upgrade/deployment_failure.go
Labels: size/S, lgtm, approved

#15230 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15229 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15235 Fix e2e script to disable cors policy for Contour tests
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#15234 fix cluster-local routes being stalled when external-domain-tls is enabled
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/testing/v1/route.go
Labels: size/L, lgtm, approved

#15204 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15249 Remove CORS tests from serving
  test/e2e-tests.sh
  test/e2e/corspolicy/cors_policy_test.go
Labels: size/L, lgtm, approved

#15246 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/L, skip-review

#15256 fix: Fixed liveness periodseconds to 10 so that crashloopback off doe…
  config/core/deployments/webhook.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#15260 Drop the k8s service name from kubectl get revision output
  config/core/300-resources/revision.yaml
Labels: size/XS, lgtm, approved

#15264 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#15265 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15261 Remove certmanager integration tests
  test/e2e/certmanager/config/100-serving-namespace.yaml
  test/e2e/certmanager/config/100-test-namespace.yaml
  test/e2e/certmanager/config/200-service-account.yaml
  test/e2e/certmanager/config/201-cluster-role.yaml
  test/e2e/certmanager/config/300-certificate.yaml
  test/e2e/certmanager/config/autotls/certmanager/caissuer/config-certmanager.yaml
  test/e2e/certmanager/config/autotls/certmanager/caissuer/generate.sh
  test/e2e/certmanager/config/autotls/certmanager/caissuer/issuer.yaml
  test/e2e/certmanager/config/autotls/certmanager/caissuer/secret.yaml
  test/e2e/certmanager/config/autotls/certmanager/http01/config-certmanager.yaml
  test/e2e/certmanager/config/autotls/certmanager/http01/issuer.yaml
  test/e2e/certmanager/config/autotls/certmanager/http01/mesh-issuer.yaml
  test/e2e/certmanager/config/autotls/certmanager/selfsigned/config-certmanager.yaml
  test/e2e/certmanager/config/autotls/certmanager/selfsigned/issuer.yaml
  test/e2e/certmanager/conformance/certificate_test.go
  test/e2e/certmanager/e2e-common.sh
  test/e2e/certmanager/e2e-tests.sh
  test/e2e/certmanager/presubmit-tests.sh
  test/e2e/certmanager/upload-test-images.sh
  vendor/knative.dev/networking/test/cleanup.go
  vendor/knative.dev/networking/test/clients.go
  vendor/knative.dev/networking/test/conformance/certificate/http01/certificate.go
  vendor/knative.dev/networking/test/conformance/certificate/http01/run.go
  vendor/knative.dev/networking/test/conformance/certificate/nonhttp01/certificate.go
  vendor/knative.dev/networking/test/conformance/certificate/nonhttp01/run.go
  vendor/knative.dev/networking/test/conformance/certificate/utils.go
  vendor/knative.dev/networking/test/defaultsystem/system.go
  vendor/knative.dev/networking/test/e2e_constants.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/knative.dev/networking/test/ingress.go
  vendor/knative.dev/networking/test/presubmit-tests.sh
  vendor/knative.dev/networking/test/prober.go
  vendor/knative.dev/networking/test/upload-test-images.sh
  vendor/knative.dev/networking/test/util.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#15272 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15273 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15282 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15275 Revert headless service change from k8s private service
  pkg/reconciler/serverlessservice/resources/services.go
  pkg/reconciler/serverlessservice/resources/services_test.go
Labels: size/XS, lgtm, approved

#15280 Do not delete ingress Secret in tests for internal tls
  test/e2e/systeminternaltls/system_internal_tls_test.go
Labels: size/XS, lgtm, approved

#15281 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15277 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15283 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15287 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review
