Repository knative/serving, pull requests merged in 2024-12, with the labels that each got.

#15647 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, skip-review

#15654 [performance/real-traffic-test] Enable AllowHTTPFullDuplexFeature
  test/performance/benchmarks/real-traffic-test/main.go
Labels: size/S, lgtm, approved

#15657 Pin version of the chainguard kind setup action
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#15656 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15659 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15661 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15660 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15655 Drop k8s v1.28 from kind testing and update cluster version to 1.30 in e2e
  .github/workflows/kind-e2e.yaml
  test/e2e-external-domain-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance/performance-tests.sh
Labels: size/S, lgtm, approved

#15658 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/gateway-api.yaml
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/XXL, skip-review

#15665 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15643 Allow securityContext.Privileged to be configurable
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  hack/schemapatch-config.yaml
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/k8s_validation_test.go
Labels: size/M, lgtm, approved, ok-to-test

#15475 fix: fixed the pinned dependencies issue
  .github/dependabot.yaml
  .github/workflows/kind-e2e.yaml
Labels: size/S, lgtm, approved, ok-to-test
