Repository knative/serving, pull requests merged in 2024-02, with the labels that each got.

#14854 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14859 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14858 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14851 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14856 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14857 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14861 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14840 [release-1.12] Don't drop traffic when upgrading a deployment fails
  pkg/apis/serving/k8s_lifecycle.go
  pkg/apis/serving/k8s_lifecycle_test.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_helpers_test.go
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/resources/pa.go
  pkg/reconciler/revision/resources/pa_test.go
  pkg/reconciler/revision/table_test.go
  test/upgrade/deployment_failure.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
Labels: area/API, size/L, lgtm, area/autoscale, approved, area/test-and-release

#14868 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/cba.go
  vendor/google.golang.org/api/internal/version.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14795 Don't drop traffic when upgrading a deployment fails
  pkg/apis/serving/k8s_lifecycle.go
  pkg/apis/serving/k8s_lifecycle_test.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_helpers_test.go
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/resources/pa.go
  pkg/reconciler/revision/resources/pa_test.go
  pkg/reconciler/revision/table_test.go
  test/upgrade/deployment_failure.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
Labels: area/API, size/L, lgtm, area/autoscale, approved, area/test-and-release

#14870 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14543 feat: Add ability to configure multiple wilcard domains
  pkg/reconciler/nscert/nscert.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/route/config/domain.go
  pkg/reconciler/route/config/domain_test.go
  pkg/reconciler/route/config/store_test.go
  pkg/reconciler/route/config/zz_generated.deepcopy.go
  pkg/reconciler/route/domains/domains_test.go
  pkg/reconciler/route/resources/ingress_test.go
  pkg/reconciler/route/resources/service_test.go
  pkg/reconciler/route/table_test.go
  pkg/reconciler/route/traffic/traffic_test.go
  pkg/reconciler/route/visibility/visibility_test.go
Labels: area/API, size/L, lgtm, area/networking, approved, ok-to-test

#14873 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/L, area/networking, skip-review

#14878 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#14865 Updating DEVELOPMENT.md to remove reference to allowedFields or preserveUnknownFields
  DEVELOPMENT.md
Labels: size/S, lgtm, approved, ok-to-test

#14880 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14886 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14883 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14885 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14890 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14884 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14892 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14896 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14893 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14891 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14895 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14898 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14899 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved, skip-review

#14901 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, area/networking, approved, skip-review

#14875 Add revision-failure test image
  test/test_images/revisionfailure/revisionfailure.go
  test/test_images/revisionfailure/service.yaml
Labels: size/M, lgtm, approved, area/test-and-release

#14902 test/e2e: WaitForScaleToZero assertion isn't strict enough
  test/e2e/e2e.go
Labels: size/XS, lgtm, approved, area/test-and-release

#14904 Drop k8s v1.27 from kind testing and update cluster version to 1.28 in e2e
  .github/workflows/kind-e2e.yaml
  test/e2e-external-domain-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance/performance-tests.sh
Labels: size/S, lgtm, approved, area/test-and-release

#14908 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14906 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14907 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14905 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14910 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14900 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, approved, skip-review

#14912 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14913 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/go.opentelemetry.io/otel/CHANGELOG.md
  vendor/go.opentelemetry.io/otel/CODEOWNERS
  vendor/go.opentelemetry.io/otel/CONTRIBUTING.md
  vendor/go.opentelemetry.io/otel/attribute/set.go
  vendor/go.opentelemetry.io/otel/version.go
  vendor/go.opentelemetry.io/otel/versions.yaml
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#14914 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14917 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#14915 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14919 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14921 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14922 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14911 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14927 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/factory.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14929 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/XXL, area/networking, skip-review

#14932 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14931 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14928 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14930 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14934 Update workflows to use knative/actions/setup-go
  .github/workflows/kind-e2e.yaml
  config/core/300-resources/configuration.yaml
  config/core/300-resources/domain-mapping.yaml
  config/core/300-resources/metric.yaml
  config/core/300-resources/podautoscaler.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/route.yaml
  config/core/300-resources/service.yaml
Labels: size/XXL, lgtm, approved

#14938 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14937 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved, skip-review

#14936 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#14941 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/config/image.yaml
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14944 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14946 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/gateway-api.yaml
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/XL, area/networking, skip-review

#14945 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14947 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/github.com/googleapis/gax-go/v2/.release-please-manifest.json
  vendor/github.com/googleapis/gax-go/v2/CHANGES.md
  vendor/github.com/googleapis/gax-go/v2/callctx/callctx.go
  vendor/github.com/googleapis/gax-go/v2/header.go
  vendor/github.com/googleapis/gax-go/v2/internal/version.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/common.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/LICENSE
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/google.golang.org/api/internal/version.go
  vendor/modules.txt
Labels: size/XL, lgtm, area/networking, approved

#14954 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14943 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14952 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14953 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14956 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14959 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14958 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14960 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14957 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review
