Repository knative/serving, pull requests merged in 2024-09, with the labels that each got.

#15491 Migrate to kube codegen
  hack/update-codegen.sh
  pkg/apis/zz_generated.deepcopy.go
Labels: size/M, lgtm, approved

#15492 Fix deepcopy gen
  hack/update-codegen.sh
  pkg/reconciler/certificate/config/zz_generated.deepcopy.go
Labels: size/S, lgtm, approved

#15493 [RELEASE-1.15] Fix deepcopy gen
  hack/update-codegen.sh
  pkg/reconciler/certificate/config/zz_generated.deepcopy.go
Labels: size/XS, lgtm, approved

#15495 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15496 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15498 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15499 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15502 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved, skip-review

#15501 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, skip-review

#15500 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, skip-review

#15505 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20poly1305/chacha20poly1305_amd64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_amd64.s
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_hurd.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_zos_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/term_windows.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#15508 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15507 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15509 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15511 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15513 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15512 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15514 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/internal/aliases/aliases.go
  vendor/golang.org/x/tools/internal/aliases/aliases_go121.go
  vendor/golang.org/x/tools/internal/aliases/aliases_go122.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/ureader_yes.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/internal/pkgbits/encoder.go
  vendor/golang.org/x/tools/internal/pkgbits/frames_go1.go
  vendor/golang.org/x/tools/internal/pkgbits/frames_go17.go
  vendor/golang.org/x/tools/internal/pkgbits/support.go
  vendor/golang.org/x/tools/internal/pkgbits/sync.go
  vendor/golang.org/x/tools/internal/pkgbits/syncmarker_string.go
  vendor/golang.org/x/tools/internal/pkgbits/version.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode.go
  vendor/google.golang.org/grpc/experimental/stats/metricregistry.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/mem/buffer_slice.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#15515 Unpin github.com/gorilla/websocket
  go.mod
  go.sum
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15518 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15517 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, skip-review

#15519 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15520 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/metadata/CHANGES.md
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/compute/metadata/syscheck.go
  vendor/cloud.google.com/go/compute/metadata/syscheck_linux.go
  vendor/cloud.google.com/go/compute/metadata/syscheck_windows.go
  vendor/github.com/gobuffalo/flect/humanize.go
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/mksyscall.go
  vendor/golang.org/x/sys/windows/registry/syscall.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/credentials/insecure/insecure.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/grpclog/internal/logger.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/server.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/channelz/channelmap.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/channelz/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/passthrough/passthrough.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/keepalive/keepalive.go
  vendor/google.golang.org/grpc/mem/buffers.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/stream_interfaces.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#15525 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, skip-review

#15526 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15527 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/crd.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15524 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15530 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15522 Use istio.sidecar.inject label instead of annotation
  config/post-install/cleanup.yaml
  config/post-install/default-domain.yaml
  config/post-install/storage-version-migration.yaml
  pkg/reconciler/revision/resources/deploy_test.go
  test/config/externaldomaintls/certmanager/http01/mesh-issuer.yaml
  test/e2e/httpproxy.go
  test/e2e/service_to_service_test.go
Labels: size/M, lgtm, approved

#15534 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved, skip-review

#15535 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15536 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, skip-review

#15537 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, lgtm, approved
