Repository knative/serving, pull requests merged in 2024-03, with the labels that each got.

#14963 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14965 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14964 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14966 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, area/networking, approved, skip-review

#14971 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved, skip-review

#14969 Modify the description of ConfigMap config-defaults
  config/core/configmaps/defaults.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#14970 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#14978 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14976 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14977 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#14974 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14975 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14982 Removed superfluous else statement
  pkg/http/request_log.go
Labels: size/S, lgtm, area/networking, approved, ok-to-test

#14985 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#14987 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14991 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#14986 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14717 add upstream TLS trust from CM bundles
  pkg/activator/certificate/cache.go
  pkg/activator/certificate/cache_test.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/configmap/configmap.go
  vendor/modules.txt
Labels: size/L, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#14993 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, area/networking, approved, skip-review

#14973 Replace deprecated uses of sets.Int
  test/e2e/externaldomaintls/http_redirect_test.go
  test/e2e/externaldomaintls/util_test.go
Labels: size/XS, lgtm, area/networking, approved, area/test-and-release, ok-to-test

#14996 Check for nil before calling deep-equal
  pkg/activator/certificate/cache_test.go
Labels: size/XS, lgtm, area/networking, area/autoscale, approved

#14995 Re-activate disabled istio tls tests
  .github/workflows/kind-e2e.yaml
  test/e2e/systeminternaltls/system_internal_tls_test.go
Labels: size/S, lgtm, approved, area/test-and-release

#14998 add contour-gateway.yaml to third_party folder
  test/e2e-common.sh
  third_party/gateway-api-latest/contour-gateway.yaml
Labels: size/L, lgtm, area/networking, approved, area/test-and-release

#15001 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#15002 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#15005 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#15003 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#15004 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#14853 Add multi-container probing
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
  pkg/apis/serving/v1/revision_defaults.go
  pkg/apis/serving/v1/revision_defaults_test.go
  pkg/apis/serving/v1/revision_helpers.go
  pkg/apis/serving/v1/revision_helpers_test.go
  pkg/queue/readiness/probe.go
  pkg/queue/readiness/probe_encoding.go
  pkg/queue/readiness/probe_encoding_test.go
  pkg/queue/readiness/probe_test.go
  pkg/queue/sharedmain/main.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
  test/e2e-tests.sh
  test/e2e/multicontainerprobing/multicontainer_readiness_test.go
Labels: area/API, size/XXL, lgtm, area/networking, area/autoscale, approved, area/test-and-release

#15006 [main] Format Go code
  pkg/queue/readiness/probe_test.go
Labels: size/XS, lgtm, area/networking, area/autoscale, approved

#15009 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#15008 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#15018 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#15016 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, area/networking, approved, skip-review

#15017 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#15015 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#15012 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15020 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#15023 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#15024 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#15025 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#15036 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#15037 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#15038 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, area/networking, skip-review

#14744 Check all container's status when calculating revision ContainerHealthy condition
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/reconciler/revision/reconcile_resources.go
Labels: area/API, size/XS, lgtm, approved, ok-to-test

#15039 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#15043 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, area/networking, skip-review

#15044 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, area/networking, skip-review

#15048 Use a copy to modify the existing secret
  pkg/activator/certificate/cache_test.go
Labels: size/S, lgtm, area/networking, area/autoscale, approved

#15045 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, area/networking, skip-review

#15040 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#15034 remove special logic for user-agent header with istio mtls
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/webhook.yaml
  pkg/queue/handler_test.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: area/API, size/M, lgtm, area/networking, area/autoscale, approved

#15042 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, area/networking, skip-review

#14866 Prevent a PodAutoscaler's DesiredScale to turn to -1
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
Labels: area/API, size/L, lgtm, area/autoscale, approved, ok-to-test

#15051 Drop unused OWNER files and drop productivity folks from being tagged for review
  cmd/OWNERS
  cmd/activator/OWNERS
  cmd/autoscaler-hpa/OWNERS
  cmd/autoscaler/OWNERS
  cmd/queue/OWNERS
  cmd/webhook/OWNERS
  hack/OWNERS
  pkg/activator/OWNERS
  pkg/apis/OWNERS
  pkg/apis/autoscaling/OWNERS
  pkg/autoscaler/OWNERS
  pkg/gc/OWNERS
  pkg/http/OWNERS
  pkg/leaderelection/OWNERS
  pkg/logging/OWNERS
  pkg/metrics/OWNERS
  pkg/queue/OWNERS
  pkg/reconciler/OWNERS
  pkg/reconciler/autoscaling/OWNERS
  pkg/reconciler/nscert/OWNERS
  pkg/reconciler/route/OWNERS
  pkg/resources/OWNERS
  pkg/testing/OWNERS
  pkg/webhook/OWNERS
  test/OWNERS
  third_party/OWNERS
Labels: area/API, size/L, lgtm, area/monitoring, area/networking, area/autoscale, approved, area/test-and-release

#15053 disable kourier-tls
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#15056 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15055 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15057 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15058 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15059 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15061 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15063 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15064 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15062 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15065 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review
