Repository knative/serving, pull requests merged in 2024-04, with the labels that each got.

#15069 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15072 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15073 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15071 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15076 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/version.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#15075 Update kapp/ytt/kail versions
  .github/workflows/kind-e2e.yaml
  test/e2e-common.sh
Labels: size/S, lgtm, approved

#15077 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15079 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15080 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, skip-review

#15081 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15083 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15084 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15086 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15088 bring back e2e kind testing with Gateway API and Istio
  .github/workflows/kind-e2e.yaml
Labels: size/S, lgtm, approved

#15094 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15098 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15099 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15100 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15103 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15102 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15104 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#15106 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15107 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15093 add e2e kind testing with Gateway API and Contour
  .github/workflows/kind-e2e.yaml
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/service_test.go
  test/e2e/destroypod_test.go
Labels: size/M, lgtm, approved

#15105 chore: fix function names in comment
  test/conformance/api/v1/generatename_test.go
  test/conformance/api/v1/revision_timeout_test.go
  test/conformance/runtime/header_test.go
  test/e2e/timeout_test.go
Labels: size/XS, lgtm, approved, ok-to-test

#15108 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15109 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#15110 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15111 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, skip-review

#15112 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/M, lgtm, approved, skip-review

#15113 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved, skip-review

#15114 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, skip-review

#15082 Make route domain error specific
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/reconciler/route/domains/domains.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/testing/v1/route.go
Labels: size/M, lgtm, approved

#15115 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15116 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15118 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15117 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15119 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15124 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, skip-review

#15123 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, skip-review

#15125 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, skip-review

#15126 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved, skip-review

#15127 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved, skip-review

#15132 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15135 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15130 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15137 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15138 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15140 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, skip-review

#15139 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, skip-review

#15142 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, skip-review

#15143 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, lgtm, approved, skip-review

#15141 bump istio,contour,cert-manager
  test/e2e-networking-library.sh
  third_party/cert-manager-latest/cert-manager.yaml
  third_party/cert-manager-latest/download-cert-manager.sh
Labels: size/L, lgtm, approved

#15144 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, skip-review

#15146 Disable logstream so the Github Action Log Viewer works
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#15136 [Automated] Update net-gateway-api nightly
  test/e2e-networking-library.sh
  third_party/gateway-api-latest/contour-gateway.yaml
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/L, lgtm, approved, skip-review

#15153 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15151 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15152 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#15147 cleanup service after tests completes
  test/conformance/runtime/container_test.go
Labels: size/XS, lgtm, approved, skip-review

#14962 feat: bubble up kcert status message when it's failed
  pkg/apis/serving/v1/route_lifecycle.go
  pkg/apis/serving/v1/route_lifecycle_test.go
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/testing/v1/route.go
Labels: area/API, size/L, lgtm, area/networking, approved, ok-to-test

#15150 re-enable contour gateway tests
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1/service_test.go
Labels: size/S, lgtm, approved

#15157 [Automated] Update net-certmanager nightly
  third_party/cert-manager-latest/net-certmanager.yaml
Labels: size/M, lgtm, approved, skip-review

#15158 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/contour-gateway.yaml
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/L, lgtm, approved, skip-review

#15159 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/contour-gateway.yaml
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/M, lgtm, approved, skip-review

#15160 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15165 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15164 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15167 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15163 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15168 Cleanup net-certmanager integration
  config/core/configmaps/logging.yaml
  test/config/ytt/certmanager/net-certmanager-config.yaml
  test/config/ytt/core/overlay-config-logging.yaml
  test/config/ytt/ingress/istio/istio-certmanager-webhook.yaml
  test/e2e-common.sh
  test/e2e/certmanager/e2e-common.sh
  test/e2e/externaldomaintls/README.md
Labels: size/S, lgtm, approved

#15169 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, skip-review
