Repository knative/serving, pull requests merged in 2024-08, with the labels that each got.

#15434 Fix bug in cert manager config
  pkg/reconciler/certificate/config/cert_manager.go
  pkg/reconciler/certificate/config/cert_manager_test.go
Labels: size/M, lgtm, approved, ok-to-test

#15414 Add support for hostipc, hostpid and hostnetwork
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  config/core/configmaps/features.yaml
  hack/schemapatch-config.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/serving/fieldmask.go
Labels: size/L, lgtm, approved

#15439 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15444 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15445 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15447 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/tsenart/vegeta/v12/README.md
  vendor/github.com/tsenart/vegeta/v12/attack.go
  vendor/github.com/tsenart/vegeta/v12/flags.go
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/golang.org/x/sync/LICENSE
  vendor/modules.txt
Labels: size/L, lgtm, approved

#15446 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15443 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15448 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15451 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15452 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15453 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15455 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15457 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15458 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15456 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15460 drop dev container as no one is maintaining it
  .devcontainer/devcontainer.json
  .devcontainer/docker-start.sh
  .devcontainer/setup.sh
  DEVELOPMENT.md
Labels: size/L, lgtm, approved

#15461 E2E tests for startup probe
  pkg/testing/v1/service.go
  test/conformance/runtime/liveness_probe_test.go
  test/e2e/multicontainerprobing/multicontainer_readiness_test.go
  test/e2e/readiness_test.go
  test/util.go
Labels: size/L, lgtm, approved

#15463 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15467 update schema-config
  hack/schemapatch-config.yaml
Labels: size/XS, lgtm, approved

#15469 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#15470 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15471 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15476 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review
