Repository knative/serving, pull requests merged in 2025-01, with the labels that each got.

#15668 fix dependabot config
  .github/dependabot.yaml
Labels: size/XS, lgtm, approved

#15672 fix dependabot config for actions that aren't versioned
  .github/dependabot.yaml
Labels: size/XS, lgtm, approved

#15674 dependabot - fix dependency name
  .github/dependabot.yaml
Labels: size/XS, lgtm, approved

#15671 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15664 Drop the use dprotaso/controller-tools fork
  cmd/schema-tweak/main.go
  cmd/schema-tweak/overrides.go
  cmd/schema-tweak/yaml.go
  config/core/300-resources/configuration.yaml
  config/core/300-resources/domain-mapping.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  go.mod
  hack/schemapatch-config.yaml
  hack/update-schemas.sh
  pkg/apis/config/features.go
Labels: size/XXL, lgtm, approved

#15675 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15662 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#15669 Update volume validation to include hostPath
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
Labels: size/M, lgtm, approved, ok-to-test

#15676 dependabot - add wildcard back to ignore names
  .github/dependabot.yaml
Labels: size/XS, lgtm, approved

#15679 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15680 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15678 [Automated] Update net-contour nightly
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
Labels: size/L, skip-review

#15683 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_helpers.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#15685 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15690 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15692 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#15689 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15691 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15696 Exclude kourier tls runtime
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#15699 fix builds on arm/v7
  pkg/gc/config.go
Labels: size/XS, lgtm, approved

#15694 Set k8s default container label
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/meta.go
  pkg/reconciler/revision/resources/meta_test.go
Labels: size/M, lgtm, approved, ok-to-test

#15701 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/fake/fake_image.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/image.go
  vendor/knative.dev/caching/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/caching/pkg/client/listers/caching/v1alpha1/image.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#15709 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15708 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15711 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15710 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15503 Ensure ContainerHealthy condition is set back to True
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/table_test.go
  pkg/testing/functional.go
  pkg/testing/v1/revision.go
Labels: size/L, lgtm, approved, ok-to-test

#15717 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15719 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, lgtm, approved, skip-review

#15720 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, lgtm, approved, skip-review

#15681 Allow paths without a leading slash in probes
  pkg/queue/health/probe.go
Labels: size/XS, lgtm, approved

#15718 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, lgtm, approved, skip-review

#15723 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15725 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15727 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15726 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15728 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15733 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#15735 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15734 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15737 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15736 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15739 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.opentelemetry.io/otel/.gitignore
  vendor/go.opentelemetry.io/otel/.golangci.yml
  vendor/go.opentelemetry.io/otel/CHANGELOG.md
  vendor/go.opentelemetry.io/otel/CONTRIBUTING.md
  vendor/go.opentelemetry.io/otel/Makefile
  vendor/go.opentelemetry.io/otel/internal/global/instruments.go
  vendor/go.opentelemetry.io/otel/internal/global/meter.go
  vendor/go.opentelemetry.io/otel/internal/global/trace.go
  vendor/go.opentelemetry.io/otel/version.go
  vendor/go.opentelemetry.io/otel/versions.yaml
  vendor/golang.org/x/oauth2/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/producer.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/internal/flags/flags.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map_go111.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map_go112.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/convert_map.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#15742 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15741 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15743 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review
