Repository knative/serving, pull requests merged in 2025-10, with the labels that each got.

#16078 add default conditions to PA to avoid potential race conditions (2nd attempt)
  config/core/300-resources/podautoscaler.yaml
  docs/serving-api.md
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/serving/v1/revision_lifecycle.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/testing/v1/factory.go
Labels: size/M, lgtm, approved

#16120 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: size/M, skip-review

#16121 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#16122 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#16123 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#16124 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review
