Repository knative/serving, pull requests merged in 2025-02, with the labels that each got.

#15732 Fix kourier tls runtime tests
  .github/workflows/kind-e2e.yaml
  pkg/activator/handler/handler.go
  pkg/activator/handler/handler_test.go
  pkg/activator/net/throttler.go
  pkg/activator/net/throttler_test.go
Labels: size/M, lgtm, approved

#15750 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15749 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/spf13/pflag/.editorconfig
  vendor/github.com/spf13/pflag/.golangci.yaml
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_serverlessservice.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/serverlessservice.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/serverlessservice.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#15757 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15763 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15762 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15769 Add a test for using a probe path without a leading slash
  pkg/queue/health/probe_test.go
Labels: size/L, lgtm, approved

#15771 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15774 bump min k8s version to v1.31
  .github/workflows/kind-e2e.yaml
  test/e2e-external-domain-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance/performance-tests.sh
Labels: size/S, lgtm, approved

#15776 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15775 Fix golangci exclude config
  .golangci.yaml
Labels: size/XS, lgtm, approved

#15779 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15782 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#15783 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/caching_client.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/fake/fake_caching_client.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/fake/fake_image.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/image.go
  vendor/knative.dev/caching/pkg/client/informers/externalversions/caching/v1alpha1/image.go
  vendor/knative.dev/caching/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/caching/pkg/client/listers/caching/v1alpha1/image.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_networking_client.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_serverlessservice.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/networking_client.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/serverlessservice.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/serverlessservice.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/serverlessservice.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#15784 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15785 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15787 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15788 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15789 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15793 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/modules.txt
Labels: size/L, lgtm, approved
