Repository knative/serving, pull requests merged in 2025-05, with the labels that each got.

#15875 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15879 Bump K8s cluster verison
  .github/workflows/kind-e2e.yaml
  test/e2e-external-domain-tls-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/performance/performance-tests.sh
Labels: size/S, lgtm, approved

#15888 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15886 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15887 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15885 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15894 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#15878 Add support for Kubernetes “image” volume type
  cmd/schema-tweak/overrides.go
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  config/core/configmaps/features.yaml
  pkg/apis/config/features.go
  pkg/apis/config/features_test.go
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/k8s_validation.go
  pkg/apis/serving/k8s_validation_test.go
Labels: size/L, lgtm, approved

#15892 Fix labels and annotations propagation to k8s service on update
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/table_test.go
  pkg/testing/v1/service.go
  test/conformance/api/v1/service_test.go
  test/conformance/api/v1/util.go
Labels: kind/bug, size/L, lgtm, approved
