Repository knative/serving, pull requests merged in 2025-06, with the labels that each got.

#15910 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15909 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#15911 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15900 Correct tryTimeoutAndWriteError to write timeout regardless of prior writes
  pkg/http/handler/timeout.go
  pkg/http/handler/timeout_test.go
Labels: size/L, lgtm, approved

#15918 Fix flakes in TestIdleTimeoutHandler
  pkg/http/handler/timeout_test.go
Labels: size/S, lgtm, approved

#15917 ignore v1.Endpoint.* deprecation
  .golangci.yaml
Labels: size/XS, lgtm, approved

#15919 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15915 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/M, skip-review

#15920 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#15921 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15927 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15931 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#15932 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15928 bump cert-manager, istio, contour
  test/e2e-networking-library.sh
  third_party/cert-manager-latest/cert-manager.yaml
  third_party/cert-manager-latest/download-cert-manager.sh
Labels: size/XXL, lgtm, approved

#15938 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.yaml.in/yaml/v2/.travis.yml
  vendor/go.yaml.in/yaml/v2/LICENSE
  vendor/go.yaml.in/yaml/v2/LICENSE.libyaml
  vendor/go.yaml.in/yaml/v2/NOTICE
  vendor/go.yaml.in/yaml/v2/README.md
  vendor/go.yaml.in/yaml/v2/apic.go
  vendor/go.yaml.in/yaml/v2/decode.go
  vendor/go.yaml.in/yaml/v2/emitterc.go
  vendor/go.yaml.in/yaml/v2/encode.go
  vendor/go.yaml.in/yaml/v2/parserc.go
  vendor/go.yaml.in/yaml/v2/readerc.go
  vendor/go.yaml.in/yaml/v2/resolve.go
  vendor/go.yaml.in/yaml/v2/scannerc.go
  vendor/go.yaml.in/yaml/v2/sorter.go
  vendor/go.yaml.in/yaml/v2/writerc.go
  vendor/go.yaml.in/yaml/v2/yaml.go
  vendor/go.yaml.in/yaml/v2/yamlh.go
  vendor/go.yaml.in/yaml/v2/yamlprivateh.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/goyaml.v2/README.md
  vendor/sigs.k8s.io/yaml/goyaml.v2/yaml_aliases.go
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_go110.go
Labels: size/XL, lgtm, approved

#15940 Fix roundToNDigits to use Round instead of Floor
  pkg/autoscaler/aggregation/bucketing.go
  pkg/autoscaler/aggregation/bucketing_test.go
Labels: size/XS, lgtm, approved
