Repository knative/serving, pull requests merged in 2025-09, with the labels that each got.

#16055 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, skip-review

#16057 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#16058 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#16059 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#16062 Serving Metric Tweaks
  pkg/autoscaler/metrics/stats_scraper.go
  pkg/queue/request_metric.go
  pkg/queue/request_metric_test.go
Labels: size/S, lgtm, approved

#16065 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#16064 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#16075 Revert "add initialize conditions to MakePA to avoid potential race conditions (#16037)"
  config/core/300-resources/podautoscaler.yaml
  docs/serving-api.md
  pkg/apis/autoscaling/v1alpha1/pa_types.go
  pkg/apis/serving/v1/revision_lifecycle_test.go
  pkg/reconciler/revision/table_test.go
  pkg/reconciler/testing/v1/factory.go
Labels: size/M, lgtm, approved

#16087 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/time.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/gotrack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/unix/affinity_linux.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/packages/visit.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/go/types/typeutil/map.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport_go122.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/modules.txt
Labels: size/XXL, skip-review

#16092 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review

#16091 [Automated] Update net-gateway-api nightly
  third_party/gateway-api-latest/istio-gateway.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: size/S, skip-review

#16090 [Automated] Update net-kourier nightly
  third_party/kourier-latest/kourier.yaml
Labels: size/S, skip-review

#16096 For orphaned certificates if we have an issue listing just log the error
  pkg/reconciler/route/route.go
Labels: size/M, lgtm, approved

#16099 bump Istio to v1.27 and Contour to v1.33
  test/e2e-networking-library.sh
Labels: size/XS, lgtm, approved

#16102 [Automated] Update net-istio nightly
  third_party/istio-latest/net-istio.yaml
Labels: size/M, skip-review
