Repository knative/serving, pull requests merged in 2025-07, with the labels that each got.

#15951 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15953 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review

#15957 Remove unused imports
  pkg/reconciler/configuration/queueing_test.go
  pkg/reconciler/metric/metric_test.go
  pkg/reconciler/nscert/nscert_test.go
  pkg/reconciler/route/route_test.go
  pkg/reconciler/serverlessservice/global_resync_test.go
  test/clients.go
Labels: size/XS, lgtm, approved

#15959 [otel] Use new serving observability configmap
  cmd/webhook/main.go
  test/e2e/logging_test.go
Labels: size/S, lgtm, approved

#15961 [otel] instrumentation of the queue-proxy
  go.mod
  go.sum
  pkg/queue/handler.go
  pkg/queue/handler_test.go
  pkg/queue/health/handler.go
  pkg/queue/health/handler_test.go
  pkg/queue/request_metric.go
  pkg/queue/request_metric_test.go
  pkg/queue/routetag_handler.go
  pkg/queue/routetag_handler_test.go
  pkg/queue/sharedmain/handlers.go
  pkg/queue/sharedmain/main.go
  pkg/queue/sharedmain/main_test.go
  pkg/queue/sharedmain/otel.go
  vendor/contrib.go.opencensus.io/exporter/zipkin/.travis.yml
  vendor/contrib.go.opencensus.io/exporter/zipkin/LICENSE
  vendor/contrib.go.opencensus.io/exporter/zipkin/Makefile
  vendor/contrib.go.opencensus.io/exporter/zipkin/README.md
  vendor/contrib.go.opencensus.io/exporter/zipkin/zipkin.go
  vendor/github.com/openzipkin/zipkin-go/.gitattributes
  vendor/github.com/openzipkin/zipkin-go/.gitignore
  vendor/github.com/openzipkin/zipkin-go/.golangci.yml
  vendor/github.com/openzipkin/zipkin-go/LICENSE
  vendor/github.com/openzipkin/zipkin-go/Makefile
  vendor/github.com/openzipkin/zipkin-go/README.md
  vendor/github.com/openzipkin/zipkin-go/SECURITY.md
  vendor/github.com/openzipkin/zipkin-go/context.go
  vendor/github.com/openzipkin/zipkin-go/doc.go
  vendor/github.com/openzipkin/zipkin-go/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/idgenerator/idgenerator.go
  vendor/github.com/openzipkin/zipkin-go/model/annotation.go
  vendor/github.com/openzipkin/zipkin-go/model/doc.go
  vendor/github.com/openzipkin/zipkin-go/model/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/model/kind.go
  vendor/github.com/openzipkin/zipkin-go/model/span.go
  vendor/github.com/openzipkin/zipkin-go/model/span_id.go
  vendor/github.com/openzipkin/zipkin-go/model/traceid.go
  vendor/github.com/openzipkin/zipkin-go/noop.go
  vendor/github.com/openzipkin/zipkin-go/propagation/propagation.go
  vendor/github.com/openzipkin/zipkin-go/reporter/http/http.go
  vendor/github.com/openzipkin/zipkin-go/reporter/recorder/recorder.go
  vendor/github.com/openzipkin/zipkin-go/reporter/reporter.go
  vendor/github.com/openzipkin/zipkin-go/reporter/serializer.go
  vendor/github.com/openzipkin/zipkin-go/sample.go
  vendor/github.com/openzipkin/zipkin-go/span.go
  vendor/github.com/openzipkin/zipkin-go/span_implementation.go
  vendor/github.com/openzipkin/zipkin-go/span_options.go
  vendor/github.com/openzipkin/zipkin-go/tags.go
  vendor/github.com/openzipkin/zipkin-go/tracer.go
  vendor/github.com/openzipkin/zipkin-go/tracer_options.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
  vendor/knative.dev/pkg/tracing/http.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/propagation/http_format_sequence.go
  vendor/knative.dev/pkg/tracing/propagation/tracecontextb3/http_format.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/knative.dev/pkg/tracing/testing/zipkin.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#15975 [Automated] Update net-contour nightly
  third_party/contour-latest/net-contour.yaml
Labels: size/S, skip-review
